### PR TITLE
Packages

### LINKED ISSUE #417: Create Package Structure
model it in Papyrus and apply it to the classes

### PR DESCRIPTION
**Pull request by acBerger**
- Difference in Naming:
In the model explorer the evaluable expressions were called "Evaluable Expressions" while in the Package Diagram and the Code they were only called "Expressions". This lead to a new created folder in the model explorer called "Expressions".
I changed all to "Evaluable Expressions".

- Classes shown in Package Diagram: I synchronized the package diagram with the model explorer. Classes and other contents of the packages are now shown in  the package diagram. Additionally changes in the existing packages are now synchronized between model explorer and package Diagram (in Both ways). 

- Adapted Code and Package Diagram: Both should now be in same package structure.

fixes #417

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/449)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
Expressions is still there.

---

Review status: 0 of 32 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/449#-:-K7MfLrMY3q8GrEgnlsy:-807168623)*

**Comment by RomanLangrehr** [comment]
Reviewed 47 of 53 files at r1.
Review status: 26 of 32 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/de/uka/ipd/sdq/beagle/analysis/FinalJudge.java, line 1 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/449#-K7Mfj2N2ctXyVVmNMnf:-K7Mfj2N2ctXyVVmNMng:230490349) ([raw file](https://github.com/beagle-pse/beagle/blob/a905aeb6cedca53c90f453b3fab871cbf7f98960/src/main/java/de/uka/ipd/sdq/beagle/analysis/FinalJudge.java#L1)):*
Why is the final judge now in analysis?

---

*[src/main/java/de/uka/ipd/sdq/beagle/analysis/FinalJudgeBlackboardView.java, line 1 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/449#-K7Mfoj6yR4mCt3hL--V:-K7Mfoj6yR4mCt3hL--W:160841994) ([raw file](https://github.com/beagle-pse/beagle/blob/a905aeb6cedca53c90f453b3fab871cbf7f98960/src/main/java/de/uka/ipd/sdq/beagle/analysis/FinalJudgeBlackboardView.java#L1)):*
Same as above.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/449)*

**Comment by acBerger** [comment]
For me it isn't. (At least I did not find it)


---

Review status: 26 of 32 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/449#-:-K7MgJ0j-N9K2rs1X-3l:603665192)*

**Comment by acBerger** [comment]
Review status: 26 of 32 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/de/uka/ipd/sdq/beagle/analysis/FinalJudge.java, line 1 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/449#-K7Mfj2N2ctXyVVmNMnf:-K7MgTSJZ3gc0WyKEBzi:-605922127) ([raw file](https://github.com/beagle-pse/beagle/blob/a905aeb6cedca53c90f453b3fab871cbf7f98960/src/main/java/de/uka/ipd/sdq/beagle/analysis/FinalJudge.java#L1)):*
I found it unnecessary to have a package only for judge.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/449)*

**Comment by RomanLangrehr** [comment]
Review status: 26 of 32 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/de/uka/ipd/sdq/beagle/analysis/FinalJudge.java, line 1 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/449#-K7Mfj2N2ctXyVVmNMnf:-K7QtmUFoa-ir_q18kXH:-307007981) ([raw file](https://github.com/beagle-pse/beagle/blob/a905aeb6cedca53c90f453b3fab871cbf7f98960/src/main/java/de/uka/ipd/sdq/beagle/analysis/FinalJudge.java#L1)):*
I think that's inconsequent, as the e.g. the result analyser have an own package and this package has exactly the same strucutre as the final judge.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/449)*

**Comment by acBerger** [comment]
Review status: 26 of 32 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/de/uka/ipd/sdq/beagle/analysis/FinalJudge.java, line 1 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/449#-K7Mfj2N2ctXyVVmNMnf:-K7R9-VzS-BJWg1tf3kK:2134945678) ([raw file](https://github.com/beagle-pse/beagle/blob/a905aeb6cedca53c90f453b3fab871cbf7f98960/src/main/java/de/uka/ipd/sdq/beagle/analysis/FinalJudge.java#L1)):*
So you prefer to have a "judge" package?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/449)*

**Comment by RomanLangrehr** [comment]
Review status: 26 of 32 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/de/uka/ipd/sdq/beagle/analysis/FinalJudge.java, line 1 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/449#-K7Mfj2N2ctXyVVmNMnf:-K7RCKVTA37HlV2yq2sP:677251276) ([raw file](https://github.com/beagle-pse/beagle/blob/a905aeb6cedca53c90f453b3fab871cbf7f98960/src/main/java/de/uka/ipd/sdq/beagle/analysis/FinalJudge.java#L1)):*
Yes.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/449)*

**Comment by acBerger** [comment]
Review status: 22 of 30 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/de/uka/ipd/sdq/beagle/judge/FinalJudge.java, line 1 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/449#-K7Mfj2N2ctXyVVmNMnf:-K7RGApgWntbUufkXeI7:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/a905aeb6cedca53c90f453b3fab871cbf7f98960/src/main/java/de/uka/ipd/sdq/beagle/judge/FinalJudge.java#L1)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/449)*

**Comment by flyfl** [comment]
`Null` instead of MethodNames:


Missing interface Names and strange looking markers on associations:


---

Review status: 22 of 30 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/449#-:-K7RPykLR5jumDFyEU87:-568683881)*

**Comment by acBerger** [comment]
Are you sure this came wih my PR? I did not change anything on this diagram.

---

Review status: 22 of 30 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/449#-:-K7Rnyt3tVvoo0nr-P7v:730131739)*

**Comment by flyfl** [comment]
That's what I see, when I look at the `Diagram Beagle Core` file from your latest commit.
Anyone else with this problem?

**Comment by acBerger** [comment]
I see it too. Question is if I did this or if it was there before. So do you have this when you are in the master branch?

---

Review status: 22 of 30 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/449#-:-K7RvdX1HS6XsifHTWxB:822761288)*

**Comment by flyfl** [comment]
The master branch seems to look fine.

**Comment by RomanLangrehr** [comment]
I have the same problem as @flyfl 



---

Review status: 22 of 30 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/449#-:-K7S1hxJ-wu8Dk0MvNoA:1520810788)*

**Comment by RomanLangrehr** [comment]
Reviewed 5 of 9 files at r3.
Review status: 24 of 30 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/de/uka/ipd/sdq/beagle/judge/package-info.java, line 2 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/449#-K7S21_XoBLdvxyeRS7i:-K7S21_XoBLdvxyeRS7j:-927611478) ([raw file](https://github.com/beagle-pse/beagle/blob/c22900f8ad9696f14aefb522978ea8f57d319542/src/main/java/de/uka/ipd/sdq/beagle/judge/package-info.java#L2)):*
The original package-info was better!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/449)*

**Comment by acBerger** [comment]
Review status: 23 of 30 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/de/uka/ipd/sdq/beagle/judge/package-info.java, line 2 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/449#-K7S21_XoBLdvxyeRS7i:-K7S7bLTSYlB79nrZAYd:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/c22900f8ad9696f14aefb522978ea8f57d319542/src/main/java/de/uka/ipd/sdq/beagle/judge/package-info.java#L2)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/449)*

**Comment by RomanLangrehr** [comment]
Did you re-create the interfaces? Because the pseudocode is broken now:


---

Reviewed 1 of 7 files at r4.
Review status: 23 of 30 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/449#-:-K7S8c_ewu7Ni5NUg95L:-562372666)*

**Comment by acBerger** [comment]
I dragged the name from the model explorer into the diagram. If this is re-creating: yes. I did not find another possiblity to fix it.

---

Review status: 23 of 30 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/449#-:-K7S8qbCc7HDO347Kaiu:-1628067686)*

**Comment by RomanLangrehr** [comment]
> I dragged the name from the model explorer into the diagram. If this is re-creating: yes. I did not find another possiblity to fix it.

Hm, i thought this would be no problem. But it's papyrus!

**Comment by acBerger** [comment]
Yes it is. And I hate it!

---

Review status: 23 of 30 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/449#-:-K7S9VktVYBiaQEXiRcN:-2013497645)*

**Comment by RomanLangrehr** [comment]
:lgtm_strong: 

---

Reviewed 4 of 7 files at r4, 21 of 21 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/449#-:-K7SxHGnylprqkGYt-Ts:-1868698381)*

**Comment by acBerger** [comment]
As this PR distroyed parts of the diagram and I now have to merge some .notation and .uml files by hand, it probably is better to remake this.

---

Review status: 5 of 30 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/449#-:-K7VRys3uFma4BJ32Xo0:847872698)*

**Pull request closed without merging**
