### PR TITLE
BeagleController now stores the results.

### PR DESCRIPTION
**Pull request by RomanLangrehr**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/731)

### CODE REVIEW

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/731#-:-KAiDDDLNi7rEqHBwwTg:1417088721)*

**Comment by acBerger** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java, line 37 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/731#-KAiDL2hw8uggFS5v-GO:-KAiDL2hw8uggFS5v-GP:2123474836) ([raw file](https://github.com/beagle-pse/beagle/blob/b01c7dc2288914bb6d597cf8db431a93170c18e3/Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java#L37)):*
Is this really necessary?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/731)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/731#-KAiKZnbjc0jREmCKfP-:-KAiKZnc7bwhdKbtGWFI:2035948447) (no related file):*
I don’t think the `BeagleController` should be responsible to catch all those `FileNotFound`Exceptions. Instead, the PCM Connection should handle them itself. I think failures should be addressed as soon as possible. (Concerns @flyfl)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/731)*

**Comment by flyfl** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/731#-KAiKZnbjc0jREmCKfP-:-KAjJFLPR_VWQV4gUk-I:599380786) (no related file):*
Neither the BeagleController nor the PcmConnection will solve this kind of Exception (that has to be done on the GUI Controller, I guess?). You propose may be better for locating the position of the FileNotFoundException, however this information is transported via our FailureHandler that tranports the FileNotFoundException. In my opinion both ways are okay.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java, line 37 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/731#-KAiDL2hw8uggFS5v-GO:-KAjKgFVoK2xdzBTzMQW:1344679044) ([raw file](https://github.com/beagle-pse/beagle/blob/96f5fc58f780d7e20802404b06d2f971f29b33de/Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java#L37)):*
(He is free to do that. I was not ... :(  )
But why should we split this class?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/731)*

**Comment by flyfl** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/731#-KAiKZnbjc0jREmCKfP-:-KAjLHT8ciC6nVx05IEL:-97645199) (no related file):*

:lgtm:

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/731)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/731#-KAiKZnbjc0jREmCKfP-:-KAjZBDHui2QgkldMbm8:1408893288) (no related file):*
> Neither the BeagleController nor the PcmConnection will solve this kind of Exception (that has to be done on the GUI Controller, I guess?). You propose may be better for locating the position of the FileNotFoundException, however this information is transported via our FailureHandler that tranports the FileNotFoundException. In my opinion both ways are okay.

I don’t get what are you are talking about. What keeps you from calling the FailureHandler in your code, thus handling the exception as soon as possible?

And of course you can’t “solve” the exception. That’s what the `FailureHandler` is for: You tell him about the failure and also tell him how to retry. 

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java, line 37 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/731#-KAiDL2hw8uggFS5v-GO:-KAjYtvu-g1XfFfO_mCq:-977658959) ([raw file](https://github.com/beagle-pse/beagle/blob/96f5fc58f780d7e20802404b06d2f971f29b33de/Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java#L37)):*
It can be discussed whether this class can meaningfully be split. But it *should* be discussed. Disabling Checkstyle just because it annoys you is not an option.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/731)*

**Comment by RomanLangrehr** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java, line 37 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/731#-KAiDL2hw8uggFS5v-GO:-KAk0ft_SvqhkmOCgOfu:-1580355412) ([raw file](https://github.com/beagle-pse/beagle/blob/f8980413bb88d421305b6aae474857fb3a854dbf/Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java#L37)):*
I don't think it makes sense to spilt the class.

By the way ClassFanOutComplexity is here 21 and allowed is 20. Don't tell me that that choosing 20 as limit and not 21 has any sense!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/731)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java, line 37 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/731#-KAiDL2hw8uggFS5v-GO:-KAk1rPlUmnkElRgutdM:-1480293754) ([raw file](https://github.com/beagle-pse/beagle/blob/f8980413bb88d421305b6aae474857fb3a854dbf/Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java#L37)):*
> Don't tell me that that choosing 20 as limit and not 21 has any sense!

Nobody does that. All I’m saying is that if it’s above 20, we should really think if there is a way to simplify things. If there isn’t, fine. But we used Checkstyle to **help** us. Ignoring it as soon as it says something contradicts that. 

I don’t see a good way to simplify this either, except for the `FileNotFoundException`s. Handling them in the PCM Connection could actually solve this issue, too. But if not, I’m fine with leaving that comment there. But please add an *explanation*.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java, line 89 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/731#-KAk2elzN29hmgO9u3EM:-KAk2elzN29hmgO9u3EN:558439104) ([raw file](https://github.com/beagle-pse/beagle/blob/f8980413bb88d421305b6aae474857fb3a854dbf/Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java#L89)):*
1. Putting the `FailureHandler` in a static attribute might be nicer (but that’s not so important)

2. You should really add a `recoverable` here. The user doesn’t want to hear “we could not read the charset and because of that we can’t continue”. Using `Charset#defaultCharset` is absolutely fine here.

Nice way to do that:

```java
private Charset readCharset(final IJavaProject javaProject) {
    try {
        return Charset.forName(javaProject.getProject().getDefaultCharset());
    } catch (final CoreException coreException) {
        FailureReport<Charset> failure = new FailureReport<>()
            .cause(coreException)
            .continueWith(Charset::defaultCharset)
            .retryWith(() -> this.readCharset(javaProject));
        return FAILURE_HANDLER.handle(failure);
    }
}
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/731)*

**Comment by viridispirus** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/731)*

**Comment by RomanLangrehr** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java, line 89 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/731#-KAk2elzN29hmgO9u3EM:-KApHRL72bAsW-SAi4xy:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/f8980413bb88d421305b6aae474857fb3a854dbf/Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java#L89)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/731)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/731#-:-KApKs3QkKRznUCThhBl:980077423)*

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/731#-:-KAskMSxzuKKhTka_msY:1417088721)*

**Comment by viridispirus** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/731)*

**Comment by jGleitz** [comment]
:white_check_mark:

**Comment by acBerger** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/731)*

**Comment by acBerger** [comment]
:lgtm: :white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/731#-:-KAt_jOelRFd3yW5uhw8:-1603124213)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/731#-:-KAtcO-G4hvGNUm4vKz7:980077423)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Reviewed 1 of 2 files at r1, 5 of 5 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/731#-:-KAthJjD2aNLQJMAXiT3:980077423)*

**Comment by acBerger** [comment]
:lgtm: :white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/731#-:-KAthxnZV4mkpKOec-UG:-1603124213)*

**Comment by viridispirus** [comment]
Reviewed 1 of 5 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/731)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/731#-:-KAuATQafnjLLgwklNoi:980077423)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: 6 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/731#-:-KAuz8130GVqcvNSHKqe:980077423)*

**Comment by viridispirus** [comment]
Reviewed 2 of 5 files at r3, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/731)*

**Comment by jGleitz** [comment]
:lgtm: :white_check_mark: 

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/731#-:-KAuzTdlMvtSZ4MjuF45:-1603124213)*

**Pull request merged**
