### PR TITLE
Updated Design Document

### LINKED ISSUE #560: Fill 2.1 or delete from Design Document

### LINKED ISSUE #561: Fill 4.3 or delete from Design Document

### LINKED ISSUE #562: Fill 5.2 or delete from Design Document

### PR DESCRIPTION
**Pull request by m1cm1c**
fixes  #560
fixes #561
fixes #562

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/565)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/565#-:-K7hf3eDojmgCzT2qgGU:980077423)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/565#-:-K7hfCUwUs1lFEmv2MyR:1417088721)*

**Comment by acBerger** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/565)*

**Comment by flyfl** [comment]
:lgtm_strong:

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/565#-:-K7hgbL_KZv8svvbNcS5:980077423)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/565#-:-K7hghPpZDnpTtLLQqJY:1417088721)*

**Pull request merged**
