### PR TITLE
[IP #110] Evaluable Expressions

### LINKED ISSUE #608: [IP #110] Implement Evaluable Expressions
Implement all subclasses of the interface EvaluableExpression.
(Package “Evaluable Expressions”)

### PR DESCRIPTION
**Pull request by acBerger**
Implemented by me and tested by @jGleitz 

fixes #608

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/652)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
Reviewed 3 of 23 files at r2, 5 of 12 files at r4, 9 of 13 files at r5, 2 of 7 files at r6, 9 of 14 files at r8, 8 of 8 files at r9.
Review status: 35 of 38 files reviewed at latest revision, 9 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ComparisonExpression.java, line 92 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-K9OqW-T_-Y70IXaeLTg:-K9OqW-T_-Y70IXaeLTh:-845502720) ([raw file](https://github.com/beagle-pse/beagle/blob/163f9a8dd9746935ac9069f0dd0d364190cbf165/Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ComparisonExpression.java#L92)):*
I think this should be in a public double constant.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ComparisonExpression.java, line 94 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-K9Oqa_mwKJKql3yCemi:-K9Oqa_mwKJKql3yCemj:-845502720) ([raw file](https://github.com/beagle-pse/beagle/blob/163f9a8dd9746935ac9069f0dd0d364190cbf165/Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ComparisonExpression.java#L94)):*
I think this should be in a public double constant.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/EvaluableVariableAssignment.java, line 111 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-K9Osfo7ww5lcF9iJ9Vb:-K9Osfo85GaoEJIfcFv9:-1831599565) ([raw file](https://github.com/beagle-pse/beagle/blob/163f9a8dd9746935ac9069f0dd0d364190cbf165/Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/EvaluableVariableAssignment.java#L111)):*
Why is each value added – and not the whole map?

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/IfThenElseExpression.java, line 100 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-K9OtaQc4wiOIbyTomLJ:-K9OtaQgEdQi_2PC-Ymv:1513628956) ([raw file](https://github.com/beagle-pse/beagle/blob/163f9a8dd9746935ac9069f0dd0d364190cbf165/Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/IfThenElseExpression.java#L100)):*
The constant mentioned in the smaller-greater evaex i mentioned shoulde be used here.
Maybe the constants should be added here.

Or even better: In the EvaEx Interface.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/SineExpression.java, line 66 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-K9OuWDM8NwoRXrqltNL:-K9OuWDM8NwoRXrqltNM:-1069531135) ([raw file](https://github.com/beagle-pse/beagle/blob/163f9a8dd9746935ac9069f0dd0d364190cbf165/Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/SineExpression.java#L66)):*
I think this should be `sin(%s)`.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ComparisonExpressionTest.java, line 130 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-K9OwguNNhQnowLm9uFu:-K9OwguNNhQnowLm9uFv:1415903661) ([raw file](https://github.com/beagle-pse/beagle/blob/163f9a8dd9746935ac9069f0dd0d364190cbf165/Core/src/test/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ComparisonExpressionTest.java#L130)):*
The test should use the constant, too.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ComparisonExpressionTest.java, line 134 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-K9OwlpMcIHMhGzr3-5z:-K9OwlpMcIHMhGzr3-6-:1415903661) ([raw file](https://github.com/beagle-pse/beagle/blob/163f9a8dd9746935ac9069f0dd0d364190cbf165/Core/src/test/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ComparisonExpressionTest.java#L134)):*
The test should use the constant, too.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ComparisonExpressionTest.java, line 138 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-K9OwofPlHmSSwUCzDih:-K9OwofPlHmSSwUCzDii:1415903661) ([raw file](https://github.com/beagle-pse/beagle/blob/163f9a8dd9746935ac9069f0dd0d364190cbf165/Core/src/test/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ComparisonExpressionTest.java#L138)):*
The test should use the constant, too.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ComparisonExpressionTest.java, line 142 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-K9OwmbGN5eTS3OOSY31:-K9OwmbHMBM4nfRmVxhD:1415903661) ([raw file](https://github.com/beagle-pse/beagle/blob/163f9a8dd9746935ac9069f0dd0d364190cbf165/Core/src/test/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ComparisonExpressionTest.java#L142)):*
The test should use the constant, too.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/652)*

**Comment by RomanLangrehr** [comment]
Reviewed 1 of 2 files at r7, 1 of 14 files at r8.
Review status: 37 of 38 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/652)*

**Comment by RomanLangrehr** [comment]
Reviewed 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/652)*

**Comment by acBerger** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/SineExpression.java, line 66 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-K9OuWDM8NwoRXrqltNL:-K9QeDAGBzlEiBmNVVzp:1563427507) ([raw file](https://github.com/beagle-pse/beagle/blob/163f9a8dd9746935ac9069f0dd0d364190cbf165/Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/SineExpression.java#L66)):*
I used paranthesis around the statement and not in in all classes to avoid things like `(5) + (3) + (sin(2x+5))`, so the inner expression decides whether paranthesis are needed. In this case this leads to `sin4` instead of `sin(4)`. 
However, I think I fogot a space: `sin 4`would be better expecially if it comes to things like `sin log 5`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/652)*

**Comment by acBerger** [comment]
Review status: 35 of 38 files reviewed at latest revision, 9 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ComparisonExpression.java, line 92 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-K9OqW-T_-Y70IXaeLTg:-K9S1FosAh5IsoXT-nK3:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/163f9a8dd9746935ac9069f0dd0d364190cbf165/Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ComparisonExpression.java#L92)):*
Done.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ComparisonExpression.java, line 94 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-K9Oqa_mwKJKql3yCemi:-K9S1GIewRwHmZD0a5dy:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/163f9a8dd9746935ac9069f0dd0d364190cbf165/Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ComparisonExpression.java#L94)):*
Done.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/EvaluableVariableAssignment.java, line 111 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-K9Osfo7ww5lcF9iJ9Vb:-K9S1cLhBj3WYeijh04e:-398770705) ([raw file](https://github.com/beagle-pse/beagle/blob/163f9a8dd9746935ac9069f0dd0d364190cbf165/Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/EvaluableVariableAssignment.java#L111)):*
I did this to have it equal to `equals`. 

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/IfThenElseExpression.java, line 100 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-K9OtaQc4wiOIbyTomLJ:-K9S2MZDhGvTxCkLkQKg:1462451377) ([raw file](https://github.com/beagle-pse/beagle/blob/163f9a8dd9746935ac9069f0dd0d364190cbf165/Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/IfThenElseExpression.java#L100)):*
I added the `FALSE`constant to the interface, but not the one for `TRUE`as true normally should be everything except `0`.
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/652)*

**Comment by jGleitz** [comment]
Review status: 33 of 38 files reviewed at latest revision, 9 unresolved discussions.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ComparisonExpressionTest.java, line 134 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-K9OwlpMcIHMhGzr3-5z:-K9Sm0LXE_jIrLm5XjmX:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/163f9a8dd9746935ac9069f0dd0d364190cbf165/Core/src/test/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ComparisonExpressionTest.java#L134)):*
Done.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ComparisonExpressionTest.java, line 138 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-K9OwofPlHmSSwUCzDih:-K9Sm27MF3_82M9tuHpp:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/163f9a8dd9746935ac9069f0dd0d364190cbf165/Core/src/test/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ComparisonExpressionTest.java#L138)):*
Done.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ComparisonExpressionTest.java, line 142 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-K9OwmbGN5eTS3OOSY31:-K9Sm2mS_D00XWy0GEFV:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/163f9a8dd9746935ac9069f0dd0d364190cbf165/Core/src/test/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ComparisonExpressionTest.java#L142)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/652)*

**Comment by jGleitz** [comment]
Review status: 33 of 38 files reviewed at latest revision, 9 unresolved discussions.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ComparisonExpressionTest.java, line 130 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-K9OwguNNhQnowLm9uFu:-K9SmBwS9aQZ1OpHMu4e:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/163f9a8dd9746935ac9069f0dd0d364190cbf165/Core/src/test/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ComparisonExpressionTest.java#L130)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/652)*

**Comment by RomanLangrehr** [comment]
Reviewed 2 of 3 files at r11, 3 of 3 files at r12.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/EvaluableVariableAssignment.java, line 111 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-K9Osfo7ww5lcF9iJ9Vb:-K9SwD5lQm1159ZUcha9:-53259075) ([raw file](https://github.com/beagle-pse/beagle/blob/163f9a8dd9746935ac9069f0dd0d364190cbf165/Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/EvaluableVariableAssignment.java#L111)):*
And why don't you just add the whole map in equals?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/652)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/EvaluableVariableAssignment.java, line 111 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-K9Osfo7ww5lcF9iJ9Vb:-K9T--90eY8tjzPPlj-v:363362236) ([raw file](https://github.com/beagle-pse/beagle/blob/163f9a8dd9746935ac9069f0dd0d364190cbf165/Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/EvaluableVariableAssignment.java#L111)):*
I don’t think this would do you think it will: [`equals` on `Map`s only compares the keys](https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#equals-java.lang.Object-).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/652)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/EvaluableVariableAssignment.java, line 111 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-K9Osfo7ww5lcF9iJ9Vb:-K9T-Jtb09YWZX-Qb1lB:1948001534) ([raw file](https://github.com/beagle-pse/beagle/blob/163f9a8dd9746935ac9069f0dd0d364190cbf165/Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/EvaluableVariableAssignment.java#L111)):*
Note that she *is* putting the whole map in the builders, but that’s not enough.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/652)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-:-K9T39k5P1W6QwKDzi5H:980077423)*

**Comment by jGleitz** [comment]
Reviewed 2 of 14 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/652)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 14 of 14 files at r13.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-:-K9iF458oLk55EbO2ofc:980077423)*

**Comment by viridispirus** [comment]
Reviewed 1 of 12 files at r4, 2 of 8 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/652)*

**Comment by viridispirus** [comment]
Reviewed 2 of 13 files at r5, 1 of 8 files at r9, 1 of 3 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/652)*

**Comment by viridispirus** [comment]
Reviewed 1 of 3 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/652)*

**Comment by viridispirus** [comment]
Reviewed 1 of 23 files at r2, 1 of 13 files at r5, 1 of 7 files at r6, 1 of 8 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/652)*

**Comment by jGleitz** [comment]
Reviewed 1 of 1 files at r16.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/652)*

**Comment by viridispirus** [comment]
Reviewed 1 of 13 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ExpressionRecursionException.java, line 0 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-K9sHErcI7lAtsTmRkuh:-K9sHErcI7lAtsTmRkui:174699412) ([raw file](https://github.com/beagle-pse/beagle/blob/d2c3943b4c6d190a3a96a7655869c02c4d080c7f/Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ExpressionRecursionException.java#L0)):*
Why is this one deleted? Did we don't need it?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/652)*

**Comment by viridispirus** [comment]
Reviewed 1 of 12 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/652)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ExpressionRecursionException.java, line  \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-K9sHErcI7lAtsTmRkuh:-K9sHgTI3GO_mYvw7jh3:-45735780) ([raw file](https://github.com/beagle-pse/beagle/blob/d2c3943b4c6d190a3a96a7655869c02c4d080c7f/Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ExpressionRecursionException.java#L)):*
Yes, it’s not needed. See #638 (Proposition: It Is Not Possible to Create an EvaEx that Contains Itself) 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/652)*

**Comment by viridispirus** [comment]
Reviewed 1 of 13 files at r5, 1 of 3 files at r12.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ExpressionRecursionException.java, line  \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-K9sHErcI7lAtsTmRkuh:-K9sIds4NFpwnooe6dNm:160384653) ([raw file](https://github.com/beagle-pse/beagle/blob/d2c3943b4c6d190a3a96a7655869c02c4d080c7f/Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/ExpressionRecursionException.java#L)):*
Ok.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/652)*

**Comment by viridispirus** [comment]
Reviewed 1 of 23 files at r2, 3 of 13 files at r5, 1 of 8 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/652)*

**Comment by jGleitz** [comment]
@viridispirus: Please don’t hit publish after every file you’ve reviewed. Hitting publish gives a notification to everyone. 

Reviewable automatically saves everything you do. Hitting Publish is only necessary if you want others to see what you did.

**Comment by viridispirus** [comment]
Ops, sorry i stop it.

2016-02-06 21:46 GMT+01:00 Joshua Gleitze <notifications@github.com>:

**Comment by viridispirus** [comment]
:lgtm: 

---

Reviewed 1 of 23 files at r2, 1 of 12 files at r4, 14 of 14 files at r13, 1 of 1 files at r16.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-:-K9sMoT0yXgn9GHl1JOe:980077423)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-:-K9sV6O3tkmPp_fn7TWG:980077423)*

**Comment by jGleitz** [comment]
+@RomanLangrehr : your lgtm got stale because of a conflict resolving merge commit.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-:-K9sg8OOsXdtpzh3IT-H:-314259066)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r16.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/652#-:-K9sgmVXksjS0FaIAWVV:980077423)*

**Pull request merged**
