### PR TITLE
Controllers diagram

### LINKED ISSUE #478: Redraw Controllers Diagram in UMLet
depends on #475

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Remade this to avoid the unnecassry dependencies.

Fixes #478 
[Website](http://romanlangrehr.github.io/Beagle/branches/controllers-diagram3/)

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/523)

### CODE REVIEW

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/523#-:-K7fBqFRLY571X4ZhQ25:1417088721)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/523#-:-K7fgVe754L_UthmhGTL:980077423)*

**Comment by acBerger** [comment]
:lgtm: 

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/523#-:-K7fgpOAuDmBfUyY4Yrr:980077423)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/523)*

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/523#-:-K7fkOnb5TbNImvcy18E:1417088721)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/523#-:-K7fknczMeNT4vjEzIbV:980077423)*

**Pull request merged**
