### PR TITLE
Evaluable Expression Diagram.

### LINKED ISSUE #476: Redraw Evaluable Expressions Diagram in UMLet

### PR DESCRIPTION
**Pull request by flyfl**
fixes #476

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/491)

### CODE REVIEW

**Comment by flyfl** [comment]
---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/491#-:-K7Z2S8sXDceJWOAocWk:1452444551)*

**Comment by m1cm1c** [comment]
Why are there minuses before the role names?

**Comment by jGleitz** [comment]
> Why are there minuses before the role names?

Because these are not minuses but the private attributes storing the relation end. And these attributes are final. 

* The interface of the Evaluable Expression interface is outdated, see my PR for what I think is right. 

* I seem to remember that when implementing interfaces in UML, you have to state the inherited methods again. Do the others know something about that?

**Comment by m1cm1c** [comment]
Thx. :lgtm:

On January 9, 2016 9:32:40 AM GMT+01:00, Joshua Gleitze <notifications@github.com> wrote:
>> Why are there minuses before the role names?
>
>Because these are not minuses but the private attributes storing the
>relation end. And these attributes are final. 
>
>* The interface of the Evaluable Expression interface is outdated, see
>my PR for what I think is right. 
>
>* I seem to remember that when implementing interfaces in UML, you have
>to state the inherited methods again. Do the others know something
>about that? 
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Beagle-PSE/Beagle/pull/491#issuecomment-170210003

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by m1cm1c** [comment]
This branch is out-of-date with the base branch. :lgtm: (Doesn't seem to work via email.)

**Comment by flyfl** [comment]
@jGleitz 
- I changed your first point (hopefully the desired way..)
- I have not written explicitly the implemented methods, because I think this is redundant. If it must be used in the diagram, I will add it.

**Comment by flyfl** [comment]
---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/491#-:-K7_vfjXEhlmrJnwAbJy:-2090831032)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/491)*

**Comment by jGleitz** [comment]
>  I think this is redundant

It certainly is. We’ll leave it out for now.

Please give all parameters called `null` meaningful names.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/491#-:-K7a347cpAzPsywJF1qr:-1562841515)*

**Comment by jGleitz** [comment]
Please merge with `master` and add your diagram to the design document!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/491#-:-K7arqSwhrHj1m9MO_JA:-2023468121)*

**Comment by acBerger** [comment]
[Website ](http://flyfl.github.io/Beagle/branches/evaluableExpression-umlet/)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/491#-:-K7asp7fa8ERi703QxD2:-1023181494)*

**Comment by acBerger** [comment]
As Travis failed trying to build the design document you probably did something wrong here.

---

Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/491#-:-K7avWZLiJ4n4pHW-YK1:-937765887)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Documentation/src/design/lyx/Parts/Component Beagle Core.lyx, line 543 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/491#-K7avo_xTAgugOn0HSTp:-K7avo_xTAgugOn0HSTq:-1292415464) ([raw file](https://github.com/beagle-pse/beagle/blob/7c43ac3dde07676913afe61a2612178282e8a16f/Documentation/src/design/lyx/Parts/Component Beagle Core.lyx#L543)):*
You need to specify the width and height for the image. See the others for an example (that’s why Travis is failing)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/491)*

**Comment by acBerger** [comment]
This is not as it should be. Maybe @jGleitz Tip can help here.


---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/491#-:-K7b7yXtEgfL4uAHm_BJ:-755027223)*

**Comment by acBerger** [comment]
As the picture is not that great: Your diagram is a lot bigger than the page.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/491#-:-K7b89B_Yjjvk7EB2BfG:1719424912)*

**Comment by flyfl** [comment]
I see. How can I set the size?

**Comment by jGleitz** [comment]
> I see. How can I set the size?

Double Click on the image element tick “Breite festlegen“ and „Höhe festlegen”. Set them to „100 Textbreite %“ and „100 Texthöhe %“, respectively. Tick „Seitenverhältnis beibehalten“

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/491#-:-K7bGNjLXFDud7LjAhQC:-723250620)*

**Comment by RomanLangrehr** [comment]
[Website](http://flyfl.github.io/Beagle/branches/evaluableExpression-umlet/)


Please remove the `?`


I think this is cutted.

---

Reviewed 1 of 1 files at r3, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/491#-:-K7bMANgaDm0r8LlcIRI:1934807433)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/491#-:-K7bXc_uLD-1xGpDXI4m:980077423)*

**Comment by RomanLangrehr** [comment]
Reviewed 1 of 1 files at r4.
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[Documentation/src/design/lyx/Parts/Component Beagle Core.lyx, line 543 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/491#-K7avo_xTAgugOn0HSTp:-K7bXjYvu6lzeTTWUpLO:-304131500) ([raw file](https://github.com/beagle-pse/beagle/blob/7c43ac3dde07676913afe61a2612178282e8a16f/Documentation/src/design/lyx/Parts/Component Beagle Core.lyx#L543)):*
I think this done...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/491)*

**Comment by jGleitz** [comment]
Please fix the cut classes: 



---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/491#-:-K7bkSeGMuoKYXbu5AdH:-1918759704)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/491#-:-K7bpf08Wf_Qou0q4TCk:980077423)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/491#-:-K7bppuQu-AbnSEtaC64:1417088721)*

**Pull request merged**
