### PR TITLE
GUI Enhancements

### PR DESCRIPTION
**Pull request by jGleitz**
This PR tunes up our GUI quite a bit.

 * Clearer control flow: 
   * Following the MVC pattern, there is now a `GuiController`. Any changes at the GUI are instructed by it. All components report to it.
   * The `while` loop was replaced by a callback based button handling.
 * Nicer UI
    * Made more elaborate messages
    * Instead of closing and re-opening them, the dialogs are updated
    * The user is promted to confirm before the analysis is aborted.
 * Failure Handler. I added a graphical failure resolver.
 * Bug fixes. Additional to the fixes from #792, the PR contains fixes for some synchronisation and other errors.

The PR also contains a fix for the Failure API. Previously, setting the resolve strategy would have to take place before class loading—hard to achieve.
Now, the resolve strategy will only be selected when the failure is reported, setting it can thus take place any time before the failure.

As most GUI code, this PR surely contains bugs. I tested the most common cases by hand and everything I did worked as expected. However, reviewing this carefully and playing around with it is surely a good idea.

Because of the use of many threads, there is a lot of potential for race conditions. In most cases, they do no harm, in others I used appropriate synchronisations. I didn’t always go for the fastest solution, but sometimes took the one that was easiest to implement.

---
This change is [Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/796)

### CODE REVIEW

**Comment by viridispirus** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/AnalysisController.java, line 162 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCPb6jjuKgMzQ1QsRAe:-KCPb6jjuKgMzQ1QsRAf:-1643550369) ([raw file](https://github.com/beagle-pse/beagle/blob/3c1879ef781b437ca9f12ae617396047a6c4cb76/Core/src/main/java/de/uka/ipd/sdq/beagle/core/AnalysisController.java#L162)):*
Why is here the same loop twice?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by viridispirus** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/AnalysisController.java, line 162 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCPb6jjuKgMzQ1QsRAe:-KCPf6bYNsPGE0SIOyAQ:-1376152138) ([raw file](https://github.com/beagle-pse/beagle/blob/3c1879ef781b437ca9f12ae617396047a6c4cb76/Core/src/main/java/de/uka/ipd/sdq/beagle/core/AnalysisController.java#L162)):*
Done.  Reviewable showed it to me twice, now it's fine.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by acBerger** [comment]
:lgtm: :white_check_mark: 

---

Reviewed 1 of 16 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-:-KCR95FVu6C8pzaqDN4P:-1603124213)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCR9qkTWXjz_Z4zaQdo:-KCR9qkTWXjz_Z4zaQdp:-1226791292) (no related file):*
+@viridispirus can you please execute the existing manual tests on this PR? It should still fulfil all existing requirements.

If you have the chance to extend the manual tests to the new features, that would be awesome!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by acBerger** [comment]
Reviewed 15 of 16 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by m1cm1c** [comment]
This branch is out-of-date with the base branch.

**Comment by RomanLangrehr** [comment]
:lgtm:

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCR9qkTWXjz_Z4zaQdo:-KCRIjaHPbFYt3iXLXL1:-1296683943) (no related file):*
The new features are the abort dialog (should show are "Are you sure?"-Dialog, The graphical failure handler and the Progress window.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-:-KCRJCT16nY-AZU02lgb:1417088721)*

**Comment by acBerger** [comment]
:o: as this should be tested by hand first

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-:-KCRMWvAhXTRWdZ7azNo:-460443907)*

**Comment by viridispirus** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCR9qkTWXjz_Z4zaQdo:-KCRQbb_bo53hfEDCpZR:1045424502) (no related file):*
ok, when I configure the constant timeout and let the field empty, the run button don't gray out and it crash when I press it than.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by acBerger** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCR9qkTWXjz_Z4zaQdo:-KCRUmvhCsSS_AUFN444:34914554) (no related file):*
Please report this in a separate issue. The run configuration is not part of this PR.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCR9qkTWXjz_Z4zaQdo:-KCV5Ng8yyx6mxZseIVu:-1685766072) (no related file):*
@viridispirus did your PR mean that you’re finished testing this?

Please do not forget to open an issue for what you found with the run configuration.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by viridispirus** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCR9qkTWXjz_Z4zaQdo:-KCV6xwN1cO7Spoq4V5N:-1992961684) (no related file):*
No, I could not test the progress bar and the abort dialog yet because I got errors when I try to run Beagle.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCR9qkTWXjz_Z4zaQdo:-KCVM35pSEj8HXAHyiT9:-1871267068) (no related file):*
I see. The errors you get might get fixed by #800 (Fix #770 - IllegalStateException). Please note that there is no progress bar but only a window stating that Beagle is analysing.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by viridispirus** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCR9qkTWXjz_Z4zaQdo:-KCdlqkAwi3hzw30r7zn:1361062414) (no related file):*
The abort dialog does not appear by pressing it and it seems that this don't stop Beagle. And the pause button does nothing by me to.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCR9qkTWXjz_Z4zaQdo:-KCeRJGBzYF4cc099qKU:-105575671) (no related file):*
Please note that both the abort functionality and the pause functionality are *not* yet properly implemented. So hitting abort and pause will have recognisable effect on the analysis.

I tried to implement the following state machine:



(Every state is a GUI window (except Eclipse, that stands for “No Beagle in sight”), every state transition starting with “Beagle” is triggered by Beagle, every other state transition is triggered by the user clicking something)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by viridispirus** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCR9qkTWXjz_Z4zaQdo:-KCeV8jsqCiD9rSECnww:1563257567) (no related file):*
ok, but the "Do you really want to abort?" dialog  do not appear.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by viridispirus** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCR9qkTWXjz_Z4zaQdo:-KCgPEoQ-w_hV1lWO5oC:1698327557) (no related file):*
The dialog not appear problem is solved. But there is an other problem now. After clicking 'abort' and than 'no' in the beagle abort dialog the text 'Beagle is analysing the project.' disappear.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by jGleitz** [comment]
Review status: 13 of 15 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCR9qkTWXjz_Z4zaQdo:-KCh2yLlbCXNhc5FwSb7:1652917864) (no related file):*
> the text 'Beagle is analysing the project.' disappear.

This should now be fixed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by acBerger** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by viridispirus** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by viridispirus** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by acBerger** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCjnyiuM43im6DWi55Y:-KCjnyiuM43im6DWi55Z:1538123646) (no related file):*
I tried this again and clicked on "Pause" as Beagle was running. There was then a new window opened saying "Beagle was aborted because the problem could not be solved". I do not think this is how it should be.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by acBerger** [comment]
:lgtm: :white_check_mark: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCjnyiuM43im6DWi55Y:-KCjqJfYp6slgxe9aktj:-2066567456) (no related file):*
I am sorry, this was my fault.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-:-KCjqNSCCRCndwrFC5rM:-1603124213)*

**Comment by acBerger** [comment]
Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-:-KCk4GIZB4z8xH45e4pQ:1417088721)*

**Comment by RomanLangrehr** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5, 1 of 2 files at r6, 2 of 2 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-:-KCkBJmOQT7BVlKTVtgP:1417088721)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCkxPAT6Lzi0MckMyIX:-KCkxPAU9g9DWbEfLi5G:-458844510) (no related file):*
This breakes the context menus, see #815 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by jGleitz** [comment]
Review status: 17 of 21 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCkxPAT6Lzi0MckMyIX:-KCkyib36egtaceuf9wn:-1620474753) (no related file):*
fixed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by m1cm1c** [comment]
Review status: 17 of 21 files reviewed at latest revision, 4 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java, line 131 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCkyiqdqJKa2SrnK3Eq:-KCkyiqdqJKa2SrnK3Er:216635604) ([raw file](https://github.com/beagle-pse/beagle/blob/79f702e983f406adb8659695088a111a7ee30aec/Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java#L131)):*
Why is this changed?

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java, line 140 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCkylimV1bo-1mTU5s0:-KCkylimV1bo-1mTU5s1:216635604) ([raw file](https://github.com/beagle-pse/beagle/blob/79f702e983f406adb8659695088a111a7ee30aec/Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java#L140)):*
Why is this changed?

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java, line 150 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCkymgpyKmpmbwoDR5a:-KCkymgpyKmpmbwoDR5b:216635604) ([raw file](https://github.com/beagle-pse/beagle/blob/79f702e983f406adb8659695088a111a7ee30aec/Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java#L150)):*
Why is this changed?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by acBerger** [comment]
Reviewed 4 of 4 files at r10.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java, line 131 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCkyiqdqJKa2SrnK3Eq:-KCkz-hWhL21_gYoHOFg:-1294361338) ([raw file](https://github.com/beagle-pse/beagle/blob/79f702e983f406adb8659695088a111a7ee30aec/Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java#L131)):*
Because it’s not true, is it? The method is not ignoring the calls. `AnalysisController` will be ignoring the calls, but you cannot rely on that because it could change.
If you want to have that comment back, I can write something like “The calls will be directed to the `{@link AnalysisController}` started by this controller.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java, line 140 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCkylimV1bo-1mTU5s0:-KCkzcPOBryqLoNU2gyq:-1294361338) ([raw file](https://github.com/beagle-pse/beagle/blob/79f702e983f406adb8659695088a111a7ee30aec/Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java#L140)):*
Because it’s not true, is it? The method is not ignoring the calls. `AnalysisController` will be ignoring the calls, but you cannot rely on that because it could change.
If you want to have that comment back, I can write something like “The calls will be directed to the `{@link AnalysisController}` started by this controller.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java, line 150 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCkymgpyKmpmbwoDR5a:-KCkzd32S4iB_C-isf1u:-1294361338) ([raw file](https://github.com/beagle-pse/beagle/blob/79f702e983f406adb8659695088a111a7ee30aec/Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java#L150)):*
Because it’s not true, is it? The method is not ignoring the calls. `AnalysisController` will be ignoring the calls, but you cannot rely on that because it could change.
If you want to have that comment back, I can write something like “The calls will be directed to the `{@link AnalysisController}` started by this controller.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by m1cm1c** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java, line 131 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCkyiqdqJKa2SrnK3Eq:-KCl-0-uxKO-sYH_zCLS:-1245742041) ([raw file](https://github.com/beagle-pse/beagle/blob/79f702e983f406adb8659695088a111a7ee30aec/Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java#L131)):*
Yes, that'd be better.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by jGleitz** [comment]
Review status: 20 of 21 files reviewed at latest revision, 4 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java, line 131 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCkyiqdqJKa2SrnK3Eq:-KCl1A56TBWUA5a7DwY2:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/79f702e983f406adb8659695088a111a7ee30aec/Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java#L131)):*
Done.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java, line 140 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCkylimV1bo-1mTU5s0:-KCl1AycUDq3ktmzQ-41:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/79f702e983f406adb8659695088a111a7ee30aec/Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java#L140)):*
Done.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java, line 150 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCkymgpyKmpmbwoDR5a:-KCl1B_eM73FT4EZJeSv:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/79f702e983f406adb8659695088a111a7ee30aec/Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java#L150)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by viridispirus** [comment]
Review status: 20 of 21 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCR9qkTWXjz_Z4zaQdo:-KCl5FtB1ghNlQpMbk1h:-1542993645) (no related file):*
Well Done. It's working. :lgtm:  :white_check_mark: 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by m1cm1c** [comment]
Reviewed 1 of 1 files at r11.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Comment by m1cm1c** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/796#-KCR9qkTWXjz_Z4zaQdo:-KCl74idLNEXIwO_EyRH:1417088721) (no related file):*
:lgtm:

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/796)*

**Pull request merged**
