### PR TITLE
Beagle launch configuration

### LINKED ISSUE #717: Realise the GUI as Eclipse Launch Configuration

### LINKED ISSUE #744: Allow the User to Set the Launch Configurations
The user shall be able to select the launch configurations they want to use to execute the measured software. Depends on #717

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Depends on #752 

Fixes #744 
Fixes #717

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/775)

### CODE REVIEW

**Comment by acBerger** [comment]
Reviewed 41 of 41 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/775)*

**Comment by acBerger** [comment]
-blocked as #752 is merged.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/775#-:-KCBO-_Q7-5EkEpYmuCG:-119958647)*

**Comment by acBerger** [comment]
Reviewed 3 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/775)*

**Comment by acBerger** [comment]
Reviewed 2 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/775)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/775)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/775)*

**Comment by acBerger** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/775)*

**Comment by viridispirus** [comment]
Reviewed 4 of 41 files at r1, 1 of 4 files at r3, 1 of 2 files at r6.
Review status: 25 of 26 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/775)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r8.
Review status: 25 of 26 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/775)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/775)*

**Comment by viridispirus** [comment]
Reviewed 18 of 41 files at r1, 1 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/775)*

**Comment by viridispirus** [comment]
Reviewed 1 of 41 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/775)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/775#-:-KCC_ftPBsn_h-Xy5qzp:1417088721)*

**Comment by viridispirus** [comment]
:white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/775#-:-KCC_fNJDiwUZj8Zs85P:1605498549)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/775#-:-KCC_tzjQfVAYxSx3-Xb:980077423)*

**Pull request merged**
