### PR TITLE
PalladioFileShare System Test

### PR DESCRIPTION
**Pull request by jGleitz**
This PR introduces a Launch Configuration that will automatically execute SoMoX and Beagle on PalladioFileShare, an evaluation project of the SDQ. The test classes are in the root project.

The PR additionally fixes the issue where the command line of “Beagle in Eclipse” could get too long on Windows.

This PR needs 5 lgtm, because I think it’s crucial that everybody can run these tests.

To test it please do at least the following

 * Checkout this PR
 * Run gradle
 * Run the “Beagle in Eclipse” launch configuration
    * You should get an inner Eclipse.
    * You should be able to execute SoMoX in the inner Eclipse.
    * You should be able to run Beagle in the inner Eclipse.
 * Run the “Beagle PalladioFileShare System Test” launch configuration (you’ll propably have to access it through Run > Run Configurations)
    * An inner Eclipse should open
    * SoMoX should be executed in the inner Eclipse
    * Beagle should be executed in the inner Eclipse
    * at the time being, the test does not terminate
    * There will be a lot of red output on the outer console. Ignore it.

Please post whether the above works for you.

---
This change is [Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/804)

### CODE REVIEW

**Comment by jGleitz** [comment]
As @acBerger correctly reported, you can and should delete the `Beagle/src/test/resources/CoCoME` folder by hand.

**Comment by acBerger** [comment]
:lgtm: (works for me now)

---

Review status: 15 of 29 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCXYoUn0_5LTPnZI0Io:2092300333)*

**Comment by m1cm1c** [comment]
I got an error that lambdas were used without Java 8 activated in `Workspace.java` arount line 245. Eclipse was able to automatically change the project settings to Java 8.

When running the launch configuration, all tests fail because of `java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils`. Stacktrace of one test: https://gist.github.com/m1cm1c/cd4a16e7f2c2a741ad20

Furthermore I get a NullPointerException: https://gist.github.com/m1cm1c/c1329190d07d931a6198

---

Review status: 15 of 29 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCY7N3gT5pcaHbSqS5k:1676687479)*

**Comment by jGleitz** [comment]
> I got an error that lambdas were used without Java 8 activated in `Workspace.java` arount line 245. Eclipse was able to automatically change the project settings to Java 8.

Please push the changed project files into this branch since there seems to be an Eclipse setup that needs them.

> When running the launch configuration, all tests fail because of `java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils`.

Please double-check that you ran `gradle` after checking out the branch. Please also check that Eclipse did not make any modifications to the launch configurations.

> Furthermore I get a NullPointerException: 

That’s related to the other one, Eclipse throws it when it finds unresolved dependencies.

---

Review status: 15 of 29 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KC_2InVIAUSRhealxxp:928975214)*

**Comment by flyfl** [comment]
**FIX for Windows**: On Windows I had to modify the "Beagle in Eclipse" Run configuration by adding a windows specific SWT plugin.

**Problem**: I could not fix this problem, when I try to start Somox in inner Eclipse:

>!ENTRY org.eclipse.core.jobs 4 2 2016-03-11 12:26:19.662
!MESSAGE An internal error occurred during: "Launching New_configuration".
!STACK 0
java.lang.NoClassDefFoundError: de/uka/ipd/sdq/beagle/core/pcmsourcestatementlink/PcmSourceStatementLinkRepository
	at de.uka.ipd.sdq.beagle.pcmsourcestatementlink.somoxextractor.PsslExtractionJob.extract(PsslExtractionJob.java:81)
	at de.uka.ipd.sdq.beagle.pcmsourcestatementlink.somoxextractor.PsslExtractionJob.execute(PsslExtractionJob.java:62)

---

Review status: 15 of 29 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KC_Rhmh3RsUFCtE4B6l:-1878112796)*

**Comment by jGleitz** [comment]
>  java.lang.NoClassDefFoundError: de/uka/ipd/sdq/beagle/core/pcmsourcestatementlink/PcmSourceStatementLinkRepository

This sounds like you don’t have the latest PCM Source Statement Link Extractor. Please pull the latest version and try again.

> On Windows I had to modify the "Beagle in Eclipse" Run configuration by adding a windows specific SWT plugin.

Can you make a PR on this branch that contains the change you had to make? (I’d like to review it before merging it in, those launch configurations are highly sensible).

---

Review status: 15 of 29 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KC_TTG68o9S0cmWNhy6:267341190)*

**Comment by flyfl** [comment]
>When running the launch configuration, all tests fail because of java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils. Stacktrace of one test: https://gist.github.com/m1cm1c/cd4a16e7f2c2a741ad20

>Furthermore I get a NullPointerException: https://gist.github.com/m1cm1c/c1329190d07d931a6198

I get both Exceptions of them AND  a **RuntimeException**: /CompressMockup can not be found.

---

Review status: 15 of 29 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KC_is-6QFHJOCWEW4KX:108127189)*

**Comment by jGleitz** [comment]
>  Added windows specific swt plugin to the runconfigurations of -Beagle in Eclipse -Beagle PalladioFileShareSystem System Test

I explicitly asked you to create a separate PR for this! Your changes broke things for the Linux/GNU folks, now I have to sort that out!

> I get both Exceptions of them

You are sure you ran gradle? Please check whether the file `Beagle/build/dependencies.jar` exists.

> RuntimeException: /CompressMockup can not be found.

As long as the other exceptions occur, we can ignore that one. It will likely go away once we soved the others.

---

Review status: 15 of 29 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KC_yM8O73hxEcpIVFTN:1802021048)*

**Comment by m1cm1c** [comment]
Review status: 14 of 29 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-KCa0q8p3JIyG5I9lsTu:-KCa0q8q1h1YtZl1eI5o:1073316256) (no related file):*
I didn't now running gradle beforehand was necessary so I undid my local changes and tried again. Now 1 test doesn't fail. `m1runSomox` and `m2runBeagle` still fail. This is the stacktrace of the error which occurred to `m1runSomox`: https://gist.github.com/m1cm1c/f5b70866c9233c8678f6 It produced this console output: https://gist.github.com/m1cm1c/4f761b85c48cf9de8a78

This time I didn't set the project Java version to Java 8 but instead changed my workspace appropriately so there are no changes to push. The failing tests (including their stacktraces) remained the same but the console output changed to https://gist.github.com/m1cm1c/d49a310141ea7ac3de73 . `PcmSourceStatementLinkReader.java` is where it belongs:



---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804)*

**Comment by flyfl** [comment]
>I explicitly asked you to create a separate PR for this! Your changes broke things for the Linux/GNU folks, now I have to sort that out!

I'm sorry. It seems that I have skip your remark and just though you would mean our Master where to merge this changes.

>You are sure you ran gradle? Please check whether the file Beagle/build/dependencies.jar exists.

Yes this exists. I have already commented out the 2 failing test cases on my machine so that gradle build keeps running until it has finished every task.

**Comment by acBerger** [comment]
:lgtm:

---

Review status: 14 of 29 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCa6vig9Ku8cq-9eHhh:1417088721)*

**Comment by jGleitz** [comment]
Review status: 14 of 29 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-KCa0q8p3JIyG5I9lsTu:-KCa55hHAK4eL-2HCo4c:1220480268) (no related file):*
>  This is the stacktrace of the error which occurred to m1runSomox

This really looks like the error I fixed in the PCM Source Statement Link Extractor the other day. Are you 100% sure your version of it is up-to-date? The latest revision is 31354 “Refresh output folder after writing the result”

>  It produced this console output:

This is the normal output. Don’t ask me where that `ClassFormatException` comes from. But it’s an error in SoMoX (or JaMoPP) and none of our business.

> but the console output changed to […]

I cannot see the difference between the two logs. Can you please point it out?

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-KCa4oWbV883ct-c7V01:-KCa4oWcZKwjt2yF3C5x:2124378565) (no related file):*
@flyfl Please check whether the run configurations I pushed work on Windows.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804)*

**Comment by m1cm1c** [comment]
Reviewed 25 of 29 files at r1, 1 of 1 files at r2, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804)*

**Comment by m1cm1c** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCaBhkwcC2TFy2Tq7Qw:1417088721)*

**Comment by flyfl** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCaFOv4hRyJTWkqNS-E:1417088721)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: 28 of 29 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCaKE_2jYsEXFE7U1mN:1417088721)*

**Comment by flyfl** [comment]
:lgtm:

**Comment by m1cm1c** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804)*

**Comment by m1cm1c** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCaNXBj9wugZw4088p1:1417088721)*

**Comment by RomanLangrehr** [comment]
I get this exception:

Looks like there is problem in URI  to file path conversion.

---

Reviewed 25 of 29 files at r1, 1 of 1 files at r2, 1 of 3 files at r4, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCb12w7XbJl3NxNHrBJ:-1047437091)*

**Comment by jGleitz** [comment]
Would the path be correct if the `%20` would be replaced by spaces?

It’s interesting that only you are getting this error, because everyone has the spaces. The URL to path conversion was taken from the Kieker Measurement Tool, where the two of us spend a lot time on getting it right.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCb1y-_ATbjt0Gqmb_E:1021681389)*

**Comment by RomanLangrehr** [comment]
> Would the path be correct if the %20 would be replaced by spaces?

Yes.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCb5vP653lHxEvOtcws:1076795876)*

**Comment by jGleitz** [comment]
Wow. It took me ages to find out what was going on. But finally, with the help of @viridispirus , I think I found a fix. Please try it!

---

Review status: 28 of 29 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCbVOLx0ukxUZUdQbMz:840331707)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: 28 of 29 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCbYCo9X56wqnP83Gkd:980077423)*

**Comment by viridispirus** [comment]
:white_check_mark: 

---

Review status: 28 of 29 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCbYOuwJ9Huk9RMoGYl:1605498549)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: 28 of 29 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCbbuhVZFDFTM-GB2iQ:1417088721)*

**Comment by m1cm1c** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804)*

**Comment by m1cm1c** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCbjR6_Y8KMPaiCfNKu:1417088721)*

**Comment by RomanLangrehr** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCbro8fahtyt6nauYCV:1417088721)*

**Comment by jGleitz** [comment]
+@flyfl please try it again, too. 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCbrvfa5rdB4PrRy40L:-717339091)*

**Comment by viridispirus** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCdjUr_8WaTrqesdvL8:1417088721)*

**Comment by flyfl** [comment]
:lgtm:

**Comment by jGleitz** [comment]
I had to make adaptations to the build logic to make this PR compatible to the new Averaging Measurement Result Analyser Plugin. 

So one last round of LGTMs and we can finally get this merged.

As you can see, I did not change any logic related to the system tests. -@flyfl 

---

Review status: 28 of 33 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCf9JrPmHAUre0UlUE2:1768435966)*

**Comment by RomanLangrehr** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r7, 1 of 1 files at r8, 4 of 4 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCfDJecsK-suIugjJsc:1417088721)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCfEt4fBAZHOGVoa_ra:1417088721)*

**Comment by m1cm1c** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitignore, line 46 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-KCfF1wdtJJUZxzKcC-3:-KCfF1wdtJJUZxzKcC-4:417518403) ([raw file](https://github.com/beagle-pse/beagle/blob/62913527bcd9bb60eb3a938dd1b5745d1bf98001/.gitignore#L46)):*
Wouldn't it be a better idea to delete `.subversion` instead of ignoring it?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitignore, line 46 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-KCfF1wdtJJUZxzKcC-3:-KCfGvwUmA9ij9rIo1PD:367845759) ([raw file](https://github.com/beagle-pse/beagle/blob/62913527bcd9bb60eb3a938dd1b5745d1bf98001/.gitignore#L46)):*
Yeah, probably.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804)*

**Comment by viridispirus** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCfInSKbU25Jf3Gq-Mu:1417088721)*

**Comment by jGleitz** [comment]
Review status: 31 of 33 files reviewed at latest revision, 1 unresolved discussion.

---

*[.gitignore, line 46 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-KCfF1wdtJJUZxzKcC-3:-KCfKFJrRPavebT5KWaS:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/62913527bcd9bb60eb3a938dd1b5745d1bf98001/.gitignore#L46)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: 31 of 33 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCfQ7LVD4VJgkYmBGHw:1417088721)*

**Comment by m1cm1c** [comment]
Reviewed 1 of 2 files at r6, 1 of 1 files at r8, 3 of 4 files at r9, 1 of 2 files at r10.
Review status: 32 of 33 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804)*

**Comment by m1cm1c** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCfQvt1tKh3Ss4wBJJn:1417088721)*

**Comment by RomanLangrehr** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCfRJSBCrSV_I-6fJla:1417088721)*

**Comment by viridispirus** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCfRTJtWwodnYYKt7KK:1417088721)*

**Comment by jGleitz** [comment]
I’m **so sorry** but after #780 (Measurement result analyser plugin) got merged, I forgot to add the Averaging Measurement Result Analyser to the list of included plugins.

So if you could try it one more time…

---

Review status: 31 of 33 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCfVHrfanDe2pk8j194:1264779927)*

**Comment by RomanLangrehr** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCfW5wZDin-KyyIrydE:1417088721)*

**Comment by viridispirus** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCfWnKuATK5ZGsDV4Pz:1417088721)*

**Comment by m1cm1c** [comment]
Reviewed 2 of 2 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804)*

**Comment by m1cm1c** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCfa-E-JzMRkispnpHz:1417088721)*

**Comment by flyfl** [comment]
:lgtm:

**Comment by acBerger** [comment]
does not work for me.  
```
The compilation failed

Details:
Compilation Output: ----------
1. WARNING in /tmp/beagle-kieker-measurement7710943881011624583/instrumented-src/de/uka/ipd/sdq/palladiofileshare/algorithms/SimpleLZW.java (at line 195)
	if (window_wc == null) {
					// if(LOUD) System.out.println("prm null -> -1");
					windowDictPos = -1;
				} else {
	                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dead code
----------
2. WARNING in /tmp/beagle-kieker-measurement7710943881011624583/instrumented-src/de/uka/ipd/sdq/palladiofileshare/algorithms/SimpleLZW.java (at line 544)
	if (RUN_VERSION==0) {
	    ^^^^^^^^^^^^^^
Comparing identical expressions
----------
----------
3. WARNING in /tmp/beagle-kieker-measurement7710943881011624583/instrumented-src/de/uka/ipd/sdq/palladiofileshare/businesslogic/BusinessCore.java (at line 3)
	import java.util.Arrays;
	       ^^^^^^^^^^^^^^^^
The import java.util.Arrays is never used
----------
4. WARNING in /tmp/beagle-kieker-measurement7710943881011624583/instrumented-src/de/uka/ipd/sdq/palladiofileshare/businesslogic/BusinessCore.java (at line 17)
	import de.uka.ipd.sdq.palladiofileshare.testdriver.TestDriver;
	       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The import de.uka.ipd.sdq.palladiofileshare.testdriver.TestDriver is never used
----------
----------
5. WARNING in /tmp/beagle-kieker-measurement7710943881011624583/instrumented-src/de/uka/ipd/sdq/palladiofileshare/businesslogic/storage/Storage.java (at line 42)
	fileOutStream = new FileOutputStream(fileStorageLocation + hashString);		
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Resource leak: 'fileOutStream' is never closed
----------
6. ERROR in /tmp/beagle-kieker-measurement7710943881011624583/instrumented-src/de/uka/ipd/sdq/palladiofileshare/businesslogic/storage/Storage.java (at line 60)
	de.uka.ipd.sdq.beagle.measurement.kieker.remote.MeasurementCentral.stopResourceDemand();
	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Unreachable code
----------
----------
7. WARNING in /tmp/beagle-systemtest7960350335757619494/PalladioFileShare/src/de/uka/ipd/sdq/palladiofileshare/testdriver/TestDriver.java (at line 376)
	FileOutputStream fw = new FileOutputStream(fileSizesCSVPath);
	                 ^^
Resource leak: 'fw' is never closed
----------
8. WARNING in /tmp/beagle-systemtest7960350335757619494/PalladioFileShare/src/de/uka/ipd/sdq/palladiofileshare/testdriver/TestDriver.java (at line 524)
	FileOutputStream fos = new FileOutputStream("./results/"+
	                 ^^^
Resource leak: 'fos' is never closed
----------
8 problems (1 error, 7 warnings)


Used command line options: -d "/tmp/beagle-kieker-measurement7710943881011624583/bin" -classpath "/usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/localedata.jar:/tmp/beagle-systemtest7960350335757619494/PalladioFileShare/config:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/nashorn.jar:/tmp/beagle-systemtest7960350335757619494/PalladioFileShare/lib/JbcParser.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/jaccess.jar:/tmp/beagle-systemtest7960350335757619494/PalladioFileShare/lib/log4j-1.2.15.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/tmp/beagle-systemtest7960350335757619494/PalladioFileShare/lib/opencsv-1.8.jar:/tmp/beagle-systemtest7960350335757619494/PalladioFileShare/src:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/tmp/beagle-systemtest7960350335757619494/CompressMockup/src:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunjce_provider.jar" -classpath "/tmp/beagle-kieker-measurement7710943881011624583/bin" -encoding UTF-8 "/tmp/beagle-kieker-measurement7710943881011624583/instrumented-src" -1.8

	at de.uka.ipd.sdq.beagle.core.failurehandling.ExceptionThrowingFailureHandler.handle(ExceptionThrowingFailureHandler.java:37)
	at de.uka.ipd.sdq.beagle.measurement.kieker.EclipseCompiler.compile(EclipseCompiler.java:133)
	at de.uka.ipd.sdq.beagle.measurement.kieker.KiekerMeasurementTool.doMeasure(KiekerMeasurementTool.java:80)
	at de.uka.ipd.sdq.beagle.measurement.kieker.KiekerMeasurementTool.measure(KiekerMeasurementTool.java:44)
	at de.uka.ipd.sdq.beagle.core.measurement.MeasurementController.measure(MeasurementController.java:130)
	at de.uka.ipd.sdq.beagle.core.AnalysisController.performAnalysis(AnalysisController.java:146)
	at de.uka.ipd.sdq.beagle.core.facade.BeagleController.startAnalysis(BeagleController.java:108)
	at de.uka.ipd.sdq.beagle.gui.ProgressDialogController.runAnalysis(ProgressDialogController.java:169)
	at de.uka.ipd.sdq.beagle.gui.ProgressDialogController.lambda$0(ProgressDialogController.java:158)
	at java.lang.Thread.run(Thread.java:745)```

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCfe3uMVaZEDpcVh5z9:-7098497)*
<!-- Sent from Reviewable.io -->

**Comment by jGleitz** [comment]
@acberger : That exception is caused by my instrumentation code. I’m going to try to fix this, but the exception proves that the system test itself works (because Beagle is being executed).

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCfj6jhuJzzdbs2D31b:811238933)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCg8aYSKDMdbINnMfxZ:1417088721)*

**Comment by acBerger** [comment]
:white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/804#-:-KCg8fhsbCzRoO_E07XW:1605498549)*

**Pull request merged**
