### PR TITLE
Minor Change on /P10/. Fixes #220.

### LINKED ISSUE #220: /P10/ grammer
> Beagle enables the user to analyse given source code regarding the resources
its internal actions’ demand when executed.

I don'T think this is a correct sentence.

### PR DESCRIPTION
**Pull request by m1cm1c**

### CODE REVIEW

**Comment by acBerger** [comment]
lgtm

**Comment by RomanLangrehr** [comment]
[PDF](http://m1cm1c.github.io/Beagle/branches/p10/Requirements%20Specification.pdf)

**Comment by RomanLangrehr** [comment]
There is still the "its", which makes no sense there, in my opinion.

**Comment by jGleitz** [comment]
> There is still the "its", which makes no sense there, in my opinion.

It does. It indicates that the resource demands belong to the source code.

**Comment by RomanLangrehr** [comment]
> It does. It indicates that the resource demands belong to the source code.

Alright. I belive in your english.
Lgtm.

**Pull request merged**
