### PR TITLE
Views from model

### PR DESCRIPTION
**Pull request by viridispirus**
Added classes Final Judge View and Measurement View to the Beagle Core design.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/309)

### CODE REVIEW

**Comment by viridispirus** [comment]
The methods will follow soon.

**Comment by RomanLangrehr** [comment]
Lgtm

**Comment by jGleitz** [comment]
Please remove `{unique}`:

unique

**Comment by jGleitz** [comment]
I think the views should be called <pre>Final Judge <b>[Blackboard ]</b>View</pre> and <Measurement <b>[Blackboard ]</b>View</pre>

**Comment by m1cm1c** [comment]
not mergeable

**Pull request closed without merging**
