### PR TITLE
Added PCM Connection to the Diagrams

### LINKED ISSUE #531: Create Classes and Javadoc for PCM

### PR DESCRIPTION
**Pull request by flyfl**
Javadoc is already there.
fixes #531

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/541)

### CODE REVIEW

**Comment by acBerger** [comment]
Did you add the Diagram to the Document? If yes: what is the name?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/541#-:-K7gh33YZDJtBVGvsXDQ:253886803)*

**Comment by acBerger** [comment]
[Website] (http://flyfl.github.io/Beagle/branches/PcmConnection-umlet/)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/541#-:-K7ghBjsvDAbCIRAoXti:-584976847)*

**Comment by flyfl** [comment]
>Did you add the Diagram to the Document? If yes: what is the name?

Not yet. Anyone an idea where to put it?

**Comment by acBerger** [comment]
@jGleitz suggests to put it in GUI

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/541#-:-K7gkNjyKJt5ShwRDf7z:1172139470)*

**Comment by RomanLangrehr** [comment]
Zum PCM Beagle Mapping müssen noch die ExternalCallPArameters.

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/541#-:-K7gxZK7VrZ7tEUh_Igw:-1205383214)*

**Comment by viridispirus** [comment]
Please update branch.

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/541#-:-K7h9tyU3nSw-hUlTEwh:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/541#-:-K7h9waMVg3qQmExtEND:980077423)*

**Pull request merged**
