### PR TITLE
Concurrent modification exception fix

### PR DESCRIPTION
**Pull request by flyfl**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/795)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
There are checkstyle problems. Please fix them.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/795#-:-KCPSHnhT1XifRsEaxJU:1737322785)*

**Comment by viridispirus** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/795)*

**Comment by jGleitz** [comment]
+@flyfl please fix this asap, evaluation depends on it!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/795#-:-KCQhsVfGwTzN4lGgP_j:1844596667)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/795#-:-KCRALVCxMu0EmVbCI_N:980077423)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/795)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/795#-:-KCRHk36qSpKDy9gf2cs:980077423)*

**Comment by acBerger** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/795)*

**Comment by jGleitz** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/795#-:-KCRXKpTPIaPl_HQQvBc:1417088721)*

**Comment by RomanLangrehr** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/795#-:-KCRn3uxpshQS3Be7lwy:1417088721)*

**Comment by RomanLangrehr** [comment]
:white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/795#-:-KCRn6c16wVc9CV9Abo0:1605498549)*

**Pull request merged**
