### PR TITLE
Removed unnecessary 'this'

### PR DESCRIPTION
**Pull request by acBerger**
Code Template for Setter created  an 'this' to much. Fixed this

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/421)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
The getter is still generating an `this` to much.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/421#-:-K787OgCJ3LduZqJ4lcv:-1931970200)*

**Comment by acBerger** [comment]
> The getter is still generating an this to much.


Does it work for you now?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/421#-:-K78B2eXiJRaW6wa50Ju:736626402)*

**Comment by RomanLangrehr** [comment]
> Does it work for you now?

Yes 
:lgtm_strong: 

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/421#-:-K78HeqhOXzVbQWtw_MM:2074537444)*

**Comment by jGleitz** [comment]
This still doesn’t seem to be right:



leads to 



but 



leads to



But as this seems to be an Eclipse bug: :lgtm_strong: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/421#-:-K78lUsG6SC-K5g2kRFP:814222522)*

**Pull request merged**
