### PR TITLE
A little bit of Content for the Quality Control Report

### PR DESCRIPTION
**Pull request by m1cm1c**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/783)

### CODE REVIEW

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/783)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/783)*

**Comment by viridispirus** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/783)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/783#-:-KCCNCZLxYZRF6mDATi6:980077423)*

**Comment by acBerger** [comment]
:lgtm: :white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/783#-:-KCCNuiQvTsmQqpB5lio:-1603124213)*

**Pull request merged**
