### PR TITLE
Even more grammar, spelling, and wording fixes

### PR DESCRIPTION
**Pull request by m1cm1c**
This should be everything. I hope ...

### CODE REVIEW

**Comment by jGleitz** [comment]
Unfortunately, this PR contains the changes of #92. Please do not merge before #92!

**Comment by jGleitz** [comment]
[See this PR’s rendered PDF](http://m1cm1c.github.io/Beagle/branches/correcting-spelling/Requirements%20Specification.pdf)

**Comment by acBerger** [comment]
lgtm

**Comment by RomanLangrehr** [comment]
Lgtm

**Pull request merged**
