### PR TITLE
Hamcrest Matcher to Assert That null Cannot be Passed in Collections

### PR DESCRIPTION
**Pull request by jGleitz**
(or arrays).

Depends on #614

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/618)

### CODE REVIEW

**Comment by jGleitz** [comment]
This now also modifies Checkstyle to put no restrictions on where to but a `(`. 

It should be at the end of a line if it opens the parameter list of a method, but if you’re writing an lambda in one line, it does not make sense to put the `(` in the old line. But these differences cannot be defined in the checkstyle configuration.

The Formatter handles these cases a I’d expect, so I doubt it’s going to be an issue.

---

Review status: 0 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/618#-:-K8QcSGyZAbNb4ozbIxv:-646566905)*

**Comment by jGleitz** [comment]
#614 is merged: -blocked 

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/618#-:-K8QdnTh5SqcrsrYxTVA:-1405220610)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 1 of 6 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/618#-:-K8QeJSmFn-r3hRugJST:980077423)*

**Comment by flyfl** [comment]
:lgtm:

**Pull request merged**
