### PR TITLE
Added the PCM tests again.

### PR DESCRIPTION
**Pull request by m1cm1c**
Blocked because this depends on #759.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/769)

### CODE REVIEW

**Comment by acBerger** [comment]
Reviewed 3 of 7 files at r1.
Review status: 3 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769)*

**Comment by m1cm1c** [comment]
@flyfl Please figure out why you throw the exceptions which cause the tests to fail.

**Comment by m1cm1c** [comment]
@flyfl If the exceptions are justified and there are state requirements, please document them in your Javadoc.

**Comment by jGleitz** [comment]
As @flyfl already explained, the exceptions are justified, but they are not actually state exceptions. They are thrown because SoMoX is producing weird input.

---

Review status: 2 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769#-:-KC5hgbVols_6HDUm9Ac:606848102)*

**Comment by jGleitz** [comment]
Please see issue #770 (Injection Exception) 

---

Review status: 2 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769#-:-KC5hv6Ot9_syDD4vJTM:12479043)*

**Comment by viridispirus** [comment]
Reviewed 3 of 7 files at r1.
Review status: 2 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r2.
Review status: 3 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769)*

**Comment by viridispirus** [comment]
Reviewed 1 of 1 files at r2.
Review status: 3 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769)*

**Comment by acBerger** [comment]
Reviewed 1 of 3 files at r3.
Review status: 3 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769)*

**Comment by viridispirus** [comment]
Reviewed 1 of 3 files at r3.
Review status: 3 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769)*

**Comment by viridispirus** [comment]
Reviewed 1 of 1 files at r4.
Review status: 3 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r4.
Review status: 3 of 9 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769)*

**Comment by jGleitz** [comment]
+blocked because it depends on #804 (PalladioFileShare System Test) 

---

Review status: 0 of 44 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769#-:-KCazY_iQAoXzRaBftzS:1205374267)*

**Comment by jGleitz** [comment]
Review status: 0 of 44 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/769#-KCazmqLBIlaoneQmXby:-KCazmqLBIlaoneQmXbz:-885430006) (no related file):*
There are still AppSensor-related resources in this PR. Please remove them.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769)*

**Comment by m1cm1c** [comment]
Review status: 0 of 40 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/769#-KCazmqLBIlaoneQmXby:-KCb1EXH41uoPAFPFAHZ:-499146009) (no related file):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769)*

**Comment by jGleitz** [comment]
How’s progress on this? Where is the problem?

**Comment by flyfl** [comment]
After spending a lot time of searching (no eclipse-debuging was possible!), I found out why one of this tests fails. There is a bug in my RepositoryExtraction implementation for given String Ids. I hope I get this fixed soon.

**Comment by flyfl** [comment]
- Now, one test fails because of a wrong Assertion (It is expected, that a blackboard created by one ID that is not within the Repository should contain something).

- The other test fails, because of expecting that trying to extract something like a picture (.png) should return an IllegalArgumentException instead of the EmfFileHelper throwing a DiagnosticWrappedException. I'm not sure how to cope with this in a proper way. I may catch this exception an generate an IllegalArgumentException. Or I check the File ending, what is a terrible solution in my opinion, because the file ending could be missing, but the file can be correctly instead.

**Comment by m1cm1c** [comment]
> Now, one test fails because of a wrong Assertion (It is expected, that a blackboard created by one ID that is not within the Repository should contain something).

I corrected the test.

Do you half the number of seff branches? There are 2 branches but you only return 1. This could be due to a branches always coming in pairs. Please tell me whether you count pairs or branches.

Your rdia count is way off: I counted 5 but you return 30.

**Comment by jGleitz** [comment]
> Do you half the number of seff branches? There are 2 branches but you only return 1. This could be due to a branches always coming in pairs. Please tell me whether you count pairs or branches.

I’m not really sure if I get you right, but I can explain what *must* happen:

Every `BranchAction` (that’s the PCM class) can contain an arbitrary number of `BranchTransitions`. The PCM connection should return on `SeffBranch` (our class) per found `BranchTransition`.

**Comment by flyfl** [comment]
>The PCM connection should return on SeffBranch (our class) per found BranchTransition.

I think you mean BranchAction? If not I am highly confused.

>Your rdia count is way off: I counted 5 but you return 30.

Thats right. The blackboard should keep for each existing InternalAction all possible kinds of ResourceDemands. And this comes to 6. (6*5 = 30)

**Comment by jGleitz** [comment]
> I think you mean BranchAction?

Oh yes. My bad. That was confusing I guess. The PCM connection should return one `SeffBranch` per `BranchAction`.

The sum of `branches` in the returned `SeffBranches` should equal the sum of `BranchTransitions` in the PCM model.

**Comment by m1cm1c** [comment]
Done.

**Comment by jGleitz** [comment]
@flyfl I had a look at the EMF Code, and I didn’t see a way to check whether this exception will be thrown. So yeah, catching it seems to be the best way to go.

---

Review status: 0 of 41 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769#-:-KCfl2SQxz86vvkZldML:519282325)*

**Comment by jGleitz** [comment]
-blocked 

---

Review status: 0 of 42 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769#-:-KCgX0VigSIOH7B99Avm:-1272864900)*

**Comment by m1cm1c** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryAdder.java, line 79 \[r20\]](https://reviewable.io:443/reviews/beagle-pse/beagle/769#-KCgvFUmWymz4Q4nqepQ:-KCgvFUnUiQp4EoOrH1q:772989062) ([raw file](https://github.com/beagle-pse/beagle/blob/a7a117e6c158112e1c7a8475a56b3a7a09cd7538/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryAdder.java#L79)):*
Please remove this comment.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769)*

**Comment by jGleitz** [comment]
Reviewed 4 of 181 files at r9, 6 of 36 files at r11, 1 of 1 files at r14, 1 of 1 files at r18, 1 of 1 files at r19.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryAdder.java, line 79 \[r19\]](https://reviewable.io:443/reviews/beagle-pse/beagle/769#-KCguVSF9aYHfgKtVyvY:-KCguVSGOlqQMslCl41u:-425218451) ([raw file](https://github.com/beagle-pse/beagle/blob/d22699d9d097060c5ebf392319b0368167d911e1/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryAdder.java#L79)):*
But I am. It will not ;)

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryAdder.java, line 89 \[r19\]](https://reviewable.io:443/reviews/beagle-pse/beagle/769#-KCguadzI_TPzXEjhba1:-KCguae-yySAplecHBfF:-298498740) ([raw file](https://github.com/beagle-pse/beagle/blob/d22699d9d097060c5ebf392319b0368167d911e1/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryAdder.java#L89)):*
Please add a message like "could not load the repository file"

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryExtractor.java, line 201 \[r19\]](https://reviewable.io:443/reviews/beagle-pse/beagle/769#-KCgvD_x6QfBAwFgLybV:-KCgvD_yjIR6eLJK1i6K:771986817) ([raw file](https://github.com/beagle-pse/beagle/blob/d22699d9d097060c5ebf392319b0368167d911e1/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryExtractor.java#L201)):*
What about guarded branch transitions? They should be taken into account to.

Writing 
```
if (identifiedObject instanceof AbstractBranchTransition) 
```

should fix that. (Using instanceof would be a good idea anyway)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r21.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769)*

**Comment by jGleitz** [comment]
Reviewed 6 of 6 files at r23.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769)*

**Comment by acBerger** [comment]
Reviewed 1 of 181 files at r9, 4 of 6 files at r23.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769)*

**Comment by flyfl** [comment]
Review status: 16 of 18 files reviewed at latest revision, 3 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryAdder.java, line 89 \[r19\]](https://reviewable.io:443/reviews/beagle-pse/beagle/769#-KCguadzI_TPzXEjhba1:-KCjg2FGNd7ByTHBV0Ed:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/d22699d9d097060c5ebf392319b0368167d911e1/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryAdder.java#L89)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769)*

**Comment by flyfl** [comment]
Reviewed 1 of 2 files at r24.
Review status: 17 of 18 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769)*

**Comment by acBerger** [comment]
Reviewed 1 of 2 files at r24.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryAdder.java, line 89 \[r19\]](https://reviewable.io:443/reviews/beagle-pse/beagle/769#-KCguadzI_TPzXEjhba1:-KCjm71IX66_J_tl4rIa:-635654522) ([raw file](https://github.com/beagle-pse/beagle/blob/d22699d9d097060c5ebf392319b0368167d911e1/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryAdder.java#L89)):*
Sorry to bother you once again. However, you are discarding the root exception, which makes things significantly harder to debug. So from my point of view, this would be better:

```
throw new IllegalArgumentException("Could not load the repository file " + repositoryFileName, exception);
```

Because like that, you have a good message, but also get the full stack trace.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769)*

**Comment by acBerger** [comment]
+@flyfl please have a look. There are several other PRs depending on it (as #816 is).

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769#-:-KCkxNHZSOJ84luIGAx0:-1203156109)*

**Comment by m1cm1c** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryAdder.java, line 89 \[r19\]](https://reviewable.io:443/reviews/beagle-pse/beagle/769#-KCguadzI_TPzXEjhba1:-KCl6OirYZg2Pf5VpiYd:1867433838) ([raw file](https://github.com/beagle-pse/beagle/blob/d22699d9d097060c5ebf392319b0368167d911e1/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryAdder.java#L89)):*
@flyfl: Please fix this soon.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769)*

**Comment by jGleitz** [comment]
Reviewed 1 of 2 files at r24, 1 of 1 files at r26.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769)*

**Comment by flyfl** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryAdder.java, line 89 \[r19\]](https://reviewable.io:443/reviews/beagle-pse/beagle/769#-KCguadzI_TPzXEjhba1:-KClFsBbyZzRYRS1DJv4:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/d22699d9d097060c5ebf392319b0368167d911e1/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryAdder.java#L89)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769)*

**Comment by m1cm1c** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryExtractor.java, line 201 \[r19\]](https://reviewable.io:443/reviews/beagle-pse/beagle/769#-KCgvD_x6QfBAwFgLybV:-KClLSpOLqGWaefKoQWZ:322177610) ([raw file](https://github.com/beagle-pse/beagle/blob/d22699d9d097060c5ebf392319b0368167d911e1/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryExtractor.java#L201)):*
@flyfl: Do you still remember this exists?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769)*

**Comment by flyfl** [comment]
Review status: 17 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryExtractor.java, line 201 \[r19\]](https://reviewable.io:443/reviews/beagle-pse/beagle/769#-KCgvD_x6QfBAwFgLybV:-KClPFipEmyT697XB6TB:-1135488157) ([raw file](https://github.com/beagle-pse/beagle/blob/d22699d9d097060c5ebf392319b0368167d911e1/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryExtractor.java#L201)):*
Thanks for remember, I could not see this comment. Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r27.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769#-:-KCltOSkr7vrMEPTB1OF:1417088721)*

**Comment by RomanLangrehr** [comment]
Reviewed 4 of 181 files at r9, 6 of 36 files at r11, 6 of 6 files at r23, 1 of 2 files at r24, 1 of 1 files at r26, 1 of 1 files at r27.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryExtractor.java, line 123 \[r30\]](https://reviewable.io:443/reviews/beagle-pse/beagle/769#-KCltijAgPvGTqwqAXBj:-KCltijAgPvGTqwqAXBk:-582241173) ([raw file](https://github.com/beagle-pse/beagle/blob/1d00eaf74934f1ea88e35fdd8f21a70b064c7752/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryExtractor.java#L123)):*
Please turn only a single rule off, not all of them.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769)*

**Comment by acBerger** [comment]
:white_check_mark: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769#-:-KClvY3yJQ15D8iu0S9G:1605498549)*

**Comment by acBerger** [comment]
Review status: 17 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryExtractor.java, line 123 \[r30\]](https://reviewable.io:443/reviews/beagle-pse/beagle/769#-KCltijAgPvGTqwqAXBj:-KCm4py3wUQnM-S1KQ4_:1211272516) ([raw file](https://github.com/beagle-pse/beagle/blob/1d00eaf74934f1ea88e35fdd8f21a70b064c7752/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryExtractor.java#L123)):*
Done. ( I moved a part of the logic into a new method).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769)*

**Comment by RomanLangrehr** [comment]
:lgtm:

---

Review status: 17 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769#-:-KCm6uBevT5guL3Jhg94:1417088721)*

**Comment by RomanLangrehr** [comment]
:white_check_mark: 

---

Review status: 17 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769#-:-KCm6zHRhQFsmokRTEBb:1605498549)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r31.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769#-:-KCm8ZeUlblb_dOJyVAR:980077423)*

**Comment by RomanLangrehr** [comment]
Reviewed 1 of 1 files at r31.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/769)*

**Pull request merged**
