### PR TITLE
IP #095: Building Eclipse projects

### LINKED ISSUE #578: [IP #095] Make gradle build eclipse projects.
Automatically resolve dependencies in `MANIFEST.MF`.

### PR DESCRIPTION
**Pull request by jGleitz**
fixes #578.

This PR
 * puts the Eclipse plugin files where they belong (`src/main/resources/`).
 * explains how to create proper subprojects
 * makes Eclipse dependencies available to eclipse plugin projects
 * can download update sites to make their content available to
 * will add a folder to your `$HOME` that contains ~1.6GB of files
 * doubles the time Travis needs to build our project (~ 5min -> >10min)
 * multiplies the time gradle needs if everything is up-to-date by 5 (<1sec -> <5sec)
 * automatically detects and includes all subprojects for build.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/594)

### CODE REVIEW

**Comment by jGleitz** [comment]
If you wan to test this, [jGleitz/Beagle:wuff](https://github.com/jGleitz/Beagle/tree/wuff) contains a minimal prototype having some dependencies declared in `MANIFEST.MF`.

**Comment by RomanLangrehr** [comment]
Why are there 2 Travis checks?

**Comment by jGleitz** [comment]
> Why are there 2 Travis checks?

Because this branch comes from our Repo. So Travis adds the usual push check to the required status checks, too. (usually this build is private to you and thus not added)

---

Review status: 0 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/594#-:-K89rV3pnVDYXdeXk6wB:-840029050)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: 0 of 22 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/594#-:-K89utPhLvJfmaNDQKiq:980077401)*

**Comment by m1cm1c** [comment]
:lgtm: 

---

Reviewed 23 of 24 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/594#-:-K89vX6k_HZnAhzwQJ87:980077423)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/594#-:-K89wlktxQ-vHAH1DLBy:1417088721)*

**Comment by RomanLangrehr** [comment]
:lgtm: 
(Works for me, too).

---

Reviewed 24 of 24 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/594#-:-K89x9ilKvz4vkET-jh6:-299964693)*

**Pull request merged**
