### PR TITLE
BeagleConfiguration bugfix.

### PR DESCRIPTION
**Pull request by m1cm1c**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/705)

### CODE REVIEW

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/705)*

**Comment by RomanLangrehr** [comment]
:lgtm: :white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/705#-:-KAS6yplrDQQX0hwKrfp:-1603124213)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/705#-:-KAS9pQvBTxJ_igM5DyC:980077423)*

**Comment by m1cm1c** [comment]
The tests for the constructor need to be updated. Since I only forget checking for `null` in the constructor (not in the setter) and Travis didn't fail for the PR before this one, the tests for the setter are obviously insufficient.

**Comment by RomanLangrehr** [comment]
This will be done in tests for project-information/facade

**Comment by m1cm1c** [comment]
But Travis fails.

**Comment by RomanLangrehr** [comment]
:lgtm: :white_check_mark: 
@jGleitz Please renew your lgtm.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/705#-:-KATyusvISJMrLHxBZ6g:-750015570)*

**Comment by RomanLangrehr** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/705)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/705#-:-KAUAsnJeGw9gIoE_lWE:980077423)*

**Pull request merged**
