### PR TITLE
Setup for the Pssl SoMoX Plugin

### PR DESCRIPTION
**Pull request by jGleitz**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/784)

### CODE REVIEW

**Comment by acBerger** [comment]
Reviewed 4 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/784)*

**Comment by acBerger** [comment]
:lgtm: :white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/784#-:-KCCjMbWebBN70G8u5rT:-1603124213)*

**Comment by RomanLangrehr** [comment]
:lgtm:

---

Reviewed 4 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/784#-:-KCCjZ4LmkGtOChHETeF:1417088721)*

**Comment by acBerger** [comment]
:lgtm: :white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/784#-:-KCCpLLUuR3OE-bXgKUl:-1603124213)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/784#-:-KCCpTFW4hEk8cmR2V32:980077423)*

**Pull request merged**
