### PR TITLE
[Checkstyle] Operators at end of line

### LINKED ISSUE #358: `=` Checkystyle vs. Formatter
The formatter formats like this
image

and checkstyle complains about it: `'=' sollte in einer neuen Zeile stehen.`

(at least in prototype checkstyle)

### PR DESCRIPTION
**Pull request by acBerger**
fixes #358

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/362)

### CODE REVIEW

**Comment by jGleitz** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/362#-:-K711OainjbklPSRuF3u:980077423)*

**Comment by RomanLangrehr** [comment]
Now, there is a new problem with strings: 
The formatter formats it like this:


And checkstyle complains: `'+' sollte in der vorangehenden Zeile stehen.`

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/362#-:-K7124XRFDakPjrU3rTY:849733980)*

**Comment by RomanLangrehr** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/362)*

**Comment by acBerger** [comment]
This should fix it.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/362#-:-K71J7Xlg02h36Dt-5YK:1264834792)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/362#-:-K71PnEu4v4wDstUdgll:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/362#-:-K72Yf2Gdos7mhpBqbBd:980077423)*

**Comment by jGleitz** [comment]
this is a test

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/362#-:-K72Z94S_c5aSVid25yo:1359023594)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/362#-:-K72_S899jJt4tlFUE14:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/362#-:-K766iyiXr1BrprZLAQN:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/362#-:-K76DdGgBvhwPtf9oj6_:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/362#-:-K76PDymwaquJ6ek1DLq:-1868698381)*

**Comment by jGleitz** [comment]
As he is the other on to have code to test on: +@m1cm1c 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/362#-:-K76rAtgucekm9xRCHS8:-704588797)*

**Comment by m1cm1c** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/362#-:-K76uutd53BzU60MZUyR:-1868698381)*

**Pull request merged**
