### PR TITLE
Pssl Reader

### PR DESCRIPTION
**Pull request by jGleitz**
Depends on #784

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/785)

### CODE REVIEW

**Comment by viridispirus** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/785)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/785#-:-KCCrX4TRTVwjbvyjCQU:980077423)*

**Comment by acBerger** [comment]
:lgtm: :white_check_mark: 

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/785#-:-KCCtJcU0edOO7A7oZKf:-1603124213)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/785#-:-KCCtcVopVBJgUC5JCiD:980077423)*

**Pull request merged**
