### PR TITLE
PCM Source Statement Links Model

### PR DESCRIPTION
**Pull request by jGleitz**
This took me far too long to create.

This is a model for linking PCM elements to source code statements. It is defined as a XML Schema. Using JAXB, the elements can be mapped onto Java classes to easily work with the model.

This PR contains both the model definition and the build setup necessary to generate the model edit code. The code will automatically be built by gradle and be made available to the Eclipse projects.

A (very short) valid instance of the model would be:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<PcmSourceStatementLinkRepository xmlns="http://sdq.ipd.uka.de/beagle/core/pcmsourcestatementlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <PcmRepositoryFile hash="trndtn50923riosso8593898kesa145" />
    <PcmSourceStatementLink pcmElementId="_drtbzlnseout0vxhgvobzuiaren">
        <FirstStatement sourceCodeFile="org.example.Foo">154</FirstStatement>
        <LastStatement sourceCodeFile="org.example.Bar">178</LastStatement>
    </PcmSourceStatementLink>
    <SourceCodeFileHash sourceCodeFile="org.example.Foo">n1460gg7sozburnrt098453srtbodoh9</SourceCodeFileHash>
    <SourceCodeFileHash sourceCodeFile="org.example.Bar">dtrn09858592beumbighwale8948924n</SourceCodeFileHash>
</PcmSourceStatementLinkRepository>
```

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/774)

### CODE REVIEW

**Comment by acBerger** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/774)*

**Comment by acBerger** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/774)*

**Comment by viridispirus** [comment]
Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/774)*

**Comment by acBerger** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/774)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/774)*

**Comment by acBerger** [comment]
Reviewed 2 of 5 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/774)*

**Comment by viridispirus** [comment]
Reviewed 1 of 5 files at r3, 1 of 5 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/774)*

**Comment by viridispirus** [comment]
Reviewed 1 of 5 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/774)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/774)*

**Comment by RomanLangrehr** [comment]
:lgtm: :white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/774#-:-KCArJQlRC5lxYRC3hi6:-1603124213)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/774#-:-KCAuEP0JL3Q4jxRsLva:1417088721)*

**Pull request merged**
