### PR TITLE
Ip 130 measurement controller analysis controller

### PR DESCRIPTION
**Pull request by m1cm1c**
[Website](http://beagle-pse.github.io/Beagle/branches/ip-130-measurement-controller-analysis-controller/)

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/694)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
Depends on #663 and #680

**Comment by acBerger** [comment]
[Website] (http://beagle-pse.github.io/Beagle/branches/ip-130-measurement-controller-analysis-controller/)

---

Review status: 0 of 97 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/694#-:-KAQcFbnaMEJDxXz0iIF:2005829879)*

**Comment by RomanLangrehr** [comment]
:lgtm: :white_check_mark: 

---

Reviewed 23 of 97 files at r1, 2 of 74 files at r2, 71 of 72 files at r3, 1 of 1 files at r4.
Review status: 32 of 33 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/694#-:-KAQovjk__kGxKbgzmYP:-1603124213)*

**Comment by RomanLangrehr** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/694)*

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 23 of 97 files at r1, 2 of 74 files at r2, 7 of 72 files at r3, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/694#-:-KAUZp_POZkYmtJAGFxj:1417088721)*

**Comment by RomanLangrehr** [comment]
Not blocked any more.
Please reslve conflicts!

**Comment by jGleitz** [comment]
Resolving conflicts staled the lgtms

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/694#-:-KAUyi5jKLmiXrDLu6MT:1417088721)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/694#-:-KAVDFlZvEfkP5JJc8kZ:1417088721)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/694#-:-KAVGep4xAtVhXQcrZHH:980077423)*

**Comment by RomanLangrehr** [comment]
:white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/694#-:-KAVH_HqQRjETrw99C3M:1605498549)*

**Pull request merged**
