### PR TITLE
Adapted Java Stubs to Design

### PR DESCRIPTION
**Pull request by m1cm1c**
The old views are still in there but I removed their content and added a comment that they need to be removed. That's because they still are dependencies of other classes which should be adapted in different PRs. This one is huge enough and should be merged quickly so it can be the basis of future work.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/552)

### CODE REVIEW

**Comment by flyfl** [comment]
Reviewed 4 of 14 files at r1, 11 of 11 files at r3, 1 of 1 files at r4.
Review status: 16 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/judge/FinalJudgeBlackboardView.java, line 9 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/552#-K7hIT_BdFzd2oUJsqVp:-K7hIT_CyH30PU1VI-od:1493260548) ([raw file](https://github.com/beagle-pse/beagle/blob/4b4ee3c5d37e1868262c0db9a7e13abc5f745363/Core/src/main/java/de/uka/ipd/sdq/beagle/core/judge/FinalJudgeBlackboardView.java#L9)):*
I thought there should be no FinalJugeBlackboardView?

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/ReadOnlyBlackboardView.java, line 10 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/552#-K7hJ2pvCGkxwoJdm9ld:-K7hJ2pwzy2O6sgiVKWS:-781466816) ([raw file](https://github.com/beagle-pse/beagle/blob/4b4ee3c5d37e1868262c0db9a7e13abc5f745363/Core/src/main/java/de/uka/ipd/sdq/beagle/core/ReadOnlyBlackboardView.java#L10)):*
Why are you deleting all this stuff?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/552)*

**Comment by m1cm1c** [comment]
Review status: 16 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/judge/FinalJudgeBlackboardView.java, line 9 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/552#-K7hIT_BdFzd2oUJsqVp:-K7hJgfQGpkaF3spJ5gK:443638554) ([raw file](https://github.com/beagle-pse/beagle/blob/4b4ee3c5d37e1868262c0db9a7e13abc5f745363/Core/src/main/java/de/uka/ipd/sdq/beagle/core/judge/FinalJudgeBlackboardView.java#L9)):*
And I wrote:
> The old views are still in there but I removed their content and added a comment that they need to be removed. That's because they still are dependencies of other classes which should be adapted in different PRs.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/ReadOnlyBlackboardView.java, line 10 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/552#-K7hJ2pvCGkxwoJdm9ld:-K7hJlkQhLblw92PyMiP:-1445816155) ([raw file](https://github.com/beagle-pse/beagle/blob/4b4ee3c5d37e1868262c0db9a7e13abc5f745363/Core/src/main/java/de/uka/ipd/sdq/beagle/core/ReadOnlyBlackboardView.java#L10)):*
Because we don't need this view any more.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/552)*

**Comment by flyfl** [comment]
Review status: 16 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/ReadOnlyBlackboardView.java, line 10 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/552#-K7hJ2pvCGkxwoJdm9ld:-K7hKUoZSaiy_aZBYRE5:-1245357287) ([raw file](https://github.com/beagle-pse/beagle/blob/4b4ee3c5d37e1868262c0db9a7e13abc5f745363/Core/src/main/java/de/uka/ipd/sdq/beagle/core/ReadOnlyBlackboardView.java#L10)):*
The PCM writer needs a view. I thought this might be useful for him as I I think we have enough Views.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/552)*

**Comment by flyfl** [comment]
Reviewed 2 of 14 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/552)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/ExternalCall.java, line 17 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/552#-K7hMc53MiCCzRbkb8q4:-K7hMc53MiCCzRbkb8q5:353957568) ([raw file](https://github.com/beagle-pse/beagle/blob/4b4ee3c5d37e1868262c0db9a7e13abc5f745363/Core/src/main/java/de/uka/ipd/sdq/beagle/core/ExternalCall.java#L17)):*
This does not exist. Delete it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/552)*

**Comment by flyfl** [comment]
lgtm_strong:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/552#-:-K7hNVSaHF_M-j_4qXC2:2111892989)*

**Comment by flyfl** [comment]
:lgtm_strong:

**Comment by jGleitz** [comment]
:lgtm: 

---

Review status: 17 of 18 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/552#-:-K7hOHbb8OjeQSKuFEOh:980077423)*

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 6 of 14 files at r1, 11 of 11 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: 18 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/552#-:-K7hTN4ChRpoxfCKnuYq:1417088721)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/552)*

**Comment by flyfl** [comment]
:lgtm:

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/552#-:-K7hVZsOdvpYQ-ocfeFb:1417088721)*

**Comment by viridispirus** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/552#-:-K7hWgiQJicnFzZqCJ2y:-1868698381)*

**Pull request merged**
