### PR TITLE
Download Test Projects

### PR DESCRIPTION
**Pull request by jGleitz**
This puts CoCoME and AppSensor into `src/test/resources` (in the top most folder, not in `Core`) before running tests.

The folder is added to the Test Run Configuration.

This should enable us to re-add the pcmconnection tests. Both projects may also be valuable for system tests.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/759)

### CODE REVIEW

**Comment by jGleitz** [comment]
I’m asking myself whether putting the projects into `Core/src/test/resources` or another folder (they don’t actually belong into `src`, do they?) would be better. Any suggestions?

**Comment by viridispirus** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/759)*

**Comment by RomanLangrehr** [comment]
:lgtm: :white_check_mark: 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/759#-:-KBmScyfhkR1kFWCXXna:-1603124213)*

**Comment by viridispirus** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/759)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/759#-:-KBsEPgWEPXT698wxlpJ:980077423)*

**Pull request merged**
