### PR TITLE
Adapt the SVN Deploy Script to Gradle

### PR DESCRIPTION
**Pull request by jGleitz**
Until now, the SVN deploy script created a directory structure like this:

```
|
|-- repository (a clone of our repository)
|-- generated (a folder where we manually copied our generated files to)
```

After this PR, we will simpld deploy the directory structure like its left after running gradle. All generated files will be found in the `build` folder.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/364)

### CODE REVIEW

**Comment by acBerger** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/364#-:-K71InQRDvIM5n6IMfKf:980077423)*

**Comment by acBerger** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/364#-:-K71IvtvVRJAPKLYMnzm:980077423)*

**Comment by RomanLangrehr** [comment]
Our SVN repo looks pretty outdated, doesn't it?

**Comment by jGleitz** [comment]
Yes, it does. The deploy script is broken since we adopted gradle, because the path to the rendered PDF changed.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/364#-:-K71NQPuPX-WF98iW4lw:1109823619)*

**Comment by RomanLangrehr** [comment]
Ah, ok. :lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/364#-:-K71O-w1d_tsw4N3eUI_:-348502714)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/364#-:-K71PIt9gZ3pdS56w9Wk:980077423)*

**Comment by acBerger** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/364#-:-K71PVEHUqiYXs8TenJd:980077423)*

**Pull request merged**
