### PR TITLE
Blackboard Design

### LINKED ISSUE #263: Model Association Qualifiers in Papyrus
I’m unable to do it. I did research, but the explained way does not work for me. Help is highly appreciated.

### LINKED ISSUE #416: Finalise Blackboard’s design
In both the class diagram and the class. Includes #263.

### LINKED ISSUE #418: Beagle UML diagram is broken
beagle-uml

### PR DESCRIPTION
**Pull request by jGleitz**
This PR should finalise the Blackboard in both the UML diagram and the Javadoc. So please report any issues or missing things you find.

I did not check the views, as others are working on them.

fixes #263 
fixes #416 
fixes #418

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/426)

### CODE REVIEW

**Comment by jGleitz** [comment]
**Attention**: I had to merge the diagrams by hand. Please double check that **I did not remove any of your changes** nor introduced an error in the diagram.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/426#-:-K78e3m0yowJhkzH4I3G:-1316394969)*

**Comment by jGleitz** [comment]
[View this PR’s rendered artefacts](http://jgleitz.github.io/Beagle/branches/blackboard-design/)

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/426#-:-K78eRbomCi8ROnS3l-n:790571475)*

**Comment by acBerger** [comment]
:lgtm_strong: 

---

Reviewed 3 of 6 files at r1, 7 of 7 files at r3, 3 of 3 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/426#-:-K7ApM8rNNFEzCJQjS88:-1868698381)*

**Comment by acBerger** [comment]
Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/426)*

**Comment by RomanLangrehr** [comment]
The final judge is completly broken:



---

Reviewed 3 of 6 files at r1, 7 of 7 files at r3, 1 of 3 files at r5, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/426#-:-K7BRo3pP0vwMyavMQe-:-181653453)*

**Comment by RomanLangrehr** [comment]
And it would add a "Measuerment" to the name of the Branch/Loop results, like `Loop Repetition Count [Measurement] Result` and `Branch Decision [Measurement] Result`, to make clear, that they are gained by measurements. (The evalubale expressions are some kind of result, too.)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/426#-:-K7BSs_Z12V5ZzZlBuSS:2016391893)*

**Comment by jGleitz** [comment]
* Fixed `Final Judge`
 * Renamed as @RomanLangrehr suggested
 * Added `Parameterised Measurement Result` to the class diagram.

As I made substantial changes, this revokes @acBerger’s lrtm. :lgtm_cancel: 

---

Review status: 6 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/426#-:-K7BZt2pI8jSLDiBMdec:-1371602008)*

**Comment by RomanLangrehr** [comment]
The final judge in the Controller diagram is still broken:


---

Reviewed 9 of 9 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/426#-:-K7BabbEowIKBa_9wQtd:324293218)*

**Comment by jGleitz** [comment]
I’m sorry. Thanks for pointing out! I took my time and tried to improve the diagram arrangement.

---

Review status: 11 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/426#-:-K7Bb9LHh80JODaemwcG:991892355)*

**Comment by acBerger** [comment]
:lgtm_cancel: 

---

Review status: 11 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/426#-:-K7BfxiL4FTUH_YRuWEd:-1600992588)*

**Comment by RomanLangrehr** [comment]
Did you add this method?


Because the "null" doesn't look nice and it's missing in the class diagram:


And I this might be a problem with #409 as it's part of #406 

---

Reviewed 3 of 3 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/426#-:-K7BiItR5iFELKkYFjXN:1389622866)*

**Comment by jGleitz** [comment]
I added this method, but not in this PR but a long while ago when creating the interface. At that time, I thought leaving the method out of the Beagle Core Diagram would be okay as a form of abstraction (it allows us to keep the Interface block small in the diagram, as it does not play an important role there)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/426#-:-K7Bj1EY9ZE88__cprb9:-532146967)*

**Comment by RomanLangrehr** [comment]
I see. :lgtm_strong: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/426#-:-K7BjvGmwc6Uew0XLO8h:2082594551)*

**Comment by acBerger** [comment]
:lgtm_strong: 

---

Reviewed 3 of 3 files at r10.
Review status: 13 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/426#-:-K7Blts-cq--ycpvUBFO:-1868698381)*

**Pull request merged**
