### PR TITLE
Javadoc Style Convention

### PR DESCRIPTION
**Pull request by m1cm1c**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/461)

### CODE REVIEW

**Comment by m1cm1c** [comment]
@viridispirus Please check whether the changes compared to #460 are okay.

**Comment by viridispirus** [comment]
:lgtm: 

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/461#-:-K7PxYKKOyRFg0sf1MqB:980077423)*

**Comment by jGleitz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[doc/Javadoc Style Convention.md, line 2 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/461#-K7QL36OrEE7IB2UYkOD:-K7QL36OrEE7IB2UYkOE:-1791685728) ([raw file](https://github.com/beagle-pse/beagle/blob/345dac4fa483aacbbe934076b0eb37e490cb279d/doc/Javadoc Style Convention.md#L2)):*
“and end with a **[full stop]**.” We use BE ;)

---

*[doc/Javadoc Style Convention.md, line 8 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/461#-K7QLdWLSLq9r7q4lr7m:-K7QLdWLSLq9r7q4lr7n:-1248994102) ([raw file](https://github.com/beagle-pse/beagle/blob/345dac4fa483aacbbe934076b0eb37e490cb279d/doc/Javadoc Style Convention.md#L8)):*
Please provide a link to Google’s definition of Camel Case as it’s not trivial.

---

*[doc/Javadoc Style Convention.md, line 11 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/461#-K7QLFrgYKUImpki5slT:-K7QLFrhs5ENsceIGkwl:1836007659) ([raw file](https://github.com/beagle-pse/beagle/blob/345dac4fa483aacbbe934076b0eb37e490cb279d/doc/Javadoc Style Convention.md#L11)):*
“**[Only]** acronyms used in the SRS are permitted.”

---

*[doc/Javadoc Style Convention.md, line 12 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/461#-K7QLSwt1-p6RkuCJa-B:-K7QLSwufVRvGyn_nvcx:-612795671) ([raw file](https://github.com/beagle-pse/beagle/blob/345dac4fa483aacbbe934076b0eb37e490cb279d/doc/Javadoc Style Convention.md#L12)):*
Please use unordered lists (with `#`) here too.

---

*[doc/Javadoc Style Convention.md, line 17 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/461#-K7QLZMj8v8YxAzPSj5U:-K7QLZMkd611gV0Yn6IS:-612795671) ([raw file](https://github.com/beagle-pse/beagle/blob/345dac4fa483aacbbe934076b0eb37e490cb279d/doc/Javadoc Style Convention.md#L17)):*
Please use unordered lists (with `#`) here too.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/461)*

**Comment by jGleitz** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/461)*

**Comment by m1cm1c** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[doc/Javadoc Style Convention.md, line 2 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/461#-K7QL36OrEE7IB2UYkOD:-K7QrMFcjqUKHgaU0XTR:677588487) ([raw file](https://github.com/beagle-pse/beagle/blob/345dac4fa483aacbbe934076b0eb37e490cb279d/doc/Javadoc Style Convention.md#L2)):*
done

---

*[doc/Javadoc Style Convention.md, line 8 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/461#-K7QLdWLSLq9r7q4lr7m:-K7QsQhcZS_91SFBPrKz:677588487) ([raw file](https://github.com/beagle-pse/beagle/blob/345dac4fa483aacbbe934076b0eb37e490cb279d/doc/Javadoc Style Convention.md#L8)):*
done

---

*[doc/Javadoc Style Convention.md, line 11 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/461#-K7QLFrgYKUImpki5slT:-K7QshfLqgdv_cvqUHsS:-1674510331) ([raw file](https://github.com/beagle-pse/beagle/blob/345dac4fa483aacbbe934076b0eb37e490cb279d/doc/Javadoc Style Convention.md#L11)):*
Done. Plus, I added something, please also check this.

---

*[doc/Javadoc Style Convention.md, line 12 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/461#-K7QLSwt1-p6RkuCJa-B:-K7QtbHXOX-uPrwd30ZF:-835822709) ([raw file](https://github.com/beagle-pse/beagle/blob/345dac4fa483aacbbe934076b0eb37e490cb279d/doc/Javadoc Style Convention.md#L12)):*
I suppose you mean `*`. If you don't, let me know.

---

*[doc/Javadoc Style Convention.md, line 17 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/461#-K7QLZMj8v8YxAzPSj5U:-K7Qthfc73w9crYaApHU:677588487) ([raw file](https://github.com/beagle-pse/beagle/blob/345dac4fa483aacbbe934076b0eb37e490cb279d/doc/Javadoc Style Convention.md#L17)):*
done

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/461)*

**Comment by RomanLangrehr** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[doc/Javadoc Style Convention.md, line 12 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/461#-K7QLSwt1-p6RkuCJa-B:-K7QzchkfvazrfjQENZ4:1121048861) ([raw file](https://github.com/beagle-pse/beagle/blob/345dac4fa483aacbbe934076b0eb37e490cb279d/doc/Javadoc Style Convention.md#L12)):*
According to this we would have SeffBranches instead of SEFFBranches, would we? I don't like that.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/461)*

**Comment by RomanLangrehr** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/461)*

**Comment by RomanLangrehr** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/461#-:-K7R09WhN-OMQeozQmXE:-1868698381)*

**Comment by viridispirus** [comment]
:lgtm: 

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/461#-:-K7R1-dkAGOIJ3-yO9P7:980077423)*

**Comment by viridispirus** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/461)*

**Comment by viridispirus** [comment]
:lgtm_strong: 

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/461#-:-K7R1hDVE8aVSCehhxML:-2095074953)*

**Comment by m1cm1c** [comment]
@viridispirus It doesn't work because there still are unresolved discussions. @jGleitz has to acknowledge what I wrote so this PR can be merged.

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[doc/Javadoc Style Convention.md, line 14 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/461#-K7R3hitkac0ZyqO1fXX:-K7R3hiuG4l2VCVjQCQq:-397634129) ([raw file](https://github.com/beagle-pse/beagle/blob/f9e268b227896980327301942c77706702d06e6f/doc/Javadoc Style Convention.md#L14)):*
> Their use when possible is mandatory.

I don’t think that’s a good idea.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/461)*

**Comment by m1cm1c** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/Javadoc Style Convention.md, line 14 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/461#-K7R3hitkac0ZyqO1fXX:-K7R4xlbjTuxFIAyUJRz:469593387) ([raw file](https://github.com/beagle-pse/beagle/blob/f9e268b227896980327301942c77706702d06e6f/doc/Javadoc Style Convention.md#L14)):*
But otherwise we'll switch around all the time. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/461)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[doc/Javadoc Style Convention.md, line 12 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/461#-K7QLSwt1-p6RkuCJa-B:-K7R4XIL2lU9-4SwLj0b:2067461334) ([raw file](https://github.com/beagle-pse/beagle/blob/345dac4fa483aacbbe934076b0eb37e490cb279d/doc/Javadoc Style Convention.md#L12)):*
@RomanLangrehr I don’t like that, too. But I think @m1cm1c is right that this provides a readable and consistent way. Because capitalising acronyms always has edge cases: in `SEFFRDIA` for example, its no clear where one Acronym starts and the other ends.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/461)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[doc/Javadoc Style Convention.md, line 14 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/461#-K7R3hitkac0ZyqO1fXX:-K7R57G5sUH_YC6WGKXi:-1178499682) ([raw file](https://github.com/beagle-pse/beagle/blob/f9e268b227896980327301942c77706702d06e6f/doc/Javadoc Style Convention.md#L14)):*
> But otherwise we'll switch around all the time.

Yes. And in Javdoc, I think that’s okay. I even think that it’s okay to mix it for names: `ResourceDemandingInternalAction` but `RDIASpecificationDetail` (fictional example)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/461)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[doc/Javadoc Style Convention.md, line 7 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/461#-K7R5Sp98-YxAj7do5G1:-K7R5Sp98-YxAj7do5G2:614533571) ([raw file](https://github.com/beagle-pse/beagle/blob/f9e268b227896980327301942c77706702d06e6f/doc/Javadoc Style Convention.md#L7)):*
Why is this in this document? It’s actually about *code*, not about Javadoc. Maybe we should merge this document with `Coding Conventions.md`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/461)*

**Comment by jGleitz** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/461)*

**Comment by m1cm1c** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[doc/Javadoc Style Convention.md, line 7 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/461#-K7R5Sp98-YxAj7do5G1:-K7R6SMF61WSWlCLrU-v:-331993508) ([raw file](https://github.com/beagle-pse/beagle/blob/f9e268b227896980327301942c77706702d06e6f/doc/Javadoc Style Convention.md#L7)):*
It's a definition of Camel Case in a document specifying code style as well as Javadoc style.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/461)*

**Comment by m1cm1c** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[doc/Javadoc Style Convention.md, line 14 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/461#-K7R3hitkac0ZyqO1fXX:-K7R7Jf4PpoGKwmD7Ciw:-2096001433) ([raw file](https://github.com/beagle-pse/beagle/blob/f9e268b227896980327301942c77706702d06e6f/doc/Javadoc Style Convention.md#L14)):*
I removed it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/461)*

**Comment by jGleitz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[doc/Javadoc Style Convention.md, line 7 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/461#-K7R5Sp98-YxAj7do5G1:-K7RA6g7q4ZFSEyU-P9a:331137667) ([raw file](https://github.com/beagle-pse/beagle/blob/f9e268b227896980327301942c77706702d06e6f/doc/Javadoc Style Convention.md#L7)):*
>  in a document specifying code style

It’s called `Javadoc Style Convention`. I personally find that very irritating because I would never look for variable naming in a document called like this.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/461)*

**Comment by RomanLangrehr** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[doc/Javadoc Style Convention.md, line 12 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/461#-K7QLSwt1-p6RkuCJa-B:-K7S2MqEMVupkPsrbkyg:40468999) ([raw file](https://github.com/beagle-pse/beagle/blob/345dac4fa483aacbbe934076b0eb37e490cb279d/doc/Javadoc Style Convention.md#L12)):*
Yes, i agree on that.

---

*[doc/Javadoc Style Convention.md, line 7 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/461#-K7R5Sp98-YxAj7do5G1:-K7S2T330LpbVyZ-hMMB:-121169736) ([raw file](https://github.com/beagle-pse/beagle/blob/f9e268b227896980327301942c77706702d06e6f/doc/Javadoc Style Convention.md#L7)):*
I agree that this doesn't fit here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/461)*

**Comment by RomanLangrehr** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/461)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[doc/Javadoc Style Convention.md, line 7 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/461#-K7R5Sp98-YxAj7do5G1:-K7Scfl2syjY92DaLy9b:-1966426618) ([raw file](https://github.com/beagle-pse/beagle/blob/f9e268b227896980327301942c77706702d06e6f/doc/Javadoc Style Convention.md#L7)):*
+@m1cm1c 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/461)*

**Comment by RomanLangrehr** [comment]
:lgtm_cancel: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/461#-:-K7VeU_IPHGN7s53W83h:502544406)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/461)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/461#-:-K7XFG614AoO215qVvvZ:980077423)*

**Comment by RomanLangrehr** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/461)*

**Pull request merged**
