### PR TITLE
Documented KITBeamer Development Setup

### LINKED ISSUE #747: Document uarial and the KIT Beamer Template
They are required to build our project and should thus be documented in `Development Setup.htmd`.

### PR DESCRIPTION
**Pull request by jGleitz**
Adds an explanation how to set up your environment to render KITBeamer presentations.

Fixes #747

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/751)

### CODE REVIEW

**Comment by viridispirus** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/751)*

**Comment by m1cm1c** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/751)*

**Comment by m1cm1c** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Web Presence/src/main/handlebars/Development Setup.htmd, line 108 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/751#-KBEG1hDs4Gdo6c8ixjj:-KBEG1hDs4Gdo6c8ixjk:516512596) ([raw file](https://github.com/beagle-pse/beagle/blob/42e093689c3c52714c1750270dd541dfbab43712/Web Presence/src/main/handlebars/Development Setup.htmd#L108)):*
`rm intall-getnonfreefonts` → `rm install-getnonfreefonts`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/751)*

**Comment by jGleitz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[Web Presence/src/main/handlebars/Development Setup.htmd, line 108 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/751#-KBEG1hDs4Gdo6c8ixjj:-KBEgK0lHKLvTET0VQi0:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/42e093689c3c52714c1750270dd541dfbab43712/Web Presence/src/main/handlebars/Development Setup.htmd#L108)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/751)*

**Comment by m1cm1c** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/751#-:-KBEhrbPsylBMTGg9Tls:1417088721)*

**Comment by m1cm1c** [comment]
:white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/751#-:-KBEhuLaiHsQdGtGLirq:1605498549)*

**Comment by m1cm1c** [comment]
:lgtm_cancel: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/751#-:-KBEiqTQ2is5dMhFQ_pu:502544406)*

**Comment by m1cm1c** [comment]
:lgtm: Sorry. I thought I found something.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/751#-:-KBEk2hex4dc6_Egojm9:-909074617)*

**Comment by RomanLangrehr** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Web Presence/src/main/handlebars/Development Setup.htmd, line 75 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/751#-KBHt8wDBOZw9E_et8HL:-KBHt8wDBOZw9E_et8HM:-886002546) ([raw file](https://github.com/beagle-pse/beagle/blob/cc2f8fd06001185848ac98c3cb08ea7806940a1d/Web Presence/src/main/handlebars/Development Setup.htmd#L75)):*
I don't think thats the proper way to install it in MixTeX. See my PR.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/751)*

**Comment by jGleitz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[Web Presence/src/main/handlebars/Development Setup.htmd, line 75 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/751#-KBHt8wDBOZw9E_et8HL:-KBI44y5EvRroPjzyEIt:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/cc2f8fd06001185848ac98c3cb08ea7806940a1d/Web Presence/src/main/handlebars/Development Setup.htmd#L75)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/751)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/751#-:-KBI4lLO_eOuXhw0gmL_:980077423)*

**Comment by m1cm1c** [comment]
:lgtm:

**Comment by jGleitz** [comment]
Please verify the test coverage.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/751#-:-KBI8ov3S2t-MZaOU-f0:-1328289731)*

**Comment by RomanLangrehr** [comment]
xD :white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/751#-:-KBI9DCRf_NPsuLBSQfX:1929956299)*

**Pull request merged**
