### PR TITLE
Remove Test Projects Before Deploying To SVN

### PR DESCRIPTION
**Pull request by jGleitz**
I forgot about that, which is bad. So here’s the fix.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/768)

### CODE REVIEW

**Comment by jGleitz** [comment]
Fortunately, Travis aborted before the files could be transferred to the server. So just let us merge this asap.

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/768#-:-KByn5dP0wOUSyykrocb:1417088721)*

**Comment by m1cm1c** [comment]
:lgtm:

**Comment by m1cm1c** [comment]
:white_check_mark:

**Comment by m1cm1c** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/768)*

**Pull request merged**
