### PR TITLE
Added throws declaration for Runtime Exceptions.

### PR DESCRIPTION
**Pull request by RomanLangrehr**
I think this is better style and it removes the checkstyle warning in eclipse.

What do you think about it?

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/446)

### CODE REVIEW

**Comment by jGleitz** [comment]
I think it’s not necessary to declare Runtime Exceptions with `throws` (because doing so has no effect on compilation). But I also see no real reason not to do it.

On the other hand, it’s kind of inconsistent to only declare `throws` for custom Runtime Exceptions. But if we did it for all Runtime Exceptions, we’d end up writing `throws NullPointException` or `throws NullPointException, IllegalArgumentExceptios` for nearly every method.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/446#-:-K7MEHWqBKbl1JhL_IPR:773785313)*

**Comment by RomanLangrehr** [comment]
> On the other hand, it’s kind of inconsistent to only declare `throws` for custom Runtime Exceptions. But if we did it for all Runtime Exceptions, we’d end up writing `throws NullPointException` or `throws NullPointException, IllegalArgumentExceptios` for nearly every method.

No, I hope your code never throws an NullPointerException.
And when you throw an IllegalArgumentException, i think it would be good to declare this.

**Comment by jGleitz** [comment]
> No, I hope your code never throws an NullPointerException.

Nearly all methods I documented declare “must not be `null`”. If they are `null`, throwing a `NullPointerException` is the correct reaction, isn’t it?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/446#-:-K7MG2XxZIEvOcOgWZmd:-1079241385)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/446)*

**Comment by jGleitz** [comment]
To be clear: I’m talking about the method’s *arguments* ;)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/446#-:-K7MGQF7JWfW-w4ebG0N:-1588076240)*

**Comment by RomanLangrehr** [comment]
> Nearly all methods I documented declare “must not be `null`”. If they are `null`, throwing a `NullPointerException` is the correct reaction, isn’t it?

Yes. An IllegalArgumentException would be better, but I think it's to much work to check all input parameters for beeing not null.

**Comment by RomanLangrehr** [comment]
Maybe declaring a RuntimeException when we declare an @throws in the JavaDoc is a good idea.

**Comment by jGleitz** [comment]
> but I think it's to much work to check all input parameters for beeing not null.

First of all: We decided to make that effort when we decided to adopt the defensive programming style.

> An IllegalArgumentException would be better,

As far as I know, the Java API usually throws a `NullPointerException` for such cases. 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/446#-:-K7MGoOrlnW7WvzLktQB:2034569289)*

**Comment by jGleitz** [comment]
I think it’s enough to declare Runtime Exceptions in the Javadoc using `@throws`. And I think even that is nice to do but not mandatory. Because they will never be thrown if the developer follows the method’s contract (which must be fully defined in the Javadoc)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/446#-:-K7MPv2mdQ0yiEAlXfH1:1363166250)*

**Pull request closed without merging**
