### PR TITLE
Sequence diagrams

### LINKED ISSUE #390: Model a simple Exemplary Run of Beagle
This should be done in the form of a sequence diagram (and is a lot of work).

### LINKED ISSUE #479: Redraw Sequence Diagram in UMLet

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Fixes #390 
fixes #479 
The sequnce diagram for `perform Analysis()` looks like this right now:
sequence diagram perform analysis
I show it to you, as this is also a proposal, how the `perform Analysis()` will look like with the two different result analysers.
I also made the diagram more general this time.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/497)

### CODE REVIEW

**Comment by m1cm1c** [comment]
This branch is out-of-date with the base branch.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7a_np0RO-IW4NcW9NE:-1909636266)*

**Comment by m1cm1c** [comment]
Are you sure that writing what variables are set to this way is possible in UML? I only know that variables which are set to a return value can be written onto the return arrow.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7aaXZGGW3DGu2_ks1O:776672816)*

**Comment by RomanLangrehr** [comment]
> Are you sure that writing what variables are set to this way is possible in UML?

Yes, it's exatctly like we learned it in the SWT1 lecture.

> I only know that variables which are set to a return value can be written onto the return arrow.

No, they are written like in my diagram.

**Comment by jGleitz** [comment]
One correction: If one analyser ran, the loop starts over again (and does not continue with the next analyser). This ensures that re-measurements will always be handled as soon as possible.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7ad22m2R4vhMPydhYN:-770858071)*

**Comment by m1cm1c** [comment]
I  just checked and it really was introduced this way in the SWT1 lecture.

The second diagram has unreadable elements.

---

Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7adFWFFFjF-2oBIwFH:-1603557846)*

**Comment by m1cm1c** [comment]
Variable "finished" is missing a "d" in it's evaluation.

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7aezLupR04yKF1qMtF:-82650712)*

**Comment by RomanLangrehr** [comment]
> The second diagram has unreadable elements.

This one should not be reviewd, yet. I just checked them in by mistake.

**Comment by RomanLangrehr** [comment]
> Variable "finished" is missing a "d" in it's evaluation.

Really? I can't find it.
Here is an d:
image
(not sure if that's waht you mean with evaluation)

**Comment by m1cm1c** [comment]
Yes, this one's missing for me somehow (see my exported images above). But it appears in the text. Seems to be a graphics error.

**Comment by RomanLangrehr** [comment]
> One correction: If one analyser ran, the loop starts over again (and does not continue with the next analyser). This ensures that re-measurements will always be handled as soon as possible.

Okay. Like this, this is ensured:
sequence diagram perform analysis 2

**Comment by jGleitz** [comment]
This is getting really complicated to read (I’m not actually sure if it’s correct in the moment).

Proposal:

All those ALT and OPT operators are a very general approach. But this is already covered in the pseudo code. I think this diagram would make a lot more sense if it was a **concrete example**: No loops, no ifs, only calls and return values, like:

`Measurement Controller` -> `Measurement Result Analyser 2` -> `Proposed Expression Analyser 1` -> `Proposed Expression Analyser 2` -> `Final Judge` -> `Measurement Controller` -> `Measurement Result Analyser 2` -> `Measurement Result Analyser 1` ->  -> `Proposed Expression Analyser 1` -> `-> `Final Judge` -> `Proposed Expression Analyser 2` -> `Final Judge` 

This would make a good diagram to explain the algorithm for a concrete example.  It would show how the feedback loops work. 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7anrryCh0FIMpDipdm:-239374374)*

**Comment by RomanLangrehr** [comment]
As I already did this: What about both?

**Comment by jGleitz** [comment]
> As I already did this
:+1: 

> What about both?

What are you hoping to convey with this version? I really find it hard to read and don’t think it offers information that cannot be read from the pseudocode.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7aqDbsq0yMUMFavH43:-47391092)*

**Comment by RomanLangrehr** [comment]
> I really find it hard to read 

What is hard to read about it? There are just some nested if/elses.

**Comment by RomanLangrehr** [comment]
> and don’t think it offers information that cannot be read from the pseudocode.

That's an arguement. I'll make it specific.

**Comment by jGleitz** [comment]
:+1:  :+1: 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7arbFhF9IJyQDU-Kj-:1039468999)*

**Comment by jGleitz** [comment]
[Website](http://romanlangrehr.github.io/Beagle/branches/sequence-diagram/) please include the diagrams in the document.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7bjS3f5x3fcVbiPPiD:863300467)*

**Comment by RomanLangrehr** [comment]
Finished all diagrams. Finally. And added them to the Design Document (for demonstration purpose, I think we can move them to the right place, when @jGleitz finished the new document structure).
-blocked -incomplete 

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7cEurU7xnSIVKWIu1G:1139644927)*

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r5, 8 of 8 files at r6.
Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7cKoCisBaKcxXf-xZY:1417088721)*

**Comment by acBerger** [comment]
Reviewed 1 of 5 files at r5, 8 of 8 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497)*

**Comment by jGleitz** [comment]
I think the code sections do not belong into the `Measurement Order`. But we can do this in another PR (you’ll have to adapt the diagram), if you want to.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7cSyBO-6kh2BTWpj-_:113425151)*

**Comment by RomanLangrehr** [comment]
> But we can do this in another PR (you’ll have to adapt the diagram), if you want to.

Please. I know that they don't belong there, but I don't know how this works correctly.

**Comment by jGleitz** [comment]
I think these assignments are not necessary anymore:



Removing them would highly increase readability. There are multiple occurrences.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7cTSPV0NymYLaHdewE:960702920)*

**Comment by m1cm1c** [comment]
Or just write them onto the return arrow. 

On January 9, 2016 11:21:38 PM GMT+01:00, Joshua Gleitze <notifications@github.com> wrote:
>I think these assignments are not necessary anymore:
>
>
>
>Removing them would highly increase readability. There are multiple
>occurrences.
>
>---
>
>Review status: all files reviewed at latest revision, all discussions
>resolved.
>
>---
>
>
>
>*Comments from the [review on
>Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7cTSPV0NymYLaHdewE:960702920)*
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Beagle-PSE/Beagle/pull/497#issuecomment-170287450

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by m1cm1c** [comment]
I learned it this way in school. Here is the Wikipedia article for persuasion that this is  valid UML (not that our advisors would care) : https://en.m.wikipedia.org/wiki/Sequence_diagram

On January 9, 2016 11:21:38 PM GMT+01:00, Joshua Gleitze <notifications@github.com> wrote:
>I think these assignments are not necessary anymore:
>
>
>
>Removing them would highly increase readability. There are multiple
>occurrences.
>
>---
>
>Review status: all files reviewed at latest revision, all discussions
>resolved.
>
>---
>
>
>
>*Comments from the [review on
>Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7cTSPV0NymYLaHdewE:960702920)*
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Beagle-PSE/Beagle/pull/497#issuecomment-170287450

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by RomanLangrehr** [comment]
> Or just write them onto the return arrow. 

No, they don't belong there. That was a mistake.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7cUy4UG4idODATaK_F:997814290)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7eXfjWV1WyS8Yien-I:1417088721)*

**Comment by acBerger** [comment]
Cannot find your diagrams in the current Design Document anymore. 

---

Reviewed 1 of 1 files at r12.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7f1FjmPXn_0n57dIk8:-282413311)*

**Comment by RomanLangrehr** [comment]
> Cannot find your diagrams in the current Design Document anymore.

Done.

---

Review status: 6 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7f3PNxy2gjIzZ161se:1907930639)*

**Comment by acBerger** [comment]
> Done.

No, you added them with a absolute path which does not work for us.

---

Review status: 6 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7f5LB9UzRZWVbZhWsD:505622425)*

**Comment by RomanLangrehr** [comment]
> No, you added them with a absolute path which does not work for us.

Done.

---

Review status: 6 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7f8jgRvJ8OVH9UOLqr:-175568651)*

**Comment by acBerger** [comment]
- This one is to big.

- This one is to big and distorted

- This one is not here


---

Review status: 6 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7fAqUTnlX7C3HPm4iT:-491063598)*

**Comment by flyfl** [comment]
Reviewed 1 of 1 files at r14.
Review status: 7 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497)*

**Comment by RomanLangrehr** [comment]
@acBerger 
Done.

---

Review status: 6 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7fPs6Aeqiifj444UEC:-583456544)*

**Comment by acBerger** [comment]
One still is not here.


---

Review status: 6 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7fRqH8uzQ2_NVJEcgn:653020509)*

**Comment by RomanLangrehr** [comment]
I'm sorry. I can't render them local at the moment.
Should be fixed now.

---

Review status: 6 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7fSNzWrI7KcNvjGqug:-1812136662)*

**Comment by flyfl** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r16.
Review status: 7 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7fW-wlXOaaGdohoF5M:1417088721)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: 7 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7fWhpeBtFGa4donx31:1417088721)*

**Comment by acBerger** [comment]
Out of date

---

Review status: 7 of 8 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7fWziUFUikYAQbaLhn:1760345290)*

**Comment by flyfl** [comment]
:lgtm_strong:

**Comment by acBerger** [comment]
:lgtm:

---

Review status: 7 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/497#-:-K7fZsxKn6U9b_c1ZAVS:1417088721)*

**Pull request merged**
