### PR TITLE
Readded tests for PCM Loader

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Depends on #759 
Some tests are failing @flyfl  should fix them.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/761)

### CODE REVIEW

**Comment by viridispirus** [comment]
Reviewed 1 of 3 files at r1, 2 of 7 files at r2.
Review status: 3 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/761)*

**Comment by jGleitz** [comment]
Review status: 3 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Core/src/test/resources/de/uka/ipd/sdq/beagle/core/pcmconnection/AppSensor.repository, line 1 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/761#-KBqsC-K07xlFFCwAHcz:-KBqsC-LS7na8fRt01IW:-922951443) ([raw file](https://github.com/beagle-pse/beagle/blob/f61e00a8a11594950f5824c12ab3bb1ee694d670/Core/src/test/resources/de/uka/ipd/sdq/beagle/core/pcmconnection/AppSensor.repository#L1)):*
Shouldn’t this file, for consistency reasons, be put into `Beagle/src/test/resources/AppSensor`? (Maybe in a subfolder like `model`)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/761)*

**Comment by jGleitz** [comment]
-blocked @flyfl , it would be nice to have this merged soon.

---

Review status: 3 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/761#-:-KBwkd0ObVeRmTISaC_u:509707559)*

**Comment by jGleitz** [comment]
Reviewed 4 of 7 files at r2.
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/761)*

**Comment by acBerger** [comment]
Reviewed 3 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/761)*

**Comment by flyfl** [comment]
You mean the 3 failing tests due to IllegalStateExceptions? That is because of Somox, that names more than one AbstractAction with the same CodeSection. Its actually a behaviour of Somox that leads to this failure.

**Comment by jGleitz** [comment]
@flyfl is there any way to make the tests work in the moment? (There is no much sense in spending to much time on it though, as the name parsing code will be removed anyway).

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/761#-:-KC175EXsJAz8K7w9ejd:1205903295)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/761#-KC1y-kJ--bh1RudmgZ3:-KC1y-kJ--bh1RudmgZ4:190988272) (no related file):*
If we want to show source code statistics in the final presentation, this PR will manipulate them. So maybe @m1cm1c should re-do this in his own PR.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/761)*

**Comment by m1cm1c** [comment]
Done. (See #769.)

**Pull request closed without merging**
