### PR TITLE
GUI Classes

### LINKED ISSUE #493: Create Classes and Javadoc for GUI

### PR DESCRIPTION
**Pull request by m1cm1c**
Depends on #488.
Fixes #493.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/496)

### CODE REVIEW

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r2, 12 of 12 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/496)*

**Comment by m1cm1c** [comment]
This PR is blocked until #488 (which it builds on top on) is merged.

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r7.
Review status: 8 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/496)*

**Comment by acBerger** [comment]
Reviewed 8 of 9 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/496)*

**Comment by m1cm1c** [comment]
-blocked because #488 has been merged.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/496#-:-K7bcD_M_ko2g5uhQ_F8:-1380046131)*

**Comment by RomanLangrehr** [comment]
[Website](http://m1cm1c.github.io/Beagle/branches/gui-classes/)

---

Reviewed 1 of 1 files at r2, 6 of 16 files at r3, 8 of 9 files at r5, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/gui/EclipseWizardPage.java, line 1 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/496#-K7bclvJdATb1jVclaqV:-K7bclvJdATb1jVclaqW:1920321757) ([raw file](https://github.com/beagle-pse/beagle/blob/3070cfce9e16c3ffc244c40e0a2d67e79279df55/Core/src/main/java/de/uka/ipd/sdq/beagle/gui/EclipseWizardPage.java#L1)):*
I think it's better to use the (correct) eclipse package here. Then we can delete this and don't have to modify the other classes, when can resolve the dependencies.

---

*[Documentation/src/design/Diagrams/GUI.uxf, line 1 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/496#-K7bd9xwlQsAR5WFvtsy:-K7bd9xwlQsAR5WFvtsz:-944777621) ([raw file](https://github.com/beagle-pse/beagle/blob/3070cfce9e16c3ffc244c40e0a2d67e79279df55/Documentation/src/design/Diagrams/GUI.uxf#L1)):*
What is changed in the diagram?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/496#-:-K7bdT1F7Q47NNY-gS2a:-29094414)*

**Comment by m1cm1c** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/gui/EclipseWizardPage.java, line 1 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/496#-K7bclvJdATb1jVclaqV:-K7cP2S4_3v2jyVqIIkz:677588487) ([raw file](https://github.com/beagle-pse/beagle/blob/3070cfce9e16c3ffc244c40e0a2d67e79279df55/Core/src/main/java/de/uka/ipd/sdq/beagle/gui/EclipseWizardPage.java#L1)):*
done

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/496)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: 4 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/496#-:-K7cR-0rhgRAmYvHqSud:980077423)*

**Comment by RomanLangrehr** [comment]
Reviewed 12 of 12 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/496)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/496#-:-K7cRJtTlzJwOv-rFinW:1417088721)*

**Pull request merged**
