### PR TITLE
Yet another document...

### PR DESCRIPTION
**Pull request by RomanLangrehr**
... to avoid fun during implementation.

(Added implementation report).

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/595)

### CODE REVIEW

**Comment by jGleitz** [comment]
> ... to avoid fun during implementation.

I couldn’t agree more :'(

Can you either add a build task for that and add it to the website (It’s pretty easy, just copy the others) or push this into our repo so I can do it?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/595#-:-K89zyVofCH4iyL8Dv1-:-1090289913)*

**Comment by jGleitz** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Documentation/src/implementation/lyx/Implementation Report.lyx, line 309 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/595#-K8A0W0a2ztDQp8K_qSs:-K8A0W0bdV0V13r-kOkR:-591814297) ([raw file](https://github.com/beagle-pse/beagle/blob/65effa00369c93bfe69bc9be39c2012129f2d3dd/Documentation/src/implementation/lyx/Implementation Report.lyx#L309)):*
“Unit**[ T]**ests”

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/595)*

**Comment by jGleitz** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/595)*

**Comment by RomanLangrehr** [comment]
Is now on the [Website](http://romanlangrehr.github.io/Beagle/branches/yad/)

**Comment by RomanLangrehr** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Documentation/src/implementation/lyx/Implementation Report.lyx, line 309 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/595#-K8A0W0a2ztDQp8K_qSs:-K8AJtgQxAwxl5A43gmz:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/65effa00369c93bfe69bc9be39c2012129f2d3dd/Documentation/src/implementation/lyx/Implementation Report.lyx#L309)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/595)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/595#-:-K8AKTh6My-Iwde2O9dE:980077423)*

**Comment by m1cm1c** [comment]
Please update branch. :lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/595#-:-K8AbBPqIKfMVCu13pdH:1734910810)*

**Comment by jGleitz** [comment]
+@acBerger must resolve the discussion.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/595#-:-K8DgAlel-8i9yqL2mpL:123517419)*

**Pull request merged**
