### PR TITLE
Fix #406

### LINKED ISSUE #406: Add missing methods in model
In ``Measurement Tool`` interface missing the `void measure(MeasurementOrder measurements)` and in ``Measurement Controller`` the `canMeasure(ReadOnlyBlackboardView blackboard)` method is still missing. Please add them to the model.

### PR DESCRIPTION
**Pull request by viridispirus**
fixes #406 

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/409)

### CODE REVIEW

**Comment by jGleitz** [comment]
Please add the `measure` method in the Beagle Core diagram, too



---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/409#-:-K76oVCugV8BTq-nZmIM:1968433617)*

**Comment by RomanLangrehr** [comment]
The problem of @jGleitz  still exists.

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/409#-:-K76wgAZHQGzzYgx0Hpn:1991579821)*

**Comment by jGleitz** [comment]
conflicted

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/409#-:-K77Sz1NT66nBk-49yd9:-504176970)*

**Comment by RomanLangrehr** [comment]
You removed MeasurementController#measure and there are now 2 can measure methods:


---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/409#-:-K7BgnoaYWc3EeCl3XfJ:-3918794)*

**Comment by jGleitz** [comment]
Is this PR still relevant?

`Measurement Tool#measure` exists and is shown in the Measurement and Controller Diagram:



`Measurement Controller#can measure` is present, too:



---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/409#-:-K7BhnSfWVMz7FIUHwOk:-490095722)*

**Comment by viridispirus** [comment]
Oh no, I thought that something gots broken.

**Pull request closed without merging**
