### PR TITLE
added "false" to Equals Matcher

### PR DESCRIPTION
**Pull request by acBerger**
Seems like I forgot to fail in the EqualsMatcher if the result of object.equals(object) is false. I am sorry. Luckily I do not think adding this changes makes something fail, so all of us did it right.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/741)

### CODE REVIEW

**Comment by m1cm1c** [comment]
:lgtm:

**Comment by m1cm1c** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/741)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/741#-:-KAuyyiGWkU6drYnUUnY:980077423)*

**Comment by jGleitz** [comment]
:lgtm: :white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/741#-:-KAv5-TNO-FiEbnIwIOH:-1603124213)*

**Pull request merged**
