### PR TITLE
Fix #770 - IllegalStateException

### LINKED ISSUE #770: IllegalStateException in PcmBeagleMappings#addPcmIdOf
An injection Exception caused by a IllegalStateException is thrown when trying to Analyse CocoMe with Beagle.

```
Caused by: java.lang.IllegalStateException
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmBeagleMappings.addPcmIdOf(PcmBeagleMappings.java:192)
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmRepositorySeffExtractor.addInternalActionToSet(PcmRepositorySeffExtractor.java:186)
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmRepositorySeffExtractor.extractBehaviourAndAddToSet(PcmRepositorySeffExtractor.java:119)
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmRepositorySeffExtractor.extractBranchAction(PcmRepositorySeffExtractor.java:163)
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmRepositorySeffExtractor.extractBehaviourAndAddToSet(PcmRepositorySeffExtractor.java:124)
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmRepositorySeffExtractor.extractBranchAction(PcmRepositorySeffExtractor.java:163)
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmRepositorySeffExtractor.extractBehaviourAndAddToSet(PcmRepositorySeffExtractor.java:124)
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmRepositorySeffExtractor.extractBranchAction(PcmRepositorySeffExtractor.java:163)
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmRepositorySeffExtractor.extractBehaviourAndAddToSet(PcmRepositorySeffExtractor.java:124)
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmRepositorySeffExtractor.extractBranchAction(PcmRepositorySeffExtractor.java:163)
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmRepositorySeffExtractor.extractBehaviourAndAddToSet(PcmRepositorySeffExtractor.java:124)
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmRepositoryExtractor.extractResourceDemandingSEFFImplAndAddContentsToSet(PcmRepositoryExtractor.java:237)
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmRepositoryExtractor.extractBasicComponentAndAddContentsToSet(PcmRepositoryExtractor.java:223)
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmRepositoryExtractor.scanRepository(PcmRepositoryExtractor.java:207)
at de.uka.ipd.sdq.beagle.core.pcmconnection.PcmRepositoryExtractor.getBlackboardForAllElements(PcmRepositoryExtractor.java:100)
```

> Ja, die IllegalStateException wird geworfen, weil Somox unterschiedliche Seff Elemente auf die gleiche CodeSections mappt (zumindest das was in den EntityNames steht, aus denen ich parse)

> Wenn wir das SourceCode Mapping mit dem Decorator hinbekommen, sollte das Problem gefixt sein. Andernfalls muss es auskommentiert werden oder Somox überarbeitet werden.

### PR DESCRIPTION
**Pull request by flyfl**
Fixes #770 
Solution:
- Introduced a variable to define if Somox' identifiers are unambigous.

- Added methods to check if the same SeffElements exists for different identifiers

- Prevented the addition of SeffElements with ambigous identifiers (More detailed: if a SeffElement should be added, but it is already known with another identifer, the addition will be prevented)

---
This change is [Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/800)

### CODE REVIEW

**Comment by m1cm1c** [comment]
Travis will fail.

**Comment by m1cm1c** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java, line 100 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/800#-KCRm1oEMQEXrVP9c6iv:-KCRm1oEMQEXrVP9c6iw:-1159449488) ([raw file](https://github.com/beagle-pse/beagle/blob/cd99a99e8ee9eef1609a5dcfa62bc4425d228252/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java#L100)):*
When is this variable ever written to?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/800)*

**Comment by m1cm1c** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/800)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java, line 100 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/800#-KCRm1oEMQEXrVP9c6iv:-KCRrvUkzGvwIVmgenHw:-1279473583) ([raw file](https://github.com/beagle-pse/beagle/blob/f0241664847936f6e152dad93dbb2db7614d9055/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java#L100)):*
If I get this right: never. It’s just a way to point out that there is code that is a workaround for a bug in SoMoX. I like the idea, however, this should be declared as `private static final`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/800)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/800)*

**Comment by jGleitz** [comment]
+@flyfl please fix the checkstyle errors.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/800#-:-KCV5vAosJ2MNZ4tBoqO:160153787)*

**Comment by flyfl** [comment]
>>+@flyfl please fix the checkstyle errors.

I could not fix the checkstyle errors in my Javadoc as Travis' output is too unspecific (stated some problem with "parsing Javadoc at lines [...]".. wow!) and I could not reproduce this fault on my machine. Eclipse does not show me any checkstyle violations.

**Comment by flyfl** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java, line 100 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/800#-KCRm1oEMQEXrVP9c6iv:-KCVjzuii1_wTKX_tmnK:658352280) ([raw file](https://github.com/beagle-pse/beagle/blob/b11bf4c0ff48ac5225dbcec643e3783f830f42eb/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java#L100)):*
Joshua stated this correctly. + this variable is now static

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/800)*

**Comment by acBerger** [comment]
> Maybe someone can help?

Probably there is something wrong with the links you used in your javadoc. Just try to redo the links at the given lines.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/800#-:-KCVlabDQr0Q7XkvzhJ9:945563663)*

**Comment by jGleitz** [comment]
Checkstyle’s Javadoc parser got confused at the given lines. That means that you produced syntactically invalid Javadoc.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/800#-:-KCVmEOVc0AyKVP-ofxI:-218675368)*

**Comment by m1cm1c** [comment]
Just write `{@code true}` instead of `{@true}`. And please start sentences with a capital letter and end them with a period.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/800#-:-KCVn3NRAx-9K-o4prfp:932830484)*

**Comment by m1cm1c** [comment]
The gradle output (which Travis gives you in case you can't run gradle on your machine) even contains the line numbers of the Javadoc you didn't write correctly.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/800#-:-KCVnIUaf5kXE2h_XqJk:-51744615)*

**Comment by flyfl** [comment]
Thanks for your answers! This code had actually wrong links and in addition this missing {@code ..}-annotation. Both is fixed, hopefully Travis will accept this.
@jGleitz This was obviously caused by an syntax error, but that kind of report was not quite helpful..

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/800#-:-KCVnHXCJiejkL1w43bm:-1982245749)*

**Comment by m1cm1c** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java, line 422 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/800#-KCVqFODtZsH4ixSovjW:-KCVqFODtZsH4ixSovjX:-1470812131) ([raw file](https://github.com/beagle-pse/beagle/blob/46c11afd1ceab57757ffd82af52f9d06876d7f20/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java#L422)):*
These still aren't sentences.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/800)*

**Comment by m1cm1c** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java, line 49 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/800#-KCVqdNDn_5LhNKaWvyS:-KCVqdNDn_5LhNKaWvyT:29738870) ([raw file](https://github.com/beagle-pse/beagle/blob/46c11afd1ceab57757ffd82af52f9d06876d7f20/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java#L49)):*
"this can be set to true" It's final.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/800)*

**Comment by m1cm1c** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/800)*

**Comment by m1cm1c** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java, line 49 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/800#-KCVqdNDn_5LhNKaWvyS:-KCVrhgf1KJnSbvsx2m7:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/46c11afd1ceab57757ffd82af52f9d06876d7f20/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java#L49)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/800)*

**Comment by m1cm1c** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/800)*

**Comment by jGleitz** [comment]
> but that kind of report was not quite helpful

Checkstyle tends to create messages that are not very helpful.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/800#-:-KCVruipCpW6qqgr1QN5:-1291129114)*

**Comment by RomanLangrehr** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java, line 422 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/800#-KCVqFODtZsH4ixSovjW:-KCVwEL0DeSrmxkOeYR2:-978559289) ([raw file](https://github.com/beagle-pse/beagle/blob/46c11afd1ceab57757ffd82af52f9d06876d7f20/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java#L422)):*
We decided that @param docs don't need to be full sentences, so this is ok here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/800#-:-KCVwRnahVCpqdlhTuB9:1417088721)*

**Comment by flyfl** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java, line 422 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/800#-KCVqFODtZsH4ixSovjW:-KCVwKAZMh1fND44qY-W:-1829337940) ([raw file](https://github.com/beagle-pse/beagle/blob/46c11afd1ceab57757ffd82af52f9d06876d7f20/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java#L422)):*
Checkstyle does not complain, anyway.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/800)*

**Comment by m1cm1c** [comment]
:lgtm: :white_check_mark: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/800#-:-KCVwxOrGnkSciK-I0ek:-1603124213)*

**Pull request merged**
