### PR TITLE
Evaluable Expression Visitors

### LINKED ISSUE #615: Modifying & Analysing Evaluable Expressions
#608 

In our Evaluable Expression Stubs we have for some evaluable expressions only setters and for others only a constructor. We need to decide how we want to set the inner expressions.
If we decide on only using a constructor we will not have the possibility to change them again (could be wanted when trying to create a similar evaluable expression to propose). On the other hand we then cannot change the values by mistake.

### PR DESCRIPTION
**Pull request by jGleitz**
Fixes #615 

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/767)

### CODE REVIEW

**Comment by viridispirus** [comment]
Reviewed 5 of 14 files at r1, 3 of 3 files at r2.
Review status: 8 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/util/ModifyingEvaluableExpressionVisitor.java, line 440 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/767#-KC-pyZ5C7soXNXCiEE9:-KC-pyZ5C7soXNXCiEEA:677194780) ([raw file](https://github.com/beagle-pse/beagle/blob/6a1c8034d02409e3ce100b0fa3658801b0789490/Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/util/ModifyingEvaluableExpressionVisitor.java#L440)):*
Why?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/767)*

**Comment by viridispirus** [comment]
Reviewed 6 of 14 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/767)*

**Comment by viridispirus** [comment]
:white_check_mark: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/767#-:-KC-xSDo-5IPu4Op7mGW:1605498549)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/util/ModifyingEvaluableExpressionVisitor.java, line 440 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/767#-KC-pyZ5C7soXNXCiEE9:-KC0GjwfwpZy81NpcF6j:21404092) ([raw file](https://github.com/beagle-pse/beagle/blob/6a1c8034d02409e3ce100b0fa3658801b0789490/Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/util/ModifyingEvaluableExpressionVisitor.java#L440)):*
The `OuterExpressionModifier` is responsible for rebuilding expressions containing expressions that were modified, to correctly reflect that modification.
As neither an `EvaluableVariable` nor a `ConstantExpression` can contain another expression, they will never be visited. Thus, those to methods will never be called.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/767)*

**Comment by viridispirus** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/util/ModifyingEvaluableExpressionVisitor.java, line 440 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/767#-KC-pyZ5C7soXNXCiEE9:-KC0K8CQON0kyDV5NeVb:160384653) ([raw file](https://github.com/beagle-pse/beagle/blob/6a1c8034d02409e3ce100b0fa3658801b0789490/Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/util/ModifyingEvaluableExpressionVisitor.java#L440)):*
Ok.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/767)*

**Comment by RomanLangrehr** [comment]
Reviewed 11 of 14 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/util/ExpressionTreeWalker.java, line 36 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/767#-KC57vuUUWIGmqYXimAl:-KC57vuUUWIGmqYXimAm:-1577487214) ([raw file](https://github.com/beagle-pse/beagle/blob/89430f4f818841f372a4ce07c2ae911177982d94/Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/util/ExpressionTreeWalker.java#L36)):*
Should be link instead of linkplain, or?

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/util/ExpressionTreeWalker.java, line 55 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/767#-KC58DJtANg8pLoTyiRu:-KC58DJtANg8pLoTyiRv:-455559786) ([raw file](https://github.com/beagle-pse/beagle/blob/89430f4f818841f372a4ce07c2ae911177982d94/Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/util/ExpressionTreeWalker.java#L55)):*
super

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/767)*

**Comment by jGleitz** [comment]
Review status: 13 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/util/ExpressionTreeWalker.java, line 36 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/767#-KC57vuUUWIGmqYXimAl:-KC5C4QAJ1jz1YZPmnOt:677194780) ([raw file](https://github.com/beagle-pse/beagle/blob/89430f4f818841f372a4ce07c2ae911177982d94/Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/util/ExpressionTreeWalker.java#L36)):*
Why?

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/util/ExpressionTreeWalker.java, line 55 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/767#-KC58DJtANg8pLoTyiRu:-KC5CMSGT339aiatJJZl:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/89430f4f818841f372a4ce07c2ae911177982d94/Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/util/ExpressionTreeWalker.java#L55)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/767)*

**Comment by RomanLangrehr** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/util/ExpressionTreeWalker.java, line 36 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/767#-KC57vuUUWIGmqYXimAl:-KC5DZDkXHP_2CegwTkY:1887211689) ([raw file](https://github.com/beagle-pse/beagle/blob/89430f4f818841f372a4ce07c2ae911177982d94/Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/util/ExpressionTreeWalker.java#L36)):*
For linkplain you need two arguments, don't you?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/767)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/util/ExpressionTreeWalker.java, line 36 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/767#-KC57vuUUWIGmqYXimAl:-KC5ECAPMyod9uHq7W0l:-665462331) ([raw file](https://github.com/beagle-pse/beagle/blob/89430f4f818841f372a4ce07c2ae911177982d94/Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/util/ExpressionTreeWalker.java#L36)):*
No, you don’t. linkplain and link have the exact same syntax. The only difference is that `@link` will be printed in a typewriter font and `@linkplain` will be printed in the default font.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/767)*

**Comment by RomanLangrehr** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/util/ExpressionTreeWalker.java, line 36 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/767#-KC57vuUUWIGmqYXimAl:-KC5EVAuEhVcniKJb0BC:1776681207) ([raw file](https://github.com/beagle-pse/beagle/blob/89430f4f818841f372a4ce07c2ae911177982d94/Core/src/main/java/de/uka/ipd/sdq/beagle/core/evaluableexpressions/util/ExpressionTreeWalker.java#L36)):*
I see.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/767)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/767#-:-KC5EeDW8_y1RtbwPbN8:980077423)*

**Comment by m1cm1c** [comment]
Reviewed 11 of 14 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/767)*

**Comment by m1cm1c** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/767#-:-KC5U2Jaf7nuOud0Zsw6:1417088721)*

**Comment by RomanLangrehr** [comment]
:white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/767#-:-KC5Vzc5SHXLwa1fKFzJ:1605498549)*

**Pull request merged**
