### PR TITLE
Gui fix la deuxième

### PR DESCRIPTION
**Pull request by m1cm1c**
See commits.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/540)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
[Website](http://m1cm1c.github.io/Beagle/branches/gui-fix-la-deuxi%C3%A8me/Design%20and%20Architecture.pdf)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/540#-:-K7gfl-0J3TigRs_xKQ6:-760670452)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/540#-:-K7gg7SWe3akHhy7yMEC:980077423)*

**Comment by RomanLangrehr** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/540)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/540#-:-K7ggcx_Y-2pTDtpbFVV:1417088721)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/540#-:-K7ghWet8tCRseErFlDO:980077423)*

**Pull request merged**
