### PR TITLE
Sequence Diagram 

### PR DESCRIPTION
**Pull request by RomanLangrehr**
My first work at #390 . Just want to share it with you, even only a small part is ready now. And this one isn't looking good. But it took many hours! (Look in the model explrer, if you have doubts ;) ).

The sequence diagram only shows the main loop. I planned to add such sequence - sub - diagrams to show the communication with the blackboard.

What do you think?

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/433)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
Strange. it works on my machine.

**Comment by jGleitz** [comment]
> But it took many hours! 

I totally believe you – it took me ages to create the first class diagram draft!

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/433#-:-K7DO2EZ5yEmYHY3-7ST:-2022944430)*

**Comment by m1cm1c** [comment]
@jGleitz: Do you get the same error message?

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/433#-:-K7DPScTsRbXkDDXa6nk:172582463)*

**Comment by jGleitz** [comment]
> @jGleitz: Do you get the same error message?

No.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/433#-:-K7DTexDVVE7Ngg2q6Xc:227823660)*

**Comment by jGleitz** [comment]
I only did a quick review, but noticed something: We decided at one meeting that only one Result Analyser or only the Final Judge is invoked in one iteration of the main loop. We decided this to enable Analysers to report new things to be measured.

Furthermore, the example could include that a certain Result Analyser can first not contribute but can contribute later and / or that a Result Analyser contributes twice.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/433#-:-K7DThIfSzKqA8JW64UO:-852576025)*

**Comment by jGleitz** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/433)*

**Comment by acBerger** [comment]
> @jGleitz: Do you get the same error message?
No.
 
I do not get the an error message, too.

---

Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/433#-:-K7GZNZ8F4dpz-_3EzE9:556353790)*

**Comment by m1cm1c** [comment]
>>> @jGleitz: Do you get the same error message?

>> No.

> I do not get the an error message, too.

This error apparently is already in the master. It doesn't seem to be a problem exclusively being caused by my workspace / installation of Eclipse / installation of Papyrus / other software on my system because I don't get this error if I check out something a few days old.

Anyway, this error message can be closed. If I do so, I'm shown the diagram.

---

Review status: 1 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/433#-:-K7GnZ0gs4VbKSyFNi8u:-2138341307)*

**Comment by flyfl** [comment]
This is a good starting point! And I like your plan, creating an over-all sequence (this PR) and sub-sequences. Are you going to improve the if-else-paths within the ALT-operator? I think they are not identifyable (actually missing?).

**Comment by jGleitz** [comment]
> It doesn't seem to be a problem exclusively being caused by my workspace / installation of Eclipse / installation of Papyrus / other software on my system because I don't get this error if I check out something a few days old.

Well that’s a wrong implication here. I’d rather say you have some bad files on your machine, as it’s working for everybody else.

---

Review status: 1 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/433#-:-K7Ieixh0svzwqjsTh77:1408062162)*

**Comment by acBerger** [comment]
This branch has conflicts that must be resolved

**Comment by RomanLangrehr** [comment]
> I only did a quick review, but noticed something: We decided at one meeting that only one Result Analyser or only the Final Judge is invoked in one iteration of the main loop. We decided this to enable Analysers to report new things to be measured.

Done

> Furthermore, the example could include that a certain Result Analyser can first not contribute but can contribute later and / or that a Result Analyser contributes twice.

I don't see a way doing this without big effort. I prefer the opt-operators.

> This is a good starting point! And I like your plan, creating an over-all sequence (this PR) and sub-sequences. Are you going to improve the if-else-paths within the ALT-operator? I think they are not identifyable (actually missing?).

What do you mean? Please note, that I don't use ALT, but OPT, which has nothing like an "else". It can be executed or not.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/433#-:-K7MxXsdAt8FJadanFOH:-1012018198)*

**Comment by flyfl** [comment]
>What do you mean? Please note, that I don't use ALT, but OPT, which has nothing like an "else". It can be executed or not.

In the main-Method we have two branches splitting depending on a boolean (first one: `MeasurementController.canContribute(readOnlyBlackboardView)`, second one: `analysersIterator.current().canContribute(readOnlyBlackboardView)`). I can't see the else-branches in your PR.

**Comment by RomanLangrehr** [comment]
> In the main-Method we have two branches splitting depending on a boolean (first one: MeasurementController.canContribute(readOnlyBlackboardView), second one: analysersIterator.current().canContribute(readOnlyBlackboardView)). I can't see the else-branches in your PR.

Okay, know I understand the problem.
I adapted the sequnce diagram accordingly.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/433#-:-K7QytKjZntG58-MZxmx:-304053740)*

**Comment by flyfl** [comment]
I am a bit confused. Now, you leave out all alt-operators.
My understanding of a sequence diagram is, that you show a sequence of a certain called method.
For my understanding this means, that you model everything from top to bottom as it is defined in the class-diagram.
You don't show several calls of a loop. You don't show the execution of a specific branch.
For loops: boxes with loop-operator, filled with exactly whith the content of the loop.
For branches: boxes with alt-operator, upper section "if" (containing content of if-branch), lower section "else" (analog to if-branch).

I thought a sequence diagram models a specific method-call as GENERAL as possible. Am I that much wrong? Is it just a CONCRETE sequence that COULD happen during execution?

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/433#-:-K7RIWrtas9SR3QgM4hs:673740380)*

**Comment by RomanLangrehr** [comment]
As far as I know a sequence diagram always shows a concrete call sequnce.
But you can use those boxes to make it more general, but this is optional.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/433#-:-K7RQkkEzUW9erLy_ogq:567514021)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/433#-:-K7XL5T7rzAo4E0sn3WK:980077423)*

**Comment by flyfl** [comment]
:lgtm_strong:

**Pull request merged**
