### PR TITLE
Measurement result analyser plugin

### LINKED ISSUE #776: Averaging Measurement Result Analyser should be a seperate plugin.

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Fixes #776

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/780)

### CODE REVIEW

**Comment by viridispirus** [comment]
Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/780)*

**Comment by acBerger** [comment]
Reviewed 1 of 21 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/780)*

**Comment by viridispirus** [comment]
Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/780)*

**Comment by viridispirus** [comment]
Reviewed 1 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/780)*

**Comment by acBerger** [comment]
Reviewed 17 of 21 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/780)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/780#-:-KCDFWagiI55lLGt2WpQ:980077423)*

**Comment by m1cm1c** [comment]
+acBerger Your tests need to be adapted.

---

Review status: 19 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/780#-:-KCOKGd0gvjW-K4JTsTR:669998710)*

**Comment by m1cm1c** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/780)*

**Comment by RomanLangrehr** [comment]
> +acBerger Your tests need to be adapted.

No, there is a build problem with the tests.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/780#-:-KCPRiLv1TmD7fcpmK-W:-147273193)*

**Comment by viridispirus** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/780)*

**Comment by jGleitz** [comment]
> No, there is a build problem with the tests.

Done.

**Comment by jGleitz** [comment]
:lgtm: :white_check_mark: 

---

Reviewed 13 of 23 files at r1, 2 of 4 files at r2, 1 of 1 files at r3, 11 of 12 files at r4, 2 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Averaging Measurement Result Analyser/dependencies.gradle, line 13 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/780#-KCa2UGDWQTtaCw7fpuI:-KCa2UGDWQTtaCw7fpuJ:1655994125) ([raw file](https://github.com/beagle-pse/beagle/blob/41015fc08a9468d406ad171b74f6d679aac07f5b/Averaging Measurement Result Analyser/dependencies.gradle#L13)):*
Are you sure all those dependencies are required? I think at least the commons-io should not be required.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/780#-:-KCa3zKx5wRBBE2rBzOj:-1603124213)*

**Comment by viridispirus** [comment]
Reviewed 2 of 23 files at r1, 7 of 12 files at r4, 2 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/780)*

**Comment by RomanLangrehr** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Averaging Measurement Result Analyser/dependencies.gradle, line 13 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/780#-KCa2UGDWQTtaCw7fpuI:-KCaxzslw4T08U7dSk8p:-706812005) ([raw file](https://github.com/beagle-pse/beagle/blob/41015fc08a9468d406ad171b74f6d679aac07f5b/Averaging Measurement Result Analyser/dependencies.gradle#L13)):*
Some are not required, but I thought it would be good to keep them there, so you can just use them if you want to.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/780)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Averaging Measurement Result Analyser/dependencies.gradle, line 13 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/780#-KCa2UGDWQTtaCw7fpuI:-KCaz4m-qDZK3yvvutoh:-301380103) ([raw file](https://github.com/beagle-pse/beagle/blob/41015fc08a9468d406ad171b74f6d679aac07f5b/Averaging Measurement Result Analyser/dependencies.gradle#L13)):*
I think this is bad practice. Because if everybody just declares the dependencies they really need, we keep the files we need to download to a minimum. Especially for production dependencies, because every dependency we’re declaring will be downloaded by the user.

And adding a line to this file to start using a dependency again is not that much work, is it?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/780)*

**Comment by jGleitz** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/780)*

**Comment by jGleitz** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/780)*

**Comment by RomanLangrehr** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Averaging Measurement Result Analyser/dependencies.gradle, line 13 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/780#-KCa2UGDWQTtaCw7fpuI:-KCcTAh_9E5-aVuIqaKm:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/41015fc08a9468d406ad171b74f6d679aac07f5b/Averaging Measurement Result Analyser/dependencies.gradle#L13)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/780)*

**Comment by viridispirus** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/780#-:-KCePTAI4USQcjMl6hOo:1417088721)*

**Comment by viridispirus** [comment]
Reviewed 3 of 12 files at r4, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/780)*

**Comment by jGleitz** [comment]
:lgtm: :white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/780#-:-KCeQtaQhmtmYqYgaKnp:-1603124213)*

**Comment by viridispirus** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/780#-:-KCeR92hxnRKQQjksoKi:1417088721)*

**Comment by jGleitz** [comment]
:lgtm: :white_check_mark:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/780#-:-KCeR8HlQYKJydHyk7Zd:-1852829003)*

**Pull request merged**
