### PR TITLE
Thread Communication + Pausing, Continuing, Aborting

### LINKED ISSUE #758: Thread Communication
For some of the features we want to implement in this phase, namely PAUSE, ABORT and TIMEOUT, we need some sort of thread communication.

I see several questions when implementing this, which I want to discuss here.

 1. From my pov, there are two concepts to realise this:
  1. Thread interrupts: The running thread is sent an interrupt to signal he’s supposed to stop what he’s doing
   1. using asynchronous callbacks: The running thread can register for the events and provide a method that handles them (could also be realised through the analyser interface, thus inforcing implementation of the handlers).
 1. For either concepts, we need more threads than we have right now. Who spawns them? I see two possibilities:
    1. spawn contributor threads: The analysis controller spawns a new thread to execute a contributor
    1. spawn event management threads: The instances issuing the events are in a separate thread (like one thread for the TIMEOUT, one thread for the GUI (that issues PAUSE and ABORT))
 1. If we use interrupts, does the interrupted thread get information about *why* it was interrupted (e.g. to save data for pause but stop immediately for abort)? If yes, how does it get it?

I’d like to hear your thoughts about this. I think 1.i and 2.ii is the best suited combination for the issue, but that raises question 3.

### PR DESCRIPTION
**Pull request by m1cm1c**
Fixes #758.
Fixes #789.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/772)

### CODE REVIEW

**Comment by jGleitz** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/AnalysisController.java, line 114 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/772#-KC7Q51rZCRe8lHhN4It:-KC7Q51sucBVUMVsQbSi:1093800523) ([raw file](https://github.com/beagle-pse/beagle/blob/207d11363c9f55a3f2af84be9f6b2b4d8de98dbf/Core/src/main/java/de/uka/ipd/sdq/beagle/core/AnalysisController.java#L114)):*
What are you doing here? You’re interrupting the thread instantly? I guess you wanted to register the callback on the `Timeout`.

If you’re interested: All this can be written way shorter as `new Thread(Thread.currentThread()::interrupt).start();`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/772)*

**Comment by m1cm1c** [comment]
Review status: 0 of 26 files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/AnalysisController.java, line 114 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/772#-KC7Q51rZCRe8lHhN4It:-KC7V7tFcKITIN1B3s4Y:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/207d11363c9f55a3f2af84be9f6b2b4d8de98dbf/Core/src/main/java/de/uka/ipd/sdq/beagle/core/AnalysisController.java#L114)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/772)*

**Comment by m1cm1c** [comment]
+blocked because this depends on #752.

---

Review status: 0 of 26 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/772#-:-KC7cYfG934Cqgm3C91a:-465182045)*

**Comment by m1cm1c** [comment]
Travis fails because of #752. The changes this PR is about don't cause Travis to fail.

**Comment by acBerger** [comment]
Reviewed 1 of 5 files at r1, 24 of 25 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/772)*

**Comment by RomanLangrehr** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[GUI/src/main/java/de/uka/ipd/sdq/beagle/gui/TimeoutWizardPage.java, line 1 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/772#-KCB75W1PFWzAr2Tu3KA:-KCB75W1PFWzAr2Tu3KB:219695251) ([raw file](https://github.com/beagle-pse/beagle/blob/1dfdaab5c1a28d6d00f45313e3b10e770a32f7fd/GUI/src/main/java/de/uka/ipd/sdq/beagle/gui/TimeoutWizardPage.java#L1)):*
Why did you edit this?
All chanages in this file will be overwritten by my PR.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/772)*

**Comment by m1cm1c** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[GUI/src/main/java/de/uka/ipd/sdq/beagle/gui/TimeoutWizardPage.java, line 1 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/772#-KCB75W1PFWzAr2Tu3KA:-KCB8pEbVUYPkWFzKx27:1904076844) ([raw file](https://github.com/beagle-pse/beagle/blob/1dfdaab5c1a28d6d00f45313e3b10e770a32f7fd/GUI/src/main/java/de/uka/ipd/sdq/beagle/gui/TimeoutWizardPage.java#L1)):*
It took very little effort and made Travis fail no longer.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/772)*

**Comment by acBerger** [comment]
Reviewed 2 of 10 files at r4, 2 of 2 files at r6, 5 of 5 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/772)*

**Comment by m1cm1c** [comment]
Unblocked because #752 got merged.

**Comment by jGleitz** [comment]
Why doesn’t this need tests anymore?

**Comment by m1cm1c** [comment]
I confused it with a different branch. This not only still needs tests but it even needs a tester.

**Comment by acBerger** [comment]
Reviewed 3 of 3 files at r11.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/772)*

**Comment by viridispirus** [comment]
Reviewed 1 of 10 files at r4, 2 of 5 files at r7, 3 of 3 files at r11.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/772)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r12.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/772)*

**Comment by acBerger** [comment]
Reviewed 3 of 3 files at r13.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/772)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r14, 1 of 1 files at r15.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/772)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r16.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/772)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r17.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/772)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r18.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/772)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r20.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/772)*

**Comment by viridispirus** [comment]
Reviewed 1 of 3 files at r13, 1 of 1 files at r14, 1 of 1 files at r16, 1 of 1 files at r17, 1 of 1 files at r20.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/facade/BeagleControllerTest.java, line 17 \[r20\]](https://reviewable.io:443/reviews/beagle-pse/beagle/772#-KCD86FO9_Hfk4idOKlq:-KCD86FO9_Hfk4idOKlr:-1487630377) ([raw file](https://github.com/beagle-pse/beagle/blob/bfcb25b080ae35db131b86fe32329eb66d4ea39c/Core/src/test/java/de/uka/ipd/sdq/beagle/core/facade/BeagleControllerTest.java#L17)):*
Missing Javadoc.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/772)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/772#-:-KCDETx1oIH0jpLsxz6d:980077423)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r21.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/772)*

**Comment by m1cm1c** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/facade/BeagleControllerTest.java, line 17 \[r20\]](https://reviewable.io:443/reviews/beagle-pse/beagle/772#-KCD86FO9_Hfk4idOKlq:-KCDcKBXJXv2Q70PZj0q:166857) ([raw file](https://github.com/beagle-pse/beagle/blob/bfcb25b080ae35db131b86fe32329eb66d4ea39c/Core/src/test/java/de/uka/ipd/sdq/beagle/core/facade/BeagleControllerTest.java#L17)):*
.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/772)*

**Comment by RomanLangrehr** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r7, 6 of 9 files at r23, 3 of 3 files at r24.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/772#-:-KCDdh-hjr2docrvlt7r:1417088721)*

**Comment by RomanLangrehr** [comment]
:white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/772#-:-KCDgAAwJsK4ckdChhIk:1605498549)*

**Comment by jGleitz** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/772#-:-KCDgpbFtNjzymTHWwgM:1417088721)*

**Pull request merged**
