### PR TITLE
Added reenginering activity diagram.

### LINKED ISSUE #44: Activity Diagram for /A10/

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Fixes #44 
The diagram is a little bit different to the preview I once posted.

### CODE REVIEW

**Comment by jGleitz** [comment]
[View this PR’s rendered SRS PDF](http://romanlangrehr.github.io/Beagle/branches/Workflow/Requirements%20Specification.pdf)

**Comment by jGleitz** [comment]
I’d change “Change architecture or hardware resources” to “Plan architecture or hardware resource changes” and add a bubble “Implement planned changes” in the “[good resulds] /execute SoMoX (to verify changes” connection to emphasise that planning is done in Palladio.

What do you think of it?

**Comment by RomanLangrehr** [comment]
> I’d change “Change architecture or hardware resources” to “Plan architecture or hardware resource changes” and add a bubble “Implement planned changes” in the “[good resulds] /execute SoMoX (to verify changes” connection to emphasise that planning is done in Palladio.

I agree with both, I'll change it...

**Comment by flyfl** [comment]
The actual slides (SWT, activity diagram) specify the content of the boxes as "actions". In your diagram the boxes mix action and state, what I don't find bad. Opinions?

**Comment by RomanLangrehr** [comment]
> The actual slides (SWT, activity diagram) specify the content of the boxes as "actions". In your diagram the boxes mix action and state, what I don't find bad. Opinions?

I actually think, I have to change my diagram. Especially the /doSomething annotation is only for state diagrams, not for activity diagrams...

**Comment by RomanLangrehr** [comment]
I change it. If you really like the old one better, we can still revert to it.

**Comment by m1cm1c** [comment]
lgtm

**Comment by jGleitz** [comment]
@RomanLangrehr I made some adaptions in RomanLangrehr/Beagle#3. Please see if you like them.

**Pull request merged**
