### PR TITLE
Fixes #22. Changed file names in accordance with the file name convention in #13.

### LINKED ISSUE #22: Adopt New File Format
In #13 we specified a file and folder name format. This has now to be consequently applied to *all* files and folders.

(Hint: Using your git tool (or `git mv`) to rename files assures git recognizes the movements instead of showing deletions and additions.)

### PR DESCRIPTION
**Pull request by m1cm1c**

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
lgtm

**Comment by m1cm1c** [comment]
This is just so you can see what I did. DO NOT MERGE THIS PULL REQUEST.

**Comment by m1cm1c** [comment]
There is this `terms and definitions.tex` in `Requirements Specification.lyx` and I don't know what to do about it.

**Comment by m1cm1c** [comment]
I renders nonetheless, btw.

**Comment by jGleitz** [comment]
> There is this terms and definitions.tex in Requirements Specification.lyx and I don't know what to do about it.

Just change it to `Terms and Definitions.tex`

> I renders nonetheless, btw.

Sure about that? It should not build the glossary probably without it. Please recheck, I’d happily remove it.

**Comment by m1cm1c** [comment]
Well, I can't find any difference. The files even have the exact same size. But I changed it.

**Comment by jGleitz** [comment]
> Well, I can't find any difference. The files even have the exact same size. But I changed it.

Thanks for reporting. You did render with `render.sh`, didn't you? I’ll look into it.

**Comment by jGleitz** [comment]
We decided to use British English for documentation. I think this should apply to folder also.

I don’t see the use of the `doc/Organization` folder at all, I think `doc/Agendas` would be sufficient.

But if you want to keep it, please name it `Organisation`.

**Comment by m1cm1c** [comment]
Yes, I rendered it using the `Render.sh`. I'll change the file structure in a minute.

**Comment by m1cm1c** [comment]
Changed the file structure.

**Comment by jGleitz** [comment]
lgtm

**Pull request merged**
