### PR TITLE
Missing tests

### PR DESCRIPTION
**Pull request by acBerger**
I added some missing tests to improve the test coverage. I think all classes and methods which can be tested with JUnit tests are covered now (except the ones covered by #769 ).

---
This change is [Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/813)

### CODE REVIEW

**Comment by jGleitz** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/AnalysisControllerTest.java, line 1 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/813#-KCgryHGmUCZDlG2zpwR:-KCgryHH0q1HzhipIR7d:1671364159) ([raw file](https://github.com/beagle-pse/beagle/blob/f20bb149f199120b5be6a4410d9cc3e1270dae88/Core/src/test/java/de/uka/ipd/sdq/beagle/core/AnalysisControllerTest.java#L1)):*
I think there should be tests asserting that only meaningful state transitions are allowed.n

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/AnalysisControllerTest.java, line 1006 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/813#-KCgrqikvPjqS9Umhe7y:-KCgrqikvPjqS9Umhe7z:-1405563018) ([raw file](https://github.com/beagle-pse/beagle/blob/f20bb149f199120b5be6a4410d9cc3e1270dae88/Core/src/test/java/de/uka/ipd/sdq/beagle/core/AnalysisControllerTest.java#L1006)):*
I think these comments are not needed any more

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmsourcestatementlink/PcmSourceStatementLinkReaderTest.java, line 52 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/813#-KCgtlxGk7T2aE-QLEp3:-KCgtlxH4zoTWgx68V2V:-456664027) ([raw file](https://github.com/beagle-pse/beagle/blob/f20bb149f199120b5be6a4410d9cc3e1270dae88/Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmsourcestatementlink/PcmSourceStatementLinkReaderTest.java#L52)):*
Please add some checks here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/813)*

**Comment by acBerger** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/AnalysisControllerTest.java, line 1 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/813#-KCgryHGmUCZDlG2zpwR:-KCgzO1XiJ5-PjusdBlH:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/f20bb149f199120b5be6a4410d9cc3e1270dae88/Core/src/test/java/de/uka/ipd/sdq/beagle/core/AnalysisControllerTest.java#L1)):*
Done.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/AnalysisControllerTest.java, line 1006 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/813#-KCgrqikvPjqS9Umhe7y:-KCgzP1AMtHYQ0108sFU:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/f20bb149f199120b5be6a4410d9cc3e1270dae88/Core/src/test/java/de/uka/ipd/sdq/beagle/core/AnalysisControllerTest.java#L1006)):*
Done.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmsourcestatementlink/PcmSourceStatementLinkReaderTest.java, line 52 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/813#-KCgtlxGk7T2aE-QLEp3:-KCgzPVgUSSjGVuTT8yG:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/f20bb149f199120b5be6a4410d9cc3e1270dae88/Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmsourcestatementlink/PcmSourceStatementLinkReaderTest.java#L52)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/813)*

**Comment by jGleitz** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/813)*

**Comment by flyfl** [comment]
Reviewed 2 of 5 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/813)*

**Comment by flyfl** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/813#-:-KCjexJDWpcFoRXaiccz:1417088721)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmsourcestatementlink/PcmSourceStatementLinkReaderTest.java, line 1 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/813#-KCjo0n81u7Ld6tuU8kI:-KCjo0n81u7Ld6tuU8kJ:1439988302) ([raw file](https://github.com/beagle-pse/beagle/blob/4c5b0e7ff839b7f99de95979fc0aa1a50be3d0cd/Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmsourcestatementlink/PcmSourceStatementLinkReaderTest.java#L1)):*
Please add:

 * A test getting the same repository two times
 * A test giving an existing file that’s not a PCM Source Statement Link Model
 * A test giving an existing PCM Source Statement Model that has another XML root element.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/813)*

**Comment by acBerger** [comment]
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmsourcestatementlink/PcmSourceStatementLinkReaderTest.java, line 1 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/813#-KCjo0n81u7Ld6tuU8kI:-KCkKUvipz0rbHDIM7rU:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/4c5b0e7ff839b7f99de95979fc0aa1a50be3d0cd/Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmsourcestatementlink/PcmSourceStatementLinkReaderTest.java#L1)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/813)*

**Comment by viridispirus** [comment]
Reviewed 1 of 3 files at r3.
Review status: 4 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/813)*

**Comment by jGleitz** [comment]
Reviewed 2 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/813)*

**Comment by acBerger** [comment]
+blocked as it has to wait for #816 (one test is failing because of the same problem).

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/813#-:-KCkx9BLPrW_qTktEfZ4:1664527748)*

**Comment by acBerger** [comment]
-blocked as #816 is merged

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/813#-:-KClFP-GR_XvxufM-bL-:865620302)*

**Comment by RomanLangrehr** [comment]
Reviewed 1 of 5 files at r1, 2 of 3 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/813)*

**Comment by RomanLangrehr** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/813#-:-KClViPya0e4wQ8URSPH:1417088721)*

**Comment by jGleitz** [comment]
:lgtm: :white_check_mark: 

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/813#-:-KClVxQq_ExLTanjkmlE:-1603124213)*

**Pull request merged**
