### PR TITLE
Blackboard design description

### LINKED ISSUE #387: Describe the design decision behind views

### LINKED ISSUE #391: Describe the Blackboard Design Decision
Reason why we chose the blackboard design.

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Fixes #387
Fixes #391

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/537)

### CODE REVIEW

**Comment by acBerger** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[Documentation/src/design/lyx/Parts/Blackboard.lyx, line 214 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/537#-K7gcMr2tXXgyTt5Kiup:-K7gcMr3W96a7SfXPiCY:44016254) ([raw file](https://github.com/beagle-pse/beagle/blob/a05ca1a0934aa43d38fda74d58b789a53884b3f3/Documentation/src/design/lyx/Parts/Blackboard.lyx#L214)):*
should be only one dot.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/537)*

**Comment by acBerger** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/537)*

**Comment by acBerger** [comment]
[Website] (http://romanlangrehr.github.io/Beagle/branches/0blackboard-design-description/)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/537#-:-K7gcf18eNCb0Wl4L5ga:-894061691)*

**Comment by RomanLangrehr** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Documentation/src/design/lyx/Parts/Blackboard.lyx, line 214 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/537#-K7gcMr2tXXgyTt5Kiup:-K7gf973Z5XG7VSwx_6M:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/3a096fbbb38e7bd0f46c79366f941d672873a148/Documentation/src/design/lyx/Parts/Blackboard.lyx#L214)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/537)*

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/537#-:-K7ggUNOF6dNuPZloJYI:1417088721)*

**Comment by flyfl** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/537#-:-K7gn1YOW-B-ANKSmpez:-1168659251)*

**Pull request merged**
