### PR TITLE
waffle.io Badge

### PR DESCRIPTION
**Pull request by waffle-iron**
Merge this to receive a badge indicating the number of issues in the ready column on your waffle.io board at https://waffle.io/Beagle-PSE/Beagle

This was requested by a real person (user jGleitz) on waffle.io, we're not trying to spam you.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/374)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/374#-:-K72XgfBP3ZeCqk1948f:980077423)*

**Comment by acBerger** [comment]
Do we need this button there? I do not like it. At least not how it is at the moment. I do not see why there has to be the number of ready issues. As nobody how does not already know 'waffle' will  know what it does and what it is for is also is useless.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/374#-:-K72uxSXPkgaUEflQJpC:-2052952656)*

**Comment by jGleitz** [comment]
Thinking about it, I guess I agree with @acBerger. We can add a link to waffle explaining what it does to the README and/or website.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/374#-:-K73-xUCcoN2EqDW58Ct:-2145600932)*

**Comment by m1cm1c** [comment]
I agree, too.

**Pull request closed without merging**
