### PR TITLE
Moved `ReadOnlyBlackboardView`

### PR DESCRIPTION
**Pull request by m1cm1c**
Moved `ReadOnlyBlackboardView` from package `de.uka.ipd.sdq.beagle.analysis` to package `de.uka.ipd.sdq.beagle.core`.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/392)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/392#-:-K760aFLfjwHIn6A-rS_:980077423)*

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/392#-:-K763lqkIqTodXJZBSy4:1417088721)*

**Comment by acBerger** [comment]
@m1cm1c please update

**Comment by acBerger** [comment]
+blocked 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/392#-:-K765xQ5wvkKIdqSz2py:-1952923270)*

**Comment by jGleitz** [comment]
@acBerger blocked this for me because I want to try to get Reviewable to not stale lgtms for simple merges.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/392#-:-K7675rLkpwQiAGv_CuX:-1298100565)*

**Comment by jGleitz** [comment]
This does not seem to be possible :(. I’ll open an issue. -blocked 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/392#-:-K7685Pgqk7CnoRfEPYe:-2003572453)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/392#-:-K769YFrwCZbfsaSLY8h:980077423)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/392#-:-K76C8jc88qGx9Iib36N:980077423)*

**Pull request merged**
