### PR TITLE
Changed /OQ30/.

### PR DESCRIPTION
**Pull request by m1cm1c**

### CODE REVIEW

**Comment by acBerger** [comment]
[PDF] (http://m1cm1c.github.io/Beagle/branches/oq30/Requirements%20Specification.pdf)

**Comment by acBerger** [comment]
is there a possibility to form this sentence without double parenthesise?

**Comment by jGleitz** [comment]
Yeah, I think we don’t have to be *that* detailed. How about “uncaught exceptions, uncaught errors, calls to `System#exit` or other unexpected exiting of the software’s process(es)”

**Comment by flyfl** [comment]
I agree with @jGleitz.

**Comment by RomanLangrehr** [comment]
> I agree with @jGleitz.

me too.

**Comment by m1cm1c** [comment]
Okay, but why `System#exit` instead of `System.exit()`?

**Comment by RomanLangrehr** [comment]
I like `System.exit()` better.

**Comment by flyfl** [comment]
Let's use `System.exit()`

**Comment by jGleitz** [comment]
> Okay, but why System#exit instead of System.exit()

`System#exit` is JavaDoc notation and means “A method of the `System` class called `exit`, any of the overloaded ones if it’s overloaded”

`System.exit()` actually means “Call the method `exit` of the `System` class that takes no arguments with no arguments”

**Comment by flyfl** [comment]
lgtm

**Comment by jGleitz** [comment]
lgtm

**Pull request merged**
