### PR TITLE
changed wording in A40

### PR DESCRIPTION
**Pull request by viridispirus**
such as Michael annotate in our SRS presentation.

### CODE REVIEW

**Comment by m1cm1c** [comment]
This now says "[...] Beagle can analyse resource demandss a PCM which can then be compared to the initial one." which obviously isn't a correct sentence.

**Comment by acBerger** [comment]
@viridispirus: Please try to fix that so that we can merge this soon.

**Comment by jGleitz** [comment]
This now looks good to me.

**Comment by jGleitz** [comment]
While we’re on it: `A40` is actually false. Could you change 

After developing the software with Palladio and implementing it, a static code analysis tool like SoMoX or Beagle can analyse resource demands of a PCM which can then be compared to the initial one. 

to something like

After developing the software with Palladio and implementing it, Beagle can analyse its resource demands which can then be compared to the predicted ones.

**Comment by jGleitz** [comment]
[View this PR’s rendered PDF](http://viridispirus.github.io/Beagle/branches/WordingA10/Requirements%20Specification.pdf)

**Comment by viridispirus** [comment]
ok, thanks for review i'am change that.


2015-12-14 18:43 GMT+01:00 Joshua Gleitze <notifications@github.com>:

**Comment by acBerger** [comment]
@viridispirus  please solve conflicts

**Comment by jGleitz** [comment]
> Beagle can analyse resource demands of a resource demands which can then be compared to the predicted ones.

Beagle can analyse resource demands[…] which can then be compared to the predicted ones.

**Comment by jGleitz** [comment]
@m1cm1c is “more easily” correct? Shouldn’t that be “easier”?

**Comment by m1cm1c** [comment]
It's correct the way it is. "detect" and "resolve" are verbs. => If they are modified, they must be modified by adverbs. "easy" is a verb, "easily" is its corresponding adverb.

**Comment by m1cm1c** [comment]
http://itknowledgeexchange.techtarget.com/writing-for-business/easier-vs-more-easily/

**Comment by jGleitz** [comment]
Thank you!

**Comment by jGleitz** [comment]
Beagle can analyse **[its]** resource demands which can then be compared to the predicted ones.

Sorry!

**Comment by jGleitz** [comment]
lgtm

**Pull request merged**
