### PR TITLE
More Documentation

### PR DESCRIPTION
**Pull request by jGleitz**
The work I did last night. Still very unfinished, but I thought I’d share it to keep the PRs reasonably small.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/569)

### CODE REVIEW

**Comment by m1cm1c** [comment]
Reviewed 10 of 17 files at r1.
Review status: 10 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/CodeSection.java, line 62 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/569#-K7l48-1u4PAOcIQybtj:-K7l48-2wTxL-4kpickL:-961262663) ([raw file](https://github.com/beagle-pse/beagle/blob/5bce18fed336db96a331fa3429f518ca82fa554e/Core/src/main/java/de/uka/ipd/sdq/beagle/core/CodeSection.java#L62)):*
`int`, not `Integer`.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/CodeSection.java, line 83 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/569#-K7l4HOl3RpkK5-h5o5L:-K7l4HOl3RpkK5-h5o5M:-961262663) ([raw file](https://github.com/beagle-pse/beagle/blob/5bce18fed336db96a331fa3429f518ca82fa554e/Core/src/main/java/de/uka/ipd/sdq/beagle/core/CodeSection.java#L83)):*
`int`, not `Integer`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/569)*

**Comment by jGleitz** [comment]
Review status: 9 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/CodeSection.java, line 62 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/569#-K7l48-1u4PAOcIQybtj:-K7l541XEgsweXKsvYVs:-295160165) ([raw file](https://github.com/beagle-pse/beagle/blob/5bce18fed336db96a331fa3429f518ca82fa554e/Core/src/main/java/de/uka/ipd/sdq/beagle/core/CodeSection.java#L62)):*
I wanted to refer to to the general English word “integer“ (because it’s already clear that’s it an `int`). I wrote it in lowercase. Is that okay?

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/CodeSection.java, line 83 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/569#-K7l4HOl3RpkK5-h5o5L:-K7l7HeYwoubklJY89IE:-295160165) ([raw file](https://github.com/beagle-pse/beagle/blob/5bce18fed336db96a331fa3429f518ca82fa554e/Core/src/main/java/de/uka/ipd/sdq/beagle/core/CodeSection.java#L83)):*
I wanted to refer to to the general English word “integer“ (because it’s already clear that’s it an `int`). I wrote it in lowercase. Is that okay?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/569)*

**Comment by RomanLangrehr** [comment]
Reviewed 15 of 17 files at r1, 1 of 1 files at r2.
Review status: 15 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/CodeSection.java, line 35 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/569#-K7rR5h6qwHNWfTty4Yu:-K7rR5h6qwHNWfTty4Yv:154523974) ([raw file](https://github.com/beagle-pse/beagle/blob/64341ef396849610eb61cfb5814a4e74142effe2/Core/src/main/java/de/uka/ipd/sdq/beagle/core/CodeSection.java#L35)):*
better: specify `startFile.isFile()` must return `true`.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/CodeSection.java, line 39 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/569#-K7rRB4yv3uYRLUDK_kR:-K7rRB4yv3uYRLUDK_kS:1061261280) ([raw file](https://github.com/beagle-pse/beagle/blob/64341ef396849610eb61cfb5814a4e74142effe2/Core/src/main/java/de/uka/ipd/sdq/beagle/core/CodeSection.java#L39)):*
better: specify `endFile.isFile()` must return `true`.
And write endFile here ;)

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/measurement/order/MeasurementEvent.java, line 10 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/569#-K7rRr9qxk9YG7hhKqSN:-K7rRr9qxk9YG7hhKqSO:-1774843761) ([raw file](https://github.com/beagle-pse/beagle/blob/64341ef396849610eb61cfb5814a4e74142effe2/Core/src/main/java/de/uka/ipd/sdq/beagle/core/measurement/order/MeasurementEvent.java#L10)):*
`content can't be changed`, maybe?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/569)*

**Comment by RomanLangrehr** [comment]
Reviewed 1 of 17 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/569)*

**Comment by jGleitz** [comment]
Review status: 14 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/CodeSection.java, line 35 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/569#-K7rR5h6qwHNWfTty4Yu:-K7rm1Jm6u48-dCr9p5h:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/64341ef396849610eb61cfb5814a4e74142effe2/Core/src/main/java/de/uka/ipd/sdq/beagle/core/CodeSection.java#L35)):*
Done.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/CodeSection.java, line 39 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/569#-K7rRB4yv3uYRLUDK_kR:-K7rm12LArtl8ZThiUny:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/64341ef396849610eb61cfb5814a4e74142effe2/Core/src/main/java/de/uka/ipd/sdq/beagle/core/CodeSection.java#L39)):*
Done.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/measurement/order/MeasurementEvent.java, line 10 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/569#-K7rRr9qxk9YG7hhKqSN:-K7rlrG_4sYNZd-O2MIh:-1293422317) ([raw file](https://github.com/beagle-pse/beagle/blob/64341ef396849610eb61cfb5814a4e74142effe2/Core/src/main/java/de/uka/ipd/sdq/beagle/core/measurement/order/MeasurementEvent.java#L10)):*
What the fuck happened here? I stopped writing in the middle of the sentence! :'D

Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/569)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/569#-:-K7vIeBqga5JBoNzmAKh:980077423)*

**Comment by flyfl** [comment]
:lgtm:

---

Reviewed 15 of 17 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/569#-:-K8-QG5l-K7zoAMarC0c:1417088721)*

**Pull request merged**
