### PR TITLE
Ip#150 averaging measuremement result analyser

### LINKED ISSUE #640: [IP #150] Averaging Measurement Result Analyser
Build a Measurement Result Analyser, which takes as
EvaluableExpression a ConstantExpression for all
MeasurableSeffElements with the average of all available
measurement results. And the  tool helper classes. (AbstractXXX)

Depends on: IP#120 ( #609 ) (Measurement Results), IP#060 ( #573 ) (Blackboard), IP#070 ( #574 ) (BlackboardViews), IP#040 ( #571 ) (SEFF classes)

### PR DESCRIPTION
**Pull request by flyfl**
Fixes #640

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/709)

### CODE REVIEW

**Comment by acBerger** [comment]
-(tester needed) 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/709#-:-KAVYxqDRiCGfwVdqBob:-210654099)*

**Comment by viridispirus** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/709)*

**Comment by viridispirus** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/709)*

**Comment by acBerger** [comment]
-(tests needed)  @flyfl please check your code

---

Review status: 7 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/709#-:-KAVxu8BWCWll4SOzZ_7:1544251102)*

**Comment by viridispirus** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/709)*

**Comment by viridispirus** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/709)*

**Comment by viridispirus** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/709)*

**Comment by viridispirus** [comment]
Reviewed 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/709)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/709#-:-KAWcN5lQhSuo3rfLh0A:980077423)*

**Comment by RomanLangrehr** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/709#-KAWh4e4SYMc2fo1Ii0y:-KAWh4e4SYMc2fo1Ii0z:-1011972753) (no related file):*
This should be a new plugin.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/709)*

**Comment by m1cm1c** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/MeasurementResultAnalyserAverage.java, line 183 \[r8\]](https://reviewable.io:443/reviews/beagle-pse/beagle/709#-KAWsDXMFZwGhHIctsfR:-KAWsDXMFZwGhHIctsfS:1923386330) ([raw file](https://github.com/beagle-pse/beagle/blob/72fd6df5183dda87307edc9e8d88f81ed146c207/Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/MeasurementResultAnalyserAverage.java#L183)):*
Potential division by zero?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/709)*

**Comment by m1cm1c** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/MeasurementResultAnalyserAverage.java, line 244 \[r8\]](https://reviewable.io:443/reviews/beagle-pse/beagle/709#-KAWsYDQI-p4KpqFLFfS:-KAWsYDRQqRno1dvKw5Y:1923386330) ([raw file](https://github.com/beagle-pse/beagle/blob/72fd6df5183dda87307edc9e8d88f81ed146c207/Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/MeasurementResultAnalyserAverage.java#L244)):*
Potential division by zero?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/709)*

**Comment by flyfl** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/MeasurementResultAnalyserAverage.java, line 183 \[r8\]](https://reviewable.io:443/reviews/beagle-pse/beagle/709#-KAWsDXMFZwGhHIctsfR:-KAWtdQxXGojpeCT2aRv:248320345) ([raw file](https://github.com/beagle-pse/beagle/blob/72fd6df5183dda87307edc9e8d88f81ed146c207/Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/MeasurementResultAnalyserAverage.java#L183)):*
No. If there is no MeasurementResult for a given SeffElement, this method is not called.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/MeasurementResultAnalyserAverage.java, line 244 \[r8\]](https://reviewable.io:443/reviews/beagle-pse/beagle/709#-KAWsYDQI-p4KpqFLFfS:-KAWtq3EnLzP72g2QC_j:2101406251) ([raw file](https://github.com/beagle-pse/beagle/blob/72fd6df5183dda87307edc9e8d88f81ed146c207/Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/MeasurementResultAnalyserAverage.java#L244)):*
see above

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/709)*

**Comment by m1cm1c** [comment]
Reviewed 7 of 8 files at r2, 1 of 1 files at r5, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/709)*

**Comment by m1cm1c** [comment]
:white_check_mark:

**Comment by m1cm1c** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/709#-KAWh4e4SYMc2fo1Ii0y:-KAWucO0MglODIXS8fzn:166857) (no related file):*
.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/709)*

**Comment by m1cm1c** [comment]
:lgtm:

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/709#-:-KAWuj5vuz9Qndz1MomZ:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/709#-:-KAWukT3Gn3PdXFy23Dz:980077423)*

**Pull request merged**
