### PR TITLE
Add Superclass Measurable SEFF Elements

### LINKED ISSUE #513: Adapt Java Stubs to Design: SEFF Elements
Create `MeasurableSEFFElement` and document it and its three subtypes.

### PR DESCRIPTION
**Pull request by acBerger**
As my descriptions for the classes are rather bad: please suggest better ones.
fixes #513

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/522)

### CODE REVIEW

**Comment by jGleitz** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/SEFFLoop.java, line 6 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/522#-K7eu1F0MFRgxGKNzjXl:-K7eu1F0MFRgxGKNzjXm:-138748279) ([raw file](https://github.com/beagle-pse/beagle/blob/40e292cdb7c396b477ccfccfc7c4115d9708a245/Core/src/main/java/de/uka/ipd/sdq/beagle/core/SEFFLoop.java#L6)):*
“ in **[a]** component’s SEFF.” (as “the” does not refer to anything here).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/522)*

**Comment by jGleitz** [comment]
Please make the class names conform to the naming convention.

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/522#-:-K7euCBqTnGpLPnu3vYb:1604795791)*

**Comment by jGleitz** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/MeasurableSEFFElement.java, line 6 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/522#-K7euMMrO9tnjiCq3xR-:-K7euMMrO9tnjiCq3xR0:-1757724500) ([raw file](https://github.com/beagle-pse/beagle/blob/40e292cdb7c396b477ccfccfc7c4115d9708a245/Core/src/main/java/de/uka/ipd/sdq/beagle/core/MeasurableSEFFElement.java#L6)):*
“from **[a component’s]** SEFF”

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/ResourceDemandingInternalAction.java, line 4 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/522#-K7euXF2mx-1Ejiq6t7H:-K7euXF2mx-1Ejiq6t7I:1128179898) ([raw file](https://github.com/beagle-pse/beagle/blob/40e292cdb7c396b477ccfccfc7c4115d9708a245/Core/src/main/java/de/uka/ipd/sdq/beagle/core/ResourceDemandingInternalAction.java#L4)):*
“Models an internal action **[demanding resources when being executed]**.”

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/SEFFBranch.java, line 4 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/522#-K7eukCVER9eN_j14CwW:-K7eukCVER9eN_j14CwX:1874731254) ([raw file](https://github.com/beagle-pse/beagle/blob/40e292cdb7c396b477ccfccfc7c4115d9708a245/Core/src/main/java/de/uka/ipd/sdq/beagle/core/SEFFBranch.java#L4)):*
“Models branches **[in a component’s]** SEFF, originating from conditional constructs.” You may include the definition of these constructs in from the Terms and Definitions.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/522)*

**Comment by acBerger** [comment]
Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/MeasurableSeffElement.java, line 6 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/522#-K7euMMrO9tnjiCq3xR-:-K7exhyYmPfvj5oiu5kW:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/40e292cdb7c396b477ccfccfc7c4115d9708a245/Core/src/main/java/de/uka/ipd/sdq/beagle/core/MeasurableSeffElement.java#L6)):*
Done.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/ResourceDemandingInternalAction.java, line 4 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/522#-K7euXF2mx-1Ejiq6t7H:-K7ewfR7LnzWMuBLtUEg:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/40e292cdb7c396b477ccfccfc7c4115d9708a245/Core/src/main/java/de/uka/ipd/sdq/beagle/core/ResourceDemandingInternalAction.java#L4)):*
Done.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/SeffBranch.java, line 4 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/522#-K7eukCVER9eN_j14CwW:-K7ewjgeZivbXPN5nYVe:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/40e292cdb7c396b477ccfccfc7c4115d9708a245/Core/src/main/java/de/uka/ipd/sdq/beagle/core/SeffBranch.java#L4)):*
Done.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/SeffLoop.java, line 6 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/522#-K7eu1F0MFRgxGKNzjXl:-K7exahyuAgCTP5_XwUN:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/40e292cdb7c396b477ccfccfc7c4115d9708a245/Core/src/main/java/de/uka/ipd/sdq/beagle/core/SeffLoop.java#L6)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/522)*

**Comment by jGleitz** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/SeffBranch.java, line 9 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/522#-K7ez-HE0CYdSURk_iMW:-K7ez-HE0CYdSURk_iMX:159172631) ([raw file](https://github.com/beagle-pse/beagle/blob/da2a67dca8050c24ef3fe7be453e1f5fd08c2c8c/Core/src/main/java/de/uka/ipd/sdq/beagle/core/SeffBranch.java#L9)):*
as above: “**[a]** component’s SEFF”.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/522)*

**Comment by jGleitz** [comment]
Reviewed 2 of 15 files at r2.
Review status: 2 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java, line 157 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/522#-K7ezKIW2PeMaXC8JhvQ:-K7ezKIW2PeMaXC8JhvR:1244772857) ([raw file](https://github.com/beagle-pse/beagle/blob/da2a67dca8050c24ef3fe7be453e1f5fd08c2c8c/Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java#L157)):*
Fix the naming conevention here

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/522)*

**Comment by acBerger** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java, line 157 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/522#-K7ezKIW2PeMaXC8JhvQ:-K7f-v4vQhEPOcoflcUK:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/da2a67dca8050c24ef3fe7be453e1f5fd08c2c8c/Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java#L157)):*
Done.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/SeffBranch.java, line 9 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/522#-K7ez-HE0CYdSURk_iMW:-K7f-yLRSaWntd7-SsQy:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/da2a67dca8050c24ef3fe7be453e1f5fd08c2c8c/Core/src/main/java/de/uka/ipd/sdq/beagle/core/SeffBranch.java#L9)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/522)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 3 of 15 files at r2, 3 of 4 files at r3, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/522#-:-K7fd9JnqlKnwDyMsJyo:980077423)*

**Comment by flyfl** [comment]
:lgtm_strong:

---

Reviewed 3 of 15 files at r2, 3 of 6 files at r4.
Review status: 6 of 12 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/522#-:-K7fyNG114DQYxoQ7Dmk:-1168659251)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 3 of 15 files at r2, 3 of 4 files at r3, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/522#-:-K7gFFPjdCw77xpnlg7C:980077423)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Review status: 8 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/522#-:-K7gGiKR1g5dkgWT2Nz7:980077423)*

**Pull request merged**
