### PR TITLE
Implementation plan

### LINKED ISSUE #462: Write implementation plan

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Fixes #462

subject to change

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/464)

### CODE REVIEW

**Comment by acBerger** [comment]
Maybe we should add the reason why we did the prototypes in the design phase.

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/Implementation/Implementation Plan.lyx, line 294 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/464#-K7SETRfzcajy3zp4dK_:-K7SETRfzcajy3zp4dKa:-1424264031) ([raw file](https://github.com/beagle-pse/beagle/blob/29c8ab045abb8270e428f3c635558659ac346921/doc/Implementation/Implementation Plan.lyx#L294)):*
As this is a document "do not" would be better.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/464#-:-K7SEicguyGCucC0ddgT:-1819252410)*

**Comment by RomanLangrehr** [comment]
> Maybe we should add the reason why we did the prototypes in the design phase.

I like the idea.
Done.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/Implementation/Implementation Plan.lyx, line 294 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/464#-K7SETRfzcajy3zp4dK_:-K7SYpAt-aVmL9NuyYdb:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/29c8ab045abb8270e428f3c635558659ac346921/doc/Implementation/Implementation Plan.lyx#L294)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/464#-:-K7S_TTAstjEgtlzZs4G:1212532988)*

**Comment by acBerger** [comment]
:lgtm_strong: 

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/464#-:-K7SfUxij5M5c2WuWxiq:-1868698381)*

**Comment by flyfl** [comment]
:lgtm_strong: 

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/464#-:-K7Sid19cUk64YVlHazi:-1868698381)*

**Pull request merged**
