### PR TITLE
Checksyle & Clean Up

### PR DESCRIPTION
**Pull request by acBerger**
Set Magic Numbers in Checkstyle for Tests on ignore.

Removed Sort Order from Clean Up as it is defined for every workspace and not for the project.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/617)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/617#-:-K8QVPvQ5FE8TeMzWMSe:980077423)*

**Comment by m1cm1c** [comment]
Why aren't members sorted any more?

---

Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/617#-:-K8RLyTs-_OX2myJoEFA:-1717141002)*

**Comment by m1cm1c** [comment]
Sorry, didn't read the PR description at first. :lgtm: 

---

Reviewed 3 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/617#-:-K8RMQK67BpzyhVKefId:1345305662)*

**Comment by flyfl** [comment]
:lgtm_strong:

**Comment by jGleitz** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/617#-:-K8T8-eyq7pU7SGos6TF:980077423)*

**Pull request merged**
