### PR TITLE
Added meeting minutes 2016-01-14

### PR DESCRIPTION
**Pull request by RomanLangrehr**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/590)

### CODE REVIEW

**Comment by m1cm1c** [comment]
:lgtm:

**Comment by RomanLangrehr** [comment]
:lgtm:

**Comment by jGleitz** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/590#-:-K84QOLI7QxxyCSuCxQX:980077423)*

**Comment by m1cm1c** [comment]
:lgtm:

**Pull request merged**
