### PR TITLE
Measurement Tool, Proposed Expression Analyser, Measurement Result Analyser Stubs

### PR DESCRIPTION
**Pull request by viridispirus**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/548)

### CODE REVIEW

**Comment by viridispirus** [comment]
Javadoc still missing.

**Comment by jGleitz** [comment]
:lgtm: 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/548#-:-K7hCscg2nDGhsD0m8qY:980077423)*

**Comment by m1cm1c** [comment]
This branch is out-of-date with the base branch.

**Comment by m1cm1c** [comment]
:lgtm: 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/548#-:-K7hE4AElRV2L789D_Wm:980077423)*

**Comment by jGleitz** [comment]
This has *compile errors*

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/548#-:-K7hFHoC0aodU9O0A162:1466124107)*

**Comment by viridispirus** [comment]
I can't gave the classes which implements the interfaces the same name said Travis. Because of cyclic inheritance. What can I do now?

**Comment by jGleitz** [comment]
First of all: it’s missing the `.java` extension!
Second: Abstract classes are usually called `AbstractInterfaceName`, e.g. `AbstractMeasurementResultAnalyser`

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/548#-:-K7hHPKfbtRTncc4j_hs:635646109)*

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/548#-:-K7hRvYrf6y_RyucmcBd:1417088721)*

**Comment by viridispirus** [comment]
Blocked by #555

**Comment by jGleitz** [comment]
This PR still fails to build. Can it be closed and be postponed to when the classes are needed in the implementation phase?

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/548#-:-K88WpK-_HnC8KWIzY1S:1202662420)*

**Comment by viridispirus** [comment]
Ok, I close this for now.

**Pull request closed without merging**
