### PR TITLE
Instrumentation Code

### PR DESCRIPTION
**Pull request by jGleitz**
This PR is only meant for review, it’s not meant to be merged!

This is the instrumentation code. It surely has a lot of edge cases not covered, but it has basic funtionality.

 * There is still one Checkstyle issue, but I can’t think of a logical way to split that method at the moment.
 * The PR contains the Fail API because I needed it. 
 * Don’t hesitate to ask any questions. I want this code to be understandable and don’t know if I achieved that.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/691)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
Reviewed 23 of 26 files at r1.
Review status: 23 of 26 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[Kieker Measurement Tool/src/main/java/de/uka/ipd/sdq/beagle/measurement/kieker/InstrumentableAstNodeLister.java, line 215 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/691#-KAM_gxQfYX5pt6k77uS:-KAM_gxQfYX5pt6k77uT:-1480791423) ([raw file](https://github.com/beagle-pse/beagle/blob/8b210926099e76902243eb74bb4e450058ad3cdf/Kieker Measurement Tool/src/main/java/de/uka/ipd/sdq/beagle/measurement/kieker/InstrumentableAstNodeLister.java#L215)):*
The code coverage  will probabaly complain, that `false` is never evulated to  `true` ;)

Why can you be sure, that those nodes are not visited?

---

*[Kieker Measurement Tool/src/main/java/de/uka/ipd/sdq/beagle/measurement/kieker/NotRecursingAstVisitor.java, line 107 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/691#-KAMY8bk5DqTzT-jBWlg:-KAMY8bk5DqTzT-jBWlh:-2001500673) ([raw file](https://github.com/beagle-pse/beagle/blob/8b210926099e76902243eb74bb4e450058ad3cdf/Kieker Measurement Tool/src/main/java/de/uka/ipd/sdq/beagle/measurement/kieker/NotRecursingAstVisitor.java#L107)):*
Why is this "not recursing"? Is this more than an empty implentation of `ASTVisitor`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/691)*

**Comment by jGleitz** [comment]
Review status: 23 of 26 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[Kieker Measurement Tool/src/main/java/de/uka/ipd/sdq/beagle/measurement/kieker/InstrumentableAstNodeLister.java, line 215 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/691#-KAM_gxQfYX5pt6k77uS:-KAMk8zjIuJLmFwRgYMg:-1691100369) ([raw file](https://github.com/beagle-pse/beagle/blob/8b210926099e76902243eb74bb4e450058ad3cdf/Kieker Measurement Tool/src/main/java/de/uka/ipd/sdq/beagle/measurement/kieker/InstrumentableAstNodeLister.java#L215)):*
> The code coverage will probabaly complain, that `false` is never evulated to `true` ;)

I realise that. But I won’t give up good coding practice because of bad tools.

> Why can you be sure, that those nodes are not visited?

They can only be within other nodes I stop the visiting of subtrees for. In that case, I stopped the recursive visiting for `AnnotataionType`. 
There may be more cases like this. I only did the `assert false` if I was 100% sure.

---

*[Kieker Measurement Tool/src/main/java/de/uka/ipd/sdq/beagle/measurement/kieker/NotRecursingAstVisitor.java, line 107 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/691#-KAMY8bk5DqTzT-jBWlg:-KAMkg5IK8pFk9PSbdCH:1324847009) ([raw file](https://github.com/beagle-pse/beagle/blob/8b210926099e76902243eb74bb4e450058ad3cdf/Kieker Measurement Tool/src/main/java/de/uka/ipd/sdq/beagle/measurement/kieker/NotRecursingAstVisitor.java#L107)):*
> Is this more than an empty implentation of `ASTVisitor`

Yeah… no. It’s actually less. A empty `ASTVisitor` would visit the whole AST.

> Why is this "not recursing"?

Because we return `false` in every method, telling the abstract class not to traverse further.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/691)*

**Comment by acBerger** [comment]
Reviewed 25 of 26 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/691)*

**Comment by acBerger** [comment]
Is there anyone, who still wants to have a look on this? Otherwise we can close it again, as @jGleitz only wanted to show his progress.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/691#-:-KAPFNN6yyWUspLe_-oi:-1340959515)*

**Pull request closed without merging**
