### PR TITLE
Checkstyle

### LINKED ISSUE #675: Remove `Anonymous inner class length` for Tests

### PR DESCRIPTION
**Pull request by acBerger**
fixes #675 

fixes another annotation and formatter problem but NOT #676 as I still have not found a solution for it.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/687)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[config/Formatter.xml, line 68 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/687#-KALoBp59o7OhqPdIC9O:-KALoBp59o7OhqPdIC9P:-1433360364) ([raw file](https://github.com/beagle-pse/beagle/blob/b24603ee19bac5b4090e24ea50570319ed716288/config/Formatter.xml#L68)):*
Why ist this set to false?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/687)*

**Comment by RomanLangrehr** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/687)*

**Comment by acBerger** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[config/Formatter.xml, line 68 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/687#-KALoBp59o7OhqPdIC9O:-KALoaYBVFDU4l7-opgk:-835500325) ([raw file](https://github.com/beagle-pse/beagle/blob/b24603ee19bac5b4090e24ea50570319ed716288/config/Formatter.xml#L68)):*
I do not know. Our formatter was not selected when I open the configuration, so I selected it. I did not change any values by hand except from the annotation wrapping.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/687)*

**Comment by m1cm1c** [comment]
Review status: 1 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/.settings/org.eclipse.jdt.core.prefs, line 10 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/687#-KALt2FYBEJpWlfL-pup:-KALt2FYBEJpWlfL-puq:-898201630) ([raw file](https://github.com/beagle-pse/beagle/blob/51f32747208f6b907e682fcab03335e27d8651a0/Core/.settings/org.eclipse.jdt.core.prefs#L10)):*
What does this do?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/687)*

**Comment by m1cm1c** [comment]
This branch is out-of-date with the base branch.

**Comment by acBerger** [comment]
Review status: 1 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[config/Formatter.xml, line 68 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/687#-KALoBp59o7OhqPdIC9O:-KALuYzkrgwWHWevlqP7:-1620474753) ([raw file](https://github.com/beagle-pse/beagle/blob/b24603ee19bac5b4090e24ea50570319ed716288/config/Formatter.xml#L68)):*
fixed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/687)*

**Comment by acBerger** [comment]
Review status: 1 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/.settings/org.eclipse.jdt.core.prefs, line 10 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/687#-KALt2FYBEJpWlfL-pup:-KALvx8vT_76A9fUbfx7:-1327998223) ([raw file](https://github.com/beagle-pse/beagle/blob/9fa106a971d4aeaf0f0fcd470ee924410a4842f3/Core/.settings/org.eclipse.jdt.core.prefs#L10)):*
I do not know. It was changes automatically.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/687)*

**Comment by m1cm1c** [comment]
I don't see how any change except the one in `config/checkstyle/Checkstyle Test.xml` is necessary.

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/687#-:-KALwVWObEDSPcNgc1s4:1246963582)*

**Comment by acBerger** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/.settings/org.eclipse.jdt.core.prefs, line 10 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/687#-KALt2FYBEJpWlfL-pup:-KALwg10HMfMHRPHWtm9:1570825978) ([raw file](https://github.com/beagle-pse/beagle/blob/9fa106a971d4aeaf0f0fcd470ee924410a4842f3/Core/.settings/org.eclipse.jdt.core.prefs#L10)):*
Okay, I think I know it now. The '16' is a constant for a setting I made. It is the one, I described above: Formerly no wrapping was allowed in annotations, which I found silly. I allowed this.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/687)*

**Comment by m1cm1c** [comment]
:lgtm:

---

Reviewed 1 of 7 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/.settings/org.eclipse.jdt.core.prefs, line 10 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/687#-KALt2FYBEJpWlfL-pup:-KALxP023AFpC4ue55JU:1651209444) ([raw file](https://github.com/beagle-pse/beagle/blob/9fa106a971d4aeaf0f0fcd470ee924410a4842f3/Core/.settings/org.eclipse.jdt.core.prefs#L10)):*
Okay, then.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/687#-:-KALxUGLuOnq8znklp1o:1417088721)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/687#-:-KAM--aGYjv04YzvN7LY:980077423)*

**Pull request merged**
