### PR TITLE
Added Blackboard Storer

### LINKED ISSUE #434: Model Blackboard Storer in class diagram

### PR DESCRIPTION
**Pull request by viridispirus**
fixes #434 

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/437)

### CODE REVIEW

**Comment by m1cm1c** [comment]
Please resolve conflicts.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/437#-:-K7GsJl_X22u8-LxhP4d:956496530)*

**Comment by acBerger** [comment]
This branch has conflicts that must be resolved

**Comment by jGleitz** [comment]
I want to link to the +discussion in #434 (Model Blackboard Storer in class diagram) whether this is necessary at all.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/437#-:-K7LyRsdV3JaT91zHrr4:-894375891)*

**Comment by acBerger** [comment]
Independently from the discussion if we need it at all: You added the Interface `BlackboardStorer`twice. One is as you probably want to have it and the other seems to be there unintentionally.


---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/437#-:-K7M-SNPjbaEi-qfPf3l:399107623)*

**Comment by acBerger** [comment]
I tried to mark both occurences in the diagram, so you can find it easier.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/437#-:-K7M00DQsu_O0FUPAJXf:1404667662)*

**Comment by viridispirus** [comment]
thanks.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/437#-:-K7MiAqIWMXI7ttvJNXj:795446752)*

**Comment by RomanLangrehr** [comment]
There should be an association between blackboard and BlackboardStorer (1 : *).

But I like it and I think it's a good idea to add this to the diagram, as this is an important part of our design.
However, it should be explained in detail in #391 

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/437#-:-K7S7CZ04ovKHoIUEzHJ:910624853)*

**Comment by viridispirus** [comment]
It is too much work. Build this new.

**Pull request closed without merging**
