### PR TITLE
Uml Tooling

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Set up UML  Tooling.
Please follow the instruction in `Development Setup.md`

A preview of the UML-diagrams can be found [here](https://github.com/RomanLangrehr/Beagle/blob/gh-pages/branches/UML2-Tooling-Demo/Requirements%20Specification.pdf), Chapter 3 "Environment"

### CODE REVIEW

**Comment by jGleitz** [comment]
lgtm

**Comment by acBerger** [comment]
For figure 3.1: parts of the text (only last letters) are not shown or not readable as the collide with the box around.
Unfortunatly I cannot say anything about the actual issue, as I am not able to have a closer look at the moment.

**Comment by RomanLangrehr** [comment]
Thats just a problem with the Demo, it has nothing to do with this PR.

**Comment by RomanLangrehr** [comment]
Any ideas why this branch isn't test by Travis? It would be important here...

**Comment by jGleitz** [comment]
@RomanLangrehr: Travis is acting up, #97 doesn’t get built either. I’m looking into it.

**Comment by jGleitz** [comment]
Seems like Travis only had hickups and is back on track. Unfortunately I don’t how to force it to build this PR. @RomanLangrehr can you push a no-opt commit (like just adding a newline) to you branch?

**Comment by jGleitz** [comment]
Still not building properly. Let’s give it some time.

**Comment by RomanLangrehr** [comment]
I don't know what's wrong there: The log says: Your build exitet with code 0, but Travis doesn't get green....

**Comment by RomanLangrehr** [comment]
Oh, I just have to complain about it ;)

**Comment by jGleitz** [comment]
wonderful.

**Comment by jGleitz** [comment]
fixes #50

**Pull request merged**
