### PR TITLE
Fix broken References in SRS

### LINKED ISSUE #238: SRS: References to tests are broken
This is unfortunate, but as they are only referenced in comments, this does not need to be fixed before the SRS is handed in.

It should, however, be fixed to assure the SRS’ quality.

### LINKED ISSUE #255: Link to fix
In our SRS on the end of page 20 is link that have to fix.

### PR DESCRIPTION
**Pull request by acBerger**
fixes #238 
fixes #255

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/382)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
This PR rendered [PDF](http://acberger.github.io/Beagle/branches/references/Requirements%20Specification.pdf).

Why is, at least the first "tested by ..." not rendered?

**Comment by acBerger** [comment]
> Why is, at least the first "tested by ..." not rendered?

"Tested by ..." is always a note (for us). Notes are not rendered at all.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/382#-:-K73Qi5IAcuPLyv2Ask9:236843170)*

**Comment by RomanLangrehr** [comment]
> "Tested by ..." is always a note (for us). Notes are not rendered at all.

I see.

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/382#-:-K75v17VOHOgBsNbko1i:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/382#-:-K766cvxgDuXoMBn4mUC:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/382#-:-K76DY7f3bpZhXXIPQ7a:980077423)*

**Comment by m1cm1c** [comment]
This branch is out-of-date with the base branch.

**Comment by RomanLangrehr** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/382#-:-K76KbF8_42Ivw6yXckp:-1868698381)*

**Comment by viridispirus** [comment]
lgtm

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/382#-:-K76oUrxYDwNYPL-UF1b:677819321)*

**Comment by acBerger** [comment]
@viridispirus You have to write : lgtm : (without spaces) to create the "lgtm-Button" which counts for the needed number of lgtm.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/382#-:-K76oyeWQ42CY5WAnPAs:-860529170)*

**Comment by viridispirus** [comment]
thanks :+1:

**Comment by viridispirus** [comment]
:lgtm:

**Comment by jGleitz** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/382#-:-K76qaWRGCEsNJheEFx1:-1868698381)*

**Pull request merged**
