### PR TITLE
Added some non functional requirments

### PR DESCRIPTION
**Pull request by RomanLangrehr**

### CODE REVIEW

**Comment by acBerger** [comment]
/OQ10/ Begale should run on every system, where eclipse and Palladio runs.
- "Beagle"
- e.g. "... on every system which runs eclipse and Palladio."  as "where" does not fit here. Additionally eclipse and palladio are  two programs, so no "s" for "run" needed.

**Comment by RomanLangrehr** [comment]
Thanks. I fixed it.

**Comment by acBerger** [comment]
lgtm

**Comment by acBerger** [comment]
lgtm

**Comment by jGleitz** [comment]
lgtm

**Pull request merged**
