### PR TITLE
Improve the SRS Render Scripts

### PR DESCRIPTION
**Pull request by jGleitz**
I’m sorry. But I have to say it.

***Windows command line sucks!***

You don’t have no `tee`, you can’t get the output of commands, you can’t put newlines in strings, you have no functions, you can’t `exit` from subroutines, you don’t have `set -e`, … 
Everything requires hacking.

I thought I’d quickly write some improvements and spend hours on getting them work on Windows.

I’m sorry. I really am. End of rant.

## PR contents
This pull requests vastly improves the SRS render scripts:

 * The momentary executed task is printed
 * Irrelevant output is not printed unless an error occurs
 * A log file is saved, containing the full output (even if one of the main commands fail)
 * The PWD is restored if any of the main commands fail
 * `-halt-on-error` also for Windows (So the script stops on error instead of prompting for input)
 * Message on main command error that informs about where to find the tempfolder

I think the changes will come in handy when looking through warnings. The massively reduce the scripts' noise, which is especially handy on Travis.

### CODE REVIEW

**Comment by m1cm1c** [comment]
lgtm and works on my machine. I can't say anything about the Windows version, though.

**Comment by acBerger** [comment]
Please do not merge, as we are waiting for @RomanLangrehr.

**Comment by flyfl** [comment]
That works on my Windows distribution. @jGleitz Please resolve the conflicts.

**Comment by jGleitz** [comment]
Please retest on Windows and Ubuntu, as I had to make changes for Umlet.

**Comment by flyfl** [comment]
worked (Windows)

**Comment by RomanLangrehr** [comment]
Worked for me, too.
Lgtm.

**Comment by jGleitz** [comment]
As it worked on two Ubuntu machines (Travis and mine) too, I’ll merge.

**Pull request merged**
