### PR TITLE
Added Palladio Paper quote to def. of "component developer".

### PR DESCRIPTION
**Pull request by m1cm1c**
Fixes second part of #169.

### CODE REVIEW

**Comment by acBerger** [comment]
[PDF] (http://m1cm1c.github.io/Beagle/branches/quotes/Requirements%20Specification.pdf)

**Comment by acBerger** [comment]
@m1cm1c  could you please do the first part too?

**Comment by m1cm1c** [comment]
@acBerger I tried but couldn't find a good quote in the Palladio paper. Why can't we quote Krogmann? If I quoted something else without knowing why we can't quote him, I might do the same mistake again.

**Comment by jGleitz** [comment]
> Why can't we quote Krogmann

Krogmann did research about source code analysis, but not about component based software. So it’s obvious he only cited others when talking about these things. 

If you quote something, you need to have a source that actually did research on the exact topic you’re quoting. This is unpleasant, as you can’t just use the citations that fit into what you’re doing. But if you think of it, it makes sense and assures quality of science, because you can’t just use the citations that fin into what you’re doing.

**Comment by m1cm1c** [comment]
Okay, I'll find some real source.

**Comment by acBerger** [comment]
Krogmann did not define this. He got it from another source himself.

2015-11-28 21:05 GMT+01:00 m1cm1c <notifications@github.com>:

**Comment by m1cm1c** [comment]
He only said the last sentence. I changed the wording so we don't have to quote him at all. Since the last sentence doesn't contain any information for which you need research, we don't need to quote anybody.

**Comment by jGleitz** [comment]
> I changed the wording so we don't have to quote him at all.

The statement is so simple that we don’t need to cite it, you’re right.

lgtm

**Comment by acBerger** [comment]
lgtm

**Pull request merged**
