### PR TITLE
Added evaluate() to the judge() function.

### LINKED ISSUE #538: Sequenc Diagram #judge(): Add call to Evaluable Expression.
I think it’s very important to show that the expressions get `evaluate`d before being judged, because we never show that mechanism anywhere (and it was created solely for that purpose).

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Fixes #538

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/544)

### CODE REVIEW

**Comment by jGleitz** [comment]
[Website](http://romanlangrehr.github.io/Beagle/branches/0judge/)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/544#-:-K7h-dWv2maJICQG5FNE:1349926201)*

**Comment by jGleitz** [comment]
It is very unrealistic to have a Constant Expression stacked into another Expression that does not change the value anyhow. If you just wanted to do a simple example, use a `Sine Expression` as outer Expression.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/544#-:-K7h0VcePkiSE65aFmgh:-577233098)*

**Comment by jGleitz** [comment]
Or `Natural Logarithm Expression` or `Exponentiation Function Expression` for that matter.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/544#-:-K7h0ZcS7Q1ugwE5Tv__:-1520689573)*

**Comment by RomanLangrehr** [comment]
@jGleitz  Done. But I can't use `Natural Logarithm Expression` here ;)

**Comment by jGleitz** [comment]
:lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/544#-:-K7hBkq6AikgUQwTtUbi:980077423)*

**Comment by jGleitz** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/544)*

**Comment by flyfl** [comment]
:lgtm_strong:

**Pull request merged**
