### PR TITLE
Added a Hamcrest Matcher to Assert That an Exception Was Thrown

### PR DESCRIPTION
**Pull request by jGleitz**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/614)

### CODE REVIEW

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/614#-:-K8PqJ0hai5QN6OMB_su:1417088721)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/614#-:-K8QE4urzSyDxImY8_UO:980077423)*

**Comment by jGleitz** [comment]
I fixed the stupid version number.

---

Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/614#-:-K8QZiB8flOg-5TjaNru:-1712876309)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/614#-:-K8QZvcUNPNTD9Bh85MD:980077423)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/614#-:-K8QaawtL0KEDF4wk-2O:1417088721)*

**Pull request merged**
