### PR TITLE
Uml diagrams

### LINKED ISSUE #84: Beagle component diagram
A small diagram showing Beagle as a component together with its provided and required interfaces

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Created a use case and a component diagram.

[PDF](https://www.dropbox.com/s/ro1s584etqiqs89/Reeningeering.pdf?dl=0)

Depends on #98 

Fixes #84

### CODE REVIEW

**Comment by jGleitz** [comment]
* I like the component diagram.
 * I like the use case diagram

---

 * Both diagrams render badly, as the font is crossing a lot of lines.
 * The component diagram could state “measurement software” (a term defined in the glossary) instead of “Kieker”, because “Kieker” is not mandatory.
 * Trac**[e]**ability (in the component diagram)
 *  Beagle an**[d]** it’s interaction with other software (in the component diagram's description)
 * “CTA supporting software” could again just be “measurement software” (a term defined in the glossary)
 * I would not open a new part for the Use Case Diagram but rather place it directly at the end of 2.1

**Comment by jGleitz** [comment]
[View this PR’s rendered SRS PDF](http://romanlangrehr.github.io/Beagle/branches/UML-Diagrams/Requirements%20Specification.pdf)

**Comment by jGleitz** [comment]
> [PDF](https://www.dropbox.com/s/ro1s584etqiqs89/Reeningeering.pdf?dl=0)

This diagram is not part of the pull request anyhow, is it?

**Comment by RomanLangrehr** [comment]
No, it isn't.

**Comment by RomanLangrehr** [comment]
> Both diagrams render badly, as the font is crossing a lot of lines.

I'm sorry, but I can't change this.

> I would not open a new part for the Use Case Diagram but rather place it directly at the end of 2.1

I removed 2.3, but LaTeX dosn't like to put it direct below 2.1.

I'm just wondering, if the use case diagram would fit better to Ch. 4. Functional Requirments. What do you think?

**Comment by flyfl** [comment]
I like all of these 3 diagrams.They look good!

**Comment by jGleitz** [comment]
> I'm sorry, but I can't change this.

There has to be a way to improve this! If you can’t do it right now we’ll merge and do it later.

> I removed 2.3, but LaTeX dosn't like to put it direct below 2.1.

Doesn’t matter. That’s what’s LaTeX is for: Placing your stuff where it fits best ;)

**Comment by acBerger** [comment]
@RomanLangrehr: please resolve conflicts!

**Comment by jGleitz** [comment]
lgtm

**Comment by RomanLangrehr** [comment]
Conflicts resolved.

**Pull request merged**
