### PR TITLE
Measurement Blackboard

### PR DESCRIPTION
**Pull request by jGleitz**
These are the changes I think are needed to have all business objects necessary. I also adapted the Fitness Function Interface. Please review carefully, this must be the last change to the Blackboard!

If you have any questions, don’t comment but directly make a call on Hangouts. We need to do this quickly!

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/527)

### CODE REVIEW

**Comment by jGleitz** [comment]
Please do not review the measurement diagram, it is WIP

**Comment by RomanLangrehr** [comment]
[Website](http://jgleitz.github.io/Beagle/branches/measurement-blackboard/)

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/527#-:-K7fippOMYS9n-Msww-Q:980077423)*

**Comment by jGleitz** [comment]
I’m so sorry, but I needed a little fix!

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/527#-:-K7fj8s5oZNKCoU3aWzz:1206498423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/527#-:-K7fjR3uPXNjbWHakEPM:980077423)*

**Comment by m1cm1c** [comment]
This branch is out-of-date with the base branch.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/527#-:-K7fl_xwQ4kqtnctTC13:-1909636266)*

**Comment by m1cm1c** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/527#-:-K7flbyWJwa8aT_vAPEt:980077423)*

**Pull request merged**
