### PR TITLE
Checkstyle for Tests

### PR DESCRIPTION
**Pull request by acBerger**
I had to add another checkstyle.xml file. This one is only for tests as they need some settings "normal" code does not need (static imports). Additionally Checkstyle is not able to detected there is a package info for tests (as the package info still is in main). Therefore Tests packages (which should be names same as the package the classes to test are in) do not need a package info.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/600)

### CODE REVIEW

**Comment by jGleitz** [comment]
* Please apply the configuration to the GUI project, too.
 * Please adapt gradle to use the correct files, too.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/.checkstyle, line 7 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/600#-K8EQ-8K6D8jwlHmn3ZV:-K8EQ-8K6D8jwlHmn3ZW:1528127900) ([raw file](https://github.com/beagle-pse/beagle/blob/64e1c7ee8c25045776e7e4a329481b97da446af9/Core/.checkstyle#L7)):*
Please call the configuration “**[Beagle]** Checkstyle for Tests”

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/600#-:-K8EQ9bAn4IVabwQaKIH:-1681860143)*

**Comment by acBerger** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/.checkstyle, line 7 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/600#-K8EQ-8K6D8jwlHmn3ZV:-K8GZFMiP6-VxpmZcQhn:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/64e1c7ee8c25045776e7e4a329481b97da446af9/Core/.checkstyle#L7)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/600)*

**Comment by jGleitz** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/600#-:-K8GZzgJ1dIgmQWtCIFj:1417088721)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 1 of 3 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/600#-:-K8GgQhmpkpxSj7oH0Pg:980077423)*

**Pull request merged**
