### PR TITLE
Ip 137 final judge

### LINKED ISSUE #612: [IP #137] Implement Final Judge
Implement Final Judge.

Depends on IP#060 (Blackboard) ( #573 ) and IP#120 (Measurement Results) ( #609 )
(Not depending on #160 (Fitness Function), because only method
stubs are needed here.)

### PR DESCRIPTION
**Pull request by m1cm1c**
fixes #612 

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/674)

### CODE REVIEW

**Comment by m1cm1c** [comment]
This is blocked until #599 is merged.

**Comment by jGleitz** [comment]
Blackboard Views are merged, this is not -blocked anymore.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/674#-:-KA9asgzfDPezn2Vh9d9:-1249683717)*

**Comment by acBerger** [comment]
Travis fails because of an error in the BlackboardFactory.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/674#-:-KA9lK725EOu2jU7BF5g:-422690384)*

**Comment by RomanLangrehr** [comment]
Reviewed 5 of 21 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/ReadOnlyProposedExpressionAnalyserBlackboardView.java, line 162 \[r6\]](https://reviewable.io:443/reviews/beagle-pse/beagle/674#-KACIV7vEVcsKe8e2SIa:-KACIV7vEVcsKe8e2SIb:1707378222) ([raw file](https://github.com/beagle-pse/beagle/blob/7bde3bd21eb469c78685ba8a4470f149db9d90d7/Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/ReadOnlyProposedExpressionAnalyserBlackboardView.java#L162)):*
I think this change is not intenden.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/judge/FinalJudge.java, line 158 \[r6\]](https://reviewable.io:443/reviews/beagle-pse/beagle/674#-KACIn0n_yQPzkc1ITZA:-KACIn0n_yQPzkc1ITZB:-1759669636) ([raw file](https://github.com/beagle-pse/beagle/blob/7bde3bd21eb469c78685ba8a4470f149db9d90d7/Core/src/main/java/de/uka/ipd/sdq/beagle/core/judge/FinalJudge.java#L158)):*
`SEFF_ELEMENT_TYPE` probably.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/674)*

**Comment by m1cm1c** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/ReadOnlyProposedExpressionAnalyserBlackboardView.java, line 162 \[r6\]](https://reviewable.io:443/reviews/beagle-pse/beagle/674#-KACIV7vEVcsKe8e2SIa:-KACOihSFm5IXaMX_b7J:-71586980) ([raw file](https://github.com/beagle-pse/beagle/blob/7bde3bd21eb469c78685ba8a4470f149db9d90d7/Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/ReadOnlyProposedExpressionAnalyserBlackboardView.java#L162)):*
You're right. This is an artifact of manual merging. I corrected it.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/judge/FinalJudge.java, line 158 \[r6\]](https://reviewable.io:443/reviews/beagle-pse/beagle/674#-KACIn0n_yQPzkc1ITZA:-KACPlUD_phNoFfDXAdB:1152077077) ([raw file](https://github.com/beagle-pse/beagle/blob/7bde3bd21eb469c78685ba8a4470f149db9d90d7/Core/src/main/java/de/uka/ipd/sdq/beagle/core/judge/FinalJudge.java#L158)):*
It was only `SE` in the past. Updated it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/674)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/674#-:-KAEnT7Sa-ca_QnJCucs:980077423)*

**Comment by RomanLangrehr** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/674)*

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 4 of 21 files at r1, 1 of 1 files at r2, 1 of 1 files at r5, 1 of 2 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/674#-:-KAG8PweGnUBTeGOtOaF:1417088721)*

**Pull request merged**
