### PR TITLE
Fix Coverage Report

### PR DESCRIPTION
**Pull request by jGleitz**
[Our coverage report](https://beagle-pse.github.io/Beagle/coverage/) fails to load its assets. This should fix it.

[Website](http://jgleitz.github.io/Beagle/branches/fix-coverage-report/)

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/673)

### CODE REVIEW

**Comment by jGleitz** [comment]
Sorry for the confusion with the PRs.

**Comment by jGleitz** [comment]
FYI: I’m still working on a good solution. (It’s not complicated, but the only way to test it is to wait for Travis).

**Comment by jGleitz** [comment]
[Finally working as expected](http://jgleitz.github.io/Beagle/branches/fix-coverage-report/coverage/)

**Comment by acBerger** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/673#-:-KA1hk7QxStFKfXL436_:1417088721)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/673#-:-KA1qKgGFhy3-fWYgbVj:980077423)*

**Comment by RomanLangrehr** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/673)*

**Pull request merged**
