### PR TITLE
Ignore Checkstyle Rules With Comments

### PR DESCRIPTION
**Pull request by jGleitz**
Sometimes, there are legitimate reasons to violate a checkstyle rule. In such cases, placing

```
// CHECKSTYLE:IGNORE RuleName
```

Above the line will ignore the specific rule at the following line.

Note that this is intended to be used *very rarely*. I’m convinced that most of the time when we think Checkstyle is wrong it’s actually right and we’re just being lazy. Adding an ignore comment should *always* include adding a description while ignoring is legitimate at that point.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/688)

### CODE REVIEW

**Comment by acBerger** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/688#-:-KALmyfCpS6UOMHICUT-:1417088721)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/688#-:-KALoJglVBuIQOyRiD8b:980077423)*

**Comment by RomanLangrehr** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/688)*

**Comment by m1cm1c** [comment]
This branch is out-of-date with the base branch.

**Comment by acBerger** [comment]
-(needs review) 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/688#-:-KAOyFB8OAN1oe8cpETn:-1025998350)*

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/688#-:-KAPC061X5lZo75NUwCI:1417088721)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/688#-:-KAPCQ1dtcYsMWoBuGnt:980077423)*

**Comment by viridispirus** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/688)*

**Pull request merged**
