### PR TITLE
Analyse-Blackboard View

### PR DESCRIPTION
**Pull request by viridispirus**
Fixed wording in methods 'loopes' -> 'loops'
in Read-Only Blackboard View and Measurement View

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/312)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
image

Why is the multiplicity 1?
Is the final judge really interessted in the things to be measured?

**Comment by RomanLangrehr** [comment]
This PR also depends on some of your other PR, but I don't know on which ones.

**Comment by jGleitz** [comment]
> Is the final judge really interessted in the things to be measured?

We once discussed that every blackboard view offers full read access. If we stick to that: yes. 

Am 24.12.2015 8:14 vorm. schrieb Roman Langrehr <notifications@github.com>:

 

Why is the multiplicity 1?
Is the final judge really interessted in the things to be measured?

**Comment by m1cm1c** [comment]
not mergeable

**Pull request closed without merging**
