### PR TITLE
Formatter and Cleanup for the whole source code.

### PR DESCRIPTION
**Pull request by jGleitz**
It’s astonishing how many changes were introduced by applying the Formatter and Clean Up on our code. It shows that most of us still don’t use Save Actions.

**So please configure your Eclipse to do Clean Up and Formatting on Save *right now*!**

However, I think that there is no better opportunity to do this change than now.

Do you agree?

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/729)

### CODE REVIEW

**Comment by acBerger** [comment]
:lgtm: :white_check_mark: 

---

Reviewed 54 of 54 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/729#-:-KAfOMby8Kc6V-2q7ybW:-1603124213)*

**Comment by jGleitz** [comment]
I added commits that remove all warnings from the project.

---

Review status: 50 of 56 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/729#-:-KAfPSsLbRpI5cQTDQ9p:-1505274413)*

**Comment by acBerger** [comment]
:lgtm: :white_check_mark: 

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/729#-:-KAfS8sUicf0Ez1tNHin:-1603124213)*

**Comment by viridispirus** [comment]
*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/facade/BeagleConfigurationTest.java, line 44 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/729#-KAfYNHFl69ipWYHgo0b:-KAfYNHFl69ipWYHgo0c:-127158852) ([raw file](https://github.com/beagle-pse/beagle/blob/7194430e94f6e1a507bb7352acb5ad032b3d6a53/Core/src/test/java/de/uka/ipd/sdq/beagle/core/facade/BeagleConfigurationTest.java#L44)):*
Why we don't need this?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/729)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Reviewed 50 of 54 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/729#-:-KAfZEqKi2rEgwrQ2K_V:980077423)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/facade/BeagleConfigurationTest.java, line 44 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/729#-KAfYNHFl69ipWYHgo0b:-KAfZ8_8QljK3yIsEhp5:-843811318) ([raw file](https://github.com/beagle-pse/beagle/blob/7194430e94f6e1a507bb7352acb5ad032b3d6a53/Core/src/test/java/de/uka/ipd/sdq/beagle/core/facade/BeagleConfigurationTest.java#L44)):*
It’s never used in the test, so obviously it’s not needed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/729)*

**Comment by jGleitz** [comment]
Had to fix an error, I’m sorry.

---

Review status: 55 of 56 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/729#-:-KAfZb_2eB8BLZbCPjAE:721115667)*

**Comment by m1cm1c** [comment]
Review status: 55 of 56 files reviewed at latest revision, 5 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java, line 240 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/729#-KAf_TZhdl4ShYNbXls0:-KAf_TZhdl4ShYNbXls1:-1028174822) ([raw file](https://github.com/beagle-pse/beagle/blob/e9895334ac602560f2a16f1c6bc521e537927809/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java#L240)):*
This is more than just formatter and clean up. Is this change intended?

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java, line 298 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/729#-KAf_cyEaoTq5t5O_R5_:-KAf_cyEaoTq5t5O_R5a:-1028174822) ([raw file](https://github.com/beagle-pse/beagle/blob/7194430e94f6e1a507bb7352acb5ad032b3d6a53/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java#L298)):*
This is more than just formatter and clean up. Is this change intended?

---

*[Core/src/test/resources/de/uka/ipd/sdq/beagle/core/PingPong.java, line 18 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/729#-KAfa04pP0nHXLPTCZA3:-KAfa04pP0nHXLPTCZA4:-1886465551) ([raw file](https://github.com/beagle-pse/beagle/blob/e9895334ac602560f2a16f1c6bc521e537927809/Core/src/test/resources/de/uka/ipd/sdq/beagle/core/PingPong.java#L18)):*
As English as bratwurst.

---

*[Core/src/test/resources/de/uka/ipd/sdq/beagle/core/PingPong.java, line 24 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/729#-KAfaBY5wpRng0mN9yLL:-KAfaBY5wpRng0mN9yLM:-1028174822) ([raw file](https://github.com/beagle-pse/beagle/blob/7194430e94f6e1a507bb7352acb5ad032b3d6a53/Core/src/test/resources/de/uka/ipd/sdq/beagle/core/PingPong.java#L24)):*
This is more than just formatter and clean up. Is this change intended?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/729)*

**Comment by m1cm1c** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/729)*

**Comment by m1cm1c** [comment]
Reviewed 49 of 54 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/729)*

**Comment by viridispirus** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/facade/BeagleConfigurationTest.java, line 44 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/729#-KAfYNHFl69ipWYHgo0b:-KAfaSwUqR81G_lKWSjQ:160415405) ([raw file](https://github.com/beagle-pse/beagle/blob/7194430e94f6e1a507bb7352acb5ad032b3d6a53/Core/src/test/java/de/uka/ipd/sdq/beagle/core/facade/BeagleConfigurationTest.java#L44)):*
ok.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/729)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java, line 240 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/729#-KAf_TZhdl4ShYNbXls0:-KAfaV07Naco2RkFUzRk:-1742820205) ([raw file](https://github.com/beagle-pse/beagle/blob/e9895334ac602560f2a16f1c6bc521e537927809/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java#L240)):*
> This is more than just formatter and clean up. Is this change intended?

Yes. This is unused code I commented out.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java, line 298 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/729#-KAf_cyEaoTq5t5O_R5_:-KAfamcVH9wxgpwaO-S6:-1817375310) ([raw file](https://github.com/beagle-pse/beagle/blob/7194430e94f6e1a507bb7352acb5ad032b3d6a53/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java#L298)):*
`handleFailureFor` was unused after I commented `addBranchActionToSet` out. So no production code used it. So yes.

---

*[Core/src/test/resources/de/uka/ipd/sdq/beagle/core/PingPong.java, line 18 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/729#-KAfa04pP0nHXLPTCZA3:-KAfb-1CH9m_uIwzpDjV:-444304835) ([raw file](https://github.com/beagle-pse/beagle/blob/e9895334ac602560f2a16f1c6bc521e537927809/Core/src/test/resources/de/uka/ipd/sdq/beagle/core/PingPong.java#L18)):*
I think “bratwurst” is actually known to some english speakers. “Schrittweite“ surely isn’t. However, this is our example code, used only for testing purposes. It thus doesn’t really matter.

---

*[Core/src/test/resources/de/uka/ipd/sdq/beagle/core/PingPong.java, line 24 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/729#-KAfaBY5wpRng0mN9yLL:-KAfbM_tTU-3z8PbvBmp:925103113) ([raw file](https://github.com/beagle-pse/beagle/blob/7194430e94f6e1a507bb7352acb5ad032b3d6a53/Core/src/test/resources/de/uka/ipd/sdq/beagle/core/PingPong.java#L24)):*
> This is more than just formatter and clean up. Is this change intended?

Actually it isn’t. Clean up removes unused fields.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/729)*

**Comment by m1cm1c** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java, line 298 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/729#-KAf_cyEaoTq5t5O_R5_:-KAfdOtsCWUxOZHXM7pZ:-1098567860) ([raw file](https://github.com/beagle-pse/beagle/blob/7194430e94f6e1a507bb7352acb5ad032b3d6a53/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java#L298)):*
But it's probably going to be used in the future. I know that you probably were going to write "It's in the git log." when reading the first sentence but @flyfl will probably disagree about deleting the code so he should write that he's okay with this.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/729)*

**Comment by m1cm1c** [comment]
Please update branch.

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java, line 298 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/729#-KAf_cyEaoTq5t5O_R5_:-KAfoCJKyxDosY_3DlT9:528537212) ([raw file](https://github.com/beagle-pse/beagle/blob/48abaf7683645b0488f14e082ba2494250f510a6/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java#L298)):*
You’re right. I wouldn’t delete code if I wasn’t 100% sure, but @flyfl, please confirm.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/729)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/729)*

**Comment by acBerger** [comment]
:lgtm: :white_check_mark: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/729#-:-KAgAkq6CA2jFCsNM52n:-1603124213)*

**Comment by viridispirus** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/729)*

**Comment by jGleitz** [comment]
+@flyfl , @m1cm1c wants you to review the changes.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/729#-:-KAkuu7jIgFhEap4kduO:-617890000)*

**Comment by flyfl** [comment]
:lgtm:

---

Reviewed 48 of 54 files at r1, 5 of 6 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java, line 298 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/729#-KAf_cyEaoTq5t5O_R5_:-KAt8NrTkeqW-87Lf-ch:1599402130) ([raw file](https://github.com/beagle-pse/beagle/blob/48abaf7683645b0488f14e082ba2494250f510a6/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositorySeffExtractor.java#L298)):*
It's okay to delete this code section.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/729#-:-KAt8WkaNQhy4VguykBJ:1417088721)*

**Comment by acBerger** [comment]
:lgtm: :white_check_mark: 

---

Review status: 49 of 50 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/729#-:-KAt9ogguk3wN4nV0589:-1603124213)*

**Comment by acBerger** [comment]
Reviewed 1 of 5 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/729)*

**Comment by flyfl** [comment]
:lgtm:

**Pull request merged**
