### PR TITLE
Formatter disable joining of lines in comments

### LINKED ISSUE #411: Checkstyle: <p> tag formatter vs. checkstyle.
image

I like to have <p> in a new line, but the formatter doesn't.

### PR DESCRIPTION
**Pull request by acBerger**
fixes #411

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/415)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
It still removes empty lines, so the checkstyle warning is still there.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/415#-:-K77N6QhsEfl4A6IFfcC:-2102767249)*

**Comment by acBerger** [comment]
Now empty lines will not be removed.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/415#-:-K77NiJMT2CuLInB-wNk:242319571)*

**Comment by RomanLangrehr** [comment]
:lgtm_strong: 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/415#-:-K77OQHqtWVARy99qlCM:-1868698381)*

**Comment by jGleitz** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/415#-:-K77R0KUYpL0woYWpfs0:-1868698381)*

**Pull request merged**
