### PR TITLE
Travis: Don’t retry

### PR DESCRIPTION
**Pull request by jGleitz**
When writing the Travis script, I thought it’d be clever to let gradle run again if it failed before and print a whole lot more information in that second run. But I’ve realised that was not that clever:

 * You need to scroll a lot on failed builds.
 * It slows down failed builds
 * The output is way to verbose and not very useful
 * **You can get that detailed info on your local machine**. You should never use Travis for debugging anyway.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/603)

### CODE REVIEW

**Comment by m1cm1c** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/603#-:-K8Gtr-lh15haUNvdqP0:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/603#-:-K8Gx1Vl5sq3onto2AQk:980077423)*

**Comment by RomanLangrehr** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/603)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/603#-:-K8GxEbCa3Sxv3e5iniv:980077423)*

**Comment by m1cm1c** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/603#-:-K8Gx_cP2VLh1SCHbR9U:1417088721)*

**Comment by m1cm1c** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/603)*

**Pull request merged**
