### PR TITLE
Fixed gradle encoding issues.

### PR DESCRIPTION
**Pull request by RomanLangrehr**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/606)

### CODE REVIEW

**Comment by jGleitz** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Core/gradle.properties, line 2 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/606#-K8KtRWhhQbYYwAnWJQU:-K8KtRWiZs2yUx53sWyk:948588194) ([raw file](https://github.com/beagle-pse/beagle/blob/d5421f134b89cfa2f09d046aed7d11d3c196ecaf/Core/gradle.properties#L2)):*
If you have to name it, please name it `'Beagle Core'`. But I think it we can omit the `project` block entirely.

---

*[Documentation/gradle.properties, line 2 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/606#-K8KtYOxbKCRg8Gh8Pj7:-K8KtYOxbKCRg8Gh8Pj8:529907979) ([raw file](https://github.com/beagle-pse/beagle/blob/d5421f134b89cfa2f09d046aed7d11d3c196ecaf/Documentation/gradle.properties#L2)):*
If you have to name it, please name it `'Beagle Documentation'`. But I think it we can omit the `project` block entirely.

---

*[GUI/gradle.properties, line 2 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/606#-K8KttjqqV2jYTtRIzPe:-K8KttjqqV2jYTtRIzPf:-87259956) ([raw file](https://github.com/beagle-pse/beagle/blob/d5421f134b89cfa2f09d046aed7d11d3c196ecaf/GUI/gradle.properties#L2)):*
If you have to name it, please name it `'Beagle GUI'`. But I think it we can omit the `project` block entirely.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/606)*

**Comment by RomanLangrehr** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Core/gradle.properties, line 2 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/606#-K8KtRWhhQbYYwAnWJQU:-K8KvSPLBZ14UtLfqgph:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/d5421f134b89cfa2f09d046aed7d11d3c196ecaf/Core/gradle.properties#L2)):*
Done.

---

*[Documentation/gradle.properties, line 2 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/606#-K8KtYOxbKCRg8Gh8Pj7:-K8KvT5NcVF6ka2Bug84:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/d5421f134b89cfa2f09d046aed7d11d3c196ecaf/Documentation/gradle.properties#L2)):*
Done.

---

*[GUI/gradle.properties, line 2 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/606#-K8KttjqqV2jYTtRIzPe:-K8KvTck9zCnOKLAilQO:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/d5421f134b89cfa2f09d046aed7d11d3c196ecaf/GUI/gradle.properties#L2)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/606)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/606#-:-K8L0RZuRHa3FvhR11cI:980077423)*

**Comment by m1cm1c** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/606#-:-K8L3G33E2y5_Xm83FwG:980077423)*

**Pull request merged**
