### PR TITLE
Bibtex

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Added BiBTeX to the Requirment Specification.
To see it in action, please check out: [Branch: bibtex-demo](https://github.com/RomanLangrehr/Beagle/tree/bibtex-demo) (It contains a sample entry and two sample citations.)
Fixes the technical aspects of #61

### CODE REVIEW

**Comment by jGleitz** [comment]
We adapt the citation style by adding some declarations to the preamble, can’t we? Because `[1]` isn’t that nice.

**Comment by RomanLangrehr** [comment]
See my last post in #61 
It isn't done in preamble, but it is just one click to change this.

**Comment by jGleitz** [comment]
wonderful. lgtmm

**Comment by jGleitz** [comment]
> but it is just one click to change this

One click for the whole document, I hope, not one click per citation?

**Comment by RomanLangrehr** [comment]
> One click for the whole document, I hope, not one click per citation?
Yes, one click for the whole document.

**Comment by acBerger** [comment]
lgtm

**Comment by m1cm1c** [comment]
@RomanLangrehr You don't mean `Requirements Specification.bib` but `Bibliography.bib`, don't you? Or should `Requirements Specification.bib` be created?

**Comment by RomanLangrehr** [comment]
No, I ment `Bibliography.bib`. (It was called `Requirements Specification.bib` before i noticed, that BiBTeX has a problem with whitespaces).

**Pull request merged**
