### PR TITLE
Measurement Tool, Proposed Expression Analyser, Measurement Result Analyser

### PR DESCRIPTION
**Pull request by viridispirus**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/535)

### CODE REVIEW

**Comment by acBerger** [comment]
[Website] (http://viridispirus.github.io/Beagle/branches/MToolMResultAnAProposedExpressionAnA/)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/535#-:-K7gWoSsVdgoSchpp_IJ:56041274)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/535#-:-K7gWze_5mnfH3pYb3kj:1417088721)*

**Comment by RomanLangrehr** [comment]
Pleas add an Abstract to the name and an <<Abstract>> about the name?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/535#-:-K7gZ2yqR3tBx7AohC-m:-782102999)*

**Comment by RomanLangrehr** [comment]
And you used the wron arrow for inheritance.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/535#-:-K7gbsoYslqRxi53eR1N:1175647317)*

**Comment by RomanLangrehr** [comment]
Sorry, you didn't, just an missing `<<implements>>`

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/535#-:-K7gc8B2xzra3MJdwKbd:1305666118)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/535)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/535#-:-K7genKDwGFvX1iD_qFL:980077423)*

**Comment by acBerger** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/535#-:-K7ggOaU4O9reNIzxwOj:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/535#-:-K7ggeHMRGmqFMHu--CB:980077423)*

**Pull request merged**
