### PR TITLE
British Spelling

### PR DESCRIPTION
**Pull request by m1cm1c**
I have no idea why but apparently "aging" is spelled "ageing" in British English.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/779)

### CODE REVIEW

**Comment by viridispirus** [comment]
:lgtm: 

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/779#-:-KCBZXOY8gTUmQl8U4D6:980077423)*

**Comment by jGleitz** [comment]
Are you sure about this? It doesn’t seem to make any sense.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/779#-:-KCBb9Ct3PX6m7YCoHzW:1399620269)*

**Comment by m1cm1c** [comment]
Just ask a dictionary. Lyx showed me "aging" as wrong when I switched to British spell checking which is how I figured this out and online dictionaries seem to agree.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/779#-:-KCBbVglcSXl9PICPKGU:1619659410)*

**Comment by jGleitz** [comment]
:lgtm: :white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/779#-:-KCBbyfsu_XetP9XYLn7:-1603124213)*

**Comment by acBerger** [comment]
Leo agrees with @m1cm1c .  :lgtm: :white_check_mark: nxx

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/779#-:-KCBbmHigRAXmziSiSR0:-19851222)*

**Pull request merged**
