### PR TITLE
implementation report

### PR DESCRIPTION
**Pull request by RomanLangrehr**
A first draft for the implementation report.
Chapter JUnitTests is missing.

[Website](http://romanlangrehr.github.io/Beagle/branches/0-implementation-report/)
[Report](http://romanlangrehr.github.io/Beagle/branches/0-implementation-report/Implementation%20Report.pdf)

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/695)

### CODE REVIEW

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/695#-:-KAQ6-2HIU5863Z5IFyo:1417088721)*

**Comment by acBerger** [comment]
:white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/695#-:-KAR0t3BRzt3VqqE4W1X:1605498549)*

**Comment by acBerger** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[Documentation/src/implementation/lyx/Implementation Report.lyx, line 3628 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/695#-KARPGB5COv3Qmp16glk:-KARPGB6beHo-iGhACTg:334241140) ([raw file](https://github.com/beagle-pse/beagle/blob/cbb36798151339931117a13b6b966fdc04b2c135/Documentation/src/implementation/lyx/Implementation Report.lyx#L3628)):*
I am not sure but shouldn't that be "meaningfully"

---

*[Documentation/src/implementation/lyx/Implementation Report.lyx, line 3634 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/695#-KARPA1KRSTk1yhDwbhZ:-KARPA1LzZ-813LxmeDx:334241140) ([raw file](https://github.com/beagle-pse/beagle/blob/cbb36798151339931117a13b6b966fdc04b2c135/Documentation/src/implementation/lyx/Implementation Report.lyx#L3634)):*
I am not sure but shouldn't that be "meaningfully"

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/695)*

**Comment by m1cm1c** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[Documentation/src/implementation/lyx/Implementation Report.lyx, line 3628 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/695#-KARPGB5COv3Qmp16glk:-KARUaDku6k3w1mpQT9B:-1521566724) ([raw file](https://github.com/beagle-pse/beagle/blob/cbb36798151339931117a13b6b966fdc04b2c135/Documentation/src/implementation/lyx/Implementation Report.lyx#L3628)):*
Yes, it should.

---

*[Documentation/src/implementation/lyx/Implementation Report.lyx, line 3634 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/695#-KARPA1KRSTk1yhDwbhZ:-KARUc1GYhrlR2cdHsc0:-1521566724) ([raw file](https://github.com/beagle-pse/beagle/blob/cbb36798151339931117a13b6b966fdc04b2c135/Documentation/src/implementation/lyx/Implementation Report.lyx#L3634)):*
Yes, it should.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/695)*

**Comment by m1cm1c** [comment]
Will look good to me after the few mentioned changes are in.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[Documentation/src/implementation/lyx/Implementation Report.lyx, line 53 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/695#-KARXZpT2EvZEvVmhQ-F:-KARXZpT2EvZEvVmhQ-G:703972713) ([raw file](https://github.com/beagle-pse/beagle/blob/cbb36798151339931117a13b6b966fdc04b2c135/Documentation/src/implementation/lyx/Implementation Report.lyx#L53)):*
report → Report

---

*[Documentation/src/implementation/lyx/Implementation Report.lyx, line 3178 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/695#-KARW1RXuAaODOxDZlZz:-KARW1RXuAaODOxDZl_-:-2144247721) ([raw file](https://github.com/beagle-pse/beagle/blob/cbb36798151339931117a13b6b966fdc04b2c135/Documentation/src/implementation/lyx/Implementation Report.lyx#L3178)):*
This sentence is wrong.

---

*[Documentation/src/implementation/lyx/Implementation Report.lyx, line 3582 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/695#-KARWNPq8gGs7PBR2-3g:-KARWNPq8gGs7PBR2-3h:-1011877331) ([raw file](https://github.com/beagle-pse/beagle/blob/cbb36798151339931117a13b6b966fdc04b2c135/Documentation/src/implementation/lyx/Implementation Report.lyx#L3582)):*
where → were

---

*[Documentation/src/implementation/lyx/Implementation Report.lyx, line 3606 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/695#-KARWaMUCWdvKO4_SRtQ:-KARWaMV5yCfLJ9WnIqq:1947816690) ([raw file](https://github.com/beagle-pse/beagle/blob/cbb36798151339931117a13b6b966fdc04b2c135/Documentation/src/implementation/lyx/Implementation Report.lyx#L3606)):*
intentional

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/695#-:-KARXeCMcKtdw6ub6UD7:11675840)*

**Comment by m1cm1c** [comment]
This branch is out-of-date with the base branch.

**Comment by RomanLangrehr** [comment]
Review status: 1 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[Documentation/src/implementation/lyx/Implementation Report.lyx, line 53 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/695#-KARXZpT2EvZEvVmhQ-F:-KATp6ut0W5djFi9QMeM:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/cbb36798151339931117a13b6b966fdc04b2c135/Documentation/src/implementation/lyx/Implementation Report.lyx#L53)):*
Done.

---

*[Documentation/src/implementation/lyx/Implementation Report.lyx, line 3178 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/695#-KARW1RXuAaODOxDZlZz:-KATp6UDiWXOpBBfwqUM:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/cbb36798151339931117a13b6b966fdc04b2c135/Documentation/src/implementation/lyx/Implementation Report.lyx#L3178)):*
Done.

---

*[Documentation/src/implementation/lyx/Implementation Report.lyx, line 3582 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/695#-KARWNPq8gGs7PBR2-3g:-KATp63JN8-NdVpAAJpy:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/cbb36798151339931117a13b6b966fdc04b2c135/Documentation/src/implementation/lyx/Implementation Report.lyx#L3582)):*
Done.

---

*[Documentation/src/implementation/lyx/Implementation Report.lyx, line 3606 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/695#-KARWaMUCWdvKO4_SRtQ:-KATp5a4_ziEBhDs4xsk:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/cbb36798151339931117a13b6b966fdc04b2c135/Documentation/src/implementation/lyx/Implementation Report.lyx#L3606)):*
Done.

---

*[Documentation/src/implementation/lyx/Implementation Report.lyx, line 3628 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/695#-KARPGB5COv3Qmp16glk:-KATp56Caahf9FFHCZdj:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/cbb36798151339931117a13b6b966fdc04b2c135/Documentation/src/implementation/lyx/Implementation Report.lyx#L3628)):*
Done.

---

*[Documentation/src/implementation/lyx/Implementation Report.lyx, line 3634 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/695#-KARPA1KRSTk1yhDwbhZ:-KATp4cgBsitSbeBrGLG:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/cbb36798151339931117a13b6b966fdc04b2c135/Documentation/src/implementation/lyx/Implementation Report.lyx#L3634)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/695)*

**Comment by acBerger** [comment]
:lgtm: :white_check_mark: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/695#-:-KAUSsmFiVqb0jp0OZr1:-1603124213)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/695#-:-KAVC7AVuTwXWW6XD_LL:980077423)*

**Pull request merged**
