### PR TITLE
final presentation

### PR DESCRIPTION
**Pull request by viridispirus**
If you need some slides for the final presentation here you can add them.
It is not the final version of the slides but a first one.

---
This change is [Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/820)

### CODE REVIEW

**Comment by jGleitz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KCzm_js3ZLEvE5Og60K:-KCzm_jtUNzTERkhTjR6:-455863421) (no related file):*
Is “close presentation” the correct english term for this? I know that “close” can mean “Abschluss”, however, I just think it sounds really odd.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/820)*

**Comment by jGleitz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KCzm_js3ZLEvE5Og60K:-KCzmzr7hbXr9loJA0ho:-560378622) (no related file):*
[Linguee suggests](http://www.linguee.de/deutsch-englisch/uebersetzung/abschlusspr%C3%A4sentation.html) “final presestation” or “closing presentation” which both sound much better to me.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/820)*

**Comment by viridispirus** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KCzm_js3ZLEvE5Og60K:-KD-1CZ5xXHqPtqCxPBc:-66256424) (no related file):*
I was also not sure but your are right final presentation sounds better.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/820)*

**Comment by jGleitz** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[Documentation/src/close presentation/lyx/Close Presentation Slides.lyx, line 117 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KD--yLIq-cCMNphA8OQ:-KD--yLIq-cCMNphA8OR:-629141591) ([raw file](https://github.com/beagle-pse/beagle/blob/55e187eadb6c142e87bf0e6649542c5c0d44bd0f/Documentation/src/close presentation/lyx/Close Presentation Slides.lyx#L117)):*
I don’t really like that definition. Because right now, we’re doing a lot more.

Maybe something like “erweiterbares Analyse-Tool” would fit better? What do the others think? @acberger @romanlangrehr @m1cm1c @flyfl 

---

*[Documentation/src/close presentation/lyx/Close Presentation Slides.lyx, line 131 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KD-03nuP-Q9XpxCExQK:-KD-03nuP-Q9XpxCExQL:947151772) ([raw file](https://github.com/beagle-pse/beagle/blob/55e187eadb6c142e87bf0e6649542c5c0d44bd0f/Documentation/src/close presentation/lyx/Close Presentation Slides.lyx#L131)):*
an**[n]**otier**[en]**n

---

*[Documentation/src/close presentation/lyx/Close Presentation Slides.lyx, line 145 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KD-0Gnywm0_JtO-0dx-:-KD-0GnzygVab7ieYbee:1478754562) ([raw file](https://github.com/beagle-pse/beagle/blob/55e187eadb6c142e87bf0e6649542c5c0d44bd0f/Documentation/src/close presentation/lyx/Close Presentation Slides.lyx#L145)):*
genetischen Ansatz **[…]** von Krogmann

We already implemented the fitness function like Krogmann defined it.

---

*[Documentation/src/close presentation/lyx/Close Presentation Slides.lyx, line 149 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KD-0EjO-5_pAxwKQrCi:-KD-0EjO-5_pAxwKQrCj:1739257789) ([raw file](https://github.com/beagle-pse/beagle/blob/55e187eadb6c142e87bf0e6649542c5c0d44bd0f/Documentation/src/close presentation/lyx/Close Presentation Slides.lyx#L149)):*
 * an**[n]**otier**[en]**n
 * von **[weiteren]** SEFF Elementen

---

*[Documentation/src/close presentation/lyx/Close Presentation Slides.lyx, line 153 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KD-0ctmaMuDIeUKx0T5:-KD-0ctmaMuDIeUKx0T6:-1463841289) ([raw file](https://github.com/beagle-pse/beagle/blob/55e187eadb6c142e87bf0e6649542c5c0d44bd0f/Documentation/src/close presentation/lyx/Close Presentation Slides.lyx#L153)):*
 HDD **[demand]** messen

---

*[Documentation/src/close presentation/lyx/Close Presentation Slides.lyx, line 155 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KD-1QKbs31rbgn40aWa:-KD-1QKbs31rbgn40aWb:1787454166) ([raw file](https://github.com/beagle-pse/beagle/blob/55e187eadb6c142e87bf0e6649542c5c0d44bd0f/Documentation/src/close presentation/lyx/Close Presentation Slides.lyx#L155)):*
Another point:

 * Regressions-Tools

---

*[Documentation/src/close presentation/lyx/Close Presentation Slides.lyx, line 181 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KD-0j0sQ0F2ktnMlnCu:-KD-0j0sQ0F2ktnMlnCv:1520529355) ([raw file](https://github.com/beagle-pse/beagle/blob/55e187eadb6c142e87bf0e6649542c5c0d44bd0f/Documentation/src/close presentation/lyx/Close Presentation Slides.lyx#L181)):*
Can you get this number excluding merge commits? Because I think that would be the much more significant one.

---

*[Documentation/src/close presentation/lyx/Close Presentation Slides.lyx, line 197 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KD-0pnOjNLYuzEKTpFF:-KD-0pnOjNLYuzEKTpFG:1667376313) ([raw file](https://github.com/beagle-pse/beagle/blob/55e187eadb6c142e87bf0e6649542c5c0d44bd0f/Documentation/src/close presentation/lyx/Close Presentation Slides.lyx#L197)):*
I think we actually have 400

---

*[Documentation/src/close presentation/lyx/Close Presentation Slides.lyx, line 210 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KD-0zW4DJcoAtdUqD7B:-KD-0zW4DJcoAtdUqD7C:1325300835) ([raw file](https://github.com/beagle-pse/beagle/blob/55e187eadb6c142e87bf0e6649542c5c0d44bd0f/Documentation/src/close presentation/lyx/Close Presentation Slides.lyx#L210)):*
We’re not giving feedback! (We’re not in the position to do so).

Maybe we could call this slide “Reflektion”

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/820)*

**Comment by viridispirus** [comment]
Review status: 2 of 4 files reviewed at latest revision, 10 unresolved discussions.

---

*[Documentation/src/close presentation/lyx/Close Presentation Slides.lyx, line 131 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KD-03nuP-Q9XpxCExQK:-KD-5OvxtO-1JKuSSNjo:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/55e187eadb6c142e87bf0e6649542c5c0d44bd0f/Documentation/src/close presentation/lyx/Close Presentation Slides.lyx#L131)):*
Done.

---

*[Documentation/src/close presentation/lyx/Close Presentation Slides.lyx, line 145 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KD-0Gnywm0_JtO-0dx-:-KD-5Pf3NfLNcLcLzU5D:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/55e187eadb6c142e87bf0e6649542c5c0d44bd0f/Documentation/src/close presentation/lyx/Close Presentation Slides.lyx#L145)):*
Done.

---

*[Documentation/src/close presentation/lyx/Close Presentation Slides.lyx, line 149 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KD-0EjO-5_pAxwKQrCi:-KD-5Q-Uariv8X802Ln6:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/55e187eadb6c142e87bf0e6649542c5c0d44bd0f/Documentation/src/close presentation/lyx/Close Presentation Slides.lyx#L149)):*
Done.

---

*[Documentation/src/close presentation/lyx/Close Presentation Slides.lyx, line 153 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KD-0ctmaMuDIeUKx0T5:-KD-5QUZPIFWvWba0r1N:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/55e187eadb6c142e87bf0e6649542c5c0d44bd0f/Documentation/src/close presentation/lyx/Close Presentation Slides.lyx#L153)):*
Done.

---

*[Documentation/src/close presentation/lyx/Close Presentation Slides.lyx, line 155 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KD-1QKbs31rbgn40aWa:-KD-5QwQEh0YB1NAJgAX:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/55e187eadb6c142e87bf0e6649542c5c0d44bd0f/Documentation/src/close presentation/lyx/Close Presentation Slides.lyx#L155)):*
Done.

---

*[Documentation/src/close presentation/lyx/Close Presentation Slides.lyx, line 181 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KD-0j0sQ0F2ktnMlnCu:-KD-4VI2cAflFty5xsCT:2004434001) ([raw file](https://github.com/beagle-pse/beagle/blob/55e187eadb6c142e87bf0e6649542c5c0d44bd0f/Documentation/src/close presentation/lyx/Close Presentation Slides.lyx#L181)):*
Yes, good point. I'll try it.

---

*[Documentation/src/close presentation/lyx/Close Presentation Slides.lyx, line 197 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KD-0pnOjNLYuzEKTpFF:-KD-4wJOEKrPCACXB5VX:1744993208) ([raw file](https://github.com/beagle-pse/beagle/blob/55e187eadb6c142e87bf0e6649542c5c0d44bd0f/Documentation/src/close presentation/lyx/Close Presentation Slides.lyx#L197)):*
Are you sure?

---

*[Documentation/src/close presentation/lyx/Close Presentation Slides.lyx, line 210 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KD-0zW4DJcoAtdUqD7B:-KD-5RzBXId7tljFY6iT:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/55e187eadb6c142e87bf0e6649542c5c0d44bd0f/Documentation/src/close presentation/lyx/Close Presentation Slides.lyx#L210)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/820)*

**Comment by jGleitz** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KCzm_js3ZLEvE5Og60K:-KD-62n8UPD1r3Wgd5rR:-2086626582) (no related file):*
Please remove the folder “close presentation”!

---

*[Documentation/src/close presentation/lyx/Close Presentation Slides.lyx, line 197 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KD-0pnOjNLYuzEKTpFF:-KD-6_LyRXU2vIATWSvM:1390614524) ([raw file](https://github.com/beagle-pse/beagle/blob/55e187eadb6c142e87bf0e6649542c5c0d44bd0f/Documentation/src/close presentation/lyx/Close Presentation Slides.lyx#L197)):*
On `master`:



Actually, we have two more in `Averaging Measurement Result Analyser`, so that sums up to 402.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/820)*

**Comment by viridispirus** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[Documentation/src/close presentation/lyx/Close Presentation Slides.lyx, line 197 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KD-0pnOjNLYuzEKTpFF:-KD-7bHO8G4JUIRcSIMo:160415405) ([raw file](https://github.com/beagle-pse/beagle/blob/55e187eadb6c142e87bf0e6649542c5c0d44bd0f/Documentation/src/close presentation/lyx/Close Presentation Slides.lyx#L197)):*
ok.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/820)*

**Comment by viridispirus** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KCzm_js3ZLEvE5Og60K:-KD-AgmEBLjQUv1pUfWt:-469593337) (no related file):*
done.

---

*[Documentation/src/close presentation/lyx/Close Presentation Slides.lyx, line 197 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KD-0pnOjNLYuzEKTpFF:-KD-AkHn16hQcY3QTX-L:-469593337) ([raw file](https://github.com/beagle-pse/beagle/blob/55e187eadb6c142e87bf0e6649542c5c0d44bd0f/Documentation/src/close presentation/lyx/Close Presentation Slides.lyx#L197)):*
done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/820)*

**Comment by viridispirus** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[Documentation/src/close presentation/lyx/Close Presentation Slides.lyx, line 197 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KD-0pnOjNLYuzEKTpFF:-KD-AnoLsVhYsdRS4Bj6:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/55e187eadb6c142e87bf0e6649542c5c0d44bd0f/Documentation/src/close presentation/lyx/Close Presentation Slides.lyx#L197)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/820)*

**Comment by jGleitz** [comment]
Reviewed 2 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/820)*

**Comment by viridispirus** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[Documentation/src/close presentation/lyx/Close Presentation Slides.lyx, line 181 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KD-0j0sQ0F2ktnMlnCu:-KD-HCWZyz8FZUlgjMwS:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/55e187eadb6c142e87bf0e6649542c5c0d44bd0f/Documentation/src/close presentation/lyx/Close Presentation Slides.lyx#L181)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/820)*

**Comment by RomanLangrehr** [comment]
I added the gradle render task and added the slides to the [Website](http://beagle-pse.github.io/Beagle/branches/closePresentation/).

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-:-KD-eVDYMgtvqiTk7WqK:35114191)*

**Comment by viridispirus** [comment]
Review status: 1 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[Documentation/src/close presentation/lyx/Close Presentation Slides.lyx, line 117 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KD--yLIq-cCMNphA8OQ:-KD2XNVkDv_LCWwHcDZE:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/55e187eadb6c142e87bf0e6649542c5c0d44bd0f/Documentation/src/close presentation/lyx/Close Presentation Slides.lyx#L117)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/820)*

**Comment by jGleitz** [comment]
Reviewed 1 of 1 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Web Presence/buildSrc/src/tasks/gradle/10 web artefacts.gradle, line 31 \[r5\]](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KD3Ah4_h3j6xV4aZnnT:-KD3Ah4aGVmuCvMQBGHh:-2107687752) ([raw file](https://github.com/beagle-pse/beagle/blob/a0f01ba13aaec3590d6ebf3fade0b4b2e4609328/Web Presence/buildSrc/src/tasks/gradle/10 web artefacts.gradle#L31)):*
to be consistent with the rest: append `doc.finalpresentationslides.logdest`

---

*[Web Presence/buildSrc/src/tasks/gradle/10 web artefacts.gradle, line 59 \[r5\]](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KD3Aosklee89sOWVYZt:-KD3Aosl1_8sBaIZTW42:-2107687752) ([raw file](https://github.com/beagle-pse/beagle/blob/a0f01ba13aaec3590d6ebf3fade0b4b2e4609328/Web Presence/buildSrc/src/tasks/gradle/10 web artefacts.gradle#L59)):*
to be consistent with the rest: append `doc.finalpresentationslides.logdest`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/820)*

**Comment by jGleitz** [comment]
:lgtm: :white_check_mark: 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-:-KD3BQIQEps0vR8rr-2S:-1603124213)*

**Comment by jGleitz** [comment]
:lgtm: :white_check_mark: 

---

Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-:-KD3cjf7hC47fFv5OGDB:-1603124213)*

**Comment by jGleitz** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/820)*

**Comment by RomanLangrehr** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 3 files at r3, 1 of 1 files at r4, 4 of 4 files at r5, 1 of 1 files at r6, 2 of 2 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Web Presence/buildSrc/src/tasks/gradle/10 web artefacts.gradle, line 31 \[r5\]](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KD3Ah4_h3j6xV4aZnnT:-KD3c20fixfk3iJmsvIZ:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/a0f01ba13aaec3590d6ebf3fade0b4b2e4609328/Web Presence/buildSrc/src/tasks/gradle/10 web artefacts.gradle#L31)):*
Done.

---

*[Web Presence/buildSrc/src/tasks/gradle/10 web artefacts.gradle, line 59 \[r5\]](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-KD3Aosklee89sOWVYZt:-KD3cHWYrfeleji17A9o:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/a0f01ba13aaec3590d6ebf3fade0b4b2e4609328/Web Presence/buildSrc/src/tasks/gradle/10 web artefacts.gradle#L59)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-:-KDD5gnURGctJNdOaLmT:1417088721)*

**Comment by RomanLangrehr** [comment]
:white_check_mark: 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-:-KDDBPuKGZXIRLDgbOKU:1605498549)*

**Comment by jGleitz** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/820#-:-KDKPoO_3iyDm-3Y78cH:1417088721)*

**Pull request merged**
