### PR TITLE
Fail API

### PR DESCRIPTION
**Pull request by viridispirus**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/703)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
Reviewed 4 of 4 files at r1, 1 of 2 files at r3.
Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/resources/META-INF/MANIFEST.MF, line 21 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/703#-KAS8arZmps93eLQkO3X:-KAS8arZmps93eLQkO3Y:1356574907) ([raw file](https://github.com/beagle-pse/beagle/blob/229104944c9de811d4d9b05087c5a34ef1c3f03d/Core/src/main/resources/META-INF/MANIFEST.MF#L21)):*
That must be removed!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/703)*

**Comment by RomanLangrehr** [comment]
Reviewed 3 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/703)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/resources/META-INF/MANIFEST.MF, line 8 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/703#-KAS9csmFoawiynsF9pP:-KAS9csnDLR_xv1xhCuo:1455309011) ([raw file](https://github.com/beagle-pse/beagle/blob/229104944c9de811d4d9b05087c5a34ef1c3f03d/Core/src/main/resources/META-INF/MANIFEST.MF#L8)):*
These two imports don’t belong here. Please remove them.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/703)*

**Comment by viridispirus** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/resources/META-INF/MANIFEST.MF, line 8 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/703#-KAS9csmFoawiynsF9pP:-KASADWkZGNtk7VeHlDL:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/229104944c9de811d4d9b05087c5a34ef1c3f03d/Core/src/main/resources/META-INF/MANIFEST.MF#L8)):*
Done.

---

*[Core/src/main/resources/META-INF/MANIFEST.MF, line 21 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/703#-KAS8arZmps93eLQkO3X:-KASADssl9MMwTdvaEGa:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/229104944c9de811d4d9b05087c5a34ef1c3f03d/Core/src/main/resources/META-INF/MANIFEST.MF#L21)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/703)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/703#-:-KASAvbUQovyVlPClrWw:980077423)*

**Comment by RomanLangrehr** [comment]
[Webiste](http://beagle-pse.github.io/Beagle/branches/fail-api/)

The coverage report is missing :(

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/703#-:-KASBQMJkNzo2EnAQK2X:926167069)*

**Comment by RomanLangrehr** [comment]
There are compilation-errors in the tests :lgtm_cancel: .

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/703#-:-KATpkie_DLYnz9SJBEm:-213968046)*

**Comment by jGleitz** [comment]
> The coverage report is missing :(

> There are compilation-errors in the tests 

One explains the other ;)

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/703#-:-KAUB58nzXBe75q_eFnl:36477659)*

**Comment by acBerger** [comment]
Reviewed 1 of 4 files at r1, 6 of 6 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/703)*

**Comment by acBerger** [comment]
Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/703)*

**Comment by acBerger** [comment]
Reviewed 2 of 2 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/703)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 3 of 6 files at r6, 1 of 2 files at r8, 2 of 2 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/703#-:-KAUwUUr0hjkMlShsMVi:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: :white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/703#-:-KAUzUWBHpbUr-0XGE9H:-1603124213)*

**Comment by flyfl** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r1, 3 of 6 files at r6, 1 of 2 files at r8, 2 of 2 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/703#-:-KAUzcFwmfFeW7QhJ1zM:1417088721)*

**Pull request merged**
