### PR TITLE
Added new text field for the source code link file.

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Fixes #777 

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/787)

### CODE REVIEW

**Comment by acBerger** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/787)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/787#-:-KCD-oyeH2H3pbiRTaTg:1417088721)*

**Comment by viridispirus** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/787)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/787#-:-KCD15uIQ0OFfIkv8RLB:980077423)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/787)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/787#-:-KCD5Aq76zC21KUt_TVa:1417088721)*

**Comment by viridispirus** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/787)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r3, 6 of 7 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/787#-:-KCDFKKX_pbGFDOeN7z0:980077423)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r3, 5 of 7 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/787)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/787)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/787#-:-KCDNJDusZIzrGIqpf0j:1417088721)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/787#-:-KCDNOAW_F8KaY7cqwFJ:980077423)*

**Comment by m1cm1c** [comment]
:lgtm: :white_check_mark: 

---

Reviewed 3 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 6 of 7 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/787#-:-KCDNRqbp9w26_TU9q6S:-1603124213)*

**Pull request merged**
