### PR TITLE
Render LyX With Gradle

### LINKED ISSUE #376: Build .lyx Documents With Gradle
The srs build script should be re-implemented in groovy.

### PR DESCRIPTION
**Pull request by jGleitz**
This PR uses gradle to render pdfs. **It depends on on #384**

 * One code to render on all platforms
 * Results in speed improvements (~20s) when rendering the srs
 * Caching of umlet conversion (-> building is a lot faster when editing the srs)
 * Builds the design document
 * Removes `gradle srsinstall`. The script is invoked directly again
 * Improves doc for LyX

From my point of view, the render code got **a great lot** easier to read, understand and maintain. Making it reusable was very easy (The task definition for the design document needs two lines!).

fixes #376 

[View this PR’s rendered artefacts](http://jgleitz.github.io/Beagle/branches/render-lyx-with-gradle/)

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/385)

### CODE REVIEW

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/385#-:-K75_8iGKBKaakdLMM1m:1417088721)*

**Comment by jGleitz** [comment]
-blocked 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/385#-:-K764JWMn8r2DAlQyYIV:-1272864900)*

**Comment by RomanLangrehr** [comment]
Doesn't work for me :(


---

Reviewed 16 of 19 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/385#-:-K765s2iksT61O9qttnh:-121606866)*

**Comment by acBerger** [comment]
:lgtm_cancel: 
As I forgot to test on my system.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/385#-:-K76CETNHCrXGZSPl_cc:-359661161)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/385#-:-K76D3LVCGzj8E0GO6mm:1417088721)*

**Comment by m1cm1c** [comment]
This branch is out-of-date with the base branch.

**Comment by acBerger** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/385#-:-K76M4se7tZoL9Q1BBXf:980077423)*

**Comment by jGleitz** [comment]
Sorry for the late response. But I took my time to extact the UMLET code into its own class and added the output check to detect render errors. Please try again now.

---

Review status: 11 of 16 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/385#-:-K76VuGGwWsbXy4VHuwm:1863960467)*

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 6 of 7 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/385#-:-K76XtQkFnruxcRIRI8N:1417088721)*

**Comment by RomanLangrehr** [comment]
I still get some strange messages:



But it works!
:lgtm_strong: 

---

Reviewed 6 of 7 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/385#-:-K76_gObb3JDmTEBdYoQ:2052042969)*

**Comment by jGleitz** [comment]
These are not caused directly by my code. I don't know where they come from, maybe from lyx. 

Maybe executing gradle in a git bash helps.

**Pull request merged**
