### PR TITLE
Add Resource Type in Resource Demanding Internal Actions

### PR DESCRIPTION
**Pull request by acBerger**
As discussed in hangouts.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/534)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/534#-:-K7gUuuBDH9OkMiZzWE2:980077423)*

**Comment by RomanLangrehr** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/534)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/534#-:-K7gcxQaVex1JaRPJgec:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/534#-:-K7gguSAHl3F1Uwo_DEv:980077423)*

**Comment by flyfl** [comment]
:lgtm_strong:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/534#-:-K7goz4_RSsL9_t3kLzY:-1168659251)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/534#-:-K7gwwPwKOvbmyw11AZu:980077423)*

**Pull request merged**
