### PR TITLE
Beagle Core Diagrams

### LINKED ISSUE #475: Redraw Beagle Core Diagram in UMLet
Include the changes discussed in the meeting and in #463 and #457

### PR DESCRIPTION
**Pull request by jGleitz**
Please review carefully—contains a bunch of API changes.

Java code will follow as soon as this is merged.

fixes #475 

beagle core

---

blackboard

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/489)

### CODE REVIEW

**Comment by viridispirus** [comment]
The Beagle Controller is the Analyse Controller, right?

**Comment by viridispirus** [comment]
Please update branch.

**Comment by m1cm1c** [comment]
No. Beagle Controller calls Analysis Controller. 

On January 9, 2016 10:05:32 AM GMT+01:00, Micha <notifications@github.com> wrote:
>The Beagle Controller is the Analyse Controller, right?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Beagle-PSE/Beagle/pull/489#issuecomment-170211819

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by flyfl** [comment]
Some multiplicities overlap with qualifier names. Can you fix that? (->blackboard)

**Comment by acBerger** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/489)*

**Comment by RomanLangrehr** [comment]
The pseudocode for the `perform analysis()` function should be added somewhere, not necassarily in the diagram and in this PR, but we should not forget that.

**Comment by RomanLangrehr** [comment]
The Read-Only BlackbaordView should also have the `get...to be measured()` methods

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/489#-:-K7aZCnCjqs52C5O3w_Z:-1508185585)*

**Comment by jGleitz** [comment]
> The pseudocode for the perform analysis() function should be added somewhere, not necassarily in the diagram and in this PR, but we should not forget that.

I totally agree and plan to integrate that into the document. It will be easier and better readable to do it there.


> The Read-Only BlackbaordView should also have the `get...to be measured()` methods

Why? The analysers should not care for them. Please see also #484, which I’ve silently already implemented here.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/489#-:-K7adSWPlwZrAeVH98zT:1700097834)*

**Comment by jGleitz** [comment]
> Some multiplicities overlap with qualifier names. Can you fix that? (->blackboard)

No, unfortunaly, there is nothing I can do about that.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/489#-:-K7aeGXPptELCONJ5zdy:1264452345)*

**Comment by viridispirus** [comment]
Please update branch.

**Comment by acBerger** [comment]
Please add your diagram to the document. The ones contained are still the old ones.
[Website] (http://jgleitz.github.io/Beagle/branches/beagle-core-in-umlet/)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/489#-:-K7avvX6-imzIs1neHQJ:205269913)*

**Comment by RomanLangrehr** [comment]
>  The analysers should not care for them. Please see also #484, which I’ve silently already implemented here.

They should! When the only kind of contribution of an result analyser is to add request measurments it's interessting which measurements are already there (and can not be executed).

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/489#-:-K7bL0vBqvIusAL3VyrG:1659572547)*

**Comment by RomanLangrehr** [comment]
> The analysers should not care for them. Please see also #484, which I’ve silently already implemented here.

Actually, the MeasurementController definitly needs them in his can measure methode!

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/489#-:-K7bNTpvQ6SCGU2Tie0y:-559866240)*

**Comment by RomanLangrehr** [comment]
These should be removed, as the Measurement Result Analysers work may not depend on them.

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/489#-:-K7bO2-4gz3B5PKG-gJO:329142918)*

**Comment by jGleitz** [comment]
> They should! When the only kind of contribution of an result analyser is to add request measurments it's interessting which measurements are already there (and can not be executed).

If a SEFF Element did not produce results while measuring, it is still removed from the to be measured list. To recognise that a SEFF Element did not produce results yet, you check whether there are measurement results for it on the blackboard.

> Actually, the MeasurementController definitly needs them in his can measure methode!

There is no Blackboard View for `Measurement Controller` anymore. As I said, please see #484 for a discussion n that matter.

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/489#-:-K7babn_3W3ELg2wzDW8:-747572492)*

**Comment by jGleitz** [comment]
>  These should be removed, as the Measurement Result Analysers work may not depend on them.

The `Measurement Result Analyser` may not see `Measurement Result`s? How can he possible analyse `Measurement Result`s then?

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/489#-:-K7bbRoXAeTeaK_oIbbR:-1562911468)*

**Comment by RomanLangrehr** [comment]
> The `Measurement Result Analyser` may not see `Measurement Result`s? How can he possible analyse `Measurement Result`s then?

I'm sorry. I mixed something up.

**Comment by jGleitz** [comment]
What is this PR lacking to be merged?

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/489#-:-K7bingue7VERc7UUvLn:2044960453)*

**Comment by RomanLangrehr** [comment]
For me: The discussion in #484

**Comment by jGleitz** [comment]
Can we please merge this and do #484 in a new PR? We have an issue for it, after all.

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/489#-:-K7bjdugAkMywSTFMxh4:-1959076378)*

**Comment by RomanLangrehr** [comment]
Okay. :lgtm: 

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/489#-:-K7bk4qa6fabWbBiG-L0:-1464566647)*

**Comment by m1cm1c** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/489#-:-K7bkWvuISN7sz0B6o2i:980077423)*

**Pull request merged**
