### PR TITLE
Implementation slides

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Will introduce the test sildes.
Please do not merge this yet, I only had to create this PR because it can only be build with the "Team"-Travis.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/739)

### CODE REVIEW

**Comment by viridispirus** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/739)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/739)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/739)*

**Comment by RomanLangrehr** [comment]
Is now finished.

**Comment by jGleitz** [comment]
:lgtm: 

---

Reviewed 7 of 10 files at r1, 4 of 5 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/739#-:-KAthazl_W3hBcHQ94Ci:980077423)*

**Comment by acBerger** [comment]
:lgtm: :white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/739#-:-KAthtDz2rTg5AGwhHqx:-1603124213)*

**Pull request merged**
