### PR TITLE
adapted the way \label and \ref work.

### PR DESCRIPTION
**Pull request by jGleitz**
`\label` was rewritten to
   a) have its ID printed when referenced
   b) print the ID when defined

`\ref` will automatically print the label’s ID

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
Lgtm

**Comment by acBerger** [comment]
/G20/ does not look as it should (it is in italics)

**Comment by acBerger** [comment]
lgtm

**Comment by RomanLangrehr** [comment]
Lgtm

**Pull request merged**
