### PR TITLE
Model Start

### PR DESCRIPTION
**Pull request by jGleitz**
Although unfinished, I wanted to share my progress so far (~ 8 hours of work)

All modelled information is accurate and correct, but incomplete.

Please take your time to carefully review, do not rely solely on the diagrams’ visual representation.

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
I get the following errror, when I try to open the Measurment Package:
image

And the file `doc/Design/Packages/Measurment.notation` doesn't exist on my hard drive.

**Comment by jGleitz** [comment]
`doc/Design/Packages/Measurment.notation` does not exist because there is no diagram in it. This is a little unfortunate. You can, however, view the contents of `Packages/Measurment` through `Beagle`.

**Comment by jGleitz** [comment]
I added an empty (almost) `doc/Design/Packages/Measurement.notation` which lets you open `Packages/Measurement` without a warning.

**Comment by RomanLangrehr** [comment]
image
That's a constructor, isn't it? It should have a ´<<create>>`

**Comment by RomanLangrehr** [comment]
image

I think the "upper" associations should not be compositions, because the classes are not only used for these associations. (They are used at least for `.... to be measured`, too).
And I'm not sure, wether we should use here an aggregation at all: When we would decide not to use the blackboard pattern any more, we would remove the blackboard class, but not the classes `SEFF Loop` and so on.

**Comment by jGleitz** [comment]
I see your point. What I wanted to model is “There may not be a SEFFLoop that is not on the blackboard.” I see that a composition is not perfectly correct here. Do you have a better idea to convey the above?

Meanwhile, I think that the aggregations are correct. I want to point out that the existence dependency only exists for compositions. For aggregations, neither part ceases to exist just because the other does.

**Comment by jGleitz** [comment]
I added the missing `»create«` and changed the compositions to aggregations.

**Comment by RomanLangrehr** [comment]
image

 * Why does not `Genetic Analyser` provide the `Result Analyser` interface?
 * What is the `Port 1` for?

**Comment by jGleitz** [comment]
The component diagram is unfinished, mainly because I don’t know how to get this right. You somehow need ports to model required and provided interfaces, yet I don’t understand what exactly they are for.

**Comment by RomanLangrehr** [comment]
> The component diagram is unfinished, mainly because I don’t know how to get this right. You somehow need ports to model required and provided interfaces, yet I don’t understand what exactly they are for.

I see.

Lgtm

**Comment by flyfl** [comment]
lgtm

**Pull request merged**
