### PR TITLE
Adapted naming of test methods

### LINKED ISSUE #637: Naming Convention for Methods in Test Classes
Currently we use `testMethodName` as names in the tests (mainly because they are generated). @jGleitz suggested to use `methodName` as this is easier to read if you have a list of all test methods.
As all test methods are in a Test class it is not needed to write 'test' before the name.

Are there any other perferences?

I agree with @jGleitz that it is better to use the simple name, even through this means we have to adapt the names generated by JUnit.

### PR DESCRIPTION
**Pull request by jGleitz**
Fixes #637

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/653)

### CODE REVIEW

**Comment by viridispirus** [comment]
:lgtm: 

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/653#-:-K9iAJSjRWjeJdi1w1aS:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/653#-:-K9iALPChXiySGLSFyrT:980077423)*

**Comment by jGleitz** [comment]
I added a checkstyle rule for this.

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/653#-:-K9iByIfm9evQdda-w3s:1814167313)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/653#-:-K9iCGltkHSZqOLB18U3:980077423)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/653#-:-K9iDsHMoyjLIchyYMBS:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/653#-:-K9kV_1cfjMWrUl-NPt_:980077423)*

**Comment by RomanLangrehr** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/653)*

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/653#-:-K9ktjAOmkz3VGMpJI2M:1417088721)*

**Pull request merged**
