### PR TITLE
Replaced CopyOnWriteArrayList by ArrayList.

### PR DESCRIPTION
**Pull request by RomanLangrehr**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/665)

### CODE REVIEW

**Comment by jGleitz** [comment]
Are you sure this is the only occurrence?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/665#-:-K9sZ5gLn4fVRaDW4sqi:2048288694)*

**Comment by RomanLangrehr** [comment]
Yes.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/665#-:-K9sZKl6YdjsdZvSWl5N:677251276)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/665#-:-K9sZZMewelFc9L9YpSV:980077423)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/665#-:-K9sZmTqW6QrxTrhEGDO:980077423)*

**Pull request merged**
