### PR TITLE
Blackboard (&View) Completion

### LINKED ISSUE #402: Create Dummy Methods (1)
For classes:
  * ReadOnlyBlackboardView
  * AnalyserBlackboardView
  * MeasurementBlackboardView
  * FinalJugdeBlackboardView

### LINKED ISSUE #403: Create Dummy Methods (2)
For every class which isn't a view.

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Fixes #402 
Fixes #403 
(Not all method stubs are there, but all that we know about yet).

Blocked as not some multiplicitys in the diagram are wrong:
image
Should be * in all views.

image
Should be *, same in Final Judge View

image
Should be 1

Maybe someone, how has a better Papyrus than me, can fix this?

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/439)

### CODE REVIEW

**Comment by m1cm1c** [comment]
Doesn't work on my machine either. It doesn't even show me a change when I try it and when I save the file (the asterisk as soon as I make the change), no changes are made to the diagram files.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/439#-:-K7IcDnZ9NsFplktfgM7:922263771)*

**Comment by acBerger** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/439)*

**Comment by acBerger** [comment]
This branch is out-of-date with the base branch.

**Comment by acBerger** [comment]
Seems like I am able to change the multiplicy.


Unfortunately there are some "lines" in this diagram for me, which probably should not be there.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/439#-:-K7LkQP32GM4s6i908wB:-711561092)*

**Comment by acBerger** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/439)*

**Comment by RomanLangrehr** [comment]
> Unfortunately there are some "lines" in this diagram for me, which probably should not be there.

They are probably associations...

**Comment by acBerger** [comment]
> They are probably associations...

Yes they are, but they are leading nowhere.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/439#-:-K7Mhh3AnHxuOBfNxTo6:2015104162)*

**Comment by RomanLangrehr** [comment]
I don't have them:
image

**Comment by acBerger** [comment]
> I don't have them:

I managed to fix it for me. They were not leading nowhere but the associations just took the longest path possible.

So I can fix your multiplicity problem.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/439#-:-K7MlRFhQz67Ml0qFij1:-371002089)*

**Comment by RomanLangrehr** [comment]
That would be great.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/439#-:-K7MmQJh0Obzuelwr76U:1282904671)*

**Comment by RomanLangrehr** [comment]
Thanks @acBerger 
-blocked 

---

Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/439#-:-K7MrYzlDNIew6hds82H:-354584286)*

**Comment by acBerger** [comment]
:lgtm_strong: 

---

Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/439#-:-K7MuyCUSQykdZkmtOMv:-1868698381)*

**Comment by acBerger** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/439)*

**Comment by flyfl** [comment]
Reviewed 2 of 6 files at r1, 2 of 2 files at r3, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/de/uka/ipd/sdq/beagle/core/MeasurementControllerBlackboardView.java, line 67 \[r7\]](https://reviewable.io:443/reviews/beagle-pse/beagle/439#-K7QNry7Rgb3j2d-YAhT:-K7QNry7Rgb3j2d-YAhU:-1980565237) ([raw file](https://github.com/beagle-pse/beagle/blob/a1397804fa424af0a7882dc63c2b9c96da6a5fcb/src/main/java/de/uka/ipd/sdq/beagle/core/MeasurementControllerBlackboardView.java#L67)):*
Could you explain what you are doing here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/439)*

**Comment by flyfl** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/de/uka/ipd/sdq/beagle/core/MeasurementControllerBlackboardView.java, line 82 \[r7\]](https://reviewable.io:443/reviews/beagle-pse/beagle/439#-K7QO5Y3dgGoLBThlePc:-K7QO5Y48o16V4EVvuoy:881105198) ([raw file](https://github.com/beagle-pse/beagle/blob/a1397804fa424af0a7882dc63c2b9c96da6a5fcb/src/main/java/de/uka/ipd/sdq/beagle/core/MeasurementControllerBlackboardView.java#L82)):*
>@param writer The class the desired data was written for. Must not be {@code null}.

Do you return `null` due to get this working as a stub that is later modified?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/439)*

**Comment by RomanLangrehr** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/de/uka/ipd/sdq/beagle/core/MeasurementControllerBlackboardView.java, line 67 \[r7\]](https://reviewable.io:443/reviews/beagle-pse/beagle/439#-K7QNry7Rgb3j2d-YAhT:-K7QshTqIklgE0SjXBKK:680742992) ([raw file](https://github.com/beagle-pse/beagle/blob/a1397804fa424af0a7882dc63c2b9c96da6a5fcb/src/main/java/de/uka/ipd/sdq/beagle/core/MeasurementControllerBlackboardView.java#L67)):*
Give the measurement controller access to store some data on the blackboard.

---

*[src/main/java/de/uka/ipd/sdq/beagle/core/MeasurementControllerBlackboardView.java, line 82 \[r7\]](https://reviewable.io:443/reviews/beagle-pse/beagle/439#-K7QO5Y3dgGoLBThlePc:-K7Qt0sXGlqlaQlUWswI:1109749654) ([raw file](https://github.com/beagle-pse/beagle/blob/a1397804fa424af0a7882dc63c2b9c96da6a5fcb/src/main/java/de/uka/ipd/sdq/beagle/core/MeasurementControllerBlackboardView.java#L82)):*
Yes, that's only because this is a stub.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/439)*

**Comment by flyfl** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/de/uka/ipd/sdq/beagle/core/MeasurementControllerBlackboardView.java, line 67 \[r7\]](https://reviewable.io:443/reviews/beagle-pse/beagle/439#-K7QNry7Rgb3j2d-YAhT:-K7RM4sZQlxsXKFPD5KF:-1820497335) ([raw file](https://github.com/beagle-pse/beagle/blob/a1397804fa424af0a7882dc63c2b9c96da6a5fcb/src/main/java/de/uka/ipd/sdq/beagle/core/MeasurementControllerBlackboardView.java#L67)):*
Okay, that just looks strange to me. Especially, we don't have this in the BeagleCore Diagram yet and we also did not decide to use the BlackboardStore Interface (#434)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/439)*

**Comment by RomanLangrehr** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/de/uka/ipd/sdq/beagle/core/MeasurementControllerBlackboardView.java, line 67 \[r7\]](https://reviewable.io:443/reviews/beagle-pse/beagle/439#-K7QNry7Rgb3j2d-YAhT:-K7RQK3EL_ELiRNDNCgF:-1115983691) ([raw file](https://github.com/beagle-pse/beagle/blob/a1397804fa424af0a7882dc63c2b9c96da6a5fcb/src/main/java/de/uka/ipd/sdq/beagle/core/MeasurementControllerBlackboardView.java#L67)):*
Really?
I think we were just discussing about whether we should mention this in the class diagram or not.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/439)*

**Comment by RomanLangrehr** [comment]
:lgtm_cancel: 
Please review again carefully, I had to resolve lots of conflicts!

---

Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/439#-:-K7Vu_T5UB5d1srwRgm9:1458832113)*

**Comment by acBerger** [comment]
:lgtm_cancel: 

---

Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/439#-:-K7Wk0HwbCgcSW2D-2m8:502544406)*

**Comment by acBerger** [comment]
:lgtm: 

---

Reviewed 2 of 3 files at r9, 4 of 4 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/439#-:-K7XDxvceEOHdsmIdbMu:980077423)*

**Comment by acBerger** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/java/de/uka/ipd/sdq/beagle/analysis/AnalyserBlackboardView.java, line 25 \[r11\]](https://reviewable.io:443/reviews/beagle-pse/beagle/439#-K7XF5udhXqODTJo2PoQ:-K7XF5udhXqODTJo2PoR:-915333885) ([raw file](https://github.com/beagle-pse/beagle/blob/a00e85cce452c8bc553e9b2485053c0f4e98c3c1/src/main/java/de/uka/ipd/sdq/beagle/analysis/AnalyserBlackboardView.java#L25)):*
This does not belong here!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/439)*

**Comment by flyfl** [comment]
Reviewed 2 of 2 files at r11.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/439)*

**Comment by RomanLangrehr** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/de/uka/ipd/sdq/beagle/analysis/AnalyserBlackboardView.java, line 25 \[r11\]](https://reviewable.io:443/reviews/beagle-pse/beagle/439#-K7XF5udhXqODTJo2PoQ:-K7XGqJkTOS867Gh3cvS:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/d5687d1c304417cdd491df20675a6173d9ec7bdc/src/main/java/de/uka/ipd/sdq/beagle/analysis/AnalyserBlackboardView.java#L25)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/439)*

**Comment by acBerger** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r11, 1 of 1 files at r12.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/439#-:-K7XGsiezcUpBfjSnWnL:980077423)*

**Comment by flyfl** [comment]
:lgtm_strong:

**Comment by acBerger** [comment]
:lgtm: 

---

Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/439#-:-K7XIJUozlL1iX3uoibH:980077423)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r13.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/439)*

**Pull request merged**
