### PR TITLE
Pausing & Aborting

### PR DESCRIPTION
**Pull request by jGleitz**
* Fixes the state management in `AnalysisController`
 * Makes the Kieker Measurement Tool respect pause & abort
 * Makes the `BeagleLaunchConfigurationDelegate` fire the terminate event on its launch

Depends on #796

---
This change is [Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/817)

### CODE REVIEW

**Comment by jGleitz** [comment]
Review status: 0 of 25 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-KCkotgqg0Q2PL20wJyq:-KCkotgrJ9oN8F7Naml6:-720528204) (no related file):*
This PR changes a lot of the handling in `AnalysisController` +@m1cm1c , I think you should have a look at it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/817)*

**Comment by acBerger** [comment]
Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/817)*

**Comment by m1cm1c** [comment]
Reviewed 2 of 26 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/AnalysisController.java, line 152 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-KCkr2bHxnM2kWpu8Z4d:-KCkr2bI6HIz2_DP6_x7:1068525231) ([raw file](https://github.com/beagle-pse/beagle/blob/857518aa9caf82ecbf64a3abaf521b74996e8fa0/Core/src/main/java/de/uka/ipd/sdq/beagle/core/AnalysisController.java#L152)):*
This line should be put into the next block.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/817)*

**Comment by m1cm1c** [comment]
Reviewed 7 of 26 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java, line 131 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-KCkrkMCDkYls4mvGaqj:-KCkrkMDQqGAky1yHrh0:216635604) ([raw file](https://github.com/beagle-pse/beagle/blob/79f702e983f406adb8659695088a111a7ee30aec/Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java#L131)):*
Why is this changed?

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java, line 140 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-KCkruAiYknut5AGS1Zm:-KCkruAiYknut5AGS1Zn:216635604) ([raw file](https://github.com/beagle-pse/beagle/blob/79f702e983f406adb8659695088a111a7ee30aec/Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java#L140)):*
Why is this changed?

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java, line 150 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-KCkrveHdBPohN95zjjZ:-KCkrveHdBPohN95zjj_:216635604) ([raw file](https://github.com/beagle-pse/beagle/blob/79f702e983f406adb8659695088a111a7ee30aec/Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java#L150)):*
Why is this changed?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/817)*

**Comment by m1cm1c** [comment]
Reviewed 16 of 26 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/817)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-:-KCktVap6tyltXcw9f0q:1417088721)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/AnalysisController.java, line 152 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-KCkr2bHxnM2kWpu8Z4d:-KCktUxOPkeXQtW1WeTo:1016616751) ([raw file](https://github.com/beagle-pse/beagle/blob/857518aa9caf82ecbf64a3abaf521b74996e8fa0/Core/src/main/java/de/uka/ipd/sdq/beagle/core/AnalysisController.java#L152)):*
No. The next block explicitly handles a state change *during* `#measure`. The state check for `#measure` is done by the loop.

(A state change during `#canMeasure` is not being adressed)

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java, line 131 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-KCkrkMCDkYls4mvGaqj:-KCktO8SfuwS7X8jv4u0:1425619263) ([raw file](https://github.com/beagle-pse/beagle/blob/79f702e983f406adb8659695088a111a7ee30aec/Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java#L131)):*
That’s actually a change from #796 

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java, line 140 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-KCkruAiYknut5AGS1Zm:-KCktSDQBEu9bEJX4ZsY:1425619263) ([raw file](https://github.com/beagle-pse/beagle/blob/79f702e983f406adb8659695088a111a7ee30aec/Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java#L140)):*
That’s actually a change from #796 

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java, line 150 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-KCkrveHdBPohN95zjjZ:-KCktTDkowHfSpvsj0-J:1425619263) ([raw file](https://github.com/beagle-pse/beagle/blob/79f702e983f406adb8659695088a111a7ee30aec/Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java#L150)):*
That’s actually a change from #796 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/817)*

**Comment by m1cm1c** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/AnalysisController.java, line 152 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-KCkr2bHxnM2kWpu8Z4d:-KCkyCBVC-L5W_EkX7ES:1117156611) ([raw file](https://github.com/beagle-pse/beagle/blob/857518aa9caf82ecbf64a3abaf521b74996e8fa0/Core/src/main/java/de/uka/ipd/sdq/beagle/core/AnalysisController.java#L152)):*
But what if the state is `ENDING` before the loop condition is checked?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/817)*

**Comment by m1cm1c** [comment]
Reviewed 1 of 26 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/817)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/AnalysisController.java, line 152 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-KCkr2bHxnM2kWpu8Z4d:-KCkzwuzWCEt09VLYn5g:1602669185) ([raw file](https://github.com/beagle-pse/beagle/blob/857518aa9caf82ecbf64a3abaf521b74996e8fa0/Core/src/main/java/de/uka/ipd/sdq/beagle/core/AnalysisController.java#L152)):*
That is very unlikely, because when the loop condition is checked, we just waited for the state to not be `ENDED`. 

And if this should be the case, the state change literally nanoseconds ago, it’s thus okay to not directly handle it (it will be handled later, though).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/817)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java, line 131 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-KCkrkMCDkYls4mvGaqj:-KCl1MwrRbZdEfs7EGp0:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/79f702e983f406adb8659695088a111a7ee30aec/Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java#L131)):*
Done.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java, line 140 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-KCkruAiYknut5AGS1Zm:-KCl1Ne_0Cs13tvAzF6C:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/79f702e983f406adb8659695088a111a7ee30aec/Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java#L140)):*
Done.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java, line 150 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-KCkrveHdBPohN95zjjZ:-KCl1PAuzsPZXX0xsxDw:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/79f702e983f406adb8659695088a111a7ee30aec/Core/src/main/java/de/uka/ipd/sdq/beagle/core/facade/BeagleController.java#L150)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/817)*

**Comment by m1cm1c** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/AnalysisController.java, line 152 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-KCkr2bHxnM2kWpu8Z4d:-KCl5mKod6Wq5Ix_fNi0:34149355) ([raw file](https://github.com/beagle-pse/beagle/blob/857518aa9caf82ecbf64a3abaf521b74996e8fa0/Core/src/main/java/de/uka/ipd/sdq/beagle/core/AnalysisController.java#L152)):*
So how is this loop stopped if the state changes to `ENDING`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/817)*

**Comment by jGleitz** [comment]
-blocked  because #796 is merged

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-:-KCl7JFBXPfSMOK7VCy6:1766562449)*

**Comment by m1cm1c** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/AnalysisController.java, line 152 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-KCkr2bHxnM2kWpu8Z4d:-KCl7lnUDsf96kytwkE6:-864509007) ([raw file](https://github.com/beagle-pse/beagle/blob/857518aa9caf82ecbf64a3abaf521b74996e8fa0/Core/src/main/java/de/uka/ipd/sdq/beagle/core/AnalysisController.java#L152)):*
Resolved.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/817)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/817)*

**Comment by RomanLangrehr** [comment]
:lgtm: :white_check_mark: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-:-KClB4dB-fDL1LXrZpHt:-1603124213)*

**Comment by m1cm1c** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-KCkotgqg0Q2PL20wJyq:-KClBL2Z0zCPvjxCCyds:-499146009) (no related file):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-:-KClBM24koteC4OR8Ww6:1417088721)*

**Comment by m1cm1c** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/817)*

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-:-KClV4lzEBkDw5p1sNub:1417088721)*

**Comment by RomanLangrehr** [comment]
:lgtm:

---

Reviewed 8 of 26 files at r1, 1 of 1 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-:-KClVTJ894ttc1HYIKZv:1417088721)*

**Comment by RomanLangrehr** [comment]
:white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-:-KClVuOPK1zLlTFr4T9p:1605498549)*

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-:-KClWEdR53Q_g70QoMq0:1417088721)*

**Comment by RomanLangrehr** [comment]
:lgtm: :white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-:-KClYeJpXFVqcG911xt9:-1603124213)*

**Comment by m1cm1c** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/817)*

**Comment by jGleitz** [comment]
Please renew your LGTMs, @acberger fixed a test.

---

Review status: 10 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-:-KCljKGKpGHqw7muxrrA:-601933138)*

**Comment by RomanLangrehr** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-:-KCljh8SqND4COAAOSon:1417088721)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-:-KClk4S-hMzlvcMV_kmm:1417088721)*

**Comment by RomanLangrehr** [comment]
:white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/817#-:-KClklsGrDTGtT1mQ_AL:1605498549)*

**Pull request merged**
