### PR TITLE
Beagle Configuration / GUI null Fix

### PR DESCRIPTION
**Pull request by m1cm1c**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/702)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/702#-:-KARrB0Q1IQD92fJlOqi:980077423)*

**Comment by RomanLangrehr** [comment]
:white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/702#-:-KARyzcN5MQTlyxx5scn:1605498549)*

**Comment by acBerger** [comment]
:lgtm:
:white_check_mark:  (as GUI still does not need to be tested by JUnit Tests)

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/702#-:-KARvon1BX9pxlMbuRxC:-760880988)*

**Comment by m1cm1c** [comment]
Don't merge!

**Comment by m1cm1c** [comment]
:o: Test coverage is not sufficient because BeagleConfiguration still needs 100% coverage. +viridispirus 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/702#-:-KAS26UqBjVqubKbOiZp:370724318)*

**Comment by RomanLangrehr** [comment]
:white_check_mark: This has nothing to do with this PR and should be done in the project-information PR!
(There are many changes to this class) -(tests needed) -virdispirus

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/702#-:-KAS2JEErWCPXrJb2dyl:-1624878483)*

**Comment by m1cm1c** [comment]
Okay, then.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/702#-:-KAS398228CfT31fNeDf:1651209444)*

**Pull request merged**
