### PR TITLE
Beagle views

### PR DESCRIPTION
**Pull request by viridispirus**
Fixes #309 
Fixes #310 
Fixes #311 
Fixes #312

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/351)

### CODE REVIEW

**Comment by viridispirus** [comment]
Please review this PR carefully. I will close the other view PRs still when this one is merged. So you can compare this one to your comments in the other PRs.

**Comment by RomanLangrehr** [comment]
image

Should be *

**Comment by RomanLangrehr** [comment]
image
should have some read methods. Maybe the one from `Read Only Blackboard View`
and some methods to add his results.
By the way: Where do we need the read only view, when each blackboard contributor has it's own view (MeasurmentToolView, ...)

**Comment by RomanLangrehr** [comment]
image
Should be a * each time.

**Comment by RomanLangrehr** [comment]
image

Missing return type.

**Comment by RomanLangrehr** [comment]
image

This should be arguments, and not return typs. And multiplicity should be *

**Comment by RomanLangrehr** [comment]
image

We could specify with an X, that the Blackboard doesn't know it's views (as this would make no sense).

**Comment by RomanLangrehr** [comment]
image

`get SEFF Loop[s] `

**Comment by jGleitz** [comment]
I’ll steal this as @viridispirus is sick. +@jGleitz 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K71X_JnzdENJdD3LqHY:-753310771)*

**Comment by RomanLangrehr** [comment]
No, @viridispirus want's to do this this evening. I talked to him.

**Comment by jGleitz** [comment]
Oh, excellent! +@viridispirus 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K71YV_R_a_Agdfr5Bog:733423765)*

**Comment by RomanLangrehr** [comment]
> By the way: Where do we need the read only view, when each blackboard contributor has it's own view (MeasurmentToolView, ...)

To answer it myself: For the can-do methods!

**Comment by jGleitz** [comment]
@RomanLangrehr:

You’re goddamn right

**Comment by viridispirus** [comment]
I don't know how to model the 'X' in an association link that the blackboard don't know that there is a view.

**Comment by RomanLangrehr** [comment]
> I don't know how to model the 'X' in an association link that the blackboard don't know that there is a view.

I think we can do this later.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K72vZjPN6aqZ7YiJsXX:1595101126)*

**Comment by RomanLangrehr** [comment]
image
Should be *

**Comment by RomanLangrehr** [comment]
The methode `add Analyse Result` should have some arguments. But we don't have the classes for them, so we should do this later, too.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K72xfDGtcrg0Ue2EL_a:366409396)*

**Comment by RomanLangrehr** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351)*

**Comment by jGleitz** [comment]
> The methode add Analyse Result should have some arguments. But we don't have the classes for them, so we should do this later, too.

The same goes for the `set final …` methods on the final view, as they will need the seff branch/seff loop/rdia they belong to.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K72ye4xJnFzHsPh42Uh:244110696)*

**Comment by jGleitz** [comment]
All views should have all methods `Read-Only Blackboard View` has.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K72z1WsIKUAeYWSsIYb:-2127216573)*

**Comment by viridispirus** [comment]
>The same goes for the set final … methods on the final view, as they will need the seff branch/seff loop/rdia they belong to.

Ok, that is strage in my model they are still there. Can you show me your view?

**Comment by jGleitz** [comment]
> Ok, that is strage in my model they are still there.

The methods are there. But they will need an argument specifying the seff branch/seff loop/rdia for which the final result is being reported.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K736eku0Os07I2AK-z9:157092984)*

**Comment by viridispirus** [comment]
Ok, you mean the arguments still missing? But they are there.

**Comment by RomanLangrehr** [comment]
> Ok, you mean the arguments still missing? But they are there

No, they don't have any paramters. But this is not part of you PR.

**Comment by jGleitz** [comment]
>But this is not part of you PR.

Agreed. 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K763s1VWgypiXW5aXoq:-1019855616)*

**Comment by RomanLangrehr** [comment]
> No, they don't have any paramters. But this is not part of you PR.

At least they have some, but not enough.

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K764O3K9_yOIkUolCz5:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K764wmeQyGCcMg4pyzP:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K76DloSsMRpsDC2yuyg:1417088721)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K76EJkRlpZctTOn3b9e:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K76EVf9YkkSQ9NireMR:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K76EneAVstG8pHASIJr:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K76EpACBTR-Hdaq5uyq:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K76EqezL0wDiZ3M1qsx:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K76EsB2aSO87yAtlnN2:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K76EthWpUCOz0iCGGs-:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K76EvDgw0u0T6Y-IdLa:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K76EwikPRF3irInGz9D:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K76EyE1SX8stjbOYHGz:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K76EzkerxQMIPb4ZumR:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K76F0GhUecjgQBW6-EF:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K76F1lb45eCbi4cX-fJ:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K76F3GiBUYstr3_b2Ck:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K76F5oeVnWoXRFlQpP5:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K76F7flfkyWEPzI9hw7:980077423)*

**Comment by RomanLangrehr** [comment]
(Sorry, but I'm so annoyed about the LGTMs, that I had to build a lgtm-writing-script)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K76FDk2H5cWqkYEibT4:-1167425478)*

**Comment by viridispirus** [comment]
ok.

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/351#-:-K76I12BeOcHHj7a2n4l:1417088721)*

**Pull request merged**
