### PR TITLE
Merged & Bugfixed

### PR DESCRIPTION
**Pull request by jGleitz**
This PR is a merge of #731, #735, and #736. It additionally contains 3 minor bugfixes.

More is not required to successfully run Beagle!

I think that’s a great achievement!

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/737)

### CODE REVIEW

**Comment by viridispirus** [comment]
Reviewed 2 of 6 files at r5, 14 of 14 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/737)*

**Comment by acBerger** [comment]
Does not work for me. I get `java.lang.IllegalStateException: Not everything has been setup yet.` .

---

Reviewed 1 of 14 files at r6, 11 of 11 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/737#-:-KAstZ3NY17gK7ciwkKp:990320655)*

**Comment by RomanLangrehr** [comment]
> Does not work for me. I get java.lang.IllegalStateException: Not everything has been setup yet. .

Hm. I fixed this error a few days ago and I think this should be in master...

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/737#-:-KAsw4Xhiv0mSB91W7yG:630678549)*

**Comment by RomanLangrehr** [comment]
Here is the fix: https://reviewable.io/reviews/Beagle-PSE/Beagle/731#-
Does this branch work for you?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/737#-:-KAsw_KR5v5Ryo8nhDDf:801348948)*

**Comment by acBerger** [comment]
Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/737)*

**Comment by viridispirus** [comment]
Reviewed 11 of 11 files at r7, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/737)*

**Comment by acBerger** [comment]
The exception was thrown because no Launch Configuration was found. Creating one fixed it.

**Comment by flyfl** [comment]
:lgtm:

---

Reviewed 2 of 6 files at r5, 13 of 14 files at r6, 11 of 11 files at r7, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/737#-:-KAuNm-GA4jhk9VHaqI0:1417088721)*

**Comment by jGleitz** [comment]
This is now ready for its final review.

**Comment by RomanLangrehr** [comment]
:lgtm: :white_check_mark: 

---

Reviewed 2 of 14 files at r6, 2 of 2 files at r8, 2 of 6 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/737#-:-KAv6Cl65vh1ucKmnEfg:-1603124213)*

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 2 of 14 files at r6, 2 of 6 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/737#-:-KAvDLLcmVf7ZgFCie8x:1417088721)*

**Pull request merged**
