### PR TITLE
Model Session 2015-12-18

### LINKED ISSUE #262: Model Our Design Progress
We need to model our design as far as it’s specified.

Please note that creating a valid, semantically rich model is important, but also difficult and time consuming. It requires careful research.

### PR DESCRIPTION
**Pull request by jGleitz**
The changes we made to the model at yesterday’s meeting.

fixes #262

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
image

Can we make this invisible in the class diagram?

**Comment by jGleitz** [comment]
@RomanLangrehr: yep, good idea. Fixed in 9618ae0

**Comment by RomanLangrehr** [comment]
Lgtm

**Comment by flyfl** [comment]
lgtm

**Pull request merged**
