### PR TITLE
Fix Kieker Overflow

### LINKED ISSUE #805: Kieker: Queue is Full
When analysing PalladioFileShare, Kieker prints these errors:

```
Mär 11, 2016 12:45:27 PM kieker.monitoring.writer.AbstractAsyncWriter newMonitoringRecord
SCHWERWIEGEND: Failed to add new monitoring record to queue. Queue is full. Either increase 'QueueSize' or change 'QueueFullBehavior' for the configured writer.
Mär 11, 2016 12:45:27 PM kieker.monitoring.core.controller.WriterController newMonitoringRecord
SCHWERWIEGEND: Error writing the monitoring data. Will terminate monitoring!
```

### PR DESCRIPTION
**Pull request by jGleitz**
Fixes #805 

Depends on #804

---
This change is [Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/808)

### CODE REVIEW

**Comment by jGleitz** [comment]
-blocked because #804 is merged.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/808#-:-KCgWnJQ5bxJoKk0wkVL:1186458045)*

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r4.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/808#-:-KCgnQZU9_okQ2eZrl99:1417088721)*

**Comment by acBerger** [comment]
:white_check_mark: ?

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/808#-:-KCgnRcQWs_4DU4kznzD:-1769152470)*

**Comment by m1cm1c** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/808)*

**Comment by m1cm1c** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/808#-:-KCgnhqnAsEsr8d1-RN1:1417088721)*

**Pull request merged**
