### PR TITLE
Added meeting minutes 2016-02-12

### PR DESCRIPTION
**Pull request by RomanLangrehr**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/684)

### CODE REVIEW

**Comment by viridispirus** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/684#-:-KAL35ku_AB3bvs6e-KQ:980077423)*

**Comment by m1cm1c** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Documentation/Meeting Minutes/2016-02-12.md, line 2 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/684#-KAL7DNUKhS5T1nxgmOD:-KAL7DNUKhS5T1nxgmOE:395889566) ([raw file](https://github.com/beagle-pse/beagle/blob/003ba206979ea56ac36ba398334de257a353b160/Documentation/Meeting Minutes/2016-02-12.md#L2)):*
case study

---

*[Documentation/Meeting Minutes/2016-02-12.md, line 6 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/684#-KAL7GQ8BAlZAM8AGoV9:-KAL7GQ9AmtWxdRBGC-D:-1223495178) ([raw file](https://github.com/beagle-pse/beagle/blob/003ba206979ea56ac36ba398334de257a353b160/Documentation/Meeting Minutes/2016-02-12.md#L6)):*
tested

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/684)*

**Comment by RomanLangrehr** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[Documentation/Meeting Minutes/2016-02-12.md, line 2 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/684#-KAL7DNUKhS5T1nxgmOD:-KALG3gD9XCwTjtZJ4Ip:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/003ba206979ea56ac36ba398334de257a353b160/Documentation/Meeting Minutes/2016-02-12.md#L2)):*
Done.

---

*[Documentation/Meeting Minutes/2016-02-12.md, line 6 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/684#-KAL7GQ8BAlZAM8AGoV9:-KALG4JDtUBK9VAu5d0s:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/003ba206979ea56ac36ba398334de257a353b160/Documentation/Meeting Minutes/2016-02-12.md#L6)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/684)*

**Comment by m1cm1c** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/684#-:-KALG_wGZBIW_S5HyWCi:1417088721)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/684#-:-KALWCkLRFqimGXw-Q2U:980077423)*

**Pull request merged**
