### PR TITLE
Ip#120 measurement results

### LINKED ISSUE #557: Write Javadoc for `ParameterChangeMeasurementResult`

### LINKED ISSUE #609: [IP #120] Implement Measurement Results
Implement ParameterisationDependentMeasurementResult and all
of its subclasses. (Package “Measurement”)

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Fixes #609 
Fixes #557 

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/647)

### CODE REVIEW

**Comment by acBerger** [comment]
Reviewed 1 of 5 files at r2, 1 of 10 files at r4, 4 of 4 files at r5.
Review status: 6 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/647)*

**Comment by jGleitz** [comment]
Reviewed 1 of 5 files at r2, 4 of 4 files at r5, 1 of 2 files at r6, 1 of 1 files at r7, 3 of 3 files at r8, 1 of 2 files at r10.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/measurement/BranchDecisionMeasurementResult.java, line 61 \[r10\]](https://reviewable.io:443/reviews/beagle-pse/beagle/647#-K9HFym6W158oA_YaTdL:-K9HFym7G3HTBlTjxM07:-1419307859) ([raw file](https://github.com/beagle-pse/beagle/blob/b7f3945294464cccc5dcb0dd3100cef3008d3070/Core/src/main/java/de/uka/ipd/sdq/beagle/core/measurement/BranchDecisionMeasurementResult.java#L61)):*
shouldn’t this include a call to `appendSuper`?

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/measurement/LoopRepetitionCountMeasurementResult.java, line 54 \[r10\]](https://reviewable.io:443/reviews/beagle-pse/beagle/647#-K9HG_NNyB3fZdJ6V5Wn:-K9HG_NNyB3fZdJ6V5Wo:-1419307859) ([raw file](https://github.com/beagle-pse/beagle/blob/b7f3945294464cccc5dcb0dd3100cef3008d3070/Core/src/main/java/de/uka/ipd/sdq/beagle/core/measurement/LoopRepetitionCountMeasurementResult.java#L54)):*
shouldn’t this include a call to `appendSuper`?

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/measurement/ResourceDemandMeasurementResult.java, line 68 \[r10\]](https://reviewable.io:443/reviews/beagle-pse/beagle/647#-K9HGtUo3g_2BsyOU1Ev:-K9HGtUo3g_2BsyOU1Ew:-1419307859) ([raw file](https://github.com/beagle-pse/beagle/blob/b7f3945294464cccc5dcb0dd3100cef3008d3070/Core/src/main/java/de/uka/ipd/sdq/beagle/core/measurement/ResourceDemandMeasurementResult.java#L68)):*
shouldn’t this include a call to `appendSuper`?

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/measurement/BranchDecisionMeasurementResultTest.java, line 56 \[r10\]](https://reviewable.io:443/reviews/beagle-pse/beagle/647#-K9HHHqU4j4JSFzAxpo8:-K9HHHqU4j4JSFzAxpo9:1723264688) ([raw file](https://github.com/beagle-pse/beagle/blob/b7f3945294464cccc5dcb0dd3100cef3008d3070/Core/src/test/java/de/uka/ipd/sdq/beagle/core/measurement/BranchDecisionMeasurementResultTest.java#L56)):*
This calls the wrong constructor

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/measurement/BranchDecisionMeasurementResultTest.java, line 58 \[r10\]](https://reviewable.io:443/reviews/beagle-pse/beagle/647#-K9HHLDoD3n6y5yeg6qi:-K9HHLDoD3n6y5yeg6qj:1881597822) ([raw file](https://github.com/beagle-pse/beagle/blob/b7f3945294464cccc5dcb0dd3100cef3008d3070/Core/src/test/java/de/uka/ipd/sdq/beagle/core/measurement/BranchDecisionMeasurementResultTest.java#L58)):*
This calls the wrong constructor.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/measurement/BranchDecisionMeasurementResultTest.java, line 93 \[r10\]](https://reviewable.io:443/reviews/beagle-pse/beagle/647#-K9HH_8u-VXidR5H2l7h:-K9HH_8vTO3i4w1Is8Nr:1320698790) ([raw file](https://github.com/beagle-pse/beagle/blob/b7f3945294464cccc5dcb0dd3100cef3008d3070/Core/src/test/java/de/uka/ipd/sdq/beagle/core/measurement/BranchDecisionMeasurementResultTest.java#L93)):*
In Java, primitives are passed by value. So changing the index afterwards is not possible. These tests thus serve no purpose and should be removed

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/measurement/LoopRepetitionCountMeasurementResultTest.java, line 57 \[r10\]](https://reviewable.io:443/reviews/beagle-pse/beagle/647#-K9HIY8S4WFLIz96lT8I:-K9HIY8S4WFLIz96lT8J:1723264688) ([raw file](https://github.com/beagle-pse/beagle/blob/b7f3945294464cccc5dcb0dd3100cef3008d3070/Core/src/test/java/de/uka/ipd/sdq/beagle/core/measurement/LoopRepetitionCountMeasurementResultTest.java#L57)):*
This calls the wrong constructor

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/measurement/LoopRepetitionCountMeasurementResultTest.java, line 59 \[r10\]](https://reviewable.io:443/reviews/beagle-pse/beagle/647#-K9HIRnViIvGBzV98sip:-K9HIRnWCHumzD4P02ly:1723264688) ([raw file](https://github.com/beagle-pse/beagle/blob/b7f3945294464cccc5dcb0dd3100cef3008d3070/Core/src/test/java/de/uka/ipd/sdq/beagle/core/measurement/LoopRepetitionCountMeasurementResultTest.java#L59)):*
This calls the wrong constructor

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/measurement/LoopRepetitionCountMeasurementResultTest.java, line 94 \[r10\]](https://reviewable.io:443/reviews/beagle-pse/beagle/647#-K9HHvLWglKBuR6ZuI--:-K9HHvLWglKBuR6ZuI-0:1320698790) ([raw file](https://github.com/beagle-pse/beagle/blob/b7f3945294464cccc5dcb0dd3100cef3008d3070/Core/src/test/java/de/uka/ipd/sdq/beagle/core/measurement/LoopRepetitionCountMeasurementResultTest.java#L94)):*
In Java, primitives are passed by value. So changing the index afterwards is not possible. These tests thus serve no purpose and should be removed

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/measurement/ResourceDemandMeasurementResultTest.java, line 92 \[r10\]](https://reviewable.io:443/reviews/beagle-pse/beagle/647#-K9HHyT3W4g5uHIIB5Ke:-K9HHyT3W4g5uHIIB5Kf:1320698790) ([raw file](https://github.com/beagle-pse/beagle/blob/b7f3945294464cccc5dcb0dd3100cef3008d3070/Core/src/test/java/de/uka/ipd/sdq/beagle/core/measurement/ResourceDemandMeasurementResultTest.java#L92)):*
In Java, primitives are passed by value. So changing the index afterwards is not possible. These tests thus serve no purpose and should be removed

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/647)*

**Comment by acBerger** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/measurement/BranchDecisionMeasurementResultTest.java, line 56 \[r10\]](https://reviewable.io:443/reviews/beagle-pse/beagle/647#-K9HHHqU4j4JSFzAxpo8:-K9O6_Bfik_TKCOal2mO:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/b7f3945294464cccc5dcb0dd3100cef3008d3070/Core/src/test/java/de/uka/ipd/sdq/beagle/core/measurement/BranchDecisionMeasurementResultTest.java#L56)):*
Done.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/measurement/BranchDecisionMeasurementResultTest.java, line 58 \[r10\]](https://reviewable.io:443/reviews/beagle-pse/beagle/647#-K9HHLDoD3n6y5yeg6qi:-K9O6aNPmCgdlUd7Ltx4:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/b7f3945294464cccc5dcb0dd3100cef3008d3070/Core/src/test/java/de/uka/ipd/sdq/beagle/core/measurement/BranchDecisionMeasurementResultTest.java#L58)):*
Done.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/measurement/BranchDecisionMeasurementResultTest.java, line 93 \[r10\]](https://reviewable.io:443/reviews/beagle-pse/beagle/647#-K9HH_8u-VXidR5H2l7h:-K9O6dE37iEdqF808Ak7:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/b7f3945294464cccc5dcb0dd3100cef3008d3070/Core/src/test/java/de/uka/ipd/sdq/beagle/core/measurement/BranchDecisionMeasurementResultTest.java#L93)):*
Done.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/measurement/LoopRepetitionCountMeasurementResultTest.java, line 57 \[r10\]](https://reviewable.io:443/reviews/beagle-pse/beagle/647#-K9HIY8S4WFLIz96lT8I:-K9O7-cuKIPTYPZKShYa:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/b7f3945294464cccc5dcb0dd3100cef3008d3070/Core/src/test/java/de/uka/ipd/sdq/beagle/core/measurement/LoopRepetitionCountMeasurementResultTest.java#L57)):*
Done.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/measurement/LoopRepetitionCountMeasurementResultTest.java, line 59 \[r10\]](https://reviewable.io:443/reviews/beagle-pse/beagle/647#-K9HIRnViIvGBzV98sip:-K9O70JofUjsVYuJKEpY:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/b7f3945294464cccc5dcb0dd3100cef3008d3070/Core/src/test/java/de/uka/ipd/sdq/beagle/core/measurement/LoopRepetitionCountMeasurementResultTest.java#L59)):*
Done.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/measurement/LoopRepetitionCountMeasurementResultTest.java, line 94 \[r10\]](https://reviewable.io:443/reviews/beagle-pse/beagle/647#-K9HHvLWglKBuR6ZuI--:-K9O762Rly9IafBs3Mw0:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/b7f3945294464cccc5dcb0dd3100cef3008d3070/Core/src/test/java/de/uka/ipd/sdq/beagle/core/measurement/LoopRepetitionCountMeasurementResultTest.java#L94)):*
Done.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/measurement/ResourceDemandMeasurementResultTest.java, line 92 \[r10\]](https://reviewable.io:443/reviews/beagle-pse/beagle/647#-K9HHyT3W4g5uHIIB5Ke:-K9O7CBSKDdOxT3es5Lz:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/b7f3945294464cccc5dcb0dd3100cef3008d3070/Core/src/test/java/de/uka/ipd/sdq/beagle/core/measurement/ResourceDemandMeasurementResultTest.java#L92)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/647)*

**Comment by jGleitz** [comment]
Reviewed 3 of 3 files at r11.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/647)*

**Comment by RomanLangrehr** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/measurement/BranchDecisionMeasurementResult.java, line 61 \[r10\]](https://reviewable.io:443/reviews/beagle-pse/beagle/647#-K9HFym6W158oA_YaTdL:-K9OLKEW33GC49PMjW7M:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/b7f3945294464cccc5dcb0dd3100cef3008d3070/Core/src/main/java/de/uka/ipd/sdq/beagle/core/measurement/BranchDecisionMeasurementResult.java#L61)):*
Done.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/measurement/LoopRepetitionCountMeasurementResult.java, line 54 \[r10\]](https://reviewable.io:443/reviews/beagle-pse/beagle/647#-K9HG_NNyB3fZdJ6V5Wn:-K9OLMLLCxl7-gzvqkyU:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/b7f3945294464cccc5dcb0dd3100cef3008d3070/Core/src/main/java/de/uka/ipd/sdq/beagle/core/measurement/LoopRepetitionCountMeasurementResult.java#L54)):*
Done.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/measurement/ResourceDemandMeasurementResult.java, line 68 \[r10\]](https://reviewable.io:443/reviews/beagle-pse/beagle/647#-K9HGtUo3g_2BsyOU1Ev:-K9OLNI-z7V883EQulZ3:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/b7f3945294464cccc5dcb0dd3100cef3008d3070/Core/src/main/java/de/uka/ipd/sdq/beagle/core/measurement/ResourceDemandMeasurementResult.java#L68)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/647)*

**Comment by jGleitz** [comment]
Reviewed 3 of 3 files at r12.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/647)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/647#-:-K9ORAzMp_156GEYtUsq:980077423)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Reviewed 3 of 3 files at r14.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/647#-:-K9T7b3dpcadOelYzsY0:980077423)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Reviewed 4 of 4 files at r15.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/647#-:-K9lDtRbnEslWu0x9JPK:980077423)*

**Comment by viridispirus** [comment]
Reviewed 1 of 3 files at r12.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/647)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r7, 3 of 3 files at r12, 1 of 3 files at r14.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/647)*

**Comment by viridispirus** [comment]
Reviewed 1 of 5 files at r2, 1 of 4 files at r5, 1 of 1 files at r7, 2 of 3 files at r12, 1 of 3 files at r14, 4 of 4 files at r15.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/647)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/647#-:-K9rvOta9Dg0t2NajMHS:980077423)*

**Comment by jGleitz** [comment]
:lgtm: -@viridispirus 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/647#-:-K9s82TwU_Qkgi-lUpi7:-949922805)*

**Pull request merged**
