### PR TITLE
Enable joining lines with Formatter as not doing it was wrong

### PR DESCRIPTION
**Pull request by acBerger**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/420)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
The adapted, exorted .xml file is missing in this PR.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/420#-:-K783AvFRbViOO8mSdRZ:-861824442)*

**Comment by jGleitz** [comment]
:lgtm_strong: 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/420#-:-K785e0Ck3idYK3SzpJ3:-1868698381)*

**Comment by jGleitz** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/420)*

**Comment by RomanLangrehr** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/420#-:-K785sP8Ea1ULL7hFw8q:-1868698381)*

**Pull request merged**
