### PR TITLE
Fix Checkstyle for Do-While

### PR DESCRIPTION
**Pull request by jGleitz**
It had that strange brace and block behaviour we already observed for catch and the like.

Don’t get confused that the property completely disappeared. We seem to match the default configuration now, that’s why it was removed.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/690)

### CODE REVIEW

**Comment by m1cm1c** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/690#-:-KALtndZWyQheAq2LD3b:980077423)*

**Comment by m1cm1c** [comment]
This branch is out-of-date with the base branch.

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/690#-:-KAM-G6wyGqePIVyXbd_:980077423)*

**Comment by acBerger** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/690)*

**Comment by m1cm1c** [comment]
:lgtm:

@RomanLangrehr Your "lgtm" has gone stale.

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/690#-:-KAMW-iWI8xVfFzV3cO2:980077423)*

**Pull request merged**
