### PR TITLE
Read-Only Blackboard View

### PR DESCRIPTION
**Pull request by viridispirus**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/310)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
The return values multiplicity should be *, not 1..*

**Comment by RomanLangrehr** [comment]
Lgtm

**Comment by RomanLangrehr** [comment]
Depends on #309

**Comment by jGleitz** [comment]
From my point of view, these are missing:

 * `get all RDIAs()`
 * `get all SEFF Branches()`
 * `get all SEFF Loops()`

there are more missing for proprerties that are not modelled right now because of #263.

**Comment by jGleitz** [comment]
<pre>get SEFF Loop<b>[]</b>s to be measured()</pre>

**Comment by jGleitz** [comment]
Please be careful when merging this. It contains elements affected by #309 which should not be overridden.

**Comment by m1cm1c** [comment]
not mergeable

**Pull request closed without merging**
