### PR TITLE
Gui Prototype

### PR DESCRIPTION
**Pull request by m1cm1c**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/633)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
:lgtm:

**Comment by jGleitz** [comment]
Reviewed 6 of 25 files at r3, 14 of 18 files at r4.
Review status: 16 of 17 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/633)*

**Comment by jGleitz** [comment]
Reviewed 1 of 18 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/633)*

**Comment by jGleitz** [comment]
:lgtm:

**Comment by jGleitz** [comment]
Test comment.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/633#-:-K8jk7AVb-WfK3H0a13_:-543381384)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Reviewed 9 of 9 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/633#-:-K8k2xEnSAjmpTlEJe73:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 6 of 25 files at r3, 15 of 18 files at r4, 9 of 9 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/633#-:-K8jiO7N6nWLqtt7KFw0:980077423)*

**Pull request merged**
