### PR TITLE
Missing classes and doc

### PR DESCRIPTION
**Pull request by jGleitz**
It took me that long because the base lacked *essential* classes. This is still in no condition to be handed in because nothing is really documented and there are major disparities to the design document. I will continue to work through the night.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/564)

### CODE REVIEW

**Comment by acBerger** [comment]
[Web] (jgleitz.github.io/Beagle/branches/missing-classes-and-doc/)

---

Review status: 0 of 35 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/564#-:-K7hcDc-QzcTXOFqINVx:803818568)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 37 of 42 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/564#-:-K7hce5oVizWbFGcVIas:980077423)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/564#-:-K7heC7LeTd09xiJKRxG:1417088721)*

**Comment by RomanLangrehr** [comment]
:lgtm:

**Comment by acBerger** [comment]
:lgtm:

---

Review status: 34 of 36 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/564#-:-K7hiopqLk4XcoFi0VPj:1417088721)*

**Pull request merged**
