### PR TITLE
Separation of Mandatory and Optional Criteria

### PR DESCRIPTION
**Pull request by m1cm1c**
Please comment one these (or more) points:
* Should the vertical tabs be removed? I left them in for now but I think we don't need them.
* Should "Wunschkriterien" be translated to "optional criteria" or "desired criteria"?
* Should chapter 7 be divided into sections or subsections?
* As it turned out, dividing the chapters isn't trivial. Is the current naming okay?

The worry that subsections would be indented turned out to be unfounded.

### CODE REVIEW

**Comment by m1cm1c** [comment]
View the rendered file [as pdf](https://github.com/m1cm1c/Beagle/raw/gh-pages/branches/separate-mandatory-optional/Requirements%20Specification.pdf) or [as graphic](https://github.com/m1cm1c/Beagle/blob/gh-pages/branches/separate-mandatory-optional/Requirements%20Specification.pdf).

**Comment by jGleitz** [comment]
As discussed in yesterday’s meeting, we want to use unnumbered paragraphs for the separation, to keep the negative impact as small as possible.

**Comment by acBerger** [comment]
correct [PDF] (http://m1cm1c.github.io/Beagle/branches/separate-mandatory-optional/Requirements%20Specification.pdf)

**Comment by acBerger** [comment]
Unnecessary as #177 already fixes this.

**Pull request closed without merging**
