### PR TITLE
Instrumentation and Measurement through Kieker

### PR DESCRIPTION
**Pull request by jGleitz**
This code is capable of automatically instrumenting the measured project’s source code and executing it. It produces Kieker measurement results. It not yet transforms these results into our Measurement Events

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/713)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
Reviewed 4 of 46 files at r1, 2 of 4 files at r3.
Review status: 6 of 48 files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/EclipseLaunchConfigurationLaunchConfiguration.java, line 89 \[r5\]](https://reviewable.io:443/reviews/beagle-pse/beagle/713#-KAXZBMUy1hBXDIrn34I:-KAXZBMVGrAPETKSg9TY:-494740995) ([raw file](https://github.com/beagle-pse/beagle/blob/c0f213f73a1e944b90e6daabb749fe01014acde2/Core/src/main/java/de/uka/ipd/sdq/beagle/core/EclipseLaunchConfigurationLaunchConfiguration.java#L89)):*
Why is this only one entry? 
(No addAll() )

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/713)*

**Comment by acBerger** [comment]
Reviewed 40 of 46 files at r1, 1 of 2 files at r2, 4 of 4 files at r3, 1 of 1 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/resources/META-INF/MANIFEST.MF, line 15 \[r5\]](https://reviewable.io:443/reviews/beagle-pse/beagle/713#-KAXZhD0epdFs1cyvKKc:-KAXZhD0epdFs1cyvKKd:1036351842) ([raw file](https://github.com/beagle-pse/beagle/blob/c0f213f73a1e944b90e6daabb749fe01014acde2/Core/src/main/resources/META-INF/MANIFEST.MF#L15)):*
I do not think there is a need for having `org.eclipse.ui`twice here

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/713)*

**Comment by RomanLangrehr** [comment]
Reviewed 19 of 46 files at r1, 1 of 2 files at r2, 2 of 4 files at r3, 1 of 1 files at r4.
Review status: 47 of 48 files reviewed at latest revision, 3 unresolved discussions.

---

*[Kieker Measurement Tool/src/main/java/de/uka/ipd/sdq/beagle/measurement/kieker/EclipseCompiler.java, line 43 \[r5\]](https://reviewable.io:443/reviews/beagle-pse/beagle/713#-KAXaiVhj3IBNF_EbgLZ:-KAXaiVhj3IBNF_EbgL_:1341275295) ([raw file](https://github.com/beagle-pse/beagle/blob/c0f213f73a1e944b90e6daabb749fe01014acde2/Kieker Measurement Tool/src/main/java/de/uka/ipd/sdq/beagle/measurement/kieker/EclipseCompiler.java#L43)):*
Does this need to be initialized here?

Looks strange...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/713)*

**Comment by jGleitz** [comment]
Review status: 47 of 48 files reviewed at latest revision, 3 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/EclipseLaunchConfigurationLaunchConfiguration.java, line 89 \[r5\]](https://reviewable.io:443/reviews/beagle-pse/beagle/713#-KAXZBMUy1hBXDIrn34I:-KAXamcRGAajMLzTzm2r:1473489706) ([raw file](https://github.com/beagle-pse/beagle/blob/c0f213f73a1e944b90e6daabb749fe01014acde2/Core/src/main/java/de/uka/ipd/sdq/beagle/core/EclipseLaunchConfigurationLaunchConfiguration.java#L89)):*
I guess it’s a composite entry.

---

*[Core/src/main/resources/META-INF/MANIFEST.MF, line 15 \[r5\]](https://reviewable.io:443/reviews/beagle-pse/beagle/713#-KAXZhD0epdFs1cyvKKc:-KAXaqXtfsfGjKeFndkG:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/c0f213f73a1e944b90e6daabb749fe01014acde2/Core/src/main/resources/META-INF/MANIFEST.MF#L15)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/713)*

**Comment by jGleitz** [comment]
Review status: 47 of 48 files reviewed at latest revision, 2 unresolved discussions.

---

*[Kieker Measurement Tool/src/main/java/de/uka/ipd/sdq/beagle/measurement/kieker/EclipseCompiler.java, line 43 \[r5\]](https://reviewable.io:443/reviews/beagle-pse/beagle/713#-KAXaiVhj3IBNF_EbgLZ:-KAXbHYa-qBhvBu1JIO7:-1512983291) ([raw file](https://github.com/beagle-pse/beagle/blob/c0f213f73a1e944b90e6daabb749fe01014acde2/Kieker Measurement Tool/src/main/java/de/uka/ipd/sdq/beagle/measurement/kieker/EclipseCompiler.java#L43)):*
If the client doesn’t configure a target folder, it would put the class files the source files, which usually is a huge mess. So if no target folder was set, the compiler will not generate any output. This value causes the compiler not to generate any output. 

This behaviour is documented.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/713)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/713)*

**Comment by RomanLangrehr** [comment]
Reviewed 17 of 46 files at r1, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/713)*

**Comment by RomanLangrehr** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Kieker Measurement Tool/src/main/java/de/uka/ipd/sdq/beagle/measurement/kieker/EclipseCompiler.java, line 43 \[r5\]](https://reviewable.io:443/reviews/beagle-pse/beagle/713#-KAXaiVhj3IBNF_EbgLZ:-KAXf3ptuGng9NbilzcH:-844119231) ([raw file](https://github.com/beagle-pse/beagle/blob/c0f213f73a1e944b90e6daabb749fe01014acde2/Kieker Measurement Tool/src/main/java/de/uka/ipd/sdq/beagle/measurement/kieker/EclipseCompiler.java#L43)):*
> This behaviour is documented.

The behaviour is documented. But it is pretty unlclear, *how* this behaviour is achived. There should be a comment (no Javadoc)  describing this.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/713)*

**Comment by RomanLangrehr** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/713)*

**Comment by jGleitz** [comment]
Review status: 47 of 48 files reviewed at latest revision, 1 unresolved discussion.

---

*[Kieker Measurement Tool/src/main/java/de/uka/ipd/sdq/beagle/measurement/kieker/EclipseCompiler.java, line 43 \[r5\]](https://reviewable.io:443/reviews/beagle-pse/beagle/713#-KAXaiVhj3IBNF_EbgLZ:-KAXg7fwpZU8H4iZEwuf:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/c0f213f73a1e944b90e6daabb749fe01014acde2/Kieker Measurement Tool/src/main/java/de/uka/ipd/sdq/beagle/measurement/kieker/EclipseCompiler.java#L43)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/713)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/713#-:-KAXgH2SpFBHc69J9pFh:980077423)*

**Comment by acBerger** [comment]
:lgtm: :white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/713#-:-KAXgKec7H9SHX9zXj5z:-1603124213)*

**Pull request merged**
