### PR TITLE
Papyrus last fixes

### PR DESCRIPTION
**Pull request by RomanLangrehr**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/473)

### CODE REVIEW

**Comment by flyfl** [comment]
:lgtm:

**Comment by jGleitz** [comment]
:lgtm:

**Comment by jGleitz** [comment]
:lgtm: 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/473#-:-K7XThoDqTfiSLVjAijx:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm_strong: 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/473#-:-K7XU3Q8FyhE9DdhzNDa:-1868698381)*

**Pull request merged**
