### PR TITLE
Fix Image Heights to Make the SRS Render Without UML PDFs

### LINKED ISSUE #377: Render the SRS if the UML PDFs are Missing
render-without-pdf

This will be needed for the Design Document, too.

### PR DESCRIPTION
**Pull request by jGleitz**
fixes #377 

I set the height to the page’s height. This is a natural limitation anyway ;)

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/384)

### CODE REVIEW

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/384#-:-K75Z6LjE0QTa8LdysYJ:1417088721)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/384#-:-K75k9hcvRK0j1V5y31-:980077423)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/384#-:-K75n3lxpEucKZwlUJWn:1417088721)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/384#-:-K75nLZaBO1lO7ZM2taC:980077423)*

**Comment by RomanLangrehr** [comment]
As the first one doesn't seem to work: :lgtm: :lgtm: :lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/384#-:-K75vD1STtRIDPyn_GNw:-1426642498)*

**Comment by jGleitz** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/384)*

**Comment by jGleitz** [comment]
I think it's @acBerger's lgtm that was not counted. 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/384#-:-K763AqZQcAflzfMNLZS:375586595)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/384#-:-K763b11A8BPq3PLXsWr:1417088721)*

**Pull request merged**
