### PR TITLE
Testing

### LINKED ISSUE #163: Test Cases Improvement
### Integrationtest
How is it possible to decide weather the test is correct? This is not trivial as comparative values are needed. Possibility: Compare "real" measurement results with Palladio to detect differences.

- /T20/ is partly an integration test

Define easy tests

- /T50/, /T60/ optional
- /T60/ has to be completed
- /T70/ What is about unreachable code in checked software?

- /OT20/ more detailed. What is "invalid input"? E.g. sourcecode decoarter which does not fit to the code  (very optional ;) )

### PR DESCRIPTION
**Pull request by acBerger**
I tried to add test cases for all requirements. Please go through the ones I created and check if you understand what is meant and how it works.

There are still some requirements which do not have test cases yet. Mostly because I couldn't think about ones. I am trying to list all of them below: OF10 to OF50, OF120, OF 170, F210, F250, OF200, Q100, Q110, OQ30 and OQ40.
If you have ideas for these (or as well for others) please tell me so I can improve this chapter.

fixes #163  and #87

### CODE REVIEW

**Comment by acBerger** [comment]
[PDF] (http://acberger.github.io/Beagle/branches/Testing/Requirements%20Specification.pdf)

**Comment by viridispirus** [comment]
So far so good.
lgtm.

**Comment by acBerger** [comment]
> So far so good.

What should that mean? As we have to be finished tomorrow, and want to be finished as soon as possible, I don't think there should be differentiations anymore.

**Comment by m1cm1c** [comment]
lgtm

**Comment by viridispirus** [comment]
@acBerger I meant very well.

**Pull request merged**
