### PR TITLE
Title Fix

### PR DESCRIPTION
**Pull request by m1cm1c**
Depends on #512.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/519)

### CODE REVIEW

**Comment by jGleitz** [comment]
[Website](http://m1cm1c.github.io/Beagle/branches/title-fix/)

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/519#-:-K7eYb5KmBVIsNc9sjq8:-2123701890)*

**Comment by acBerger** [comment]
As the title for the Glossary is displayed wrong (Probably I forgot to change it in the meta  data): could you adapt that too?

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/519#-:-K7elkJFKQbt2X4rGCdJ:1480280907)*

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/519#-:-K7fD8rGECn7_KEp1Xfu:1417088721)*

**Comment by m1cm1c** [comment]
It's "Glossary and Acronyms". That's correct.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/519#-:-K7fDU6VWG_ejJwbIp0-:-361175622)*

**Comment by acBerger** [comment]
That's what I thought but:

If it is right, I cannot expain why this is happening.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/519#-:-K7fEIC_oumBt279VhBd:2132710730)*

**Comment by m1cm1c** [comment]
Neither can I. But it definitely shows me the correct title (I tried Okular and Evince).

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/519#-:-K7fG41rsRGnyZz0OVOS:-657389486)*

**Comment by flyfl** [comment]
:lgtm:

**Comment by acBerger** [comment]
Okay. Then this probably is a bug only for me. However, we cannot fix it.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/519#-:-K7fGTCLaGhw1WtBVFg7:-1085670574)*

**Comment by m1cm1c** [comment]
Does this happen if you download what Travis rendered? https://github.com/m1cm1c/Beagle/raw/gh-pages/branches/title-fix/javadoc/Glossary.pdf

**Comment by acBerger** [comment]
No then it is correct.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/519#-:-K7fGrw3rRFTNSSN6nKL:-583499090)*

**Pull request merged**
