### PR TITLE
Added content to 1.2

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Added Nice to Have Criteria (1.2) in Chapter 1 (Purpose).

### CODE REVIEW

**Comment by jGleitz** [comment]
Your diff is broken, it shows everything as deleted and re-added. This is unfortunate.

You might have an issue with line endings.

**Comment by RomanLangrehr** [comment]
Fixed this.

**Comment by jGleitz** [comment]
thanks. 

lgtm



[LGTM](http://lgtm.in/i/uxJlCtASp)

[:+1:](http://lgtm.in/u/uxJlCtASp) [:-1:](http://lgtm.in/r/uxJlCtASp)

**Comment by jGleitz** [comment]
Please includes @flyfl’s spelling changes

**Pull request merged**
