### PR TITLE
Chapter `Component Beagle GUI`

### PR DESCRIPTION
**Pull request by m1cm1c**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/506)

### CODE REVIEW

**Comment by acBerger** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[Documentation/src/design/lyx/Parts/Component Beagle GUI.lyx, line 163 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/506#-K7cG-NMSN6OI7rwGwKO:-K7cG-NMSN6OI7rwGwKP:-1859158464) ([raw file](https://github.com/beagle-pse/beagle/blob/db5fe75c3467a09d2d2d407ff245ba0bbe81f4ad/Documentation/src/design/lyx/Parts/Component Beagle GUI.lyx#L163)):*
please use \gls for GUI

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/506)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/506)*

**Comment by m1cm1c** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[Documentation/src/design/lyx/Parts/Component Beagle GUI.lyx, line 163 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/506#-K7cG-NMSN6OI7rwGwKO:-K7cJjtPrJ7NB5w4KoWe:677588487) ([raw file](https://github.com/beagle-pse/beagle/blob/81226b92754bf7f5f673c79cc00303505f759455/Documentation/src/design/lyx/Parts/Component Beagle GUI.lyx#L163)):*
done

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/506)*

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/506#-:-K7cLH1F5hadzKn5HRDT:1417088721)*

**Comment by RomanLangrehr** [comment]
[Website](http://m1cm1c.github.io/Beagle/branches/gui-document/)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Documentation/src/design/lyx/Parts/Component Beagle GUI.lyx, line 228 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/506#-K7cQXktD-E0n11n9HYB:-K7cQXktD-E0n11n9HYC:443614747) ([raw file](https://github.com/beagle-pse/beagle/blob/a6b834ac30b8c38d496bc961e3a58b3d23f055f5/Documentation/src/design/lyx/Parts/Component Beagle GUI.lyx#L228)):*
This witch does not belong here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/506#-:-K7cPf5eXe0_LXi-M05Q:-1432033021)*

**Comment by flyfl** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/506#-:-K7cSqDuVJ3Y_KGHrgKl:1417088721)*

**Comment by m1cm1c** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[Documentation/src/design/lyx/Parts/Component Beagle GUI.lyx, line 228 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/506#-K7cQXktD-E0n11n9HYB:-K7cYvdx2iQz7WRcXU3S:428260625) ([raw file](https://github.com/beagle-pse/beagle/blob/47b5297827758cd4e1ce68dda3fbf534a6b3ac57/Documentation/src/design/lyx/Parts/Component Beagle GUI.lyx#L228)):*
I burned it on the stake. Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/506)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/506#-:-K7cZRvRbbBRjGBTx6p2:980077423)*

**Comment by RomanLangrehr** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/506)*

**Comment by flyfl** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/506)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/506#-:-K7c_WgYr60F7rtZkG4k:1417088721)*

**Pull request merged**
