### PR TITLE
Ip090 extension points

### LINKED ISSUE #576: [IP #090] Integrate prototype for Eclipse Extension Points
Integrate the prototype for Eclipse Extension Points into Beagle.

Depends on: IP#020

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Fixes #576

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/663)

### CODE REVIEW

**Comment by jGleitz** [comment]
Reviewed 2 of 41 files at r1, 14 of 45 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-K9rl-uKFnDjxS4F0OYW:-K9rl-uKFnDjxS4F0OYX:-497295461) (no related file):*
Missing in `MeasurementTool`: “Because measurement tools are loaded through extension points, they need a public zero argument constructor”

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/MeasurementResultAnalyser.java, line 25 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-K9rkaxjh-CzF4ATNUAd:-K9rkaxjh-CzF4ATNUAe:1163569420) ([raw file](https://github.com/beagle-pse/beagle/blob/1038f838b469f37e0c36f999b3ad5be436ab3c0e/Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/MeasurementResultAnalyser.java#L25)):*
“Because measurement result analysers are loaded through extension points, they need a public zero argument constructor”

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/MeasurementResultAnalyserContributionsHandler.java, line 53 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-K9rloUmLwvA64d-TXC6:-K9rloUmLwvA64d-TXC7:729415966) ([raw file](https://github.com/beagle-pse/beagle/blob/1038f838b469f37e0c36f999b3ad5be436ab3c0e/Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/MeasurementResultAnalyserContributionsHandler.java#L53)):*
If an instance of a**[ny]** measurement result analyser could not
be created for any reason, e.g. **[because]** the measurement result analyser **[has]** no
public zero argument constructor or **[because]** a**[]**
`{@code MeasurmentResultAnalyserClass}` provided via the extension point
**[is]** not implementing `{@link MeasurementResultAnalyser}`.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/ProposedExpressionAnalyser.java, line 19 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-K9rknMx1iijai6uzWy7:-K9rknMx1iijai6uzWy8:-1918891619) ([raw file](https://github.com/beagle-pse/beagle/blob/1038f838b469f37e0c36f999b3ad5be436ab3c0e/Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/ProposedExpressionAnalyser.java#L19)):*
“Because proposed expression analysers are loaded through extension points, they need a public zero argument constructor”

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/ProposedExpressionAnalyserContributionsHandler.java, line 53 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-K9rmb33-0TwbgByQD8q:-K9rmb33-0TwbgByQD8r:95804313) ([raw file](https://github.com/beagle-pse/beagle/blob/1038f838b469f37e0c36f999b3ad5be436ab3c0e/Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/ProposedExpressionAnalyserContributionsHandler.java#L53)):*
If an instance of a**[ny]** proposed expression analyser could not
be created for any reason, e.g. **[because]** the proposed expression analyser **[has]** no
public zero argument constructor or **[because]** a**[]**
`{@code ProposedExpressionAnalyserClass}` provided via the extension point
**[is]** not implementing `{@link ProposedExpressionAnalyser}`.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/measurement/MeasurementToolContributionsHandler.java, line 48 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-K9rn6YWZEhNFJFKsI4u:-K9rn6YWZEhNFJFKsI4v:1555228307) ([raw file](https://github.com/beagle-pse/beagle/blob/1038f838b469f37e0c36f999b3ad5be436ab3c0e/Core/src/main/java/de/uka/ipd/sdq/beagle/core/measurement/MeasurementToolContributionsHandler.java#L48)):*
If an instance of a**[ny]** measurement tool could not
be created for any reason, e.g. **[because]** the measurement tool **[has]** no
public zero argument constructor or **[because]** a**[]**
`{@code MeasurementToolClass}` provided via the extension point
**[is]** not implementing `{@link MeasurementTool}`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663)*

**Comment by RomanLangrehr** [comment]
Review status: 8 of 14 files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-K9rl-uKFnDjxS4F0OYW:-K9s9xwAJ0Jt-MiurY1K:-499146009) (no related file):*
Done.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/MeasurementResultAnalyser.java, line 25 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-K9rkaxjh-CzF4ATNUAd:-K9s4x-IYxykdN23eqx4:659956776) ([raw file](https://github.com/beagle-pse/beagle/blob/1038f838b469f37e0c36f999b3ad5be436ab3c0e/Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/MeasurementResultAnalyser.java#L25)):*
Okay?
Done.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/MeasurementResultAnalyserContributionsHandler.java, line 53 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-K9rloUmLwvA64d-TXC6:-K9s5I3Sw2_vmleJtBII:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/1038f838b469f37e0c36f999b3ad5be436ab3c0e/Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/MeasurementResultAnalyserContributionsHandler.java#L53)):*
Done.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/ProposedExpressionAnalyser.java, line 19 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-K9rknMx1iijai6uzWy7:-K9s5bkbGkytk238mfCN:659956776) ([raw file](https://github.com/beagle-pse/beagle/blob/1038f838b469f37e0c36f999b3ad5be436ab3c0e/Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/ProposedExpressionAnalyser.java#L19)):*
Okay?
Done.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/ProposedExpressionAnalyserContributionsHandler.java, line 53 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-K9rmb33-0TwbgByQD8q:-K9s5q7bQBq_KAgHqXSn:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/1038f838b469f37e0c36f999b3ad5be436ab3c0e/Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/ProposedExpressionAnalyserContributionsHandler.java#L53)):*
Done.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/measurement/MeasurementToolContributionsHandler.java, line 48 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-K9rn6YWZEhNFJFKsI4u:-K9s69hKsQ5FoLyZqkxo:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/1038f838b469f37e0c36f999b3ad5be436ab3c0e/Core/src/main/java/de/uka/ipd/sdq/beagle/core/measurement/MeasurementToolContributionsHandler.java#L48)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663)*

**Comment by jGleitz** [comment]
Reviewed 1 of 7 files at r5.
Review status: 9 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/measurement/MeasurementTool.java, line 26 \[r5\]](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-K9sBP1eZt4SYF8CpT7G:-K9sBP1eZt4SYF8CpT7H:1278602258) ([raw file](https://github.com/beagle-pse/beagle/blob/0f10819b895dce36d06c62f10de0f60ee50837bd/Core/src/main/java/de/uka/ipd/sdq/beagle/core/measurement/MeasurementTool.java#L26)):*
Executes a**[]** measurement. This method should return after the complete measurement.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663)*

**Comment by jGleitz** [comment]
Reviewed 5 of 7 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-:-K9sBgOvvkMigtEPwWFt:980077423)*

**Comment by RomanLangrehr** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/measurement/MeasurementTool.java, line 26 \[r5\]](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-K9sBP1eZt4SYF8CpT7G:-K9sD65ufV3kY-UtSurj:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/0f10819b895dce36d06c62f10de0f60ee50837bd/Core/src/main/java/de/uka/ipd/sdq/beagle/core/measurement/MeasurementTool.java#L26)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-:-K9sDqtUav8qE8jzCeLv:980077423)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-K9v1Y91tLtt2YzgSQ73:-K9v1Y91tLtt2YzgSQ74:-1258427269) (no related file):*
+@viridispirus should manually test this and confirm its functionality by giving his lgtm

(this comment will keep this from being merged until then)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-K9v1Y91tLtt2YzgSQ73:-KA1AffyyHl6GcOWG_-5:-627722253) (no related file):*
@viridispirus : how’s your progress?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663)*

**Comment by viridispirus** [comment]
I am Start testing when i am at home. Ca. In 30 min.
Am 08.02.2016 21:17 schrieb "Joshua Gleitze" <notifications@github.com>:

**Comment by viridispirus** [comment]
Reviewed 3 of 7 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663)*

**Comment by RomanLangrehr** [comment]
@viridispirus  Two project folders are called "Neuer Ordner" / "Neuer Ordner (2)". Please rename them!

---

Review status: 13 of 64 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-:-KAGyihWuXG1fY5jV3sx:1417443464)*

**Comment by jGleitz** [comment]
Reviewed 1 of 1 files at r19.
Review status: 11 of 65 files reviewed at latest revision, 3 unresolved discussions.

---

*[Core/src/main/resources/META-INF/MANIFEST.MF, line 12 \[r19\]](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-KALWeb_YP9FLVgAIxzR:-KALWeba7ENTGKVWpHEt:-1080027386) ([raw file](https://github.com/beagle-pse/beagle/blob/e81a10122b6d3a770e52e52722fdf0a567f7d9ba/Core/src/main/resources/META-INF/MANIFEST.MF#L12)):*
I think we can safely export the whole `core` package. It’s intended to be an API.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663)*

**Comment by viridispirus** [comment]
Review status: 11 of 65 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-K9v1Y91tLtt2YzgSQ73:-KALmHbKTE-FdcfIOmxk:1766308287) (no related file):*
Still finished.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663)*

**Comment by jGleitz** [comment]
Reviewed 1 of 68 files at r13.
Review status: 12 of 65 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663)*

**Comment by RomanLangrehr** [comment]
Review status: 11 of 65 files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/resources/META-INF/MANIFEST.MF, line 12 \[r19\]](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-KALWeb_YP9FLVgAIxzR:-KALzXDSi4mmLCQNIPMR:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/e81a10122b6d3a770e52e52722fdf0a567f7d9ba/Core/src/main/resources/META-INF/MANIFEST.MF#L12)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663)*

**Comment by jGleitz** [comment]
Review status: 11 of 65 files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/resources/META-INF/MANIFEST.MF, line 12 \[r19\]](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-KALWeb_YP9FLVgAIxzR:-KAMCCjTy9MSzR0j_kFe:90117101) ([raw file](https://github.com/beagle-pse/beagle/blob/e81a10122b6d3a770e52e52722fdf0a567f7d9ba/Core/src/main/resources/META-INF/MANIFEST.MF#L12)):*
That was not what I meant. You can simply to

```
Export-Package: de.uka.ipd.sdq.beagle.core
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663)*

**Comment by RomanLangrehr** [comment]
Review status: 11 of 65 files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/resources/META-INF/MANIFEST.MF, line 12 \[r19\]](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-KALWeb_YP9FLVgAIxzR:-KAMDWvNQBsiy4-PXtR6:-125254080) ([raw file](https://github.com/beagle-pse/beagle/blob/e81a10122b6d3a770e52e52722fdf0a567f7d9ba/Core/src/main/resources/META-INF/MANIFEST.MF#L12)):*
That didn't work for me.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663)*

**Comment by jGleitz** [comment]
Review status: 11 of 65 files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/resources/META-INF/MANIFEST.MF, line 12 \[r19\]](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-KALWeb_YP9FLVgAIxzR:-KAMGaBptZNm8owFeS2U:968840696) ([raw file](https://github.com/beagle-pse/beagle/blob/e81a10122b6d3a770e52e52722fdf0a567f7d9ba/Core/src/main/resources/META-INF/MANIFEST.MF#L12)):*
My bad.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r21.
Review status: 12 of 65 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663)*

**Comment by acBerger** [comment]
Could you please change the test projects from gradle project to normal java projects? This leads to unneeded errors in my eclipse as it is not a real gradle project.

---

Reviewed 3 of 45 files at r2, 32 of 68 files at r13, 3 of 3 files at r16, 34 of 37 files at r17, 2 of 2 files at r18, 1 of 1 files at r19.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-:-KAMWNe9LlUa319UeKfz:-253214173)*

**Comment by acBerger** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-KAOzb-JP82Ig56q37am:-KAOzb-JP82Ig56q37an:-1349331993) (no related file):*
Please change the test projects from gradle project to normal java projects? This leads to unneeded errors in my eclipse as it is not a real gradle project.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663)*

**Comment by acBerger** [comment]
Reviewed 4 of 45 files at r2, 5 of 7 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663)*

**Comment by viridispirus** [comment]
Who du you mean?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-:-KAP8vvGhN0svurT3kW4:-1948311215)*

**Comment by acBerger** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-KAOzb-JP82Ig56q37am:-KAPDA6Hg_wCHAnstHP-:1120141100) (no related file):*
I can do that.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663)*

**Comment by acBerger** [comment]
Review status: 34 of 65 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-KAOzb-JP82Ig56q37am:-KAPF4cuvlqsDV3hvqzV:-499146009) (no related file):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663)*

**Comment by viridispirus** [comment]
Reviewed 1 of 61 files at r22.
Review status: 35 of 65 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663)*

**Comment by acBerger** [comment]
Reviewed 2 of 72 files at r17, 5 of 90 files at r22.
Review status: 14 of 64 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-KAPMP8xPMRCv7lBNcCZ:-KAPMP8yghQBL3JAnY5F:-1491842555) (no related file):*
I fixed all occuring problems in  my eclipse but however it still does not work. There is a new eclipse  starting but I cannot find a "Beagle Button" and there were several exceptions thrown.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663)*

**Comment by RomanLangrehr** [comment]
Review status: 13 of 64 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-KAPMP8xPMRCv7lBNcCZ:-KAPxICmrqM4y8TDDLhB:-410480854) (no related file):*
Did you use a run configuration that loads these plugins?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663)*

**Comment by acBerger** [comment]
Review status: 13 of 64 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-KAPMP8xPMRCv7lBNcCZ:-KAQ0Vpmz40Oy3-Ojlfh:917426223) (no related file):*
I thinks so.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663)*

**Comment by RomanLangrehr** [comment]
Tests have been fixed!

Please do NEVER AGAIN modify code without talking to the responsible people!

**Comment by jGleitz** [comment]
> Please do NEVER AGAIN modify code without talking to the responsible people!

I’m sorry for that. Was definitely my fault.

You should document why you’re violating a whole bunch of our style guidelines (folder naming, projects structure, class naming, etc.), because otherwise people will just assume you did a bad job.

**Comment by RomanLangrehr** [comment]
Review status: 12 of 59 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-KAPMP8xPMRCv7lBNcCZ:-KAQQSOrX9hetdhQCIn1:-499146009) (no related file):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663)*

**Comment by acBerger** [comment]
Review status: 12 of 59 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-KAPMP8xPMRCv7lBNcCZ:-KAQSQfS-rnQkqmEmUP4:46557990) (no related file):*
Works for me now.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663)*

**Comment by acBerger** [comment]
[Website] (http://beagle-pse.github.io/Beagle/branches/ip090-extension-points/)

---

Review status: 12 of 59 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-:-KAQbwEzN9Hl1NpOB7MW:-1306254547)*

**Comment by acBerger** [comment]
:lgtm: 
:white_check_mark: (MeasurementController, MeasurementEventParser etc. do not have to be tested in this PR)

---

Reviewed 1 of 1 files at r25.
Review status: 13 of 59 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-:-KAQthawQm5m9NQh_3Am:-1833405019)*

**Comment by RomanLangrehr** [comment]
@jGleitz @acBerger  Your lgtms got stole. Please renew them.

---

Review status: 13 of 59 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-:-KARM0D0pT9aLRrsJRYG:-1266896539)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Reviewed 3 of 45 files at r2, 3 of 3 files at r16, 17 of 72 files at r17, 1 of 3 files at r18, 27 of 90 files at r22, 73 of 103 files at r23, 1 of 1 files at r24, 1 of 1 files at r25, 2 of 2 files at r26, 7 of 14 files at r27, 6 of 7 files at r28, 1 of 1 files at r29.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-:-KARODswvXgLuzNkbEsa:980077423)*

**Comment by acBerger** [comment]
:lgtm:
:white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/663#-:-KAROlHis1EVrF6MeHQB:-1198925855)*

**Pull request merged**
