### PR TITLE
Activity diagrams

### LINKED ISSUE #45: Activity Diagram for /A20/

### LINKED ISSUE #46: Activity Diagram for /A30/

### LINKED ISSUE #48: Activity Diagram for /A40/

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Fixes #45 
Fixes #46 
Fixes #48 

Unfortunatly, the diagrams for /A20/ and /A40/ are nearly identical.

[PDF](http://romanlangrehr.github.io/Beagle/branches/activity/Requirements%20Specification.pdf)

Blocks #195

### CODE REVIEW

**Comment by jGleitz** [comment]
> Unfortunatly, the diagrams for /A20/ and /A40/ are nearly identical.

Thinking of it, I’m not even sure what’s the difference between `/A20/` and `/A40/` anymore.

**Comment by RomanLangrehr** [comment]
> Thinking of it, I’m not even sure what’s the difference between /A20/ and /A40/ anymore.

I think mainly the target group.

**Comment by acBerger** [comment]
lgtm

**Comment by jGleitz** [comment]
I think the diagrams can be improved visually here an there, but we can do that later if we have time left.

lgtm

**Pull request merged**
