### PR TITLE
Launch configuration enhancement

### LINKED ISSUE #794: Use the Fail API if there are no Run Configurations
If the user does not have any launch configurations configured, Beagle fails with an `IllegalArgumentException`. However, this case should be handled by the facade.

For now, I think reporting through the Failure Handler is enough, as we could then easily show a GUI message.

### LINKED ISSUE #802: Run Configuration Costant Timeout
By manual testing I found a bug. When the constant timeout field is empty the run button do not gray out.

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Fixes #794
Fixes #802 

---
This change is [Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/810)

### CODE REVIEW

**Comment by m1cm1c** [comment]
:lgtm: :white_check_mark: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-:-KCfr-fspmyY6i0SQV4C:-1603124213)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[GUI/src/main/java/de/uka/ipd/sdq/beagle/gui/BeagleLaunchConfigurationDelegate.java, line 118 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-KCfz2ccVLLcq-dfDmNE:-KCfz2ccVLLcq-dfDmNF:-1408377538) ([raw file](https://github.com/beagle-pse/beagle/blob/6cb7c4ed118b16e7fcefc4c63827162334887763/GUI/src/main/java/de/uka/ipd/sdq/beagle/gui/BeagleLaunchConfigurationDelegate.java#L118)):*
This will not be necessary anymore after #796 (GUI Enhancements) , so you can omit it.

---

*[GUI/src/main/java/de/uka/ipd/sdq/beagle/gui/LaunchConfigurationTab.java, line 239 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-KCfzBkuVsPj4UARpHjD:-KCfzBkuVsPj4UARpHjE:-510998054) ([raw file](https://github.com/beagle-pse/beagle/blob/6cb7c4ed118b16e7fcefc4c63827162334887763/GUI/src/main/java/de/uka/ipd/sdq/beagle/gui/LaunchConfigurationTab.java#L239)):*
Shouldn’t this also check whether the launch configurations exist? Why is there no check for the repository and source statements file?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[GUI/src/main/java/de/uka/ipd/sdq/beagle/gui/BeagleLaunchConfigurationDelegate.java, line 118 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-KCfz2ccVLLcq-dfDmNE:-KCfzR78FeYxlScPBypp:314402034) ([raw file](https://github.com/beagle-pse/beagle/blob/6cb7c4ed118b16e7fcefc4c63827162334887763/GUI/src/main/java/de/uka/ipd/sdq/beagle/gui/BeagleLaunchConfigurationDelegate.java#L118)):*
Oh, sorry, I’m wrong. This is actually to early for the GUI to catch it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810)*

**Comment by RomanLangrehr** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[GUI/src/main/java/de/uka/ipd/sdq/beagle/gui/BeagleLaunchConfigurationDelegate.java, line 118 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-KCfz2ccVLLcq-dfDmNE:-KCh7TRmLOCPJdrw-_Zm:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/1c1fe868e01a114f1fe7c4da370c0d2bef8c920b/GUI/src/main/java/de/uka/ipd/sdq/beagle/gui/BeagleLaunchConfigurationDelegate.java#L118)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810)*

**Comment by acBerger** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810)*

**Comment by RomanLangrehr** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[GUI/src/main/java/de/uka/ipd/sdq/beagle/gui/LaunchConfigurationTab.java, line 239 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-KCfzBkuVsPj4UARpHjD:-KCkEyRBoJXnoPNj24OM:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/1c1fe868e01a114f1fe7c4da370c0d2bef8c920b/GUI/src/main/java/de/uka/ipd/sdq/beagle/gui/LaunchConfigurationTab.java#L239)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810)*

**Comment by acBerger** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-:-KCkKYf_MpDU7PcQkjes:980077423)*

**Comment by viridispirus** [comment]
Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810)*

**Comment by jGleitz** [comment]
Does this also addres #802 ?

**Comment by RomanLangrehr** [comment]
No.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-:-KClAbrYl5VRPm0NPuFC:160383816)*

**Comment by jGleitz** [comment]
:lgtm: :white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-:-KClAjzDVosZIgsTmVhj:-1603124213)*

**Comment by jGleitz** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-KClDE4XLyyFNuvdHnIW:-KClDE4XLyyFNuvdHnIX:-1331764834) (no related file):*
The standard Eclipse configurations manage to show a little message about what’s wrong if they’re invalid. [“We have Lift-Off”](https://eclipse.org/articles/Article-Launch-Framework/launch.html) makes it look like that only requires a call to `AbstractLaunchConfigurationTab#setErrorMessage`.

Do you think you could add that? It would certainly be something to show off in the presentation. We could also remove the `UIJob` in the launch configuration delegate, which is a little inconsistent in the way errors are handled.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810)*

**Comment by flyfl** [comment]
Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810)*

**Comment by jGleitz** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810)*

**Comment by RomanLangrehr** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-KClDE4XLyyFNuvdHnIW:-KClUx1KWVhbVmYnfjTb:1238062840) (no related file):*
I tried setErrorMessage, but I never saw where the actual error message appered.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-KClDE4XLyyFNuvdHnIW:-KClVJfkzckaqcDka8VP:-1891877590) (no related file):*
Do you have the code somewhere I can pull it from?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810)*

**Comment by RomanLangrehr** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-KClDE4XLyyFNuvdHnIW:-KClVyorlI5VLlhBtfay:-1800770773) (no related file):*
No, I deleted it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-KClDE4XLyyFNuvdHnIW:-KClbD-7zNk7IYSYxVLP:550707923) (no related file):*
It works pretty well on my machine. Maybe that’s a windows problem? If you agree, I’ll push it in a few minutes.



---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810)*

**Comment by RomanLangrehr** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-KClDE4XLyyFNuvdHnIW:-KClboJebJEymbcXLcwC:2113252095) (no related file):*
> If you agree, I’ll push it in a few minutes.

Okay.

I expected to be the message exactly like this, but I didn't worked when I tired it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810)*

**Comment by acBerger** [comment]
Reviewed 6 of 8 files at r5.
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810)*

**Comment by jGleitz** [comment]
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-KClDE4XLyyFNuvdHnIW:-KCm0yn5-4_0u97fhHTg:992529277) (no related file):*
I’m very sorry that it took me so long! I thought this was a simple fix that would look cool in the presentation, but it took me a lot longer than expected.

Anyway, I think it was worth it:

  * The launch configuration settings show an error message if the configuration is bad
  * The launch delegate shows an error window if the launch configuration is bad
  * Both share the same checking code

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-:-KCm1jyMv4ZB2m45S1HQ:980077423)*

**Comment by m1cm1c** [comment]
Reviewed 7 of 8 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810)*

**Comment by m1cm1c** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-:-KCm37DcPhDXlc6NVJp0:1417088721)*

**Comment by jGleitz** [comment]
:lgtm: :white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-:-KCm3USjsHcgSX4WV90v:-1603124213)*

**Comment by jGleitz** [comment]
:lgtm_cancel: :o:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-:-KCm4Y-1cepGFoaKam4_:-955535473)*

**Comment by acBerger** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-KCm5FD0GRp6tAQFjXPr:-KCm5FD0GRp6tAQFjXPs:-1535887101) (no related file):*
Did not work for me. @jgleitz  is on solving the problem.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: 4 of 9 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-KCm5FD0GRp6tAQFjXPr:-KCmAMOgpMsS8gbqMJ5-:-1620474753) (no related file):*
fixed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-:-KCmAOMQ7vd7dqfg3SL7:1417088721)*

**Comment by jGleitz** [comment]
:lgtm:

---

Review status: 4 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-:-KCmAQeygGNGnfltxA0T:1417088721)*

**Comment by jGleitz** [comment]
Reviewed 5 of 8 files at r5, 1 of 1 files at r6, 1 of 2 files at r7, 2 of 2 files at r8.
Review status: 6 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810)*

**Comment by acBerger** [comment]
:white_check_mark: 

---

Review status: 6 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-:-KCmAWm3qR8BI1eq31hZ:1605498549)*

**Comment by jGleitz** [comment]
Reviewed 3 of 3 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810)*

**Comment by RomanLangrehr** [comment]
By the way: The error messages work for me as well.

---

Reviewed 3 of 8 files at r5, 1 of 1 files at r6, 2 of 2 files at r8, 3 of 3 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-:-KCmBYcKut6gz8bK03cC:1056019967)*

**Comment by jGleitz** [comment]
> The error messages work for me as well.

Good to hear!

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-:-KCmCUDDTlk9BOYs6csF:114473847)*

**Comment by acBerger** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-KCmKMRz3H9JW0ZC07tD:-KCmKMRz3H9JW0ZC07tE:452344311) (no related file):*
This has to wait.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810)*

**Comment by acBerger** [comment]
:lgtm: :white_check_mark: 

---

Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-KCmKMRz3H9JW0ZC07tD:-KCmLZ4E8OSe7ffGfVVa:-375518728) (no related file):*
Okay now as the bug is fixed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-:-KCmLcROYARVjzSgk8ZG:-1603124213)*

**Comment by jGleitz** [comment]
:lgtm:

---

Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810#-:-KCmLuyRBu2uvLjgVRaE:1417088721)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/810)*

**Pull request merged**
