### PR TITLE
Packages

### PR DESCRIPTION
**Pull request by acBerger**
#417 

I redid my PR packages (#449) as it lead to great conflicts.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/470)

### CODE REVIEW

**Comment by flyfl** [comment]
The package overview looks good. But to the BeagleCore Diagram has the same problems as before.

---

Reviewed 46 of 46 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/470#-:-K7VlSO6K-koJGF-Z8nL:-1956507885)*

**Comment by acBerger** [comment]
I checked it several times. For me only the note of Beagle Controller was broken (some of the links) and I fixed that before uploading. Every thing else was fine then and is still fine. 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/470#-:-K7Vn9fTwLLg8MngUOPZ:1012499811)*

**Comment by RomanLangrehr** [comment]
Yes, it's the same problem as before:


---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/470#-:-K7VzlrylYdX9-dl2wqy:1367361715)*

**Comment by jGleitz** [comment]
Fuck this shit!



---

Review status: 24 of 28 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/470#-:-K7WE4igfYGcD8wGNmVq:-703130770)*

**Comment by acBerger** [comment]
This is just impossible!

---

Review status: 24 of 28 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/470#-:-K7WGvsqlGrevAF-Mwsj:-435161767)*

**Comment by acBerger** [comment]
As we switch to another UML Tool I'll close that and do it then again.

**Pull request closed without merging**
