### PR TITLE
Update package diagram

### LINKED ISSUE #417: Create Package Structure
model it in Papyrus and apply it to the classes

### PR DESCRIPTION
**Pull request by acBerger**
Added all new classes

caution: roman will delete "demo" from the names in contextmenus and I therefore already used the correct one.

Fixes #417 

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/549)

### CODE REVIEW

**Comment by jGleitz** [comment]
The new classes are missing. Please compare to the latest class diagrams!

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/549#-:-K7hH9CCbsqzSm7lNeDJ:1200943489)*

**Comment by RomanLangrehr** [comment]
[Website](http://acberger.github.io/Beagle/branches/packages/)

Read-Only Blackboard View
doesn't exist any more.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/549#-:-K7hWdWyuZkF3YNHymE0:-1282677127)*

**Comment by RomanLangrehr** [comment]
This is cut off.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/549#-:-K7hXGpuXhVhlUjKrsW8:-1229721005)*

**Comment by acBerger** [comment]
Sorry, forgot to remove it before.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/549#-:-K7hZc6-hbrsObPox1xM:-181388574)*

**Comment by acBerger** [comment]
please wait, I'll check with @jGleitz  PR

**Comment by RomanLangrehr** [comment]
ok. for now: :lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/549#-:-K7hdFNsS2TUm9w9sl1b:-1929696478)*

**Comment by flyfl** [comment]
:lgtm_strong:

**Comment by acBerger** [comment]
Should be okay now.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/549#-:-K7heHhJf991Fw7OBk0c:621275663)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/549#-:-K7hfxAjyF6mgv1IAXel:980077423)*

**Pull request merged**
