### PR TITLE
Added next 3 agenda files.

### PR DESCRIPTION
**Pull request by m1cm1c**

### CODE REVIEW

**Comment by jGleitz** [comment]
#### Purpose

Let’s discuss whether creating those files makes sense. Some arguments:
 **+** We’ll have to make pull requests, forcing us to discuss the agenda
 **-** We’ll have to make pull requests just to put items on the agenda

Would GitHub issues be a better place to do this? We can discuss there too.

#### File Names
 1. I used small letters throughout folder and file names. We may use capital letters if you prefer that, but please don’t mix that. So please change your folders to lowercase or open a ticket to discuss folder capitalization. 

 1. Do we need double nested folders? Can’t we just create a `agenda` folder, without a `organization` one above it?

**Comment by m1cm1c** [comment]
If we were to use GitHub issues instead, we'd just be avoiding a problem that doesn't exist in a poor way. We could make an exception for agenda files (and even note files). This way we'd have the same effect (everyone can edit it without approval of others) but we'd still have our documentation all packed together in a platform-independent structure, therefore improving documentation.

**Comment by RomanLangrehr** [comment]
Lgtm

**Comment by jGleitz** [comment]
@m1cm1c I get what you’re saying. 

My only thinking was that meeting minutes are something that need to be documented and therefore belong in the repository. Agenda files, on the contrary, completely use their purpose after the meeting (and will be documented in the meeting’s minutes).

**Comment by m1cm1c** [comment]
We won't have complete meeting minutes and agendas give a short overview over what was being discussed. For example, (if someone takes notes at all) we probably won't write down that the structure we chose for the Software Requirements Specification Document was okay (if it will be okay, of course), but if it's documented in the agenda file, we know that we talked about it in the official meeting of 2015-11-20.

Another point I can think of is that these files not only are backed up by every one of us, but are easily searchable by tools like `gnome-search-tool`. I have no idea how we'd find something like this easily if it only was stored on GitHub.

**Comment by jGleitz** [comment]
@m1cm1c you have a point.

Looks good to me, because we’ll make a consistent file structure once #13 is decided.

**Pull request merged**
