### PR TITLE
Fixed gradle encoding issues for windows.

### PR DESCRIPTION
**Pull request by RomanLangrehr**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/566)

### CODE REVIEW

**Comment by m1cm1c** [comment]
:lgtm:

**Comment by jGleitz** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[gradle.properties, line 5 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/566#-K7hufbBjN0T5Tix_y5M:-K7hufbCZrv4-r1I5Quc:621794886) ([raw file](https://github.com/beagle-pse/beagle/blob/735a9e4d80d028f4c9f7cb729520cb5432787936/gradle.properties#L5)):*
If this property shall remain, it should at least be spelled right. I guarantee that it has no effect at all in the moment.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/566)*

**Comment by jGleitz** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/566)*

**Comment by RomanLangrehr** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[gradle.properties, line 5 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/566#-K7hufbBjN0T5Tix_y5M:-K7hxOFhfuiLNNlpNDtD:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/735a9e4d80d028f4c9f7cb729520cb5432787936/gradle.properties#L5)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/566)*

**Comment by m1cm1c** [comment]
:lgtm:

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/566#-:-K7hyprztLFIE2vYe2Wo:980077423)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/566#-:-K7i-QD3MvL7ui1R2eqh:980077423)*

**Comment by m1cm1c** [comment]
:lgtm: 

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/566#-:-K7i-SwM83DoBGY85hHZ:980077423)*

**Pull request merged**
