### PR TITLE
Revised Discussion

### LINKED ISSUE #201: Revise Discussion

### PR DESCRIPTION
**Pull request by acBerger**
fixes #201

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
[PDF](http://acberger.github.io/Beagle/branches/Discussion/Requirements%20Specification.pdf)

**Comment by RomanLangrehr** [comment]
> e. Fortunately, it most of the
time imposes little loss of generality

I think it should be:
Fortunately, it imposes  most of the
time little loss of generality

**Comment by m1cm1c** [comment]
The sentence is correct (except for what's inside the parentheses).

**Comment by RomanLangrehr** [comment]
Lgtm

**Comment by m1cm1c** [comment]
Well, the part inside the parentheses is still wrong. :D

**Comment by RomanLangrehr** [comment]
What's wrong with it?



Am 2015-11-29 um 20:46 schrieb m1cm1c:

**Comment by m1cm1c** [comment]
"regarding" is the wrong word for this. Just merge it in, I'll reopen #201 and revise `Discussion` again.

**Comment by m1cm1c** [comment]
lgtm

**Pull request merged**
