### PR TITLE
Fitness Function View in Model

### PR DESCRIPTION
**Pull request by viridispirus**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/530)

### CODE REVIEW

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/530)*

**Comment by RomanLangrehr** [comment]
[Website](http://viridispirus.github.io/Beagle/branches/FitnessFunctionView/)

Please update branch!

**Comment by RomanLangrehr** [comment]
Verry good.

Just add an `<<implements>>`to the new arrows to make it perfect ;)

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/530#-:-K7gUYEnCusRGGgq5TdW:-1543885631)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/530#-:-K7gbWJwoWxquJQmnzM7:980077423)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/530#-:-K7gbmEmhq846tpYgMlo:1417088721)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/530)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/530#-:-K7gebBJ_P-7eftJtWgk:980077423)*

**Pull request merged**
