### PR TITLE
Qs report

### PR DESCRIPTION
**Pull request by acBerger**
I added a document (frame) for the QS report.
Every thing done in this Phase has to be added here!

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/766)

### CODE REVIEW

**Comment by acBerger** [comment]
I already added some points. If you have any improvement feel free to express.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/766#-:-KByDOg9I8PvoGxg9hp7:1329216442)*

**Comment by m1cm1c** [comment]
This branch is out-of-date with the base branch.

**Comment by RomanLangrehr** [comment]
Can you add the report to the webiste, please?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/766#-:-KC5lp81ckUgGPVZ7LrQ:876986558)*

**Comment by acBerger** [comment]
[Website] (http://acberger.github.io/Beagle/branches/QSReport/)

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/766#-:-KC62OP9T6Lp3Ghso2YT:-741208043)*

**Comment by m1cm1c** [comment]
:white_check_mark: :lgtm:

**Comment by m1cm1c** [comment]
Reviewed 1 of 1 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/766)*

**Comment by flyfl** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/766#-:-KCAL0rDXP7X_DVNvLXc:1417088721)*

**Pull request merged**
