### PR TITLE
System to Read and Write PCM data

### PR DESCRIPTION
**Pull request by jGleitz**
* not yet documented in the design document
 * data between reading and writing is exchanged via the blackboard
 * `PCM Beagle Mapping` is intentionally not filled in the class diagram because of #455 
 * Adapted `Blackboard` and `Analysis Controller` accordingly
 * fixed some things in the Beagle Core diagram

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/456)

### CODE REVIEW

**Comment by jGleitz** [comment]
[View this PR’s rendered artefacts](http://jgleitz.github.io/Beagle/branches/blackboard-factory/)

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/456#-:-K7NJe9n3pGVLsV6Ldmm:44005897)*

**Comment by flyfl** [comment]
:lgtm_strong:
Naming and your division into classes makes sense. And I did not found any big mistakes.
To the others: please resolve discussion #455 , so that we can integrate this
changes into the BeagleCore.

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/456#-:-K7QH2NjRrmRlT3fXOk2:1760605481)*

**Comment by RomanLangrehr** [comment]
Reviewed 7 of 15 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/de/uka/ipd/sdq/beagle/pcmconnection/PcmBeagleMappings.java, line 91 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/456#-K7S4PJXgPOu3hq9Nhdh:-K7S4PJXgPOu3hq9Nhdi:166114628) ([raw file](https://github.com/beagle-pse/beagle/blob/58aeaf756f3c0115f446b0f4edc35e0c774a41a5/src/main/java/de/uka/ipd/sdq/beagle/pcmconnection/PcmBeagleMappings.java#L91)):*
Do we need a set method here? I think an addPcmIdOf... would fit better.

---

*[src/main/java/de/uka/ipd/sdq/beagle/pcmconnection/PcmBeagleMappings.java, line 101 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/456#-K7S4XPqYsWDbipIrmhH:-K7S4XPqYsWDbipIrmhI:-1582418045) ([raw file](https://github.com/beagle-pse/beagle/blob/58aeaf756f3c0115f446b0f4edc35e0c774a41a5/src/main/java/de/uka/ipd/sdq/beagle/pcmconnection/PcmBeagleMappings.java#L101)):*
See above.

---

*[src/main/java/de/uka/ipd/sdq/beagle/pcmconnection/PcmBeagleMappings.java, line 111 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/456#-K7S4Yr-UyihEwpqFFbu:-K7S4Yr-UyihEwpqFFbv:-1582418045) ([raw file](https://github.com/beagle-pse/beagle/blob/58aeaf756f3c0115f446b0f4edc35e0c774a41a5/src/main/java/de/uka/ipd/sdq/beagle/pcmconnection/PcmBeagleMappings.java#L111)):*
See above.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/456)*

**Comment by RomanLangrehr** [comment]
Is it on purpose, that the types are missing here?

And the blackbaord-reference got lost:



Is it on purpose, that these classes are in the package overview?

---

Reviewed 8 of 15 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/456#-:-K7S5TCFDsSrRkrSSrEU:-431172633)*

**Comment by acBerger** [comment]
Reviewed 7 of 15 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/456)*

**Comment by jGleitz** [comment]
>  Is it on purpose, that the types are missing here?

Yep. The line would get way to long otherwise.

>  Is it on purpose, that these classes are in the package overview?

Yes. It’s meant to already be compatible to the changes of #449 (Packages) 

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/de/uka/ipd/sdq/beagle/pcmconnection/PcmBeagleMappings.java, line 91 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/456#-K7S4PJXgPOu3hq9Nhdh:-K7SbirnLTB89c_19PQH:342147660) ([raw file](https://github.com/beagle-pse/beagle/blob/58aeaf756f3c0115f446b0f4edc35e0c774a41a5/src/main/java/de/uka/ipd/sdq/beagle/pcmconnection/PcmBeagleMappings.java#L91)):*
I think those are pretty equivalent. I will rename them to `addPcmIdOf` if you like that better.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/456#-:-K7Sb9miwUETR42l5VW_:1596198666)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/de/uka/ipd/sdq/beagle/pcmconnection/PcmBeagleMappings.java, line 111 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/456#-K7S4Yr-UyihEwpqFFbu:-K7ScMWv61gEdb9znf1A:1960736842) ([raw file](https://github.com/beagle-pse/beagle/blob/58aeaf756f3c0115f446b0f4edc35e0c774a41a5/src/main/java/de/uka/ipd/sdq/beagle/pcmconnection/PcmBeagleMappings.java#L111)):*
Not resolved

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/456)*

**Comment by RomanLangrehr** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/de/uka/ipd/sdq/beagle/pcmconnection/PcmBeagleMappings.java, line 91 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/456#-K7S4PJXgPOu3hq9Nhdh:-K7SciVeDCj3-2HFAh6m:372892306) ([raw file](https://github.com/beagle-pse/beagle/blob/58aeaf756f3c0115f446b0f4edc35e0c774a41a5/src/main/java/de/uka/ipd/sdq/beagle/pcmconnection/PcmBeagleMappings.java#L91)):*
Yes, and `addPcmIdOf` should throw an Exception, if the rida was already added.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/456)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/de/uka/ipd/sdq/beagle/pcmconnection/PcmBeagleMappings.java, line 91 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/456#-K7S4PJXgPOu3hq9Nhdh:-K7Sk2WCutrIVPQNNtRA:-1881165043) ([raw file](https://github.com/beagle-pse/beagle/blob/58aeaf756f3c0115f446b0f4edc35e0c774a41a5/src/main/java/de/uka/ipd/sdq/beagle/pcmconnection/PcmBeagleMappings.java#L91)):*


> Yes, and addPcmIdOf should throw an Exception, if the rida was already added.

But only if the user tries to set a different ID. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/456)*

**Comment by jGleitz** [comment]
Fixed the pseudocode.

---

Review status: 12 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/main/java/de/uka/ipd/sdq/beagle/pcmconnection/PcmBeagleMappings.java, line 91 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/456#-K7S4PJXgPOu3hq9Nhdh:-K7SqrEFGqGD9fE9xihc:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/58aeaf756f3c0115f446b0f4edc35e0c774a41a5/src/main/java/de/uka/ipd/sdq/beagle/pcmconnection/PcmBeagleMappings.java#L91)):*
Done.

---

*[src/main/java/de/uka/ipd/sdq/beagle/pcmconnection/PcmBeagleMappings.java, line 101 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/456#-K7S4XPqYsWDbipIrmhH:-K7Sqrz8Y9N2AhbYvWCu:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/58aeaf756f3c0115f446b0f4edc35e0c774a41a5/src/main/java/de/uka/ipd/sdq/beagle/pcmconnection/PcmBeagleMappings.java#L101)):*
Done.

---

*[src/main/java/de/uka/ipd/sdq/beagle/pcmconnection/PcmBeagleMappings.java, line 111 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/456#-K7S4Yr-UyihEwpqFFbu:-K7Sqsdiw-M9R_y4uITE:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/58aeaf756f3c0115f446b0f4edc35e0c774a41a5/src/main/java/de/uka/ipd/sdq/beagle/pcmconnection/PcmBeagleMappings.java#L111)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/456#-:-K7SqtdD8HJC5q841vPw:-2038170877)*

**Comment by RomanLangrehr** [comment]
:lgtm_strong: 

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/456#-:-K7SvWqBwQUf5BxcoVmg:-1868698381)*

**Pull request merged**
