### PR TITLE
Basic documentation

### PR DESCRIPTION
**Pull request by jGleitz**
This pull requests adds two basic documents about discussions and findings to date. They are limited and need to be extended in the future.

Furthermore, this pull requests adds a basic `.project` file with almost no information (it's not even a Java project). It extends `.gitignore` to exlude `.metadata`, to prevent eclipse workspace data from accidentally being commited.

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
I think, instead of putting everything in doc/ we should make an folder structure here, because the documentation will definitly increase. Especially we will probably put the system specification document, product requirements document, etc.. here.

But its a great idea to create these .md documents now. They will come in handy, when we will create the system specification.

**Comment by jGleitz** [comment]
I agree that the doc folder will need a much better file structure in the future. But in the moment, I have a hard time to predict what structure will fit. So I just threw the files in. I think we should just move them around as needed while the documentation grows.

**Comment by jGleitz** [comment]
I actually never thought about system specification when writing these, I just had the feeling that it's stuff that should be written down. But you're right on that, I think. 

Maybe we could make it a habit to put the bullet points whatever we find and discuss in here.

**Comment by jGleitz** [comment]
@m1cm1c added some grammar fixes. 

Further comments? 

@romanlangrehr, do you want to introduce a directory layout for doc, or can we leave it until more documentation is done?

**Comment by RomanLangrehr** [comment]
No, i don't know which directory layout will fit now. We should do this later.

Lgtm

**Comment by m1cm1c** [comment]
@jGleitz Nope, looks fine.

**Pull request merged**
