### PR TITLE
Set up Travis for Continuous Integration

### LINKED ISSUE #56: Configure Continuous Integration
Configuring a continuous integration service like [Travis](https://travis-ci.org/) will add valuable improvements to our project:

### Quality control
 * We already had PRs breaking the build. With CI, we can recognise them _before_ merging.
 * CI assures us that we know all the steps necessary to build our software and all its assets on a clean system.
 * CI will automatically run tests (as soon as there is something to test)

### Convenience
 * CI can automatically deploy our software for us. That could mean:
   * pushing the most recent version of the documentation in `master` to the web.
   * pushing a rendered file of pull requests to the origin repository. This means you can simply **download a render to review it** – how cool is that?
   * things like automatic set up of update sites at a later point.

### PR DESCRIPTION
**Pull request by jGleitz**
fixes #56.

This pull request introduces continuous integration. As I already pointed out in #56, this is a vast improvement. Some key features:

 * Pull Requests will automatically be tested to see if they break the build
 * Documentation will automatically be built – so reviewers don’t need to check out SRS pull requests just to see the PDF they produce

 * You can see the PDF Travis built for this branch at http://jgleitz.github.io/Beagle/branches/travis/Requirements%20Specification.pdf
 * You can see how this Pull Request is check by Travis
 * Travis unfortunately needs about 4 minutes to build, as a lot of packages must be downloaded
 * Travis will not deploy artifacts of pull requests for security reasons.

To test the PDF generation:
 * Follow the guides given in doc/Development Setup.md to set up Travis
 * Push this pull request (my branch `travis`) to your repo
 * Consult the results in your gh-pages branch or on http://[user].github.io/Beagle/branches/[how-you-named-your-branch]

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
Lgtm.
(And works for me!)

**Comment by jGleitz** [comment]
@RomanLangrehr: Did you get the PDF pushed to your `gh-pages` branch? Because it doesn’t work for @acBerger.

**Comment by RomanLangrehr** [comment]
I only pushed everything to [my Travis-Test branch](https://github.com/RomanLangrehr/Beagle/tree/Travis-Test), and the test was succesfull. A `gh-pages` branch was not created. (Should there be a `Travis-Test gh-pages` branch or should there be one `gh-pages` branch for all branches...)?

**Comment by jGleitz** [comment]
> (Should there be a Travis-Test gh-pages branch or should there be one gh-pages branch for all branches...)?

There should be one `gh-pages` branch, containing a folder structure representing the branches. You can see that in my fork.

**Comment by jGleitz** [comment]
@RomanLangrehr could you push my latest commit to your fork, and see if you get a PDF built and pushed to `gh-pages` (which will get created automatically for you)

**Comment by RomanLangrehr** [comment]
@jGleitz I did so and the test passed, but there still is no `gh-pages` branch in my repo.

**Comment by acBerger** [comment]
lgtm

**Comment by jGleitz** [comment]
@RomanLangrehr that’s bad, because it’s working for @acBerger now.

In your Travis log, all down at the bottom, there is a line `./deploy/Deploy\ Publish.sh`. Click on it to get to see what was printed by that script.
Please print everything that came after that.

**Comment by RomanLangrehr** [comment]
`The command "cd $OLDPWD" exited with 0.
after_success
0.01s$ ./deploy/Deploy\ Publish.sh
The GH_TOKEN ENV is not set. Thus, we won't deploy to gh-pages.`

Sounds like it was my fault. I'll try to fix it....

**Comment by jGleitz** [comment]
@RomanLangrehr yup, you forgot about the token. Add it on Travis and then you can hit a button to run the build again.

**Comment by RomanLangrehr** [comment]
Now it worked. [Hurray!](https://github.com/RomanLangrehr/Beagle/blob/gh-pages/branches/Travis-Test/Requirements%20Specification.pdf)

**Comment by jGleitz** [comment]
:+1:

**Pull request merged**
