### PR TITLE
Fix UMLet Racing Condition

### PR DESCRIPTION
**Pull request by jGleitz**
Maybe this prevents the racing condition. It’s worth a shot.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/678)

### CODE REVIEW

**Comment by m1cm1c** [comment]
:lgtm:

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/678#-:-KA7Ko2AV9-4G1nqRIn3:980077423)*

**Comment by RomanLangrehr** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/678)*

**Comment by jGleitz** [comment]
@m1cm1c I stalled your lgtm

**Comment by m1cm1c** [comment]
:lgtm:

**Pull request merged**
