### PR TITLE
Ip#050 repository loader

### LINKED ISSUE #572: [IP #050] PCM Repository loader
Create a class that provides all information from the PCM which are
relevant for Beagle and a factory that uses these information to create
the SEFFLoops, SEFFBranches, ResourceDemandingInternalActions
and ExternalCallParameters.

Depends partly on IP#040 ( #571 ) (SEFF classes).

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Fixes #572 

Depends on #602 .

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/613)

### CODE REVIEW

**Comment by jGleitz** [comment]
-blocked as this is now expressed by +(tests needed) 

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-:-K8Wdu2EYLBRSeVit0Ok:-1370017168)*

**Comment by flyfl** [comment]
Could not solve gradle's failure. It can not find hamcrest.library

**Comment by jGleitz** [comment]
>  It can not find hamcrest.library

The hamcrest library is a test dependency. [As detailed in our documentation](http://beagle-pse.github.io/Beagle/Dependency%20Management.html), these belong into gradle, not into `MANIFEST.MF`.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-:-K8zrLEhRHkoH5IYGZrJ:-1919112667)*

**Comment by flyfl** [comment]
>The hamcrest library is a test dependency. As detailed in our documentation, these belong into gradle, not into MANIFEST.MF.

But if I do so, Eclipse can not resolve these dependencies anymore.

**Comment by jGleitz** [comment]
> But if I do so, Eclipse can not resolve these dependencies anymore.

If you [imported our project through Buildship](http://beagle-pse.github.io/Beagle/Development%20Setup.html), clicking on the project that requires the dependency and hitting F5 imports the dependency into Eclipse.  If that doesn’t work, your setup is broken.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-:-K91E4Cdi9Qqazatm7Fg:1443691923)*

**Comment by jGleitz** [comment]
+blocked because this depends on #598 (IP #060 Blackboard) 

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-:-K928-N-f4JCBUthbn8S:1449322577)*

**Comment by flyfl** [comment]
Gradle still fails.. Now there are a lot of compiler errors.
EMF Helper
- cannot access CDOObject
- class file for org.eclipse.emf.cdo.CDOObject not found

Other PcmConnector Classes
- incomparable types: Class<CAP#1> and Class<ResourceDemandingSEFFImpl>
- Symbol not found (.eAllContents() )
- incompatible types: AbstractAction cannot be converted to EObject

... and so on. I neither know how to fix the "not found" error nor the class cast errors.

**Comment by jGleitz** [comment]
@flyfl I fixed the build errors. The rest is yours to fix. -(help wanted) 

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-:-K93iThnNZvkSnwChQYs:-1867215444)*

**Comment by acBerger** [comment]
Reviewed 1 of 4 files at r1, 2 of 4 files at r4, 3 of 4 files at r9.
Review status: 6 of 7 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java, line 125 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-K96V7bN2zksoTAvdIm1:-K96V7bOC1J2d4O6VLUd:360984951) ([raw file](https://github.com/beagle-pse/beagle/blob/e8c2450f59f6adb8e6901e3b517da97c53f1ddad/Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java#L125)):*
It is FitnessFunction, isn't it?

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java, line 244 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-K96VmZemZyz3ISviMNG:-K96VmZemZyz3ISviMNH:1421238723) ([raw file](https://github.com/beagle-pse/beagle/blob/e8c2450f59f6adb8e6901e3b517da97c53f1ddad/Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java#L244)):*
This is much easier using `this.rdiasToBeMeasured.addAll(Arrays.asList(toMeasureRdias));`

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java, line 269 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-K96W36R_tODAr27ZHqy:-K96W36R_tODAr27ZHqz:-1582418045) ([raw file](https://github.com/beagle-pse/beagle/blob/e8c2450f59f6adb8e6901e3b517da97c53f1ddad/Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java#L269)):*
See above.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java, line 293 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-K96W6oo8plHHNziAIvb:-K96W6oo8plHHNziAIvc:2101406251) ([raw file](https://github.com/beagle-pse/beagle/blob/e8c2450f59f6adb8e6901e3b517da97c53f1ddad/Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java#L293)):*
see above

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java, line 317 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-K96W7vW-7WuXtsd-wcK:-K96W7vW-7WuXtsd-wcL:2101406251) ([raw file](https://github.com/beagle-pse/beagle/blob/e8c2450f59f6adb8e6901e3b517da97c53f1ddad/Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java#L317)):*
see above

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613)*

**Comment by acBerger** [comment]
Reviewed 1 of 4 files at r9.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613)*

**Comment by acBerger** [comment]
Reviewed 1 of 2 files at r10.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613)*

**Comment by jGleitz** [comment]
Review status: 5 of 8 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java, line 125 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-K96V7bN2zksoTAvdIm1:-K9sCPEANIRcxgBvHTR1:923575639) ([raw file](https://github.com/beagle-pse/beagle/blob/e8c2450f59f6adb8e6901e3b517da97c53f1ddad/Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java#L125)):*
This is the wrong PR for this. It needs to be fixed in #598 (IP #060 Blackboard) (if it wasn’t already)

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java, line 244 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-K96VmZemZyz3ISviMNG:-K9sBz2smmy5wQG5i8gI:923575639) ([raw file](https://github.com/beagle-pse/beagle/blob/e8c2450f59f6adb8e6901e3b517da97c53f1ddad/Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java#L244)):*
This is the wrong PR for this. It needs to be fixed in #598 (IP #060 Blackboard) (if it wasn’t already)

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java, line 269 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-K96W36R_tODAr27ZHqy:-K9sCMAwXu3opUWav-jz:923575639) ([raw file](https://github.com/beagle-pse/beagle/blob/e8c2450f59f6adb8e6901e3b517da97c53f1ddad/Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java#L269)):*
This is the wrong PR for this. It needs to be fixed in #598 (IP #060 Blackboard) (if it wasn’t already)

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java, line 293 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-K96W6oo8plHHNziAIvb:-K9sCTLxJjOCfkqm80EN:923575639) ([raw file](https://github.com/beagle-pse/beagle/blob/e8c2450f59f6adb8e6901e3b517da97c53f1ddad/Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java#L293)):*
This is the wrong PR for this. It needs to be fixed in #598 (IP #060 Blackboard) (if it wasn’t already)

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java, line 317 \[r9\]](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-K96W7vW-7WuXtsd-wcK:-K9sCW77JfnVPRlit4wa:923575639) ([raw file](https://github.com/beagle-pse/beagle/blob/e8c2450f59f6adb8e6901e3b517da97c53f1ddad/Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java#L317)):*
This is the wrong PR for this. It needs to be fixed in #598 (IP #060 Blackboard) (if it wasn’t already)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613)*

**Comment by RomanLangrehr** [comment]
-blocked Blackboard is in master.

---

Review status: 4 of 15 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-:-KA0fYRFQD1byLmnTqMx:-532290486)*

**Comment by m1cm1c** [comment]
This branch has conflicts that must be resolved.

**Comment by acBerger** [comment]
- Please resolve conflicts
- Travis fails because of failing Tests

---

Review status: 1 of 148 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-:-KAPnd_tFTfJLZor83Nw:1418972438)*

**Comment by jGleitz** [comment]
Conflicts are resolved, +@m1cm1c must fix his tests

---

Review status: 0 of 148 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-KAPpr_P4fGqqktSXVIv:-KAPpr_QQsRgExvgs9vC:-1679960136) (no related file):*
Concerns @flyfl: I don’t think it’s a good idea to check in that AppSensor project. What do you need it for?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-:-KAPpmvuUX6qPPxJFTeb:-1991420640)*

**Comment by flyfl** [comment]
Review status: 0 of 148 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-KAPpr_P4fGqqktSXVIv:-KAPuWqmZCUDHPF1J1Sa:1330801096) (no related file):*
As @m1cm1c wanted an already working repository to test the Loader with, he used the AppSensor.repository file. But as my implementation of the Loader depends on the relative path of the files (to create the CodeSections), the source code of this project needed to be imported, too. I know, that this is no good solution.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613)*

**Comment by RomanLangrehr** [comment]
Review status: 0 of 148 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-KAPpr_P4fGqqktSXVIv:-KAPvs1Pw3-n0ApYL9LA:233597778) (no related file):*
Can you put the code to src/test/ressources/  ?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613)*

**Comment by RomanLangrehr** [comment]
Depends on the fail API, doesn't it?

---

Reviewed 1 of 5 files at r19, 1 of 2 files at r31, 1 of 5 files at r39, 2 of 3 files at r51.
Review status: 4 of 148 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-:-KAQG3RBMNO7P_-aAsV7:-363112808)*

**Comment by RomanLangrehr** [comment]
Reviewed 1 of 5 files at r19, 1 of 2 files at r21, 1 of 7 files at r25, 1 of 7 files at r32, 3 of 5 files at r39, 2 of 131 files at r41, 1 of 1 files at r43, 1 of 3 files at r51, 2 of 5 files at r52, 2 of 2 files at r53.
Review status: 18 of 148 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/SeffElementCreator.java, line 7 \[r53\]](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-KAQIQnN8ShVdKJ3D-Ov:-KAQIQnOeeF31rvKqJqn:-494177703) ([raw file](https://github.com/beagle-pse/beagle/blob/ed9522ad9acb3cf937e4cc43340ab3b72cf10fa1/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/SeffElementCreator.java#L7)):*
Please remove.

---

*[Core/src/main/resources/pseudoFile.md, line 2 \[r53\]](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-KAQGHZhQI62okyUWTST:-KAQGHZhQI62okyUWTSU:-433295490) ([raw file](https://github.com/beagle-pse/beagle/blob/ed9522ad9acb3cf937e4cc43340ab3b72cf10fa1/Core/src/main/resources/pseudoFile.md#L2)):*
Is this needed for tests or why is this here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613)*

**Comment by m1cm1c** [comment]
Review status: 18 of 148 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-KAPpr_P4fGqqktSXVIv:-KAQbJfjEynPBpbBmxPz:495737534) (no related file):*
A working project is needed for test coverage. Tests are still failing but the tests are correct.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613)*

**Comment by m1cm1c** [comment]
Review status: 18 of 148 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/SeffElementCreator.java, line 7 \[r53\]](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-KAQIQnN8ShVdKJ3D-Ov:-KAQbrhq986eeT-OMwIt:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/ed9522ad9acb3cf937e4cc43340ab3b72cf10fa1/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/SeffElementCreator.java#L7)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613)*

**Comment by jGleitz** [comment]
Review status: 17 of 148 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-KAPpr_P4fGqqktSXVIv:-KAQrtJQBhwvXIUxrZ1o:1670959671) (no related file):*
> A working project is needed for test coverage.

Can you elaborate? I don’t understand.

> Tests are still failing but the tests are correct.

If this is true, +@flyfl is responsible.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613)*

**Comment by RomanLangrehr** [comment]
Blocked, because depends on Fail API

**Comment by RomanLangrehr** [comment]
-- Please no more changes in this branch --
(Merging is allowed, of course.

**Comment by acBerger** [comment]
Reviewed 4 of 5 files at r39, 1 of 131 files at r41, 1 of 1 files at r43, 1 of 2 files at r48, 1 of 3 files at r51, 2 of 5 files at r52, 1 of 2 files at r53, 1 of 6 files at r57.
Review status: 17 of 150 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

Plesase let us merge this with the AppSensor files. We can change this later easily but now it would be too much work.

---

Reviewed 22 of 131 files at r41, 1 of 2 files at r48, 1 of 5 files at r52, 1 of 1 files at r55, 3 of 6 files at r57, 1 of 3 files at r58, 1 of 1 files at r59, 1 of 1 files at r60, 1 of 1 files at r63.
Review status: 46 of 150 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-:-KARx8zAnZQ8oYzxMYIG:470991219)*

**Comment by RomanLangrehr** [comment]
Review status: 46 of 150 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-KAPpr_P4fGqqktSXVIv:-KARxQy-5TFfBWnqD-IO:-1868454874) (no related file):*
Travis goes green. How can there be any failing tests?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613)*

**Comment by m1cm1c** [comment]
Review status: 46 of 150 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-KAPpr_P4fGqqktSXVIv:-KARytlJLSwmTrjnlTqR:950367944) (no related file):*
>> A working project is needed for test coverage.
>
> Can you elaborate? I don’t understand.

Code sections are needed because otherwise the blackboard wouldn't be filled by the repository loader which would not only make it impossible to test this behavior (and make for really, really bad test coverage) but also would cause all tests verifying the desired behavior to fail because they expect the resulting blackboard to be filled.

> Travis goes green. How can there be any failing tests?

Travis didn't go green when I wrote this.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613)*

**Comment by m1cm1c** [comment]
Review status: 46 of 150 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-KAPpr_P4fGqqktSXVIv:-KAS-FWHUGfVxBnAQJ-r:-347645466) (no related file):*
@jgleitz: Just look at the tests verifying that exceptions are thrown if the repository file is corrupted. The only thing corrupted about them is that for each of them a single fie path in an annotation is changed so no file is found in the (wrongly) stated location. Of course this also wouldn't work if there were no file at all. If you leave out the annotations all together, virtually nothing would work.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613)*

**Comment by RomanLangrehr** [comment]
:lgtm: 
(My lgtm won't count because I created this PR. @flyfl can you please give yourself a :lgtm: for this PR?)

---

Review status: 45 of 150 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-:-KAV2WtbNgXhDoSSPObx:-633600564)*

**Comment by flyfl** [comment]
:lgtm:

**Comment by acBerger** [comment]
:O:

I am very sorry, but there are complete classes which are not tested. 

---

Review status: 45 of 150 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-:-KAV9AwY2WMyJeZ9tIEm:1141399978)*

**Comment by acBerger** [comment]
:o: 

---

Review status: 45 of 150 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-:-KAV9PJxqNrHL4l9ASBi:676335584)*

**Comment by flyfl** [comment]
> I am very sorry, but there are complete classes which are not tested. 

**SeffElementCreator.java** is not used anymore.
**PcmRepositoryWriter.java**  and **BeagleMappings **should be tested in #706 

To the other java-files with low coverage:
**EMFHelper** I don't think we should test this source.
**PcmRepositorySeffExtractor** Test coverage is not shown for catch-blocks, although they have been executed.

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r55, 1 of 1 files at r68.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613)*

**Comment by m1cm1c** [comment]
Reviewed 2 of 5 files at r19, 1 of 2 files at r21, 1 of 7 files at r25, 4 of 5 files at r39, 1 of 131 files at r41, 1 of 1 files at r43, 1 of 2 files at r48, 2 of 3 files at r51, 3 of 5 files at r52, 1 of 2 files at r53, 1 of 1 files at r55, 1 of 6 files at r57, 1 of 1 files at r71, 1 of 1 files at r72.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613)*

**Comment by m1cm1c** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-:-KAVqn1vs7ypAqI5OG24:1417088721)*

**Comment by RomanLangrehr** [comment]
:white_check_mark: 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-:-KAVrUTvsl5uTPw1xfUW:1605498549)*

**Comment by m1cm1c** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/resources/pseudoFile.md, line 2 \[r53\]](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-KAQGHZhQI62okyUWTST:-KAVsrKpqk55Rrzq5h2s:166857) ([raw file](https://github.com/beagle-pse/beagle/blob/ed9522ad9acb3cf937e4cc43340ab3b72cf10fa1/Core/src/main/resources/pseudoFile.md#L2)):*
.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613)*

**Comment by RomanLangrehr** [comment]
@flyfl Please renew your lgtm.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/613#-:-KAVsuFCmd1U5uo4Uwmh:-926255244)*

**Comment by flyfl** [comment]
:lgtm:

**Pull request merged**
