### PR TITLE
Purpose and Goals Improvements. Fixes #155.

### LINKED ISSUE #155: Purpose and Goals Improvements
### 1.1 Criteria

- /P10/  can easily be misunderstood, either change "analyse" to a better fitting word or try to make clear what we mean in an other way.

- /P30/ this can be followed from /P10/ and /P20/. Expand these points to include /P30/.

### 1.2 Boundary
 - /B40/  As Beagle could be used with other languages than Java if it is implemented for this, this point should be deleted.

### PR DESCRIPTION
**Pull request by m1cm1c**

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
[PDF](http://m1cm1c.github.io/Beagle/branches/issue-155/Requirements%20Specification.pdf)

**Comment by RomanLangrehr** [comment]
Lgtm

**Comment by acBerger** [comment]
> /P10/ [...] regarding the resources
its internal actions’ demand when executed.

I don't think this is a correct sentence.

**Comment by m1cm1c** [comment]
Why not?

**Comment by jGleitz** [comment]
How about

“Beagle enables users to measure the resources given source code's internal actions demand when executed”

instead of

>Beagle enables the user to analyse given source code regarding the resources its internal actions demand when executed.

**Comment by m1cm1c** [comment]
> How about
>
> “Beagle enables users to measure the resources given source code's internal actions demand when executed”

I think this sentence doesn't make sense.

**Comment by jGleitz** [comment]
> I think this sentence doesn't make sense.

Why not?

**Comment by m1cm1c** [comment]
1. You don't measure resources. You measure resource demands.
2. Do you really want to say "source code's internal actions demand"? We don't care about demand on internal actions but about demand on the resources these internal actions use.

**Comment by jGleitz** [comment]
Well, unfortunately, you failed to build sentence correctly (although the part you failed to comprehend is **exactly** like in yours). Let’s compare:

>Beagle enables the user to analyse given source code regarding the resources its internal actions demand when executed.

Means: the internal actions, which are properties of the source code, demand resources, and we’re going to analyse that.

> Beagle enables users to measure the resources given source code's internal actions demand when executed

Means: the internal actions, which are properties of the source code, demand resources, and we’re going to measure that.

**Comment by jGleitz** [comment]
You know what? I’m **so** tired of these discussions. We’re bashing arguments about ***absolutely irrelevant*** stuff in our faces. I’m feeling like a five year old again when doing that.

Please just use the sentence you want. We just need to stop these discussion. I have code to write.

lgtm

**Comment by flyfl** [comment]
lgtm

**Pull request merged**
