### PR TITLE
Ip 160 Fitness Function

### PR DESCRIPTION
**Pull request by m1cm1c**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/700)

### CODE REVIEW

**Comment by acBerger** [comment]
[Website] (http://beagle-pse.github.io/Beagle/branches/ip-160-fitness-function/)

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/700#-:-KARu-5D9eftQQIWY6az:1754167274)*

**Comment by viridispirus** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/700)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/700#-:-KASCim3pG-TEnqDzxKQ:980077423)*

**Comment by RomanLangrehr** [comment]
:white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/700#-:-KASCu65v54gHIdWorlc:1605498549)*

**Comment by viridispirus** [comment]
:lgtm:  :white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/700#-:-KAUQVQJfMVGA9u7Y38r:697796009)*

**Pull request merged**
