### PR TITLE
This fixes gradle!

### PR DESCRIPTION
**Pull request by RomanLangrehr**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/648)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
:lgtm:

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/648#-:-K9DcfO6ggbT_PcpoYUb:1417088721)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/648#-:-K9DeZMtoEdfUzY1lYob:980077423)*

**Comment by acBerger** [comment]
+blocked 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/648#-:-K9DgBfFJU_Ost5Ofw-2:-1952923270)*

**Comment by acBerger** [comment]
-blocked 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/648#-:-K9DhRqkP7198AAkFfvq:-1272864900)*

**Pull request merged**
