### PR TITLE
[design] details about reading and writing from and to the PCM.

### PR DESCRIPTION
**Pull request by jGleitz**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/554)

### CODE REVIEW

**Comment by jGleitz** [comment]
+blocked, wrong blackboard diagram

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/554#-:-K7hPwyIsvpw9y2ZLibD:1630561959)*

**Comment by flyfl** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/554#-:-K7hQ0Qp4FzjX18hBoKk:1417088721)*

**Comment by jGleitz** [comment]
not blocked, the Blackboard fix is not even merged yet. My bad.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/554#-:-K7hQARaBoJoWmARWVO9:-1614837683)*

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/554#-:-K7hRbe02oMG4vJbZfpf:1417088721)*

**Comment by viridispirus** [comment]
please update.

**Pull request merged**
