### PR TITLE
Fixed invalid BiBTeX entries. Fixes #107.

### LINKED ISSUE #107: Invalid BiBTeX-entries: conwaysLaw, tuChemPcm
This entry is invalid, as it doesn't provide enough information (Title, Author, etc are always required).

And when citing websites: _Always write down, when you visited the website and make a local copy!_
We can discuss, if it would be a good idea to put these local copys in our repo.

### PR DESCRIPTION
**Pull request by m1cm1c**
I included the local copies into the repository. Please comment on this.

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
I'm not sure, whether we should put the website copies in our repo. This kind of "spams" it.

**Comment by jGleitz** [comment]
Oh no, I don’t like where this is heading.

Can’t we find a published paper for those two statements? That would be nicer and mor “professional” altogether.

Starting to copy webpages for the sake of two little citations seems like using a sledgehammer to crack a nut to me.

**Comment by m1cm1c** [comment]
Conway's law is in a book and I used the publishing date of this book. The website is the website of the author.

Should I tar these websites to avoid spaming a lot of files in there?

**Comment by jGleitz** [comment]
Once again, there surely are papers we can use for citing. If you think that your citation is in the book, just cite the book. I’m sure nobody will check this. (If you’re a corrector and reading this, be honest, you already did something like that, too :D)

**Comment by m1cm1c** [comment]
I already did this for Conway's Law with my commits 14 minutes ago. I'll search for a source of the other one.

**Comment by RomanLangrehr** [comment]
> Should I tar these websites to avoid spaming a lot of files in there?

Much better than before. Thanks.

**Comment by jGleitz** [comment]
> I'll search for a source of the other one.

:+1:

**Comment by m1cm1c** [comment]
As it turned out, this was copied by several university websites. I found a paper with the exact same wording in it and quoted it.

**Comment by RomanLangrehr** [comment]
Lgtm.

**Comment by flyfl** [comment]
lgtm

**Comment by jGleitz** [comment]
> As it turned out, this was copied by several university websites. I found a paper with the exact same wording in it and quoted it.

Marvellous.

**Pull request merged**
