### PR TITLE
Documented and Applied SRS Changes.

### PR DESCRIPTION
**Pull request by jGleitz**
Also moves the section about the CTA.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/504)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
Missing whitespace.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/504#-:-K7bFRE8a2t75MgIyWKZ:807367162)*

**Comment by RomanLangrehr** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/504)*

**Comment by RomanLangrehr** [comment]
[Website](http://jgleitz.github.io/Beagle/branches/srs-changes/).

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/504#-:-K7bjtz2pz8XTTTNS0op:-110651087)*

**Comment by acBerger** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/504#-:-K7bm3KU_1TlhS1SnCXe:980077423)*

**Comment by RomanLangrehr** [comment]
> ✂-1
Missing whitespace.

Not yet fixed

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/504#-:-K7bpdDoeiVeAWGPfSla:1550575939)*

**Comment by flyfl** [comment]
:lgtm: 

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/504#-:-K7brh-nur9Hbx3t36MM:980077423)*

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/504#-:-K7c49V8rvgTtQzI2-i0:1417088721)*

**Pull request merged**
