### PR TITLE
ProgressDialogController: fix open & close

### PR DESCRIPTION
**Pull request by jGleitz**
The fixes we did in the last meeting.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/792)

### CODE REVIEW

**Comment by viridispirus** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/792#-:-KCLoax_QXDe4NGjaI5t:980077423)*

**Comment by jGleitz** [comment]
I pushed another commit. It fixes a bug I introduced when fixing the other bugs.

It also significantly improves the code’s quality by removing duplicated code and using constants instead of magic numbers.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/792#-:-KCLv3k49EJmqC6qQW_H:32649365)*

**Comment by m1cm1c** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[GUI/src/main/java/de/uka/ipd/sdq/beagle/gui/ProgressDialogController.java, line 108 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/792#-KCM0T5-fPJsEg4l9c9j:-KCM0T5-fPJsEg4l9c9k:1113248246) ([raw file](https://github.com/beagle-pse/beagle/blob/1d8b4cab93d68005f83d1bc57fa35f5e03662b3b/GUI/src/main/java/de/uka/ipd/sdq/beagle/gui/ProgressDialogController.java#L108)):*
You can use `MessageDialog.NONE` here instead of `0`. (Same for the other occurrences.)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/792)*

**Comment by viridispirus** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/792)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/792)*

**Comment by jGleitz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[GUI/src/main/java/de/uka/ipd/sdq/beagle/gui/ProgressDialogController.java, line 108 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/792#-KCM0T5-fPJsEg4l9c9j:-KCRAnBPmOS1TO7sUb7l:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/27cbc083e1467dcdac2c2f89b0f0c5d0fb73bf95/GUI/src/main/java/de/uka/ipd/sdq/beagle/gui/ProgressDialogController.java#L108)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/792)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/792)*

**Comment by RomanLangrehr** [comment]
:lgtm: :white_check_mark: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/792#-:-KCRHg4B_CWmqxmdko3W:-1603124213)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/792#-:-KCRHvEbbQP29sj4pxjU:980077423)*

**Comment by m1cm1c** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[GUI/src/main/java/de/uka/ipd/sdq/beagle/gui/ProgressDialogController.java, line 108 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/792#-KCM0T5-fPJsEg4l9c9j:-KCRJTB3y3M9wE14x4c0:551209080) ([raw file](https://github.com/beagle-pse/beagle/blob/27cbc083e1467dcdac2c2f89b0f0c5d0fb73bf95/GUI/src/main/java/de/uka/ipd/sdq/beagle/gui/ProgressDialogController.java#L108)):*
You put `BUTTON_PAUSE_OR_CONTINUE` there, not `MessageDialog.NONE`. This now probably shows a graphic in the dialog.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/792)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[GUI/src/main/java/de/uka/ipd/sdq/beagle/gui/ProgressDialogController.java, line 108 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/792#-KCM0T5-fPJsEg4l9c9j:-KCRLBFdbMKXuVNiKtH1:-813802592) ([raw file](https://github.com/beagle-pse/beagle/blob/27cbc083e1467dcdac2c2f89b0f0c5d0fb73bf95/GUI/src/main/java/de/uka/ipd/sdq/beagle/gui/ProgressDialogController.java#L108)):*
No. The last argument to the constructor specifies the default button index. The dialog’s image is set in the 5th argument, which is set to the `INFORMATION` image, which makes sense.

Please refer to [`MessageDialog`’s documentation](http://help.eclipse.org/juno/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjface%2Fdialogs%2FMessageDialog.html).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/792)*

**Pull request merged**
