### PR TITLE
Analyser stubs

### LINKED ISSUE #518: Adapt Java Stubs to Design: Analysers
Adapt the old `Measurement Analyser` and create `Proposed Expression Analyser`.

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Fixes #518 
However, the views must be adapted. But they don't exist yet.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/528)

### CODE REVIEW

**Comment by acBerger** [comment]
Reviewed 7 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/528)*

**Comment by acBerger** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/528)*

**Comment by m1cm1c** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/528#-:-K7gYkHxoasSTTwd5D21:980077423)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/528#-:-K7ghOsXB4pSWvVJh22s:1417088721)*

**Pull request merged**
