### PR TITLE
Added two more sentences to justify why Beagle will not use the CTA

### LINKED ISSUE #369: Modifications of SRS
Do we want to adapt the SRS? Following the document Roman found, we can change the SRS to fit to the Design.

### PR DESCRIPTION
**Pull request by flyfl**
fixes #369

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/494)

### CODE REVIEW

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/494#-:-K7a4XNwe66OCGHQ8U93:1417088721)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/494#-:-K7a6HHJDSER5dttUspC:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/494#-:-K7a6p3hh-SVAokhdoD4:980077423)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/494)*

**Pull request merged**
