### PR TITLE
Design frame document.

### LINKED ISSUE #368: Create Document Frame for Design
TOC:

 * Architectual Overview
      * Overview of the whole system
      * Description of components’ interaction
 * Communication between Core and external Components
 * Component: Beagle Core
      * Describe most important classes
      * Give reasons for chosen design
      * Describe chosen design patterns
      * Describe Evaluable Expressions
      * Describe conversion from and to Palladio
 * Component: Beagle GUI
      * Describe most important classes
      * Give reasons for chosen design
      * Describe chosen design patterns (Model-View-Controller!)
 * Component: Measurement Tool
      * Give reasons for the generally chosen design
      * Describe adapter to Kieker
 * Component: Result Analyser
      * Give reasons for the generally chosen design
 * Component: Final Judge
      * Give reasons for the generally chosen design
      * Describe the Final Judge that will be implement in the first iteration (averaging Final Judge)

Generally:
 * List all associated packages for each point

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Fixes #368 

I added some sample *section* headlines, according to the TOC. They can be changed, of course.

I think
>      * Description of components’ interaction
 * Communication between Core and external Components

was duplicated. (Maybe it was a mistake). I changed the second point to `Communication between Beagle and external tools` and made it a section in the first chapter.

Here is the [rendered document](https://www.dropbox.com/s/t7mb67vogll95x8/Design.pdf?dl=0).

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/378)

### CODE REVIEW

**Comment by jGleitz** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[doc/Design/Design.lyx, line 53 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/378#-K72snnkHSxYeKY8VZzK:-K72snnlp5IdMtnLTv7a:36504547) ([raw file](https://github.com/beagle-pse/beagle/blob/f44878d823dcd5496c2f678a7eb48ada28f04ac1/doc/Design/Design.lyx#L53)):*
The usage of the ampersand is informal. Plus, there is an “n” at the end which does not belong there (but does not show up in your rendering)

---

*[doc/Design/Parts/Component Beagle GUI.lyx, line 74 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/378#-K72tugXicNvX9_wpeUO:-K72tugXicNvX9_wpeUP:1810812093) ([raw file](https://github.com/beagle-pse/beagle/blob/f44878d823dcd5496c2f678a7eb48ada28f04ac1/doc/Design/Parts/Component Beagle GUI.lyx#L74)):*
hyphen missing

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/378)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[doc/Design/Parts/Component Beagle GUI.lyx, line 74 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/378#-K72tugXicNvX9_wpeUO:-K72uJhhFXV8rNUH0aOQ:-835716975) ([raw file](https://github.com/beagle-pse/beagle/blob/f44878d823dcd5496c2f678a7eb48ada28f04ac1/doc/Design/Parts/Component Beagle GUI.lyx#L74)):*
colon missing, I’m sorry. At least you used a colon for the other headings.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/378)*

**Comment by acBerger** [comment]
Reviewed 8 of 8 files at r1.
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/378)*

**Comment by RomanLangrehr** [comment]
Review status: 4 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[doc/Design/Design.lyx, line 53 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/378#-K72snnkHSxYeKY8VZzK:-K72vNv9WNYPz6qbYUYl:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/f44878d823dcd5496c2f678a7eb48ada28f04ac1/doc/Design/Design.lyx#L53)):*
Done.

---

*[doc/Design/Parts/Component Beagle GUI.lyx, line 74 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/378#-K72tugXicNvX9_wpeUO:-K72vKhjZi9IgDM8Zzjf:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/f44878d823dcd5496c2f678a7eb48ada28f04ac1/doc/Design/Parts/Component Beagle GUI.lyx#L74)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/378)*

**Comment by jGleitz** [comment]
Review status: 4 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[doc/Design/Design.lyx, line 53 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/378#-K72vY3bq4B6uTn8fh4R:-K72vY3cHQ4ZOFvhqNeL:-2105350913) ([raw file](https://github.com/beagle-pse/beagle/blob/f44878d823dcd5496c2f678a7eb48ada28f04ac1/doc/Design/Design.lyx#L53)):*
No, you did not. This line sets the pdf metadata (not the same as the subtitle). I didn’t realise that when writing the comment, too.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/378)*

**Comment by jGleitz** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/378)*

**Comment by RomanLangrehr** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/Design/Design.lyx, line 53 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/378#-K72vY3bq4B6uTn8fh4R:-K72wJ-ARK3EsfjIGqut:853443570) ([raw file](https://github.com/beagle-pse/beagle/blob/f44878d823dcd5496c2f678a7eb48ada28f04ac1/doc/Design/Design.lyx#L53)):*
I know. And I changed it for both to `and`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/378)*

**Comment by acBerger** [comment]
:lgtm: 

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/378#-:-K72wNyrpT4qlQRMZBjP:980077423)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/Design/Design.lyx, line 53 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/378#-K72vY3bq4B6uTn8fh4R:-K72wW5JS6uACGn8hFa6:-1600867599) ([raw file](https://github.com/beagle-pse/beagle/blob/f44878d823dcd5496c2f678a7eb48ada28f04ac1/doc/Design/Design.lyx#L53)):*
That change did not show up for me when writing that comment. I’m sorry.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/378#-:-K72wgC1qpH7DKBCWyLy:980077423)*

**Comment by RomanLangrehr** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/Design/Design.lyx, line 53 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/378#-K72vY3bq4B6uTn8fh4R:-K72y2zMRU3ukswKhnEY:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/f44878d823dcd5496c2f678a7eb48ada28f04ac1/doc/Design/Design.lyx#L53)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/378)*

**Comment by RomanLangrehr** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/Design/Design.lyx, line 53 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/378#-K72vY3bq4B6uTn8fh4R:-K72y6SbJlnpJSNo4kUy:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/f44878d823dcd5496c2f678a7eb48ada28f04ac1/doc/Design/Design.lyx#L53)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/378)*

**Pull request merged**
