### PR TITLE
Moved Facade-Specific Classes out of Core

### LINKED ISSUE #742: Move Facade-Specifc Classes from Core to Facade
* `EclipseLaunchConfiguration`
 * `BlackboardCreator`

### PR DESCRIPTION
**Pull request by jGleitz**
Fixes #742 

I think that only facade and pcmconnection classes were affected by this change proves my point.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/750)

### CODE REVIEW

**Comment by m1cm1c** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/750)*

**Comment by m1cm1c** [comment]
:white_check_mark:

**Comment by m1cm1c** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/750#-:-KBE0_Mn9zgFJVdRViWq:1417088721)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/750#-:-KBE2x4RTpXTl3S_gUaM:980077423)*

**Comment by viridispirus** [comment]
Out of date.

**Pull request merged**
