### PR TITLE
Blackboard Diagram Fix

### PR DESCRIPTION
**Pull request by jGleitz**
I hope that everything is fine now.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/550)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
[Website](http://jgleitz.github.io/Beagle/branches/blackboard-fix/)

**Comment by RomanLangrehr** [comment]
This should be removed.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/550#-:-K7hD_2zlG2lstnThGHW:-315963914)*

**Comment by RomanLangrehr** [comment]
Something is wrong with the intedation here.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/550#-:-K7hDp8idvSZuTxJoKKp:-383561911)*

**Comment by jGleitz** [comment]
@RomanLangrehr fixed

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/550#-:-K7hGBisenjB04hcPPXO:641704961)*

**Comment by m1cm1c** [comment]
Please add the blackboard constructor.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/550#-:-K7hIPF-f2I4zX-_8Mx9:978930734)*

**Comment by m1cm1c** [comment]
This branch is out-of-date with the base branch.

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/550#-:-K7hSarTVmM7nZ96BxNk:1417088721)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/550#-:-K7hXnWJkS2EICjx-hR7:980077423)*

**Comment by m1cm1c** [comment]
Please update branch.

**Pull request merged**
