### PR TITLE
Resource type mappings

### LINKED ISSUE #657: Write to PCM models

### PR DESCRIPTION
**Pull request by flyfl**
This should finally fix #657

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/735)

### CODE REVIEW

**Comment by acBerger** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryWriterAnnotator.java, line 223 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/735#-KAk69nPJcrBW3KgaGY2:-KAk69nQHYude91jXLIl:1386622705) ([raw file](https://github.com/beagle-pse/beagle/blob/4953657aec4f1a98d7dd2411ae193079c02c3203/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryWriterAnnotator.java#L223)):*
I do not think we need 2 blank lines here Please use the Formatter & Clean-Up on all your classes.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/735)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/735#-:-KAk76XvH0cKYmHJennm:980077423)*

**Comment by viridispirus** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/735)*

**Comment by jGleitz** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryWriterAnnotator.java, line 221 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/735#-KAkE2CsYzivVp9i2EiO:-KAkE2CsYzivVp9i2EiP:-1507574381) ([raw file](https://github.com/beagle-pse/beagle/blob/4953657aec4f1a98d7dd2411ae193079c02c3203/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryWriterAnnotator.java#L221)):*
The above lines could be a one liner with the Apache Commons:

```java
final ListIterator<EObject> contentListIterator = IteratorUtils.toListIterator(repository.eAllContents());
```

I think this is much easier to read. See https://commons.apache.org/proper/commons-collections/javadocs/api-release/org/apache/commons/collections4/IteratorUtils.html#toListIterator%28java.util.Iterator%29

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/735)*

**Comment by acBerger** [comment]
Reviewed 5 of 9 files at r3.
Review status: 5 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/735)*

**Comment by acBerger** [comment]
:lgtm: :white_check_mark: 

---

Reviewed 2 of 9 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/735#-:-KAtUz0KuiwYqfeENlKL:-1603124213)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 2 of 9 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/735#-:-KAt_vZuZWBadTkJVPrd:980077423)*

**Pull request merged**
