### PR TITLE
Test Fix

### PR DESCRIPTION
**Pull request by jGleitz**
This should fix the failing tests @acBerger and @flyfl are facing when running gradle.

---
This change is [Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/816)

### CODE REVIEW

**Comment by acBerger** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/816)*

**Comment by jGleitz** [comment]
Does not work because this is actually for after #796

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/816)*

**Comment by jGleitz** [comment]
-blocked because #796 is merged.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/816#-:-KClAKJWhyejW0PKTD5F:-690444955)*

**Comment by RomanLangrehr** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/816#-:-KClBRkqQJG9ha2FwAYa:1417088721)*

**Comment by acBerger** [comment]
:lgtm: :white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/816#-:-KClFKdqbka_zCQPT5Mf:-1603124213)*

**Pull request merged**
