### PR TITLE
Design control flow

### LINKED ISSUE #389: Describe the purpose of `Beagle Controller`
This includes its interaction with `Measurement Controller`, `Result Analyser`, `Final Jugde`.

### LINKED ISSUE #397: Make final judge an interface in class diagram

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Fixes #389 
Fixes #397

[PDF](https://www.dropbox.com/s/om5t8mrhsta7zf2/Design.pdf?dl=0)

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/404)

### CODE REVIEW

**Comment by jGleitz** [comment]
Depends on #352 (Design: Improvments for Controllers) +blocked 

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/404#-:-K76f7VRGBvHYlTX4ajl:1255693052)*

**Comment by RomanLangrehr** [comment]
Double blocked because I destoried this PR!

**Comment by jGleitz** [comment]
> Double blocked because I destoried this PR!

What do you mean by “destroy”?

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/404#-:-K76mSt625BvFwwCtfH-:-1774307173)*

**Comment by RomanLangrehr** [comment]
> What do you mean by “destroy”?

The last two commits should go in another PR.

**Comment by RomanLangrehr** [comment]
I force psuhed, but they don't get away in this PR.

**Comment by RomanLangrehr** [comment]
> The last two commits should go in another PR.

Fixed.

**Comment by jGleitz** [comment]
-(help wanted) 

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/404#-:-K76zViLdhEy2mW0O2Cb:-1276057435)*

**Comment by jGleitz** [comment]
[View this PR’s rendered artefacts](http://romanlangrehr.github.io/Beagle/branches/design-control_flow/)

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/Design/Parts/Component Beagle Core.lyx, line 243 \[r6\]](https://reviewable.io:443/reviews/beagle-pse/beagle/404#-K777NXSiYq0tRJe0pvS:-K777NXThv3IMN81COkh:196235303) ([raw file](https://github.com/beagle-pse/beagle/blob/add78bcc59043ba37d360db0aa9fbc30f6e3aad1/doc/Design/Parts/Component Beagle Core.lyx#L243)):*
You are using an absolute path here! Unfortunately, Travis can’t detect that because we have that workaround for LyX.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/404#-:-K777AxAUP4wepzKIfiN:-732851267)*

**Comment by RomanLangrehr** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/Design/Parts/Component Beagle Core.lyx, line 243 \[r6\]](https://reviewable.io:443/reviews/beagle-pse/beagle/404#-K777NXSiYq0tRJe0pvS:-K77CUhdRkBhqInZgZm7:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/add78bcc59043ba37d360db0aa9fbc30f6e3aad1/doc/Design/Parts/Component Beagle Core.lyx#L243)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/404)*

**Comment by jGleitz** [comment]
Can you give a summary of what this PR introduces? I see the chapter in the design document and the component diagram.

---

Reviewed 2 of 7 files at r1.
Review status: 2 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/404#-:-K77Rs0HwVYOopOf1cI1:-1144265177)*

**Comment by RomanLangrehr** [comment]
> Can you give a summary of what this PR introduces? I see the chapter in the design document and the component diagram.

That's it. The diagram is made with papyrus, so there is a new class diagram file.

---

Review status: 2 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/404#-:-K77SDM2MZgVPrWAB32p:1503241286)*

**Comment by jGleitz** [comment]
:lgtm_strong: 

---

Review status: 2 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/404#-:-K77SkINtZRlIDtUqMhX:-1868698381)*

**Comment by jGleitz** [comment]
Reviewed 2 of 7 files at r1, 1 of 4 files at r8, 3 of 3 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/404)*

**Comment by acBerger** [comment]
The diagram on page 4 of the Design Document is not readable and it seems to be to big for the page.

---

Reviewed 4 of 7 files at r1, 1 of 4 files at r8, 3 of 3 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/404#-:-K77VgUKnPu8Zgo9Cw-g:-1021714508)*

**Comment by RomanLangrehr** [comment]
> The diagram on page 4 of the Design Document is not readable and it seems to be to big for the page.

If you see a better way to arrange the classes, feel free to do so. I already tried a lot and this is the best I solution I found. And as we do everything with vector graphics, you can just zoom in ;)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/404#-:-K78223OK5V3ARIdKPMo:523045295)*

**Comment by acBerger** [comment]
This is not a problem you can solve with zooming in. You can hardly read it, because it is distorted.
And it does not fit on the page.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/404#-:-K782eBPk4VsdpjLpaz6:1578734930)*

**Comment by RomanLangrehr** [comment]
Oh. That was a mistake. Done.

---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/404#-:-K785If72YnqQHgh19Zl:-1966397957)*

**Comment by acBerger** [comment]
@RomanLangrehr you are out of date

**Comment by acBerger** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/404#-:-K789pZnLOGIFVzhQkU2:-1868698381)*

**Comment by acBerger** [comment]
This branch is out-of-date with the base branch

**Pull request merged**
