### PR TITLE
Corrrected spelling errors and different small changes.

### PR DESCRIPTION
**Pull request by m1cm1c**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/568)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/568#-:-K7iAHofb1L0T_iq2_6T:980077423)*

**Comment by m1cm1c** [comment]
:lgtm:

**Comment by jGleitz** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Documentation/src/design/lyx/Parts/Blackboard.lyx, line 102 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/568#-K7iP9A1eJLdtmkxDFzV:-K7iP9A1eJLdtmkxDFzW:-792340094) ([raw file](https://github.com/beagle-pse/beagle/blob/258bae5a6f36070782658d87bc528dcff5d2e2a6/Documentation/src/design/lyx/Parts/Blackboard.lyx#L102)):*
This change actually introduces a different, wrong meaning. Roman wrote: “The fact that everything is on the blackboard, together with the fact that everything on the blackboard is serialisable, allows that the whole analysis can be serialised”, which is true.
You’re saying something else I can’t quite put into a sentence. But the fact that everything on the blackboard is serialisable is not a consequence of the fact that the analysis is serialisable. It’s the other way round.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/568)*

**Comment by m1cm1c** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Documentation/src/design/lyx/Parts/Blackboard.lyx, line 102 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/568#-K7iP9A1eJLdtmkxDFzV:-K7iTSU6fvGwjqtjIAG1:1547480808) ([raw file](https://github.com/beagle-pse/beagle/blob/258bae5a6f36070782658d87bc528dcff5d2e2a6/Documentation/src/design/lyx/Parts/Blackboard.lyx#L102)):*
You're reading it wrong. 

"all starts information is stored on the blackboard" => "serialization of 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/568)*

**Comment by m1cm1c** [comment]
You're reading it wrong. 

"all starts information is stored on the blackboard" => "serialisation of an analysis is possible" 

Reason: As a consequence of this decision, all elements on the blackboard are serialisable. 

On January 11, 2016 3:09:53 AM GMT+01:00, Joshua Gleitze <notifications@github.com> wrote:
>
>
>
>
>Reviewed 2 of 2 files at r1.
>Review status: all files reviewed at latest revision, 1 unresolved
>discussion.
>
>---
>
>*[Documentation/src/design/lyx/Parts/Blackboard.lyx, line 102
>\[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/568#-K7iP9A1eJLdtmkxDFzV:-K7iP9A1eJLdtmkxDFzW:-792340094)
>([raw
>file](https://github.com/beagle-pse/beagle/blob/258bae5a6f36070782658d87bc528dcff5d2e2a6/Documentation/src/design/lyx/Parts/Blackboard.lyx#L102)):*
>This change actually introduces a different, wrong meaning. Roman
>wrote: “The fact that everything is on the blackboard, together with
>the fact that everything on the blackboard is serialisable, allows that
>the whole analysis can be serialised”, which is true.
>You’re saying something else I can’t quite put into a sentence. But the
>fact that everything on the blackboard is serialisable is not a
>consequence of the fact that the analysis is serialisable. It’s the
>other way round.
>
>---
>
>
>*Comments from the [review on
>Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/568)*
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Beagle-PSE/Beagle/pull/568#issuecomment-170416905

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by flyfl** [comment]
:lgtm:

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Documentation/src/design/lyx/Parts/Blackboard.lyx, line 102 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/568#-K7iP9A1eJLdtmkxDFzV:-K7kbTJdd1vsp0LsegRC:2135855078) ([raw file](https://github.com/beagle-pse/beagle/blob/258bae5a6f36070782658d87bc528dcff5d2e2a6/Documentation/src/design/lyx/Parts/Blackboard.lyx#L102)):*
> "all starts information is stored on the blackboard" => "serialization of 

Yes, this part is clear (because that’s the one you left untouched). But you are saying:

“[…] all status information is stored on the Blackboard […] as a consequence of this all elements  on the blackboard are serialisable” which is plain *wrong*.

You could say:

“[…] all status information is stored on the Blackboard […] as a consequence of this all elements  on the blackboard **[must be]** serialisable”, but that would still be a worse sentence than the initial one.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/568)*

**Comment by m1cm1c** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[Documentation/src/design/lyx/Parts/Blackboard.lyx, line 102 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/568#-K7iP9A1eJLdtmkxDFzV:-K7iUxX_odtq_mHIgweV:1143570141) ([raw file](https://github.com/beagle-pse/beagle/blob/258bae5a6f36070782658d87bc528dcff5d2e2a6/Documentation/src/design/lyx/Parts/Blackboard.lyx#L102)):*
I disagree but don't care. Undid the change.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/568)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/568#-:-K7ko0-u3hZ40up78oaK:980077423)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/568#-:-K7lUQrJjBKIJCik1ffa:980077423)*

**Pull request merged**
