### PR TITLE
Component diagram

### PR DESCRIPTION
**Pull request by viridispirus**
I have forget which was the last input. Can someone help me?

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/485)

### CODE REVIEW

**Comment by viridispirus** [comment]
fixes #481.

**Comment by viridispirus** [comment]
Here is the diagram:

componemtmodel

**Comment by jGleitz** [comment]
The right one is called `Measurement Result Analyser` (since today). The bottom right is `Proposed Expression Analyser`.

**Comment by jGleitz** [comment]
You could make the component less high and the lines a little shorter to make everything more compact. Apart from that: lgtm

**Comment by jGleitz** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/485)*

**Comment by viridispirus** [comment]
componemtmodel

**Comment by acBerger** [comment]
:lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/485#-:-K7_rTojSzY8y3uDRmFP:980077423)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/485)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/485#-:-K7_smD2Q37fcCCZHk8M:980077423)*

**Pull request merged**
