### PR TITLE
Increased NCSS limit for tests.

### PR DESCRIPTION
**Pull request by RomanLangrehr**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/685)

### CODE REVIEW

**Comment by viridispirus** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/685)*

**Comment by m1cm1c** [comment]
:lgtm:

**Comment by m1cm1c** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/685)*

**Comment by jGleitz** [comment]
Sure that that makes sense? I mean that there will be a case where there’s no meaningful way to split the test method?

(I for example managed to get small methods in the final judge test by only testing one thing in one method, even though all tests tested the same method).

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/685#-:-KALVjs1I5V8Iz55Gtrg:884867758)*

**Comment by RomanLangrehr** [comment]
Probably that's the better solution.

**Pull request closed without merging**
