### PR TITLE
Scalable Project Directory Structure

### PR DESCRIPTION
**Pull request by jGleitz**
This PR aims to rework our repository’s file structure to better represent our design and improve various other aspects like scalability and consistency.

### Why?
**Or repository reflects our design**. Or at least, it should. 

When thinking about #463, I realised that *concrete classes do not belong to the API*. They will be plugged in using Eclipse’s extension points and thus should be developed as projects of their own.
I then realised that there were other changes I thought our repository badly needs. So I started adapting the structure.

### Subproject structure
In the new layout, every major aspect of our project is a subproject. This makes for **good scalability**. Over the time, we plan to develop the `Averaging Final Judge`, the `Kieker Measurement Tool`, some `Result Analyser`s and the `Genetical Final Judge`. These should be independent from each other. Thus, we’ll create a new subproject for each. This will keep the structure clean and easy to understand.

Besides various other advantages, the new structure is from my point of view more consistent regarding our naming convention: Everything is written in English Caption Style except for elements of the standard layout structure. 

#### Core
This project holds all classes we’ve written so far. I left it untouched except for moving all classes into a common `de.uka.ipd.sdq.beagle.core` package.

#### Documentation
One major change: The lyx files are treated as source files. This makes a lot of sense, as they *are* source files that will be built using gradle. The structure should reflect that!

#### Web presence 
All files building the Web Presence. I moved some of our `.md` to this project, to publish them on the website. I think this has some advantages:
 * These important documentation files can be found more easily as they can be linked and cross-referenced on the website.
 * The website becomes **the central documentation artefact**, linking all other artefacts. I think this is really cool, because we can tell our tutors and people interested in our project: Look, here is everything about our project!”!
 * The `.md` files are rendered more nicely ;)

#### Build Logic
The build logic was split and distributed to the relevant projets. gradle’s configuration (but not usage!) became a little more complex, but also more flexible.

### Reviewing
This PR is a **proposal**. It’s meant to be discussed, I’m sure I did not find the perfect solution everywhere. Please take your time to carefully think everything through. I think this PR makes such fundamental changes that **it requires a lgtm from everyone**.

Please note that you’ll want to import all new Eclipse projects. (`File > Import > General > Existing Projects Into Workspace > Next > select Beagle as root directory > Check ”Search for nested projects" > Finish)

Please do also have a look at [the new website](http://jgleitz.github.io/Beagle/branches/project-structure/), that also includes [an explanation of the new structure](http://jgleitz.github.io/Beagle/branches/project-structure/Developers.html).

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/467)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
[artefacts](http://jgleitz.github.io/Beagle/branches/project-structure/)

**Comment by RomanLangrehr** [comment]
I don't know, if this a problem of your pull request, but in the web presence the links for the reports (Checkstyle and Code Coverage) don't work.

---

Review status: 0 of 185 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/467#-:-K7T2pUYVfetQJZRd2yJ:314509492)*

**Comment by RomanLangrehr** [comment]
The folder prototypes shoudl be called Prototypes.

Please note:
After merging this PR everybody has to clean up the Beagle folder a little bit by himself, because the files ignored by git don't get moved ;)

I like the new structure.

---

Review status: 0 of 185 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/467#-:-K7T4Q7k1EIL4rbRZ38o:-871288540)*

**Comment by jGleitz** [comment]
> in the web presence the links for the reports (Checkstyle and Code Coverage) don't work.

Jacoco (Test Coverage) never worked because we have no tests yet. I pushed a fix for Checkstyle.

> The folder prototypes shoudl be called Prototypes.

Which one do you mean? There [exists a `/Prototypes`](https://github.com/jGleitz/Beagle/tree/project-structure/Prototypes), but no `/prototypes`.

> After merging this PR everybody has to clean up the Beagle folder a little bit by himself, because the files ignored by git don't get moved ;)

Maybe this is your problem for the `/Prototypes` folder?

---

Review status: 0 of 195 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/467#-:-K7TL1cgzifZ1_GYA-_7:-1613098016)*

**Comment by RomanLangrehr** [comment]
> Which one do you mean? There [exists a `/Prototypes`](https://github.com/jGleitz/Beagle/tree/project-structure/Prototypes), but no `/prototypes`.

Ah, thats a windows problem ;)

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 313 of 335 files at r1, 30 of 31 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/467#-:-K7VvRnB2jc1McfY_uuq:980077423)*

**Comment by acBerger** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/467#-:-K7W2xwqzrUBLOh6SDg4:980077423)*

**Comment by m1cm1c** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/467#-:-K7W6i6SNn_TdMdYX74d:980077423)*

**Comment by viridispirus** [comment]
:lgtm:

**Comment by viridispirus** [comment]
:lgtm:

**Comment by jGleitz** [comment]
+@flyfl 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/467#-:-K7X8-pX6aqSHQGtiZ8d:-485793663)*

**Comment by flyfl** [comment]
:lgtm:

**Comment by acBerger** [comment]
+blocked as all other PR have to be merged before.
-(needs review) 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/467#-:-K7XDfAiX1b4po5lx9wP:1725639111)*

**Comment by flyfl** [comment]
:lgtm_strong:

**Comment by acBerger** [comment]
:lgtm_strong:

---

Review status: 179 of 195 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/467#-:-K7XEqboku1CKJqcfqH9:-1168659251)*

**Comment by m1cm1c** [comment]
:lgtm_strong:

**Comment by RomanLangrehr** [comment]
:lgtm_strong: 

---

Reviewed 16 of 16 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/467#-:-K7XEwAWHHDReI9rIOLf:-1868698381)*

**Comment by viridispirus** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/467#-:-K7XF0XED1OdX83eOExG:-1868698381)*

**Pull request merged**
