### PR TITLE
Design: Improvments for Controllers

### LINKED ISSUE #289: Indentation in Pseudocode in Class Diagram
The intendation of the pseudocode in the class diagram is not *displayed* properly.

### LINKED ISSUE #299: Use “can-do”-pattern for Measurement Controller, too
We have the pattern that a `Result Analyser` may decide for itself whether it can contribute or not. For the `Measurement Controller`, the `Beagle Controller` makes this decision for him. I think we should add a method `can measure(: Read-Only Blackboard [1])` to `Measurement Controller` and use that in the first `if` of the main method.

I think that pattern is more flexible, as the deciding whether it’s possible to measure may become more sophisticated in the future.

We can discuss whether `Result Analyser` and `Measurement Controller` should implement a common interface like `Blackboard Contributor` that contains this pattern.

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Fixes #289 
Fixes #299 

Looks like this:
image

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/352)

### CODE REVIEW

**Comment by jGleitz** [comment]
That’s awesome. While you’re on it, could you do #299, too? (See the stubs for reference)

**Comment by jGleitz** [comment]
There’s a newline missing:

if-newline

**Comment by RomanLangrehr** [comment]
I'm wondering wether we should replace the `:=` by the correct Unicode definition symbol `≔`.
What do you like better:
image

**Comment by jGleitz** [comment]
I think using the correct symbol is always a good idea and like the first variant better.

Am 30.12.2015 11:39 vorm. schrieb Roman Langrehr <notifications@github.com>:

I'm wondering wether we should replace the := by the correct Unicode definition symbol ≔.
What do you like better:

**Comment by RomanLangrehr** [comment]
> That’s awesome. While you’re on it, could you do #299, too? (See the stubs for reference)

Done.

**Comment by jGleitz** [comment]
The pseudo-code should be adapted accordingly. +TODO 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/352#-:-K6y8McYv2hZ3vOifhSd:1933863561)*

**Comment by jGleitz** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/352)*

**Comment by RomanLangrehr** [comment]
Hm. I think I did it wrong: The method `can measure(...)` doesn't make sense on the `Measurment Controller`, as there is only one. We need such a method in the measurment tool and the logic in the measurment contoller, need we?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/352#-:-K6yAlmt5808QH_faGt2:-228977143)*

**Comment by jGleitz** [comment]
For now, I think the `can measure(...)` makes sense in `Measurment Controller`. If it wants to delegate the decision, we can add methods to `Measurement Tool` at a later point.

Of course there is always only one `Measurment Controller`. But it can report whether calling it at the start of the main loop makes sense or not.

As an alternative, we could specify that the `Measurment Controller` will always be the first to be called in the main loop and may do something or return directly.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/352#-:-K6yBUBSQJbxqOjoMWqY:-592026980)*

**Comment by RomanLangrehr** [comment]
> Of course there is always only one Measurment Controller. But it can report whether calling it at the start of the main loop makes sense or not.

In which scenario would calling the measurment controller at the start of the main loop make no sense?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/352#-:-K6yEkdNoaeALDh1Z9S5:-1459393977)*

**Comment by jGleitz** [comment]
As soon as there is nothing new to measure – which will be the case most of the time.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/352#-:-K6yGwzxCAmUD7TN9Pcc:780637648)*

**Comment by RomanLangrehr** [comment]
This is currently checked by the `Beagle Controller`. So you want to delegate this to the `measurment controller`?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/352#-:-K6yTzTCwzPI6sMIRzmd:1327754005)*

**Comment by jGleitz** [comment]
> So you want to delegate this to the measurment controller?

Yeah, that was my idea in the first place. The algorithm deciding whether there is something to be measured or not is from my point of view a secret of the `Measurement Controller`.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/352#-:-K6yVF6NeQP9JIF1hfH8:-1679529426)*

**Comment by RomanLangrehr** [comment]
> The algorithm deciding whether there is something to be measured or not is from my point of view a secret of the Measurement Controller.

I agree on that.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/352#-:-K6yW04K_tBhMaJJQKsz:-643462293)*

**Comment by jGleitz** [comment]
-(needs review) 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/352#-:-K6yWQ9xLtFpTHsNMymA:-1025998350)*

**Comment by RomanLangrehr** [comment]
Depends on #351

**Comment by jGleitz** [comment]
:lgtm_strong: 

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/352#-:-K76XhSa-H-WoyokI7m8:-1868698381)*

**Comment by jGleitz** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/352)*

**Comment by acBerger** [comment]
:lgtm_strong: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/352#-:-K77GsaajjPn2jzOOqhd:-1868698381)*

**Pull request merged**
