### PR TITLE
Final judge javadoc

### LINKED ISSUE #516: Adapt Java Stubs to Design: Final Judge
Make the Final Judge a class and create the `Fitness Function` interface.

### PR DESCRIPTION
**Pull request by flyfl**
fixes #516

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/556)

### CODE REVIEW

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/556#-:-K7hVnOw8fai79yv8y4S:1417088721)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/556#-:-K7hYTpcjnhVTeAw30zY:980077423)*

**Comment by acBerger** [comment]
As Travis failed here: Did gradle run succesfully on your PC?

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/556#-:-K7hZyvozLlkA9SLbo5U:1069204332)*

**Comment by acBerger** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/judge/FinalJudge.java, line 7 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/556#-K7h_Ph-Hu6T4VyB-fO4:-K7h_Ph-Hu6T4VyB-fO5:1829215655) ([raw file](https://github.com/beagle-pse/beagle/blob/d1c231034c504e6917010d0787b4b38a01949304/Core/src/main/java/de/uka/ipd/sdq/beagle/core/judge/FinalJudge.java#L7)):*
Add package before name in links if they are in other packages. Else it cannot be build

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/judge/FinalJudge.java, line 7 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/556#-K7h_Q1OSW1WEmb2_pJe:-K7h_Q1OSW1WEmb2_pJf:1829215655) ([raw file](https://github.com/beagle-pse/beagle/blob/d1c231034c504e6917010d0787b4b38a01949304/Core/src/main/java/de/uka/ipd/sdq/beagle/core/judge/FinalJudge.java#L7)):*
Add package before name in links if they are in other packages. Else it cannot be build

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/judge/FinalJudge.java, line 16 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/556#-K7h_MKaSF9GOwdNPCwq:-K7h_MKaSF9GOwdNPCwr:1829215655) ([raw file](https://github.com/beagle-pse/beagle/blob/d1c231034c504e6917010d0787b4b38a01949304/Core/src/main/java/de/uka/ipd/sdq/beagle/core/judge/FinalJudge.java#L16)):*
Add package before name in links if they are in other packages. Else it cannot be build

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/judge/FinalJudge.java, line 17 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/556#-K7h_IyRapouUMnQVEc2:-K7h_IyRapouUMnQVEc3:1829215655) ([raw file](https://github.com/beagle-pse/beagle/blob/d1c231034c504e6917010d0787b4b38a01949304/Core/src/main/java/de/uka/ipd/sdq/beagle/core/judge/FinalJudge.java#L17)):*
Add package before name in links if they are in other packages. Else it cannot be build

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/556)*

**Comment by flyfl** [comment]
I will close this as I will not get it in time all changes merged manually.

**Pull request closed without merging**
