### PR TITLE
Documentation Build

### LINKED ISSUE #466: Add glossary to Design (LyX Document)

### LINKED ISSUE #490: Build Design Document Including UMLet Diagrams

### PR DESCRIPTION
**Pull request by jGleitz**
* Better directory structure for diagrams
 * Common bibliography and glossary
 * Build design document’s diagrams
 * Build Implementation Plan and link it from the website

fixes #490
fixes #466

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/498)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
[Website](http://jgleitz.github.io/Beagle/branches/doc-setup/)

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: 0 of 29 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/498#-:-K7aWQEaw1YjUAe5UyOK:980077423)*

**Comment by RomanLangrehr** [comment]
Reviewed 39 of 39 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/498)*

**Comment by acBerger** [comment]
the link for javadoc on the website does not work (404).

---

Reviewed 1 of 39 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/498#-:-K7aY1J1vEXtK74ILEc1:540965778)*

**Comment by m1cm1c** [comment]
This branch has conflicts that must be resolved.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/498#-:-K7a_hTXaNPLLhP_T3j5:-1066966179)*

**Comment by jGleitz** [comment]
I just pushed a commit that fixes errors but also contains content improvements. I’m sorry for that!

---

Review status: 25 of 31 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/498#-:-K7abQM5_w8tZ1u4dKcE:-1694693498)*

**Comment by RomanLangrehr** [comment]
> the link for javadoc on the website does not work (404).

Problem still exists.

**Comment by jGleitz** [comment]
> Problem still exists.

You’ll have to wait for Travis to finish ;)

---

Reviewed 1 of 39 files at r1.
Review status: 24 of 31 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/498#-:-K7acPUl3XUgM_Luk1Da:1213116632)*

**Comment by RomanLangrehr** [comment]
Sorry.
:lgtm: 

---

Reviewed 8 of 8 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/498#-:-K7aeF8ffr9m-xYq1q4P:97558944)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/498#-:-K7ajJXfV_Gsgpm-7ax0:1417088721)*

**Pull request merged**
