### PR TITLE
added 'Checkstyle:OFF' to 'Checkstyle Protoype.xml'

### LINKED ISSUE #356: CHECKSTYLE:OFF doesn't work in prototype
I copied some stub classes in my prototype, because i need them there, but now I get checkstyle errors:
image

### PR DESCRIPTION
**Pull request by acBerger**
fixes #356

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/357)

### CODE REVIEW

**Comment by m1cm1c** [comment]
Doesn't work for me.

**Comment by RomanLangrehr** [comment]
Neither for me.

**Comment by acBerger** [comment]
This should fix it, sorry.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/357#-:-K6yIVoWfcmlFeuK4MrV:1757277675)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/357#-:-K6yItHU7R3eJa-GBvpu:980077423)*

**Comment by m1cm1c** [comment]
works, :lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/357#-:-K6yJ0GMDOrT7tfRwtaf:-1042780381)*

**Pull request merged**
