### PR TITLE
Added the proper blackboard views to the pseudocode.

### PR DESCRIPTION
**Pull request by RomanLangrehr**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/424)

### CODE REVIEW

**Comment by jGleitz** [comment]
How do you render the PDF on your machine? It is totally broken on mine! http://owncloud.joshuagleitze.de/index.php/s/AXOPQ1qxRHdaadm

---

Reviewed 3 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/424#-:-K78huXeNHsj9rF4YuLO:1841111414)*

**Comment by jGleitz** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/424)*

**Comment by RomanLangrehr** [comment]
Right click on Beagle in doc/Design -> Export all Diagrams

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/424#-:-K78ij43-iAD29zlJiEr:-1143926038)*

**Comment by jGleitz** [comment]
Oh. I did not know you can do that. But it does not change the results for me. Anyway, that’s something for it’s own PR. :lgtm_strong: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/424#-:-K78jGHKP5nys6adB2_m:87609835)*

**Comment by acBerger** [comment]
:lgtm_strong: 

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/424#-:-K7AosBXdsG3osdmEfLj:-1868698381)*

**Pull request merged**
