### PR TITLE
Adapted citing style.

### PR DESCRIPTION
**Pull request by RomanLangrehr**

### CODE REVIEW

**Comment by m1cm1c** [comment]
Travis failed but it doesn't seem like it's because of your changes. Maybe try it again.

**Comment by m1cm1c** [comment]
Other than that: lgtm.

**Comment by RomanLangrehr** [comment]
Yes, it dosn't seem to be my fault:
image

**Comment by RomanLangrehr** [comment]
By the way: [PDF](https://github.com/RomanLangrehr/Beagle/blob/gh-pages/branches/Citing/Requirements%20Specification.pdf)

**Comment by jGleitz** [comment]
lgtm

**Pull request merged**
