### PR TITLE
Launch configuration

### LINKED ISSUE #717: Realise the GUI as Eclipse Launch Configuration

### PR DESCRIPTION
**Pull request by RomanLangrehr**
This is not intended to be merged right now.

I set the launch configuration for Beagle up and the next step is to implement the Tabs (convert WizardPages to LaunchConfigurationTabs).
I was just not sure, wether I should do this or @m1cm1c , as he wrote the existing GUI code.

Fixes #717 

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/760)

### CODE REVIEW

**Comment by m1cm1c** [comment]
>  I was just not sure, wether I should do this or @m1cm1c , as he wrote the existing GUI code.

We're throwing the existing GUI away anyway, so there's nothing to understand about it. I think you should do this because you already read into how to use the launch configuration API.

**Comment by viridispirus** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/760)*

**Comment by acBerger** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/760)*

**Comment by acBerger** [comment]
Reviewed 1 of 24 files at r2.
Review status: 1 of 26 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/760)*

**Comment by acBerger** [comment]
Reviewed 17 of 24 files at r2, 8 of 8 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/760)*

**Comment by RomanLangrehr** [comment]
The basic Beagle Launch configuration is finished now.
(Just an icon is missing ;) )
Still blocked, because it depends on #752 

---

Review status: 21 of 36 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/760#-:-KC0sCfJr1F8SKdsYwpH:1390569144)*

**Comment by acBerger** [comment]
Reviewed 15 of 15 files at r4.
Review status: 35 of 36 files reviewed at latest revision, 1 unresolved discussion.

---

*[GUI/src/main/java/de/uka/ipd/sdq/beagle/gui/ProjectTab.java, line 53 \[r4\]](https://reviewable.io:443/reviews/beagle-pse/beagle/760#-KC15fYwliiuwZmWIelj:-KC15fYwliiuwZmWIelk:-653510909) ([raw file](https://github.com/beagle-pse/beagle/blob/de16f9ef6a7c426c7f564030bd9bfebbc24851a9/GUI/src/main/java/de/uka/ipd/sdq/beagle/gui/ProjectTab.java#L53)):*
There should not be any TODOs in out code. Please make sure to remove the others too.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/760)*

**Comment by jGleitz** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/760)*

**Comment by RomanLangrehr** [comment]
I put this in a new branch, beagle-launch-configuration.

**Pull request closed without merging**
