### PR TITLE
Added website link to `README.md` of website project so this address …

### PR DESCRIPTION
**Pull request by m1cm1c**
…can be found easily.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/660)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
why not...
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/660#-:-K9rGbGSSMjLMbQhLXRK:81680802)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/660#-:-K9rJFRDwcIWlv0aZILE:980077423)*

**Comment by viridispirus** [comment]
Out of date, please update.

**Comment by jGleitz** [comment]
Travis missed this PR. Please push a little change to wake him up. (Alternatively: push a change and remove it with the next commit)

**Comment by jGleitz** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/660)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/660#-:-K9riWeW9rzYvU1hdcED:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/660#-:-K9sAkRd-sEXRTIrQcG6:980077423)*

**Pull request merged**
