### PR TITLE
Corrected spelling mistake in Javadoc.

### PR DESCRIPTION
**Pull request by m1cm1c**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/440)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
:lgtm_strong: 

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/440#-:-K7IdZjiIhO0V2XvieNY:-1868698381)*

**Comment by jGleitz** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/java/de/uka/ipd/sdq/beagle/analysis/AnalyserBlackboardView.java, line 110 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/440#-K7If9rF-GVzF3lOcpYw:-K7If9rF-GVzF3lOcpYx:795275556) ([raw file](https://github.com/beagle-pse/beagle/blob/7f983ad604e4fc10ead59ca28ce61d2e0f155449/src/main/java/de/uka/ipd/sdq/beagle/analysis/AnalyserBlackboardView.java#L110)):*
“A**[]** resource demanding internal action to get the measurement results of.”

---

*[src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java, line 215 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/440#-K7IfK3iHT2OHB1N9W2c:-K7IfK3iHT2OHB1N9W2d:795275556) ([raw file](https://github.com/beagle-pse/beagle/blob/7f983ad604e4fc10ead59ca28ce61d2e0f155449/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java#L215)):*
“A**[]** resource demanding internal action to get the measurement results of.”

---

*[src/main/java/de/uka/ipd/sdq/beagle/core/ReadOnlyBlackboardView.java, line 114 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/440#-K7IfPj1bNFkln2G2WzR:-K7IfPj1bNFkln2G2WzS:795275556) ([raw file](https://github.com/beagle-pse/beagle/blob/7f983ad604e4fc10ead59ca28ce61d2e0f155449/src/main/java/de/uka/ipd/sdq/beagle/core/ReadOnlyBlackboardView.java#L114)):*
“A**[]** resource demanding internal action to get the measurement results of.”

---

*[src/main/java/de/uka/ipd/sdq/beagle/judge/FinalJudgeBlackboardView.java, line 144 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/440#-K7IfQTCwWuUsifm4gL1:-K7IfQTCwWuUsifm4gL2:795275556) ([raw file](https://github.com/beagle-pse/beagle/blob/7f983ad604e4fc10ead59ca28ce61d2e0f155449/src/main/java/de/uka/ipd/sdq/beagle/judge/FinalJudgeBlackboardView.java#L144)):*
“A**[]** resource demanding internal action to get the measurement results of.”

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/440)*

**Comment by m1cm1c** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/java/de/uka/ipd/sdq/beagle/analysis/AnalyserBlackboardView.java, line 110 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/440#-K7If9rF-GVzF3lOcpYw:-K7IqYuRmVPFTvbtFMmg:677588487) ([raw file](https://github.com/beagle-pse/beagle/blob/7f983ad604e4fc10ead59ca28ce61d2e0f155449/src/main/java/de/uka/ipd/sdq/beagle/analysis/AnalyserBlackboardView.java#L110)):*
done

---

*[src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java, line 215 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/440#-K7IfK3iHT2OHB1N9W2c:-K7IqZlst9lmPu19FUvd:677588487) ([raw file](https://github.com/beagle-pse/beagle/blob/7f983ad604e4fc10ead59ca28ce61d2e0f155449/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java#L215)):*
done

---

*[src/main/java/de/uka/ipd/sdq/beagle/core/ReadOnlyBlackboardView.java, line 114 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/440#-K7IfPj1bNFkln2G2WzR:-K7Iqa0rhJ2L4izkcuuE:677588487) ([raw file](https://github.com/beagle-pse/beagle/blob/7f983ad604e4fc10ead59ca28ce61d2e0f155449/src/main/java/de/uka/ipd/sdq/beagle/core/ReadOnlyBlackboardView.java#L114)):*
done

---

*[src/main/java/de/uka/ipd/sdq/beagle/judge/FinalJudgeBlackboardView.java, line 144 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/440#-K7IfQTCwWuUsifm4gL1:-K7IqjuID-WHuNbZElzu:677588487) ([raw file](https://github.com/beagle-pse/beagle/blob/7f983ad604e4fc10ead59ca28ce61d2e0f155449/src/main/java/de/uka/ipd/sdq/beagle/judge/FinalJudgeBlackboardView.java#L144)):*
done

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/440)*

**Comment by acBerger** [comment]
This branch is out-of-date with the base branch.

**Comment by jGleitz** [comment]
:lgtm_strong: 

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/440#-:-K7Lx3QKXTiE7p_smclZ:-1868698381)*

**Pull request merged**
