### PR TITLE
Added test factories

### PR DESCRIPTION
**Pull request by flyfl**
Plus Modified the resources to include all dependencies needed.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/621)

### CODE REVIEW

**Comment by jGleitz** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[Core/src/main/resources/build.properties, line 5 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/621#-K8TiZuoNv23kMc9Nfb7:-K8TiZupM3WVuoLQFBpR:1800968486) ([raw file](https://github.com/beagle-pse/beagle/blob/dbc1812fe210f7a6a78bebffe36db302bb2aa0b0/Core/src/main/resources/build.properties#L5)):*
Please undo these changes!

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/testutil/factories/EvaluableExpressionFactory.java, line 19 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/621#-K8TishW11_pVImn2fub:-K8TishW11_pVImn2fuc:586612374) ([raw file](https://github.com/beagle-pse/beagle/blob/d4b69b8fd636de4339eed6e39f1a6f8f7839c87a/Core/src/test/java/de/uka/ipd/sdq/beagle/core/testutil/factories/EvaluableExpressionFactory.java#L19)):*
Please add yourself as `@author`.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/testutil/factories/EvaluableExpressionFactory.java, line 37 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/621#-K8TipdS0J5VjfDC4oNR:-K8TipdS0J5VjfDC4oNS:-1240424246) ([raw file](https://github.com/beagle-pse/beagle/blob/d4b69b8fd636de4339eed6e39f1a6f8f7839c87a/Core/src/test/java/de/uka/ipd/sdq/beagle/core/testutil/factories/EvaluableExpressionFactory.java#L37)):*
Please add `getAllAsSet()`

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/testutil/factories/ExternalCallParameterFactory.java, line 12 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/621#-K8Tij-ybOiUl3Ng3KdM:-K8Tij-ybOiUl3Ng3KdN:586612374) ([raw file](https://github.com/beagle-pse/beagle/blob/d4b69b8fd636de4339eed6e39f1a6f8f7839c87a/Core/src/test/java/de/uka/ipd/sdq/beagle/core/testutil/factories/ExternalCallParameterFactory.java#L12)):*
Please add yourself as `@author`.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/testutil/factories/ResourceDemandingInternalActionFactory.java, line 12 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/621#-K8Tj-53uO0hax-UWCRX:-K8Tj-547-39E-HMP3xh:586612374) ([raw file](https://github.com/beagle-pse/beagle/blob/d4b69b8fd636de4339eed6e39f1a6f8f7839c87a/Core/src/test/java/de/uka/ipd/sdq/beagle/core/testutil/factories/ResourceDemandingInternalActionFactory.java#L12)):*
Please add yourself as `@author`.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/testutil/factories/SeffBranchFactory.java, line 12 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/621#-K8Tj2GMGj-tu76vVWZk:-K8Tj2GMGj-tu76vVWZl:586612374) ([raw file](https://github.com/beagle-pse/beagle/blob/d4b69b8fd636de4339eed6e39f1a6f8f7839c87a/Core/src/test/java/de/uka/ipd/sdq/beagle/core/testutil/factories/SeffBranchFactory.java#L12)):*
Please add yourself as `@author`.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/testutil/factories/SeffLoopFactory.java, line 13 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/621#-K8Tj7s_lodQ_TPAXN1l:-K8Tj7s_lodQ_TPAXN1m:586612374) ([raw file](https://github.com/beagle-pse/beagle/blob/d4b69b8fd636de4339eed6e39f1a6f8f7839c87a/Core/src/test/java/de/uka/ipd/sdq/beagle/core/testutil/factories/SeffLoopFactory.java#L13)):*
Please add yourself as `@author`.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/testutil/NullHandlingMatchers.java, line 18 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/621#-K8TjCC07R9oUYZWx5UH:-K8TjCC5zFMV7g6RAYjy:-946732006) ([raw file](https://github.com/beagle-pse/beagle/blob/dbc1812fe210f7a6a78bebffe36db302bb2aa0b0/Core/src/test/java/de/uka/ipd/sdq/beagle/core/testutil/NullHandlingMatchers.java#L18)):*
Please undo this change!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/621)*

**Comment by flyfl** [comment]
Review status: 3 of 9 files reviewed at latest revision, 8 unresolved discussions.

---

*[Core/src/main/resources/build.properties, line 5 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/621#-K8TiZuoNv23kMc9Nfb7:-K8TrtXp37-6XvvqJHqa:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/dbc1812fe210f7a6a78bebffe36db302bb2aa0b0/Core/src/main/resources/build.properties#L5)):*
Done.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/testutil/factories/EvaluableExpressionFactory.java, line 19 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/621#-K8TishW11_pVImn2fub:-K8TruQ_8gd9XEvd9duF:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/d4b69b8fd636de4339eed6e39f1a6f8f7839c87a/Core/src/test/java/de/uka/ipd/sdq/beagle/core/testutil/factories/EvaluableExpressionFactory.java#L19)):*
Done.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/testutil/factories/EvaluableExpressionFactory.java, line 37 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/621#-K8TipdS0J5VjfDC4oNR:-K8Trv7Y3nj54jXcx0el:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/d4b69b8fd636de4339eed6e39f1a6f8f7839c87a/Core/src/test/java/de/uka/ipd/sdq/beagle/core/testutil/factories/EvaluableExpressionFactory.java#L37)):*
Done.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/testutil/factories/ExternalCallParameterFactory.java, line 12 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/621#-K8Tij-ybOiUl3Ng3KdM:-K8Trw5RYcD4nb7BAahw:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/d4b69b8fd636de4339eed6e39f1a6f8f7839c87a/Core/src/test/java/de/uka/ipd/sdq/beagle/core/testutil/factories/ExternalCallParameterFactory.java#L12)):*
Done.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/testutil/factories/ResourceDemandingInternalActionFactory.java, line 12 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/621#-K8Tj-53uO0hax-UWCRX:-K8TrwjPy4AawpoazKxJ:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/d4b69b8fd636de4339eed6e39f1a6f8f7839c87a/Core/src/test/java/de/uka/ipd/sdq/beagle/core/testutil/factories/ResourceDemandingInternalActionFactory.java#L12)):*
Done.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/testutil/factories/SeffBranchFactory.java, line 12 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/621#-K8Tj2GMGj-tu76vVWZk:-K8TrxNAPFjBbbB2Vs-8:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/d4b69b8fd636de4339eed6e39f1a6f8f7839c87a/Core/src/test/java/de/uka/ipd/sdq/beagle/core/testutil/factories/SeffBranchFactory.java#L12)):*
Done.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/testutil/factories/SeffLoopFactory.java, line 13 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/621#-K8Tj7s_lodQ_TPAXN1l:-K8Try0s9NlgNEs-xKU_:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/d4b69b8fd636de4339eed6e39f1a6f8f7839c87a/Core/src/test/java/de/uka/ipd/sdq/beagle/core/testutil/factories/SeffLoopFactory.java#L13)):*
Done.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/testutil/NullHandlingMatchers.java, line 18 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/621#-K8TjCC07R9oUYZWx5UH:-K8TrykQi_29AZeh9Uq3:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/dbc1812fe210f7a6a78bebffe36db302bb2aa0b0/Core/src/test/java/de/uka/ipd/sdq/beagle/core/testutil/NullHandlingMatchers.java#L18)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/621)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/621#-:-K8Tz-IHoyuHnn74tKsx:980077423)*

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 2 of 10 files at r1, 5 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/621#-:-K8UIhWe8EYqEX4-yeug:1417088721)*

**Pull request merged**
