### PR TITLE
Added folder `buildSrc` to `.gitignore`.

### PR DESCRIPTION
**Pull request by m1cm1c**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/359)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
Why on earth should we do this?

**Comment by jGleitz** [comment]
> Why on earth should we do this?

That’s what I ask myself, too. +discussion +invalid 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/359#-:-K6ymDeKObU_aL1xsmA7:2081720249)*

**Comment by jGleitz** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/359)*

**Comment by m1cm1c** [comment]
What is in this folder? It changes its content when gradle runs.

**Comment by jGleitz** [comment]
> What is in this folder?
Please refer to [its README](https://github.com/Beagle-PSE/Beagle/tree/master/buildSrc). 

> It changes its content when gradle runs.
It has its own subolder `build`, which of course changes its content [but is already included in the `.gitignore`](https://github.com/Beagle-PSE/Beagle/blob/master/.gitignore#L4). There should be no content changes outside of its `build` subfolder.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/359#-:-K6ymi-oOyH8uvfTQ2R_:-1139326500)*

**Comment by m1cm1c** [comment]
Okay. Somehow there were many newly created files when I ran gradle the last time. I can't reproduce it, however.

**Comment by jGleitz** [comment]
So can we close this?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/359#-:-K6yonRxzybQPQOEs5P6:1361098102)*

**Comment by m1cm1c** [comment]
Oops, I think they were in `.gradle`, not `buildScr` and by now `.gradle` already is ignored.

**Pull request closed without merging**
