### PR TITLE
Checkstyle Exclude Common Utility Classes From Fan Out Complexity

### PR DESCRIPTION
**Pull request by jGleitz**
Fan out complexity is a good check in general.

However, there are classes that should be excluded from it:
 
 * Basic data types and collection types are required for a class to function. They don‘t make it more complex
 * Input checking and failure handling classes improve the code’s quality and should not result in a penalty for the using class.

Note that most classes were taken from Checkstyle’s default configuration.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/699)

### CODE REVIEW

**Comment by acBerger** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/699#-:-KAQtUxFGQsXOciMScaI:980077423)*

**Comment by acBerger** [comment]
:white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/699#-:-KAR0MvwysC2-9Mm4UmG:1605498549)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/699#-:-KAR1eC6zQEPNxgMu5mb:980077423)*

**Comment by viridispirus** [comment]
:white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/699#-:-KAR1yy9VoNthCICb6dk:1605498549)*

**Pull request merged**
