### PR TITLE
Integration

### LINKED ISSUE #650: Projet Information and Factory
Create a class "Project Information" and a factory for the blackboard, that gets the project information, the fitness function and the seff-elements to create the blackboard.

### LINKED ISSUE #658: Write Beagle Controller (facade)

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Contains integration and
Fixes #650 
Fixes #658 
Fixes lots of bugs (Integration of all things that are right now in master).

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/711)

### CODE REVIEW

**Comment by viridispirus** [comment]
Reviewed 2 of 33 files at r1, 2 of 41 files at r5, 2 of 21 files at r9.
Review status: 6 of 38 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/711)*

**Comment by acBerger** [comment]
Is someone testing this? Or are there already tests?

---

Review status: 6 of 39 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/711#-:-KAWUZ67LXnXRSAwcpH6:883310397)*

**Comment by viridispirus** [comment]
Reviewed 3 of 33 files at r1, 1 of 8 files at r3, 6 of 20 files at r4, 6 of 41 files at r5, 6 of 12 files at r7, 1 of 2 files at r8, 13 of 21 files at r9, 2 of 2 files at r11.
Review status: 38 of 39 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java, line 68 \[r11\]](https://reviewable.io:443/reviews/beagle-pse/beagle/711#-KAWcjLwxzypFOfN63mu:-KAWcjLwxzypFOfN63mv:345719218) ([raw file](https://github.com/beagle-pse/beagle/blob/90d72fd04be327e4739f758c7c1c08c986135567/Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java#L68)):*
Why is this in here? Is this right?

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java, line 76 \[r11\]](https://reviewable.io:443/reviews/beagle-pse/beagle/711#-KAWdLjycFgJUuOpnO4p:-KAWdLjycFgJUuOpnO4q:345719218) ([raw file](https://github.com/beagle-pse/beagle/blob/90d72fd04be327e4739f758c7c1c08c986135567/Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java#L76)):*
Why is this in here? Is this right?

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java, line 84 \[r11\]](https://reviewable.io:443/reviews/beagle-pse/beagle/711#-KAWdMX6LtE_hYNctdt7:-KAWdMX6LtE_hYNctdt8:345719218) ([raw file](https://github.com/beagle-pse/beagle/blob/90d72fd04be327e4739f758c7c1c08c986135567/Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java#L84)):*
Why is this in here? Is this right?

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java, line 92 \[r11\]](https://reviewable.io:443/reviews/beagle-pse/beagle/711#-KAWdNAAnX6okeAaC001:-KAWdNAB2IruHGQhpm6v:345719218) ([raw file](https://github.com/beagle-pse/beagle/blob/90d72fd04be327e4739f758c7c1c08c986135567/Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java#L92)):*
Why is this in here? Is this right?

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java, line 100 \[r11\]](https://reviewable.io:443/reviews/beagle-pse/beagle/711#-KAWdOCSquHI3dPw3-TY:-KAWdOCSquHI3dPw3-TZ:345719218) ([raw file](https://github.com/beagle-pse/beagle/blob/90d72fd04be327e4739f758c7c1c08c986135567/Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java#L100)):*
Why is this in here? Is this right?

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java, line 108 \[r11\]](https://reviewable.io:443/reviews/beagle-pse/beagle/711#-KAWdOmUixJaFovovRDV:-KAWdOmUixJaFovovRDW:345719218) ([raw file](https://github.com/beagle-pse/beagle/blob/90d72fd04be327e4739f758c7c1c08c986135567/Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java#L108)):*
Why is this in here? Is this right?

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java, line 116 \[r11\]](https://reviewable.io:443/reviews/beagle-pse/beagle/711#-KAWdQ1YF9vMDYEpPuwa:-KAWdQ1YF9vMDYEpPuwb:345719218) ([raw file](https://github.com/beagle-pse/beagle/blob/90d72fd04be327e4739f758c7c1c08c986135567/Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java#L116)):*
Why is this in here? Is this right?

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java, line 124 \[r11\]](https://reviewable.io:443/reviews/beagle-pse/beagle/711#-KAWdR3MOwdHkuds2H9n:-KAWdR3MOwdHkuds2H9o:345719218) ([raw file](https://github.com/beagle-pse/beagle/blob/90d72fd04be327e4739f758c7c1c08c986135567/Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java#L124)):*
Why is this in here? Is this right?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/711)*

**Comment by viridispirus** [comment]
Reviewed 1 of 21 files at r9.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/711)*

**Comment by viridispirus** [comment]
Reviewed 2 of 2 files at r12.
Review status: 38 of 39 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/711)*

**Comment by RomanLangrehr** [comment]
Review status: 38 of 39 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java, line 68 \[r11\]](https://reviewable.io:443/reviews/beagle-pse/beagle/711#-KAWcjLwxzypFOfN63mu:-KAWkF6fWGL2Z0VzAoeE:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/90d72fd04be327e4739f758c7c1c08c986135567/Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java#L68)):*
Done.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java, line 76 \[r11\]](https://reviewable.io:443/reviews/beagle-pse/beagle/711#-KAWdLjycFgJUuOpnO4p:-KAWkE_e1xHGqaMB-HM0:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/90d72fd04be327e4739f758c7c1c08c986135567/Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java#L76)):*
Done.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java, line 84 \[r11\]](https://reviewable.io:443/reviews/beagle-pse/beagle/711#-KAWdMX6LtE_hYNctdt7:-KAWkEBQhX75csoD6oD-:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/90d72fd04be327e4739f758c7c1c08c986135567/Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java#L84)):*
Done.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java, line 92 \[r11\]](https://reviewable.io:443/reviews/beagle-pse/beagle/711#-KAWdNAAnX6okeAaC001:-KAWkDwoLJDzEKAhF6It:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/90d72fd04be327e4739f758c7c1c08c986135567/Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java#L92)):*
Done.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java, line 100 \[r11\]](https://reviewable.io:443/reviews/beagle-pse/beagle/711#-KAWdOCSquHI3dPw3-TY:-KAWkD37aTHdj1f4pIm4:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/90d72fd04be327e4739f758c7c1c08c986135567/Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java#L100)):*
Done.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java, line 108 \[r11\]](https://reviewable.io:443/reviews/beagle-pse/beagle/711#-KAWdOmUixJaFovovRDV:-KAWkCn0N4G3FsjFJ2Qo:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/90d72fd04be327e4739f758c7c1c08c986135567/Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java#L108)):*
Done.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java, line 116 \[r11\]](https://reviewable.io:443/reviews/beagle-pse/beagle/711#-KAWdQ1YF9vMDYEpPuwa:-KAWkCZFXYfAQlkQgNIH:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/90d72fd04be327e4739f758c7c1c08c986135567/Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java#L116)):*
Done.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java, line 124 \[r11\]](https://reviewable.io:443/reviews/beagle-pse/beagle/711#-KAWdR3MOwdHkuds2H9n:-KAWkCIrqaBnqytn7usB:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/90d72fd04be327e4739f758c7c1c08c986135567/Core/src/test/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryBlackboardFactoryTest.java#L124)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/711)*

**Comment by viridispirus** [comment]
Reviewed 1 of 1 files at r13.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/711)*

**Comment by acBerger** [comment]
Reviewed 5 of 33 files at r1, 1 of 8 files at r3, 6 of 20 files at r4, 7 of 41 files at r5, 4 of 12 files at r7, 1 of 2 files at r8, 14 of 21 files at r9, 1 of 1 files at r13, 2 of 2 files at r14.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/711)*

**Comment by viridispirus** [comment]
Reviewed 2 of 2 files at r14.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/711)*

**Comment by viridispirus** [comment]
Reviewed 1 of 1 files at r15.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/711)*

**Comment by acBerger** [comment]
Reviewed 1 of 21 files at r9, 1 of 1 files at r15.
Review status: 36 of 39 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/711)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: 36 of 39 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/711#-:-KAWrrUqT-CTa3VMiSj5:1417088721)*

**Comment by acBerger** [comment]
:white_check_mark: 

---

Review status: 36 of 39 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/711#-:-KAWrtXQ_ZNTfY95RO5B:1605498549)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Reviewed 3 of 3 files at r16.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/711#-:-KAWs4clpGopxMdym-3r:980077423)*

**Comment by flyfl** [comment]
Reviewed 3 of 33 files at r1, 1 of 8 files at r3, 6 of 20 files at r4, 6 of 41 files at r5, 6 of 12 files at r7, 1 of 2 files at r8, 14 of 21 files at r9, 2 of 2 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/711)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r17.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/711)*

**Comment by viridispirus** [comment]
Reviewed 1 of 1 files at r17, 1 of 1 files at r18.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/711)*

**Comment by RomanLangrehr** [comment]
Please renew LGTMs

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/711#-:-KAWtNyFBm99VmpK8w_k:919695643)*

**Comment by acBerger** [comment]
Reviewed 1 of 3 files at r16, 1 of 1 files at r18.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/711)*

**Comment by acBerger** [comment]
:lgtm: :white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/711#-:-KAWtUi08MCKzmjZJyvd:-1603124213)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/711#-:-KAWt_2F8aJUG9fjI1S2:980077423)*

**Comment by flyfl** [comment]
:lgtm:

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/711#-:-KAWv35GMAyjAnBJExoN:980077423)*

**Comment by acBerger** [comment]
:white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/711#-:-KAWvZBUo-dEirxquHYY:1605498549)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: 39 of 40 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/711#-:-KAWyQLUnB3YrX0DtEpW:980077423)*

**Comment by m1cm1c** [comment]
:white_check_mark: :lgtm:

**Comment by m1cm1c** [comment]
Reviewed 1 of 1 files at r20.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/711)*

**Pull request merged**
