### PR TITLE
Added discussion points from meeting 2015-11-23

### LINKED ISSUE #121: Compare the SRS Draft to meeting minutes
We had 3 meetings to specify attributes of our software. We should check that everything written in the mettings’ minutes found its ways into the SRS.

### PR DESCRIPTION
**Pull request by jGleitz**
I think that closes #121. @flyfl, can you confirm?

### CODE REVIEW

**Comment by jGleitz** [comment]
This PR also modifies (mostly extends) the other points in “Challenges”.

**Comment by acBerger** [comment]
[PDF] (http://jgleitz.github.io/Beagle/branches/meeting-minutes-check/Requirements%20Specification.pdf)

**Comment by acBerger** [comment]
> /C30/ [...]  Beagle relies on this to be true and may
produce inaccurate or wrong results if it’s not. [...]

should be "if it is not."

**Comment by acBerger** [comment]
In /C120/ you also used several abbreviations.

**Comment by acBerger** [comment]
Everything else:  lgtm

**Comment by jGleitz** [comment]
@acBerger: Thanks, fixed it.

**Comment by RomanLangrehr** [comment]
Lgtm

**Pull request merged**
