### PR TITLE
Added Umlet Measurement Diagram

### LINKED ISSUE #510: Redraw measurement Results diagram
We forgot this during the meeting.

### PR DESCRIPTION
**Pull request by acBerger**
fixes #510

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/520)

### CODE REVIEW

**Comment by jGleitz** [comment]
[Website](http://acberger.github.io/Beagle/branches/measurement-umlet/)

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/520#-:-K7etdlA8XfgZRpMUqVw:-45494345)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/520#-:-K7evz0sAjbVCtH0FRWP:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/520#-:-K7exzMyuqBy68baWfrr:980077423)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/520#-:-K7f27r3Dp8t6o6QtbhN:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/520#-:-K7f_MeUjRB0PDkh4rKW:980077423)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/520#-:-K7ffmw_O-ozf5T7nDVj:980077423)*

**Pull request merged**
