### PR TITLE
Run Configuration

### PR DESCRIPTION
**Pull request by jGleitz**
This is an attempt to create the one and only run configuration launching our plugin in an inner Eclipse. 

This configuration already solves the classloading issue. I now want to make sure that it’s running on **every one’s** machine. So please check out the branch `launch-test` from our repository and run the launch configuration “Beagle in Eclipse”. You should be able to launch our GUI through the context menus.

Please report whether this works and and errors that occur.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/679)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
Works for me. :lgtm: 
Is it on purpose, that this branch is not the branch we should test?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/679#-:-KA9fkPcP0TTqrJjuXwa:-1522540773)*

**Comment by jGleitz** [comment]
>  Is it on purpose, that this branch is not the branch we should test?

Yes it is. This branch contains only the configuration. The other one contains (a modified version) of the GUI so you have something you can try out.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/679#-:-KA9gxXMSdjjYeIqVl0y:1070389865)*

**Comment by acBerger** [comment]
It does not work for me at the moment, but I think this is because of my eclipse. 
However, I would be very interesting, if it works for all of you. Testing this is only 2 clicks (may be more but it is less than 5 minutes) and it would be very helpful.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/679#-:-KAARdbMdSXdp2lFHBeC:343077884)*

**Comment by viridispirus** [comment]
Works for me. :lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/679#-:-KAAVjpTHu6Sy9KzBSvr:-2017668592)*

**Comment by flyfl** [comment]
Opening the GUI via context menu works.
:lgtm:

**Comment by acBerger** [comment]
After fixing my eclipse: SoMoX does not work but the run configuration does.
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/679#-:-KAG41mirKc_Y7yN52UE:1850188050)*

**Comment by RomanLangrehr** [comment]
+m1cm1c
What's with you?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/679#-:-KAGUXaeiBw2u7dbPVMJ:-620781586)*

**Comment by jGleitz** [comment]
@m1cm1c if you ignore the SoMoX problems, does Beagle’s GUI work for you with the run configuration?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/679#-:-KAGWVpk8zXlEku8C3_-:1489212206)*

**Comment by m1cm1c** [comment]
I ignored them yesterday which is why the inner Eclipse launched at all. But then I don't have SoMoX available in the inner Eclipse.

**Comment by jGleitz** [comment]
I don't know whether the problem with SoMoX lies in your (and Annika's) Setup or this configuration. 

The main goal of this PR is to get Beagle running on everybody's machine, so please give your lgtm if you can launch the GUI with this configuration.

**Comment by m1cm1c** [comment]
I can't. I can't even create the diagrams atm.

**Comment by jGleitz** [comment]
>  I can't even create the diagrams atm.

You could just create a repository using Palladio! 

Am 11.02.2016 7:51 nachm. schrieb m1cm1c <notifications@github.com>:

I can't. I can't even create the diagrams atm.

**Comment by RomanLangrehr** [comment]
@m1cm1c  Or just download [this sample project](https://www.dropbox.com/s/dy1zjih7x91m5y9/SoMoX%20Sample.zip?dl=0). SoMoX has already run on it.

**Comment by m1cm1c** [comment]
@RomanLangrehr Thank you! It works. :lgtm:

**Pull request merged**
