### PR TITLE
Umlet Package Diagram

### LINKED ISSUE #477: Redraw Package Diagram in UMLet

### PR DESCRIPTION
**Pull request by acBerger**
fixes #477

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/483)

### CODE REVIEW

**Comment by acBerger** [comment]
This is the diagram:



---

Review status: 0 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/483#-:-K7Y6hAmQKxyAUn2EP4n:-279787742)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: 0 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/483#-:-K7YFmzpJDCvBwEF4kBF:980077423)*

**Comment by jGleitz** [comment]
RCM Beagle Mapping -> PCM Beagle Mapping

---

Review status: 0 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/483#-:-K7YXl_x38lKVqtBrLFI:-454945954)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Reviewed 41 of 42 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/483#-:-K7Y_CPGSMtS5syLm-CR:980077423)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/483#-:-K7_aHa7OzgHPz4U_lYf:980077423)*

**Pull request merged**
