### PR TITLE
Pcm storer

### PR DESCRIPTION
**Pull request by flyfl**
This includes the Pcm Id Mapping and the PcmStorer.
I like to share it with you, so you can start to review - although there are some minor
things to add/change so far.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/706)

#657

### CODE REVIEW

**Comment by acBerger** [comment]
Reviewed 24 of 24 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/706)*

**Comment by acBerger** [comment]
+(tests needed)  I'll  try to test that.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/706#-:-KAUfUMb4JegOvHFx_xd:1871373544)*

**Comment by viridispirus** [comment]
Reviewed 24 of 24 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/706)*

**Comment by acBerger** [comment]
-(tests needed) 
I added some test, but unfortunately some of the fail. @flyfl please check your code.

---

Review status: 19 of 26 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/706#-:-KAVB91pGjQeEXsFZXfn:-1947580976)*

**Comment by viridispirus** [comment]
Reviewed 7 of 10 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/706)*

**Comment by m1cm1c** [comment]
This branch has conflicts that must be resolved.

**Comment by viridispirus** [comment]
Reviewed 5 of 15 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/706)*

**Comment by viridispirus** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/706)*

**Comment by viridispirus** [comment]
Reviewed 5 of 7 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/706)*

**Comment by viridispirus** [comment]
Reviewed 8 of 8 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/706)*

**Comment by m1cm1c** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryWriterAnnotator.java, line 243 \[r7\]](https://reviewable.io:443/reviews/beagle-pse/beagle/706#-KAWlPQ0vefnevP1oG4s:-KAWlPQ0vefnevP1oG4t:-671707602) ([raw file](https://github.com/beagle-pse/beagle/blob/759efb487e41bc9b5bef568f132d1bc48176dbd8/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryWriterAnnotator.java#L243)):*
Why do you even accept EObjects in general if you can only use Identifiers? Is this necessary because this signature is mandatory?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/706)*

**Comment by m1cm1c** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Documentation/Discussions/PCMStorer/PcmStorerReport_1.md, line 54 \[r7\]](https://reviewable.io:443/reviews/beagle-pse/beagle/706#-KAWmY7ndwrylg6fHObb:-KAWmY7ndwrylg6fHObc:978103783) ([raw file](https://github.com/beagle-pse/beagle/blob/759efb487e41bc9b5bef568f132d1bc48176dbd8/Documentation/Discussions/PCMStorer/PcmStorerReport_1.md#L54)):*
Why is this in German?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/706)*

**Comment by m1cm1c** [comment]
Reviewed 1 of 24 files at r1, 2 of 15 files at r3, 1 of 2 files at r4, 2 of 3 files at r6, 8 of 8 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/706)*

**Comment by RomanLangrehr** [comment]
Reviewed 1 of 15 files at r3, 1 of 2 files at r4, 1 of 3 files at r6, 2 of 8 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Documentation/Discussions/PCMStorer/PcmStorerReport_1.md, line 54 \[r7\]](https://reviewable.io:443/reviews/beagle-pse/beagle/706#-KAWmY7ndwrylg6fHObb:-KAWoaKPwb6hFvaqA3rb:-424991050) ([raw file](https://github.com/beagle-pse/beagle/blob/759efb487e41bc9b5bef568f132d1bc48176dbd8/Documentation/Discussions/PCMStorer/PcmStorerReport_1.md#L54)):*
Will be resolved later.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/706)*

**Comment by flyfl** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryWriterAnnotator.java, line 243 \[r7\]](https://reviewable.io:443/reviews/beagle-pse/beagle/706#-KAWlPQ0vefnevP1oG4s:-KAWp6sWKPj_zu0UzWj9:419169423) ([raw file](https://github.com/beagle-pse/beagle/blob/759efb487e41bc9b5bef568f132d1bc48176dbd8/Core/src/main/java/de/uka/ipd/sdq/beagle/core/pcmconnection/PcmRepositoryWriterAnnotator.java#L243)):*
They need to be casted to apply getId() to them

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/706)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/706#-:-KAWpkJ5QPDSKuKQOAUy:980077423)*

**Comment by m1cm1c** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/706#-:-KAWpnhBhSpQI2AOEP0F:1417088721)*

**Comment by viridispirus** [comment]
:white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/706#-:-KAWq4I0Yl3TJ4wljrtE:1605498549)*

**Comment by m1cm1c** [comment]
:white_check_mark:

**Pull request merged**
