### PR TITLE
Checkstyle2

### PR DESCRIPTION
**Pull request by acBerger**
Added another static import to allowed import.
The import is needed for junit testing.
depends on #592 .

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/593)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/593#-:-K895iZSSrOFNB1GHAoA:980077423)*

**Comment by RomanLangrehr** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/593)*

**Comment by jGleitz** [comment]
As #592 (Fixed Checkstyle Issues)  is merged, this is not -blocked anymore.

:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/593#-:-K89qzMiNg8GjJQlVZUT:237897501)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/593#-:-K89rOezDbIHlKKS5Ejz:980077423)*

**Pull request merged**
