### PR TITLE
Simple tests

### PR DESCRIPTION
**Pull request by viridispirus**
Some Tests but not all yet.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/764)

### CODE REVIEW

**Comment by acBerger** [comment]
Travis fails as the tests are failing. @romanlangrehr  & @viridispirus have a look and fix it.

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/764#-:-KBwpyjVRrQgTqoLnpYx:-1905934145)*

**Comment by acBerger** [comment]
Please.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/764#-:-KBwqQZKVmdvppIocULk:-972084033)*

**Comment by RomanLangrehr** [comment]
@acberger Done. (I fixed the bugs in the test cases and in my code).

:lgtm: 

---

Review status: 2 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/764#-:-KBxENt2HA5jOswQse49:-1997767034)*

**Comment by RomanLangrehr** [comment]
Reviewed 2 of 4 files at r1, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/764)*

**Comment by acBerger** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/764)*

**Comment by acBerger** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/ProjectInformation.java, line 83 \[r5\]](https://reviewable.io:443/reviews/beagle-pse/beagle/764#-KBxdTlGSkD1YTdBYYXK:-KBxdTlHfXzZlUKUQjRL:1697776042) ([raw file](https://github.com/beagle-pse/beagle/blob/c1a174fd9e06d3a9eb6c7b5b9f2eea72ce2390c1/Core/src/main/java/de/uka/ipd/sdq/beagle/core/ProjectInformation.java#L83)):*
If you do this, `this.charset = charset == null ? Charset.default() : charset;` is not needed. As Javadoc defines that entering `null `as charset leads to the usage of the default charset it would be better to remove `Validate.notNull(charset)`.
@viridispirus please also remove the test case asserting, that the null leads to an Exception.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/764)*

**Comment by viridispirus** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/ProjectInformation.java, line 83 \[r5\]](https://reviewable.io:443/reviews/beagle-pse/beagle/764#-KBxdTlGSkD1YTdBYYXK:-KBxg1UTDK4fen_rQrMk:-469593337) ([raw file](https://github.com/beagle-pse/beagle/blob/c1a174fd9e06d3a9eb6c7b5b9f2eea72ce2390c1/Core/src/main/java/de/uka/ipd/sdq/beagle/core/ProjectInformation.java#L83)):*
done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/764)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/ProjectInformationTest.java, line 45 \[r6\]](https://reviewable.io:443/reviews/beagle-pse/beagle/764#-KBxhYMLNBKtwTiJlNQv:-KBxhYMMuGs31rTSo5ot:482039933) ([raw file](https://github.com/beagle-pse/beagle/blob/7b8bc26ade17b28a85a52d026724b44a67f6c7ca/Core/src/test/java/de/uka/ipd/sdq/beagle/core/ProjectInformationTest.java#L45)):*
I think this should be before opening the method.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/764)*

**Comment by viridispirus** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/test/java/de/uka/ipd/sdq/beagle/core/ProjectInformationTest.java, line 45 \[r6\]](https://reviewable.io:443/reviews/beagle-pse/beagle/764#-KBxhYMLNBKtwTiJlNQv:-KBxpkXP2GjsDxuBlWPH:-469593337) ([raw file](https://github.com/beagle-pse/beagle/blob/7b8bc26ade17b28a85a52d026724b44a67f6c7ca/Core/src/test/java/de/uka/ipd/sdq/beagle/core/ProjectInformationTest.java#L45)):*
done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/764)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/764)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/ProjectInformation.java, line 83 \[r5\]](https://reviewable.io:443/reviews/beagle-pse/beagle/764#-KBxdTlGSkD1YTdBYYXK:-KC-cAzgz7v0Xw3gJCCt:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/c1a174fd9e06d3a9eb6c7b5b9f2eea72ce2390c1/Core/src/main/java/de/uka/ipd/sdq/beagle/core/ProjectInformation.java#L83)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/764#-:-KC-cCLkzB-HdbBCdN6j:980077423)*

**Comment by acBerger** [comment]
:lgtm: :white_check_mark: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/764#-:-KC0K_oxbH5HzWaPUl6S:-1603124213)*

**Comment by acBerger** [comment]
:lgtm: :white_check_mark: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/764#-:-KC0gQKMNg2azbdeyzGi:-1603124213)*

**Comment by m1cm1c** [comment]
:lgtm:

---

Reviewed 2 of 4 files at r1, 2 of 4 files at r5, 1 of 1 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/764#-:-KC0nt-fqz7URjzkTWfL:1417088721)*

**Pull request merged**
