### PR TITLE
More Requirements

### PR DESCRIPTION
**Pull request by jGleitz**
This pull request introduces more functional and non-functional requirements. It also changes the way requirements are structured into a topic-bundled structure.

Please note that while this PR adds more points, I have the feeling that we not yet have reached a state where our project is sufficiently described.

### CODE REVIEW

**Comment by acBerger** [comment]
I cannot render the pdf (it says "! Package xkeyval Error: `useri' undefined in families `glossentry'.

See the xkeyval package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.33 }
")

**Comment by jGleitz** [comment]
fixed. @flyfl, @acBerger, please review!

**Comment by acBerger** [comment]
I don't like "Beagle’s result PCM instance" as I think it can be easily missunderstood, but I don't know a better term.
I think you should either include the last to points into the structure or delete it (if you think its content is described before)

**Comment by jGleitz** [comment]
I see your point, but can’t think of a better wording in the moment. What do the others think about it?

**Comment by flyfl** [comment]
lgtm

**Comment by jGleitz** [comment]
Hm. “result-annotated PCM”?

**Comment by acBerger** [comment]
I don't know if this is better. Maybe just leave it and keep it in mind?

**Comment by jGleitz** [comment]
> Maybe just leave it and keep it in mind?

I’d be okay with that. @flyfl?

**Comment by jGleitz** [comment]
fixes #80

**Comment by jGleitz** [comment]
I’ll just merge this to have some progress, as both @flyfl and @acBerger aren’t too concerned about the wording. 
It’s something that can be revised when moving towards the final version.

**Pull request merged**
