### PR TITLE
Changed a file name in order to establish compatibility with MS Windows.

### LINKED ISSUE #215: Invalid path
I can't check out anymore, because of `doc/Requirements Specification/Local Copies of Websites/2015-11-29 14:49 Committees Paper.tar`: On windows, ":" is not allowed in file/folder names.

Can someone please rename it?

(Stupid windows)

### PR DESCRIPTION
**Pull request by m1cm1c**
Fixes #215.

### CODE REVIEW

**Comment by jGleitz** [comment]
Before merging this, please explain why we need the tar at all (as discussed in #215)

**Comment by RomanLangrehr** [comment]
Lgtm.

**Comment by RomanLangrehr** [comment]
> Before merging this, please explain why we need the tar at all (as discussed in #215)

It's better than hundreds of .html  files

**Comment by jGleitz** [comment]
> It's better than hundreds of .html files

That’s not the point. As explained in #215, we don’t need a copy of this website because according to @m1cm1c, the quote comes from a published paper.

**Comment by m1cm1c** [comment]
No, that's the other quote. Conway's law is about a concept which is why I think that his comment is important.

**Comment by flyfl** [comment]
Lgtm

**Pull request merged**
