### PR TITLE
Design Document: Change Everything

### LINKED ISSUE #499: Fill the Design Document With As Much Meaningful Content as Possible

### PR DESCRIPTION
**Pull request by jGleitz**
I went through the document and made changes to almost everything. While I also added some content, I mainly restructured everything. I hope you like it.

[Website](http://jgleitz.github.io/Beagle/branches/design-structure/)

fixes #499

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/512)

### CODE REVIEW

**Comment by acBerger** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Documentation/src/design/lyx/Parts/Architectual Overview.lyx, line 109 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/512#-K7eYflCc63hfPeNH9B4:-K7eYflD4jl1aHu2kVsq:2052503415) ([raw file](https://github.com/beagle-pse/beagle/blob/0cc11805384324ee1213d148e0491aa64083b7ed/Documentation/src/design/lyx/Parts/Architectual Overview.lyx#L109)):*
should be \gls{PCM}

---

*[Documentation/src/design/lyx/Parts/Architectual Overview.lyx, line 164 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/512#-K7eYnVvwHe26EAv7Bah:-K7eYnVvwHe26EAv7Bai:-1062894605) ([raw file](https://github.com/beagle-pse/beagle/blob/0cc11805384324ee1213d148e0491aa64083b7ed/Documentation/src/design/lyx/Parts/Architectual Overview.lyx#L164)):*
As there is an acronym RDIA we should probably add it here.

---

*[Documentation/src/design/lyx/Parts/Architectual Overview.lyx, line 304 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/512#-K7eZ20mnU3CQTZhTA_Q:-K7eZ20nXhVNUiJ2zOXo:-64169146) ([raw file](https://github.com/beagle-pse/beagle/blob/0cc11805384324ee1213d148e0491aa64083b7ed/Documentation/src/design/lyx/Parts/Architectual Overview.lyx#L304)):*
\gls{GUI}

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/512)*

**Comment by jGleitz** [comment]
Review status: 8 of 14 files reviewed at latest revision, 3 unresolved discussions.

---

*[Documentation/src/design/lyx/Parts/Architectual Overview.lyx, line 109 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/512#-K7eYflCc63hfPeNH9B4:-K7esD6B4LysiJvVmoB7:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/0cc11805384324ee1213d148e0491aa64083b7ed/Documentation/src/design/lyx/Parts/Architectual Overview.lyx#L109)):*
Done.

---

*[Documentation/src/design/lyx/Parts/Architectual Overview.lyx, line 164 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/512#-K7eYnVvwHe26EAv7Bah:-K7esEJFMy66HiPc9iTC:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/0cc11805384324ee1213d148e0491aa64083b7ed/Documentation/src/design/lyx/Parts/Architectual Overview.lyx#L164)):*
Done.

---

*[Documentation/src/design/lyx/Parts/Architectual Overview.lyx, line 304 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/512#-K7eZ20mnU3CQTZhTA_Q:-K7esHGw_nOj_am1X-Vf:-1785810357) ([raw file](https://github.com/beagle-pse/beagle/blob/0cc11805384324ee1213d148e0491aa64083b7ed/Documentation/src/design/lyx/Parts/Architectual Overview.lyx#L304)):*
Done. (By removing the part altogether)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/512)*

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/512#-:-K7eu7bSJm-Xb5avDYl1:1417088721)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/512#-:-K7exFYTSdaNlH7mr1CS:980077423)*

**Pull request merged**
