### PR TITLE
LayerDiagram

### LINKED ISSUE #480: Draw Layer Diagram
As discussed in today’s meeting.

### PR DESCRIPTION
**Pull request by viridispirus**
fixes #480.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/486)

### CODE REVIEW

**Comment by viridispirus** [comment]
Here is the digram:

layerdiagram

**Comment by acBerger** [comment]
if possible you could try to move the names on the arrows a little bit . This would make it nicer and easier readable.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/486#-:-K7YMLdMPK14tM1zwF0n:-1326972514)*

**Comment by viridispirus** [comment]
layerdiagram

**Comment by acBerger** [comment]
:lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/486#-:-K7YQ_alVRbXae1KoypY:980077423)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/486)*

**Comment by jGleitz** [comment]
* You can write `halign=left` to get the firs line left aligned, too.
 * `Result Analyser` is now called `Measurement Result Analyser`.
 * The “identity” on `Proposed Expressions` is not the `Fitness Function` but the new `Proposed Expression Analyser`.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/486#-:-K7YZ9vFRP0UKHB4qx7f:1944996839)*

**Comment by viridispirus** [comment]
layerdiagram

**Comment by viridispirus** [comment]
layerdiagram

**Comment by m1cm1c** [comment]
:lgtm:

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/486#-:-K7_rhKJQbR_q3s3pT0z:1417088721)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/486#-:-K7_sxSzJgYd-zNKAVOw:980077423)*

**Comment by m1cm1c** [comment]
This branch is out-of-date with the base branch.

**Pull request merged**
