### PR TITLE
Measurement API

### LINKED ISSUE #393: Create Measurement API
The interface `MeasurementTool` needs to be filled with content so that it's possible to use Kieker with it.

Additionally, the PCM elements classes (see #455) need to be extended to point to source code sections.

### PR DESCRIPTION
**Pull request by jGleitz**
Diagram for Measurement API and Analysis Chapter.

fixes #393 

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/542)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
In the Blackboard layer I'd like Measurement Tools better than Measurement Controller.

:lgtm: 

---

Reviewed 6 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/542#-:-K7h-RD-wkeG4eiXHRj8:1999385322)*

**Comment by jGleitz** [comment]
> In the Blackboard layer I'd like Measurement Tools better than Measurement Controller.

I still disagree, but that’s your chapter, so I changed it.

---

Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/542#-:-K7h1W01M4hH6dVG3x_I:113263619)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/542#-:-K7h1oEYHd-9wg1cFRIr:1417088721)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/542#-:-K7h1zYk5BxYjiiEMhpt:980077423)*

**Pull request merged**
