### PR TITLE
Adapted Java Dummies to Design

### LINKED ISSUE #514: Adapt Java Stubs to Design: Blackboard & Views
Realise the newly defined methods on the Blackboard and create all Views. Document all of this.

Attention: While you’re on it, rename `get all SEFF Loops to be measured ()` -> `get SEFF Loops to be measured ()` on the diagrame.

### PR DESCRIPTION
**Pull request by m1cm1c**
So far I adapted the blackboard. Please already review this. I'll create the new views and adapt the old ones once you reviewed the blackboard.

Fixes #514.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/533)

### CODE REVIEW

**Comment by jGleitz** [comment]
Pleas fix the naming convention for the views, too. I won’t mark every occurrence, so please look them through yourself.

---

Review status: 0 of 16 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/AnalyserBlackboardView.java, line 46 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/533#-K7gGCawsEsR6JxduJUz:-K7gGCawsEsR6JxduJV-:1654386231) ([raw file](https://github.com/beagle-pse/beagle/blob/5204146b31580b3cdb314828263ade869751b891/Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/AnalyserBlackboardView.java#L46)):*
fix naming convention here.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/AnalyserBlackboardView.java, line 140 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/533#-K7gGKhf9tZgSiN4EJMM:-K7gGKhf9tZgSiN4EJMN:1654386231) ([raw file](https://github.com/beagle-pse/beagle/blob/5204146b31580b3cdb314828263ade869751b891/Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/AnalyserBlackboardView.java#L140)):*
fix naming convention here.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/AnalyserBlackboardView.java, line 168 \[r1\]](https://reviewable.io:443/reviews/beagle-pse/beagle/533#-K7gGMhOKE_ChBV45hT6:-K7gGMhOKE_ChBV45hT7:1654386231) ([raw file](https://github.com/beagle-pse/beagle/blob/5204146b31580b3cdb314828263ade869751b891/Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/AnalyserBlackboardView.java#L168)):*
fix naming convention here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/533#-:-K7gGPlHRpdeeyPLgSoV:1505708141)*

**Comment by m1cm1c** [comment]
Yes, of course. I'll do this when I adapt the views.

---

Review status: 0 of 16 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/533#-:-K7gHI4C1wMAn3pKGNzl:-23324901)*

**Comment by jGleitz** [comment]
This PR has a whole bunch of Javadoc issues.

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/533#-:-K7gHMLza37VzjrUni6c:523776560)*

**Comment by m1cm1c** [comment]
Only look at the `Blackboard` class and point out the issues in this class.

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/533#-:-K7gHTd3dT9VrOvlSAbs:149220868)*

**Comment by m1cm1c** [comment]
Don't review until I resolved the conflicts and fixed the Javadoc issues I find myself.

---

Review status: 0 of 16 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/533#-:-K7gIdX4_7UEvpVoHq28:-274274796)*

**Comment by m1cm1c** [comment]
This is now -blocked. Travis will still fail but only because the Javadoc in the not yet updated views doesn't match the blackboard any more.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/533#-:-K7gSShuBlJue3WChxNJ:-1407126595)*

**Comment by m1cm1c** [comment]
Please tell me about problems with the blackboard.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/533#-:-K7gSxFEQ9EOXtSI1vAL:-115379379)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 3 of 18 files at r1, 9 of 10 files at r2, 8 of 8 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/533#-:-K7geV4cniQOa4DGnXVe:980077423)*

**Comment by flyfl** [comment]
Reviewed 3 of 18 files at r1, 8 of 10 files at r2, 8 of 8 files at r3.
Review status: 16 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/AnalyserBlackboardView.java, line 17 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/533#-K7gfEUGbfFjbV7d-lpb:-K7gfEUHW0vetXZn0Is2:-1441218113) ([raw file](https://github.com/beagle-pse/beagle/blob/329f296320e8a2a9ac3edee6354efe26ee7cc652/Core/src/main/java/de/uka/ipd/sdq/beagle/core/analysis/AnalyserBlackboardView.java#L17)):*
Only proposedExpressionAnalyser? What about MeasurementAnalyser?
Or is the naming of this class wrong?

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/EvaluableExpressionFitnessFunction.java, line 13 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/533#-K7ghwEIuhzXJ6HCWXeJ:-K7ghwEJo8-_GSY-cJO2:2026125414) ([raw file](https://github.com/beagle-pse/beagle/blob/329f296320e8a2a9ac3edee6354efe26ee7cc652/Core/src/main/java/de/uka/ipd/sdq/beagle/core/EvaluableExpressionFitnessFunction.java#L13)):*
We have an extra fitnessFunction class? I thought we would just have an abstract class so far.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/533)*

**Pull request closed without merging**
