### PR TITLE
SRS Application improvements, gls genetive plural

### PR DESCRIPTION
**Pull request by jGleitz**

### CODE REVIEW

**Comment by acBerger** [comment]
I think /A10/, /A20/ and /A40/ have to be explained in more detail. But this does not have to be done now.
I like 2.2 (Target Group)

**Comment by RomanLangrehr** [comment]
All refernces are displaxed as "2.1". Please fix this.

**Comment by jGleitz** [comment]
Please accept this PR first. I will introduce correct labels in another PR, as the latter will affect the whole document.

**Comment by RomanLangrehr** [comment]
Allright.
Lgtm

**Pull request merged**
