### PR TITLE
Ip#125 measurement order

### LINKED ISSUE #492: Do Javadoc and enable checkstyle for Measurement Tool and Measurement Order

### LINKED ISSUE #610: [IP #125] Implement Measurement Order
Implement MeasurementOrder

Depends on: IP#040 (SEFF Classes). ( #571 )

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Fixes #610 
Fixes #492 

Travis is only failing, because the test coverage has problems with `assert` statements. The test coverage is 100% and this can be reviewed.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/680)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
Coverage problems have been fixed, please review.

**Comment by viridispirus** [comment]
Reviewed 13 of 26 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: 16 of 27 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/680)*

**Comment by viridispirus** [comment]
Reviewed 11 of 26 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/680)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/680#-:-KAMcPwhN9lujHj2eGO6:980077423)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/680)*

**Comment by jGleitz** [comment]
:vertical_traffic_light: (this is just a test)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/680#-:-KAPNCsCxzo-zmU8Vgg7:2124960570)*

**Comment by jGleitz** [comment]
Review status: 25 of 27 files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/measurement/MeasurementEventParser.java, line 290 \[r5\]](https://reviewable.io:443/reviews/beagle-pse/beagle/680#-KAPt_MXR53CUOvQd7kF:-KAPt_MYMbFA5yq4yHzu:-1063416104) ([raw file](https://github.com/beagle-pse/beagle/blob/e9ff58c410b1ec4d6669cf1f4f507634871dba27/Core/src/main/java/de/uka/ipd/sdq/beagle/core/measurement/MeasurementEventParser.java#L290)):*
You’re never using this field.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/680)*

**Comment by RomanLangrehr** [comment]
Review status: 25 of 27 files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/measurement/MeasurementEventParser.java, line 290 \[r5\]](https://reviewable.io:443/reviews/beagle-pse/beagle/680#-KAPt_MXR53CUOvQd7kF:-KAPyfzi6O6mtI0FULKN:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/e9ff58c410b1ec4d6669cf1f4f507634871dba27/Core/src/main/java/de/uka/ipd/sdq/beagle/core/measurement/MeasurementEventParser.java#L290)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/680)*

**Comment by viridispirus** [comment]
Reviewed 1 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/680)*

**Comment by RomanLangrehr** [comment]
@viridispirus Your LGTM got stale, please renew it.

---

Review status: 26 of 27 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/680#-:-KARME-P6Ctf9WyrkSd8:-829961438)*

**Comment by viridispirus** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/680)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/680#-:-KAROtsNRWKj6A0djCBu:980077423)*

**Comment by RomanLangrehr** [comment]
Sorry @viridispirus Your review got stole again.
And somebody else should review, too.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/680#-:-KARTnbLVyn5vhZOrxLU:1525695054)*

**Comment by viridispirus** [comment]
No problem. :lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/680#-:-KARU0EEzAhDo0af7OQc:322469277)*

**Comment by RomanLangrehr** [comment]
@viridispirus Guess what happend. Sorry.

---

Review status: 26 of 27 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/680#-:-KARV0EmNQ9CdcAqSUpT:-1945119132)*

**Comment by viridispirus** [comment]
"One more time." (Count Basie)  :lgtm: 

---

Reviewed 1 of 1 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/680#-:-KARVxCH-vvCk_28Grgh:-594184691)*

**Comment by viridispirus** [comment]
"One more ones." :lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/680#-:-KAUZvlZ4Mt1j0q5nLQ9:961157929)*

**Comment by flyfl** [comment]
:lgtm:

---

Reviewed 22 of 26 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/680#-:-KAUvXdWR7avN5RPIJBp:1417088721)*

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/680)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/680#-:-KAUvzteDA2FrrSBfaGK:980077423)*

**Comment by jGleitz** [comment]
Has full coverage :white_check_mark:

**Pull request merged**
