### PR TITLE
Kieker Measurement Tool: Breakthrough

### PR DESCRIPTION
**Pull request by jGleitz**
This is the small portion of code missing for the “breakthrough”: The Kieker Measurement Tool will now produce results.

 * Wait for the launch configuration to terminate
 * Use Java 1.8 to compile
 * GUI improvement by @RomanLangrehr 
 * Process Kieker’s results
 * Add the Kieker Measurement Tool to the launch configuration

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/714)

### CODE REVIEW

**Comment by acBerger** [comment]
Reviewed 3 of 4 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/714)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 3 of 4 files at r1, 3 of 5 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/714#-:-KAg0g7kYIjoauhCSQjH:980077423)*

**Comment by RomanLangrehr** [comment]
Just stale my own :lgtm: ^^

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/714#-:-KAg1lgC2UB40g-av5gL:721109596)*

**Comment by RomanLangrehr** [comment]
:white_check_mark: (Tests are not part of this PR, but maybe we should create some for the Kieker part).

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/714#-:-KAg2BtcLNVi3fOlnuRP:-543338538)*

**Comment by acBerger** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/714#-:-KAgAOSDD_7Ce1uDukF6:1417088721)*

**Pull request merged**
