### PR TITLE
Fixed Checkstyle Issues

### PR DESCRIPTION
**Pull request by acBerger**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/592)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/592#-:-K85wigUNyvyfAKsLjm3:980077423)*

**Comment by m1cm1c** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/592#-:-K869AnylrQbuAEBBOno:1417088721)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/592#-:-K895bpRTC7hjKAqGTe0:980077423)*

**Comment by RomanLangrehr** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/592)*

**Pull request merged**
