### PR TITLE
Enabled Assertions in Launch Configurations

### PR DESCRIPTION
**Pull request by jGleitz**
Using assertions is a good thing. Even better is to enable them during development.

So thin PR enables assertions for the “Beagle Core Tests” and “Beagle in Eclipse” run configurations.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/757)

### CODE REVIEW

**Comment by m1cm1c** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/757)*

**Comment by m1cm1c** [comment]
:lgtm: :white_check_mark:

**Comment by viridispirus** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/757)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/757#-:-KBYVV2jZ3ETa-UDm-vB:1417088721)*

**Pull request merged**
