### PR TITLE
 Application Improvements #156 

### PR DESCRIPTION
**Pull request by flyfl**
Refers to #156 
- Did not specify "execute Somox" in diagram. Because I don't know how to do.
- Did not add more application fields, as I could not read out any more of them from the TSE paper so far

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
> Did not specify "execute Somox" in diagram. Because I don't know how to do.

What do you mean with that?

**Comment by flyfl** [comment]
> What do you mean with that?
Maybe you could write "creating PCM with SoMoX". But I notice that your boxes next to the arrays do this already. I'm not sure if this is precise enough, because in the meeting the box "execute Somox" was criticised as it is saying almost nothing.

**Comment by jGleitz** [comment]
At this point, I highly disagree with Michael. SoMoX is out of our project’s scope. I think naming the artefacts passed between the tools is sufficient.

**Comment by jGleitz** [comment]
lgtm

**Comment by RomanLangrehr** [comment]
> At this point, I highly disagree with Michael. SoMoX is out of our project’s scope. I think naming the artefacts passed between the tools is sufficient.

I agree with you

**Comment by RomanLangrehr** [comment]
I'm don't agree 100% with your changes.

If we should apply something like this, please point out, that "re-engineering" is only /A10/.

And not all sofware archtiects will use beagle, of course. Neither do all component developer or all deployer. I don't think we should point this out.

**Comment by jGleitz** [comment]
> I don't think we should point this out.

Once again, I totally agree with you. Michael Langhammer doesn’t...

**Comment by RomanLangrehr** [comment]
> Michael Langhammer doesn’t...

That's bad luck for him...

**Comment by RomanLangrehr** [comment]
Should we close this PR?
I think it's good, as it is right now.

**Comment by jGleitz** [comment]
> Should we close this PR?

Yep

**Comment by flyfl** [comment]
As some other projects/issues seems to depend on this and I don't think this discussion is really necessary, just close this PR.

**Pull request closed without merging**
