### PR TITLE
GUI Design

### PR DESCRIPTION
**Pull request by m1cm1c**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/488)

### CODE REVIEW

**Comment by m1cm1c** [comment]
I don't know what fields to add to class `UserConfiguration`. Especially because of the network configuration. But I think it's best to delete it anyway because I think we won't implement running Beagle over a network.

**Comment by jGleitz** [comment]
I think we need a `Beagle Controller` that uses `PCM Repository Blackboard Factory`, `Analysis Controller` and `PCM Repository Writer`. This is not the same as `GUI Controller`, as the first controls Beagle’s business logic, the other the GUI.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7YYHtpRVEeZJSmsWVJ:1497038074)*

**Comment by jGleitz** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488)*

**Comment by m1cm1c** [comment]
I'm so sorry. I set me a reminder when you told me so I wouldn't miss it but I felt so tired that I set it for 08:00 tomorrow because I was expecting to go to bed. I'll add these.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7YZvltzixs27H4Aufn:-1803514409)*

**Comment by jGleitz** [comment]
> I'm so sorry. 

Don’t be ;)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7Y_LhclqyCCwjP6O94:-423878298)*

**Comment by viridispirus** [comment]
Please update branch.

**Comment by jGleitz** [comment]
`Beagle Controller` -> `Analysis controller` should be a use relation (dashed line), you drew an association. And I think there should really be a use relation to `PCM Repository Blackboard Factory` and `PCM Repository Writer`.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7_rx5sWR_PDwn3ZSQ5:-500318922)*

**Comment by m1cm1c** [comment]
Beagle Controller won't hold an object of Beagle Analysis? 

On January 9, 2016 11:16:14 AM GMT+01:00, Joshua Gleitze <notifications@github.com> wrote:
>`Beagle Controller` -> `Analysis controller` should be a use relation
>(dashed line), you drew an association. And I think there should really
>be a use relation to `PCM Repository Blackboard Factory` and `PCM
>Repository Writer`.
>
>---
>
>Review status: 0 of 1 files reviewed at latest revision, all
>discussions resolved.
>
>---
>
>
>
>*Comments from the [review on
>Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7_rx5sWR_PDwn3ZSQ5:-500318922)*
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Beagle-PSE/Beagle/pull/488#issuecomment-170221002

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488)*

**Comment by jGleitz** [comment]
* What exactly does `Component` do?
 * `GUI Controller` -> `Component` is lacking the multiplicity on the left side
 * `Beagle Analysis Wizard` -> `User Configuration` is lacking all multiplicities
 * Shouldn’t someone contain all pages?

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7a29QplVKuXnCN1CfE:321970055)*

**Comment by m1cm1c** [comment]
> What exactly does Component do?

It's a component to measure. I think we don't yet have a class for it. (I asked for it 20 minutes ago in Hangouts.) But it'd be nice to have one. The context menue calls would then deliver sets of `Component` objects instead of just Strings.

> GUI Controller -> Component is lacking the multiplicity on the left side

Done.

> Beagle Analysis Wizard -> User Configuration is lacking all multiplicities

Done.

> Shouldn’t someone contain all pages?

You mean a package only for `WizardPage`s?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7a4YdPQY_ouD1Sf6cd:484852379)*

**Comment by m1cm1c** [comment]
I changed the design. Please review again.

**Comment by RomanLangrehr** [comment]
The wizard construcotrs should have a `<<create>>`.

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7aUSwDZ7JucCNvxTZN:-1336626012)*

**Comment by jGleitz** [comment]
> You mean a package only for WizardPages?

No. I mean a class creating and “holding” them.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7aevcApDpngqGwbSiv:162392811)*

**Comment by jGleitz** [comment]
> It's a component to measure. I think we don't yet have a class for it. (I asked for it 20 minutes ago in Hangouts.) But it'd be nice to have one. The context menue calls would then deliver sets of Component objects instead of just Strings.

Please see `PCM Repository Blackboard Factory`, as it already solves that, but differently: You give it the PCM IDs you want to have and get a populated Blackboard in return.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7afBc3C4luKrClrv5e:758552104)*

**Comment by m1cm1c** [comment]
> No. I mean a class creating and “holding” them.

They're held by `Beagle Analysis Wizard`.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7afZcJEOTjD1aeIU3m:1600181002)*

**Comment by m1cm1c** [comment]
> The wizard construcotrs should have a `<<create>>`.

Done.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7agy7Ujzci9HtEIHrY:-1480758710)*

**Comment by jGleitz** [comment]
> They're held by `Beagle Analysis Wizard`.

I thought so, but this is not modeled in the diagram. By the way: Please remove the package, I don’t think it’s needed.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7ahDuyPIYANTG7TmrA:-1121706112)*

**Comment by m1cm1c** [comment]
So I should put uses relations there?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7ai1voy6v7D1VFxKmP:566148912)*

**Comment by jGleitz** [comment]
> So I should put uses relations there?

Yes: 

Does the `Beagle Analysis Wizard` hold references to the Pages ? -> model association
Does the `Beagle Analysis Wizard` only create the Pages ? -> Model use relation

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7aj0s3EkO42GzUjWZz:-657658219)*

**Comment by m1cm1c** [comment]
I think it's rather obvious but added them.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7akJlmtAxqxGKPwnI9:638899177)*

**Comment by m1cm1c** [comment]
> Please see PCM Repository Blackboard Factory, as it already solves that, but differently: You give it the PCM IDs you want to have and get a populated Blackboard in return.

These are only Strings. There is no guarantee it doesn't just say "trolololol".

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7akleYZUIuClXKxlO5:-2095288240)*

**Comment by m1cm1c** [comment]
I modeled it anyway.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7alN1IfCqZAbZ7Kex4:-163975062)*

**Comment by jGleitz** [comment]
> These are only Strings. There is no guarantee it doesn't just say "trolololol".

If you pass "trolololol", you’ll get an empty Blackzoard back. Your fault.

Anyway: At some point, you have to translate the PCM to our model. We could use the PCM classes (might even be more elegant), but I knew way to little about them to create something meaningful with them.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7alwmE-_KW_WqmIAlb:442069510)*

**Comment by jGleitz** [comment]
What are you trying to express with all that `{{unique}}`? I don’t think it makes any sense for 1:1 relations.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7amd-ppg3qVPKw3-O_:-803441499)*

**Comment by m1cm1c** [comment]
I removed them.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7appDhE3eA2SueX4wA:92142230)*

**Comment by jGleitz** [comment]
Now this looks good I think!

Last thing: If you treated `String` as a primitive and therefore removed the associations and modeled them as attributes, you could remove the comment and have a cleaner structure.

---

Reviewed 1 of 1 files at r7.
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7asGIF_aypISnxulKg:1167843495)*

**Comment by m1cm1c** [comment]
But then we can't model that a PCM element is known to this class. 

On January 9, 2016 3:57:17 PM GMT+01:00, Joshua Gleitze <notifications@github.com> wrote:
>Now this looks good I think!
>
>Last thing: If you treated `String` as a primitive and therefore
>removed the associations and modeled them as attributes, you could
>remove the comment and have a cleaner structure.
>
>---
>
>Reviewed 1 of 1 files at r7.
>Review status: 0 of 1 files reviewed at latest revision, all
>discussions resolved.
>
>---
>
>
>
>*Comments from the [review on
>Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7asGIF_aypISnxulKg:1167843495)*
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Beagle-PSE/Beagle/pull/488#issuecomment-170245238

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by m1cm1c** [comment]
done

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7bNlAzDX351zqEgI9C:677588487)*

**Comment by flyfl** [comment]
:Lgtm_strong:

---

Reviewed 1 of 1 files at r10.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7bO0jbLJgKd_1XFvgd:-1004338963)*

**Comment by RomanLangrehr** [comment]
Please add a note, that the WizardPage is an eclipse class.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7bP_3TbWsZXpceBC-4:2018191583)*

**Comment by jGleitz** [comment]
> done

now the strings are completely gone. Don’t you want to have them included (e.g. as attributes)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7bPn2catYMTraYkqMg:-1946530659)*

**Comment by m1cm1c** [comment]
> Please add a note, that the WizardPage is an eclipse class.

done

> now the strings are completely gone. Don’t you want to have them included (e.g. as attributes)

They have been degraded to implementation details of the class `UserConfiguration`.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7bWkQ-lvlrt2dl8nfC:-937157233)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r11.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7balHR01_KHl45xl46:980077423)*

**Comment by jGleitz** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/488#-:-K7bbu5n2YZ08Pk_NHis:980077423)*

**Pull request merged**
