### PR TITLE
Measurement & Final Judge View

### PR DESCRIPTION
**Pull request by viridispirus**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/311)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
The return value of `get SEFF Loops to be masured` multiplicity should be \*, not 1..\*

**Comment by viridispirus** [comment]
#313

**Comment by RomanLangrehr** [comment]
> added remesure methods.	

You usually don't want to remeasure all RDIAs(branches/..., but only some of them. So the methods should be like `remasure RDIA(:RDIA)`

**Comment by RomanLangrehr** [comment]
Depends on #310

**Comment by RomanLangrehr** [comment]
> The return value of `get SEFF Loops to be masured` multiplicity should be \*, not 1..\*

This problem still exists, but is not part of this PR, maybe it will be solved, when #309 gets merged.

**Comment by jGleitz** [comment]
The measurement blackboard view should contain all methods the read-only measurement view contains. So please note the comments in #310.

Further methods will need to be added as soon as the properties blocked by #263 are modeled.

**Comment by jGleitz** [comment]
As far as I can see, this PR also introduces changes to the `Final Judge Blackboard View`. So I will comment on these, too.

**Comment by jGleitz** [comment]
final judge methods

the parameters should not be called `blackboard`.

**Comment by jGleitz** [comment]
final judge construct

<pre>con<b>[s]</b>truct</pre>

**Comment by jGleitz** [comment]
> You usually don't want to remeasure all RDIAs(branches/..., but only some of them. So the methods should be like remasure RDIA(:RDIA)

In the implementation, you’d usually offer both (or use variadric parameters, or both). I think the multiplicity is irrelevant for the model. But the methods’ arguments need to be added.

**Comment by m1cm1c** [comment]
not mergeable

**Pull request closed without merging**
