### PR TITLE
Environment

### PR DESCRIPTION
**Pull request by jGleitz**
This is a follow up PR from #47 containing improvements

> The Environments are added from the PDF

### CODE REVIEW

**Comment by acBerger** [comment]
lgtm

**Comment by RomanLangrehr** [comment]
I think we should mention in /E30/ the Common Trace API.

**Comment by acBerger** [comment]
Unfortunately the labels are there twice

**Comment by jGleitz** [comment]
@acBerger fixed it.

**Comment by m1cm1c** [comment]
lgtm

**Comment by acBerger** [comment]
lgtm

**Pull request merged**
