### PR TITLE
Fixed AsssertionError in ConstantTimeoutTest.

### PR DESCRIPTION
**Pull request by RomanLangrehr**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/789)

### CODE REVIEW

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/789)*

**Comment by jGleitz** [comment]
:lgtm: :white_check_mark:

**Comment by viridispirus** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/789#-:-KCDMyg1DzwtFHcjsWa6:980077423)*

**Comment by m1cm1c** [comment]
Closed because #789 will fix (is merged in) this so we don't have to wait for Travis.

**Pull request closed without merging**
