### PR TITLE
Context menus

### LINKED ISSUE #507: Add Context Menu Handle Classes to GUI Diagram
Blocked until #506 is merged.

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Fixes #507
[Website](http://romanlangrehr.github.io/Beagle/branches/context-menus/)

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/526)

### CODE REVIEW

**Comment by m1cm1c** [comment]
Please insert the diagram into `GUI.uxf`.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/526#-:-K7feefHFUnallEwHgBC:1044203404)*

**Comment by RomanLangrehr** [comment]
> Please insert the diagram into GUI.uxf.

That's probably the better solution.
Done.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/526#-:-K7fhWtHOWcoJJLZ53ol:-1425660720)*

**Comment by m1cm1c** [comment]
I already adapted the GUI design diagram to the "let's put blanks into class names" style (but apparently didn't do so very good as I now see that I missed some occurrences). Please make the diagram uniform and please also add blacks where I missed them / remove them everywhere. And please add that GuiController can't navigate back to the 3 context menu classes.

---

Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/526#-:-K7fihsnX1E5dgrNH2v1:-747226322)*

**Comment by RomanLangrehr** [comment]
> I already adapted the GUI design diagram to the "let's put blanks into class names" style (but apparently didn't do so very good as I now see that I missed some occurrences). 

I don't know where blanks should be added. Maybe you can do it later?

Rest is fixed.

---

Review status: 9 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/526#-:-K7fkfFhE7pVSyqtIKUZ:-1609932549)*

**Comment by RomanLangrehr** [comment]
> I don't know where blanks should be added. Maybe you can do it later?

Now I got it. I'll fix it.

---

Review status: 9 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/526#-:-K7flHrvIQGTE2VSNcVd:-1799283035)*

**Comment by RomanLangrehr** [comment]
> Now I got it. I'll fix it.

Done.

---

Review status: 9 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/526#-:-K7fm5tOo3jfOpIvRfyx:860024701)*

**Comment by flyfl** [comment]
The UI diagram mentionts "Context Menu Entry Handler For Components" twice. One of them should be "Context Menu Entry Handler For Internal Actions"

---

Reviewed 1 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Documentation/src/design/lyx/Parts/GUI.lyx, line 259 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/526#-K7fvqDp53JF2oaBJ6Qu:-K7fvqDqlXosWcPHsvYA:1992957867) ([raw file](https://github.com/beagle-pse/beagle/blob/bd8165ca95c4403c15ffadbe0d68d66a123e1639/Documentation/src/design/lyx/Parts/GUI.lyx#L259)):*
I think the .repository file should be enough.

---

*[Documentation/src/design/lyx/Parts/GUI.lyx, line 275 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/526#-K7fwBHqobYXg-09NXob:-K7fwBHroNCVuq7Cc1Rd:-892259808) ([raw file](https://github.com/beagle-pse/beagle/blob/bd8165ca95c4403c15ffadbe0d68d66a123e1639/Documentation/src/design/lyx/Parts/GUI.lyx#L275)):*
What is Internal Action Edit Part and what is Internal Action 2 Edit Parts?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/526#-:-K7fwXbd1Z5D3wVOGsKD:-1465116583)*

**Comment by RomanLangrehr** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Documentation/src/design/lyx/Parts/GUI.lyx, line 259 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/526#-K7fvqDp53JF2oaBJ6Qu:-K7g-PoTGdHzCIL7Ln5g:1336717149) ([raw file](https://github.com/beagle-pse/beagle/blob/bd8165ca95c4403c15ffadbe0d68d66a123e1639/Documentation/src/design/lyx/Parts/GUI.lyx#L259)):*
I think it makes on both sense. Why not both?

---

*[Documentation/src/design/lyx/Parts/GUI.lyx, line 275 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/526#-K7fwBHqobYXg-09NXob:-K7g-T-60Cnwc3TymVlg:858487804) ([raw file](https://github.com/beagle-pse/beagle/blob/bd8165ca95c4403c15ffadbe0d68d66a123e1639/Documentation/src/design/lyx/Parts/GUI.lyx#L275)):*
I don't know what the difference is, but those two exist.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/526)*

**Comment by RomanLangrehr** [comment]
> The UI diagram mentionts "Context Menu Entry Handler For Components" twice. One of them should be "Context Menu Entry Handler For Internal Actions"

Thanks, I fixed it.

---

Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/526#-:-K7g-u4eHt1jYIzCYgOM:-359372596)*

**Comment by acBerger** [comment]
Reviewed 8 of 10 files at r1, 1 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/526)*

**Comment by flyfl** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Documentation/src/design/lyx/Parts/GUI.lyx, line 259 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/526#-K7fvqDp53JF2oaBJ6Qu:-K7g75i0ZrMnFzES7vaH:1840119315) ([raw file](https://github.com/beagle-pse/beagle/blob/bd8165ca95c4403c15ffadbe0d68d66a123e1639/Documentation/src/design/lyx/Parts/GUI.lyx#L259)):*
Because we get all information from the .repository file we need. But just keep it that way, I don't think it's really important.

---

*[Documentation/src/design/lyx/Parts/GUI.lyx, line 275 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/526#-K7fwBHqobYXg-09NXob:-K7g7_f_Gm7r3qcZXpeq:1264908511) ([raw file](https://github.com/beagle-pse/beagle/blob/bd8165ca95c4403c15ffadbe0d68d66a123e1639/Documentation/src/design/lyx/Parts/GUI.lyx#L275)):*
These sound like implementation specific objects. I don't think this part is really understanable, if the reader does not know these details. I would prefer keeping it simple: "The last one is for analysing internal actions ...". I don't know how to fill out the dots, maybe just leave this part out.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/526)*

**Comment by RomanLangrehr** [comment]
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[Documentation/src/design/lyx/Parts/GUI.lyx, line 259 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/526#-K7fvqDp53JF2oaBJ6Qu:-K7gFQJlbe6dCwLMfYgM:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/bd8165ca95c4403c15ffadbe0d68d66a123e1639/Documentation/src/design/lyx/Parts/GUI.lyx#L259)):*
Done.

---

*[Documentation/src/design/lyx/Parts/GUI.lyx, line 275 \[r3\]](https://reviewable.io:443/reviews/beagle-pse/beagle/526#-K7fwBHqobYXg-09NXob:-K7gFRLjHkwTjPsBE9pm:1681485764) ([raw file](https://github.com/beagle-pse/beagle/blob/bd8165ca95c4403c15ffadbe0d68d66a123e1639/Documentation/src/design/lyx/Parts/GUI.lyx#L275)):*
I think you are right, that's to technical.
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/526)*

**Comment by acBerger** [comment]
:lgtm:

---

Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/526#-:-K7gKucb5j4wmPtktnFB:1417088721)*

**Comment by m1cm1c** [comment]
:lgtm: 

---

Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/526#-:-K7g_pdHVMR7ZlH4Klk7:980077423)*

**Comment by m1cm1c** [comment]
Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/526)*

**Pull request merged**
