### PR TITLE
(Hopefully) Speed Up the SVN Deployment

### PR DESCRIPTION
**Pull request by jGleitz**
This PR aims to speed up the SVN deployment while still correctly deploying the files. I will check its results once it’s merged.

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/596)

### CODE REVIEW

**Comment by RomanLangrehr** [comment]
:lgtm:

**Comment by m1cm1c** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/596#-:-K8ATZMK6PCIH4IP4r-F:980077423)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/596#-:-K8AaWqpePzjYaUkj7iN:980077423)*

**Comment by jGleitz** [comment]
Since #597, this works and speeds up deployment to SVN.

**Pull request merged**
