### PR TITLE
Controllers diagram

### LINKED ISSUE #478: Redraw Controllers Diagram in UMLet
depends on #475

### PR DESCRIPTION
**Pull request by RomanLangrehr**
Fixes #478 
Depends on #497 (by mistake)
[Website](http://romanlangrehr.github.io/Beagle/branches/controllers-diagram/)

[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/511)

### CODE REVIEW

**Comment by jGleitz** [comment]
`Measurement Controller` has the wrong interface (must use its Blackboard View). @flyfl forgot to change that in the main diagram. Could you adapt it there, too?

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/511#-:-K7cbJ3p0uh15702YEON:694214339)*

**Comment by RomanLangrehr** [comment]
> Measurement Controller has the wrong interface (must use its Blackboard View). @flyfl forgot to change that in the main diagram. Could you adapt it there, too?

Done.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/511#-:-K7cfAQZbieggoWA911R:1097915147)*

**Comment by jGleitz** [comment]
Formatting issues: 





I think it’d be best to break it like this:

```
  + can contribute ( blackboard: Read-Only
                  Measurement Controller Blackboard View )
       : boolean
```

(like in `Measurement Result Analyser`)

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/511#-:-K7chDdCHxQDpvXfEjku:1429230704)*

**Comment by RomanLangrehr** [comment]
> I think it’d be best to break it like this:
  + can contribute ( blackboard: Read-Only
                  Measurement Controller Blackboard View )
       : boolean
(like in Measurement Result Analyser)

Done.

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/511#-:-K7ewCV4waUxfIGoXY3V:216317307)*

**Comment by flyfl** [comment]
Your diagrams are linked with absolute paths in the Analysis.lyx Document

---

Reviewed 1 of 2 files at r4.
Review status: 1 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/511#-:-K7f8i5DLDYZcilim6hl:-878623332)*

**Comment by RomanLangrehr** [comment]
See #523 now.

**Pull request closed without merging**
