### PR TITLE
Missing blackboard methods

### PR DESCRIPTION
**Pull request by viridispirus**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/683)

### CODE REVIEW

**Comment by m1cm1c** [comment]
This is not what was decided in https://github.com/Beagle-PSE/Beagle/issues/682#issuecomment-182975682.

**Comment by m1cm1c** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java, line 183 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/683#-KAHbnMzq0RwxqMYfmR2:-KAHbnMzq0RwxqMYfmR3:456320457) ([raw file](https://github.com/beagle-pse/beagle/blob/2647aadddc69e56af361b30025eba91e4de047b8/Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java#L183)):*
These methods shouldn't be here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/683)*

**Comment by viridispirus** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java, line 183 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/683#-KAHbnMzq0RwxqMYfmR2:-KAL8biXqDsR6JfZzK97:-499146009) ([raw file](https://github.com/beagle-pse/beagle/blob/2647aadddc69e56af361b30025eba91e4de047b8/Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java#L183)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/683)*

**Comment by m1cm1c** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java, line 183 \[r2\]](https://reviewable.io:443/reviews/beagle-pse/beagle/683#-KAHbnMzq0RwxqMYfmR2:-KALER3n6Epr3Np1v5Y4:-489908877) ([raw file](https://github.com/beagle-pse/beagle/blob/2647aadddc69e56af361b30025eba91e4de047b8/Core/src/main/java/de/uka/ipd/sdq/beagle/core/Blackboard.java#L183)):*
Nope.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/683)*

**Comment by m1cm1c** [comment]
I opened #686. This is closed.

**Pull request closed without merging**
