### PR TITLE
added methods to clear the toBeMeasured elements lists.

### PR DESCRIPTION
**Pull request by m1cm1c**
[Review on Reviewable](https://reviewable.io/reviews/beagle-pse/beagle/686)

### CODE REVIEW

**Comment by m1cm1c** [comment]
@viridispirus Please make sure this PR contains what you want to change on the blackboard.

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/686#-:-KALGNm1dL4v9OuQah7I:980077423)*

**Comment by viridispirus** [comment]
Yes, it does.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/686#-:-KALGKEOfdoQ0nkdZtLc:-949314506)*

**Comment by RomanLangrehr** [comment]
We need to add tests for it :lgtm_cancel: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/686#-:-KALHl-OFrjJTG_6bjNv:619131337)*

**Comment by m1cm1c** [comment]
@flyfl Please write the tests.

**Comment by acBerger** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/686)*

**Comment by acBerger** [comment]
Travis fails because there are no tests.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/686#-:-KAMGgeUG-O-ck-gAzwq:2083913889)*

**Comment by acBerger** [comment]
As @flyfl is not here today and he still got other things to do, I'll do that.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/686#-:-KAMOJALbY7dG4fzU-Ba:-670882241)*

**Comment by m1cm1c** [comment]
@RomanLangrehr The tests are there.

@viridispirus Please add a :lgtm: for me. Mine won't count because I opened this PR even if the only commit is yours.

**Comment by viridispirus** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/686)*

**Comment by viridispirus** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/686#-:-KAMVZIFvnQfThncc4fH:980077423)*

**Comment by acBerger** [comment]
-(tests needed) -@flyfl 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/686#-:-KAMX0tfZCE26Od-7_m7:-1326653627)*

**Comment by m1cm1c** [comment]
Somehow either of your "lgtm"s doesn't count.

**Comment by acBerger** [comment]
@RomanLangrehr  had his 'lgtm' cancelled before, this is why it does not count.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/686#-:-KAOx8dR264MIv1gpEcH:-1662071248)*

**Comment by RomanLangrehr** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/beagle-pse/beagle/686#-:-KAPGdP_G4BTdUFCg4Cm:980077423)*

**Pull request merged**
